### ISSUE TITLE
Stacked LSTMs and GRUs

### ISSUE THREAD

**Issue by prajdabre** [chainer/chainer#1123]
We need stacked versions of LSTMs and GRUs where we can have multiple layers of RNN cells.

**Comment by prajdabre** [comment]
I have already sent a pull request about my implementation.
Kindly let me know if anything needs to be changed.

**Comment by unnonouno** [comment]
Great! We'll check your PR. Thanks.

**Comment by beam2d** [comment]
We now have `NStepLSTM` and `NStepGRU` that stacks multiple layers of LSTMs/GRUs and utilizes the optimized cuDNN implementations.
