### ISSUE TITLE
Optimize LSTM and GRU implementation

### ISSUE THREAD

**Issue by fabiencro** [chainer/chainer#1143]
This article gives some good tips for optimizing LSTMs/GRUs:
https://devblogs.nvidia.com/parallelforall/optimizing-recurrent-neural-networks-cudnn-5/,

Since support for GRU/LSTM will be included in cudnn 5, I guess chainer developpers will make use of the cudnn implementation at some point. But in the meantime, I found that most of these improvements were quite easy to add to chainer's implementation.

I tried and found that using Optimization 1 and 3 (from the linked article) gave me a ~100% speedup over the current implementation of GRU. Not bad.

If there is interest, I can try to put my implementation of these optimizations in a proper Pull Request when I have time.

**Comment by unnonouno** [comment]
Thank you and it's a nice news. I'm now trying to use cuDNN's RNN library from Chainer and CuPy, and found that it is not enough flexible. Your optimized version of GRU helps a lot of users. Please send a Pull Request if you have time!

**Comment by fabiencro** [comment]
OK. Actually, I found that Chainer's LSTM was more optimized than GRU, and was already somehow using optimizations 1 and 3. So the improvements will only be for GRU.

I will make an initial pull request for my optimizations of GRU.

I was also interested in implementing optimization 2: applying the Linear functions to the input and previous states in parallel. To do this, I would need to run two Linear operations on 2 different cuda streams. Some ideas about how to do this?

**Comment by beam2d** [comment]
We now support calling cuDNN's RNN routines via `NStepLSTM` and `NStepGRU` links.
