### ISSUE TITLE
How is the output signal be computed of chainer.functions.lstm ?

### ISSUE THREAD

**Issue by Yevgnen** [chainer/chainer#1159]
Hi,

Thanks for offering the awesome library!
I'm new to RNN/LSTM and I recently read some materials of LSTM like [LSTM: A Search Space Odyssey](http://arxiv.org/pdf/1503.04069v1). I read that the current cell state `c` is computed after the current cell state as the formula shown in page 2.

I also find that the function `chainer.functions.lstm` has signature `lstm(c_prev, x)` and returns the updated cell state `c` and the outgoing signal `h`.

My question is how can one pass a output source `o` which is part of the input signal of `x` before computing the current(updated) cell state ? [source](https://github.com/pfnet/chainer/blob/master/chainer/functions/activation/lstm.py#L73)

Any help will be appreciated.

**Comment by unnonouno** [comment]
Do you mean peephole connection? Chainer's original LSTM unit doesn't have peephole connection.

**Comment by beam2d** [comment]
If this issue is about peephole connection, we have started supporting `StatefulPeepholeLSTM`, which should work for you.
