### ISSUE TITLE
Support API that easily initializes or changes dtype of parameters of Link.

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#1228]
Although we now loosen type condition of subclasses of `Function` (e.g. #1162). Most of subclasses of `Link` initializes parameters with `numpy.float32`. If we want to change the `dtype` of parameters, we must change them one by one as follows.

```
dtype = numpy.float64
model = L.Linear(10, 2)
model.W.data = model.W.data.astype(dtype)
model.b.data = model.b.data.astype(dtype)
model.W.grad = model.W.grad.astype(dtype)
model.b.grad = model.b.grad.astype(dtype)
```

**Comment by delta2323** [comment]
One of the solution is to add setter of `dtype` that recursively change the `dtype` of parameters to `Link` and `Chain`.

**Comment by beam2d** [comment]
We now have initializers with which we can customize the dtype of each parameter.
