### ISSUE TITLE
Extract Scale link Bias link from caffe_function

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#1239]
`chainer.links.caffe.caffe_function._Scale` is a link that perform elementwise affine transformation whose parameters are learnable. This link is reusable as a general module. So we would like to extract this link and move to `chainer.links.connection`.

Same is true for `chainer.links.caffe.caffe_function._Bias` link.

Related to #930, #1028 and #1234.

**Comment by takagi** [comment]
Close via #1252.

**Comment by beam2d** [comment]
`Scale` and `Bias` are now Chainer's official built-in links.
