### ISSUE TITLE
Serialize CaffeFunction?

### ISSUE THREAD

**Issue by aaronnech** [chainer/chainer#1274]
Loading a big CaffeModel (E.g. VGG-19 or VGGFace) takes a very long time. (5-10 minutes sometimes). I think this could be sped up if we could serialize the CaffeFunction object and deserialize it to a file. Is this possible currently? The constructor expects a model path so I can't initialize an empty object to fill from the deserialization step, so I'm assuming no?

**Comment by aaronnech** [comment]
Temp solution that works pretty well (cuts loading time from ~7 minutes to 10 seconds for me): Pickle the CaffeFunction object after loading, and then for subsequent loads unpickle the object from the pickle file. Takes up more space (1.6GB for VGGFace) but much faster!

**Comment by unnonouno** [comment]
Yes, Pickle is a good solution. Please note that pickled file is depend on its internal structure. I mean, when we modify internal structure of Caffe function in the future, you cannot use the pickled files even if we keep its interface. And, pickled file with py2 is not compatible with py3's.

C++ implementation of protobuf is faster than pure python implementation. But, it cannot treat large data such as CaffeModels. I sent a patch to fix this behavior to protobuf, but my patch is not merged yet.
https://github.com/google/protobuf/tree/master/python#c-implementation

**Comment by unnonouno** [comment]
Chainer now supports cpp-implementation of protobuf 3 in #1443. Please try it. It is about 10 times faster in my environment.

**Comment by beam2d** [comment]
Looks the root problem (slow loading of caffe models) has already been solved.
