### ISSUE TITLE
We need a cute mascot :)

### ISSUE THREAD

**Issue by repeatedly** [chainer/chainer#13]
chainer has a ring log but we want a cute mascot.
For example, Hive has so cute mascot: https://hive.apache.org/
Fluentd too: http://www.fluentd.org/

Cute mascot is very important for spreading softwares.

**Comment by unnonouno** [comment]
:+1:

**Comment by nobu-k** [comment]
:+1:

**Comment by nushio3** [comment]
:+1: 

How about a cute mascot wearing a China dress?

**Comment by prajdabre** [comment]
Hi,
How about something like this: https://www.butlerandwilson.co.uk/media/catalog/product/cache/1/image/1800x/040ec09b1e35df139433887a97daa66f/c/r/crystal-swinging-panda-chain-necklace.6936.full.jpg

**Comment by Crissman** [comment]
We have discussed this question and decided on the new Chainer mascot. Behold, the Chainer Parrot!

![chainerparrot](https://user-images.githubusercontent.com/4338467/31375973-3fa996b0-adde-11e7-9911-5789b3d85e3c.gif)

**Comment by Crissman** [comment]
To ask @kuenishi for Jubatus-like mascot.

**Comment by Crissman** [comment]
We discussed, and decided that since we have a logo, getting a mascot isn't necessary.

Thanks!
