### ISSUE TITLE
chainer.testing.assert_array_equal

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#1368]
As NumPy and CuPy has `xp.testing.assert_array_equal`, we can implement, `chainer.testing.assert_array_equal` that accepts a pair of `numpy.ndarray`s, `cupy.ndarray`'s, or mixture of them. This function is just an utility one because we can also write as

```
numpy.testing.assert_array_equal(cuda.to_cpu(x), cuda.to_cpu(y))
```

or

```
xp = get_array_module(x)
xp.testing.assert_array_equal(x, y)
```

**Comment by beam2d** [comment]
We already have `chainer.testing.assert_allclose` which fits to most of the usages in tests of Chainer. I will close it now; if anyone is interested in adding it too, please reopen it or a new one.
