### ISSUE TITLE
chainer v1.11.0 example-imagenet(model:alexbn) CUDA_ERROR_INVALID_IMAGE

### ISSUE THREAD

**Issue by miglopst** [chainer/chainer#1385]
In the backpropagation stage of Alexbn model, the program will throw an error after returning from 3rd conv layer before entering 2nd conv layer.
Using pdb to print out traces:
`(Pdb)

> /home/peng/.local/lib/python2.7/site-packages/chainer/variable.py(349)backward()
> -> gxs = func.backward(in_data, out_grad)
> (Pdb)
> CUDADriverError: CUDADriv...nvalid',)
> /home/peng/.local/lib/python2.7/site-packages/chainer/variable.py(349)backward()
> -> gxs = func.backward(in_data, out_grad)
> (Pdb)
> --Return--
> /home/peng/.local/lib/python2.7/site-packages/chainer/variable.py(349)backward()->None
> -> gxs = func.backward(in_data, out_grad)
> (Pdb)
> CUDADriverError: CUDADriv...nvalid',)
> /home/peng/.local/lib/python2.7/site-packages/chainer/optimizer.py(389)update()
> -> loss.backward()
> (Pdb)
> --Return--
> /home/peng/.local/lib/python2.7/site-packages/chainer/optimizer.py(389)update()->None
> -> loss.backward()
> (Pdb)
> CUDADriverError: CUDADriv...nvalid',)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/updater.py(179)update_core()
> -> optimizer.update(loss_func, *in_vars)
> (Pdb)
> --Return--
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/updater.py(179)update_core()->None
> -> optimizer.update(loss_func, *in_vars)
> (Pdb)
> CUDADriverError: CUDADriv...nvalid',)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/updater.py(167)update()
> -> self.update_core()
> (Pdb)
> --Return--
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/updater.py(167)update()->None
> -> self.update_core()
> (Pdb)
> CUDADriverError: CUDADriv...nvalid',)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(265)run()
> -> update()
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(270)run()
> -> for _, entry in extensions:
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(271)run()
> -> finalize = entry.extension.finalize
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(272)run()
> -> if finalize:
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(273)run()
> -> finalize()
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(270)run()
> -> for _, entry in extensions:
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(271)run()
> -> finalize = entry.extension.finalize
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(272)run()
> -> if finalize:
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(270)run()
> -> for _, entry in extensions:
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(271)run()
> -> finalize = entry.extension.finalize
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(272)run()
> -> if finalize:
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(273)run()
> -> finalize()
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(270)run()
> -> for _, entry in extensions:
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(271)run()
> -> finalize = entry.extension.finalize
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(272)run()
> -> if finalize:
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(273)run()
> -> finalize()
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(270)run()
> -> for _, entry in extensions:
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(271)run()
> -> finalize = entry.extension.finalize
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(272)run()
> -> if finalize:
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(273)run()
> -> finalize()
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(270)run()
> -> for _, entry in extensions:
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(271)run()
> -> finalize = entry.extension.finalize
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(272)run()
> -> if finalize:
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(270)run()
> -> for _, entry in extensions:
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(271)run()
> -> finalize = entry.extension.finalize
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(272)run()
> -> if finalize:
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(270)run()
> -> for _, entry in extensions:
> (Pdb)
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(274)run()
> -> self.updater.finalize()
> (Pdb)
> --Return--
> /home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py(274)run()->None
> -> self.updater.finalize()
> (Pdb)
> CUDADriverError: CUDADriv...nvalid',)
> /home/peng/workplace/chainer_new/chainer/examples/imagenet/train_imagenet.py(175)main()
> -> trainer.run()
> (Pdb)
> --Return--
> /home/peng/workplace/chainer_new/chainer/examples/imagenet/train_imagenet.py(175)main()->None
> -> trainer.run()
> (Pdb)
> CUDADriverError: CUDADriv...nvalid',)
> /home/peng/workplace/chainer_new/chainer/examples/imagenet/train_imagenet.py(179)<module>()
> -> main()
> (Pdb)
> --Return--
> /home/peng/workplace/chainer_new/chainer/examples/imagenet/train_imagenet.py(179)<module>()->None
> -> main()
> (Pdb)
> Traceback (most recent call last):
>   File "./train_imagenet.py", line 179, in <module>
>     main()
>   File "./train_imagenet.py", line 175, in main
>     trainer.run()
>   File "/home/peng/.local/lib/python2.7/site-packages/chainer/training/trainer.py", line 265, in run
>     update()
>   File "/home/peng/.local/lib/python2.7/site-packages/chainer/training/updater.py", line 167, in update
>     self.update_core()
>   File "/home/peng/.local/lib/python2.7/site-packages/chainer/training/updater.py", line 179, in update_core
>     optimizer.update(loss_func, *in_vars)
>   File "/home/peng/.local/lib/python2.7/site-packages/chainer/optimizer.py", line 389, in update
>     loss.backward()
>   File "/home/peng/.local/lib/python2.7/site-packages/chainer/variable.py", line 349, in backward
>     gxs = func.backward(in_data, out_grad)
>   File "/home/peng/.local/lib/python2.7/site-packages/chainer/functions/normalization/batch_normalization.py", line 85, in backward
>     gbeta = gy.sum(axis=axis)
>   File "cupy/core/core.pyx", line 701, in cupy.core.core.ndarray.sum (cupy/core/core.cpp:13555)
>   File "cupy/core/core.pyx", line 709, in cupy.core.core.ndarray.sum (cupy/core/core.cpp:13426)
>   File "cupy/core/reduction.pxi", line 252, in cupy.core.core.simple_reduction_function.__call__ (cupy/core/core.cpp:44377)
>   File "cupy/util.pyx", line 36, in cupy.util.memoize.decorator.ret (cupy/util.cpp:1256)
>   File "cupy/core/reduction.pxi", line 181, in cupy.core.core._get_simple_reduction_function (cupy/core/core.cpp:42952)
>   File "cupy/core/reduction.pxi", line 108, in cupy.core.core._get_simple_reduction_kernel (cupy/core/core.cpp:40781)
>   File "cupy/core/carray.pxi", line 87, in cupy.core.core.compile_with_cache (cupy/core/core.cpp:26605)
>   File "/home/peng/.local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 138, in compile_with_cache
>     mod.load(cubin)
>   File "cupy/cuda/function.pyx", line 156, in cupy.cuda.function.Module.load (cupy/cuda/function.cpp:3884)
>   File "cupy/cuda/function.pyx", line 157, in cupy.cuda.function.Module.load (cupy/cuda/function.cpp:3832)
>   File "cupy/cuda/driver.pyx", line 77, in cupy.cuda.driver.moduleLoadData (cupy/cuda/driver.cpp:1458)
>   File "cupy/cuda/driver.pyx", line 59, in cupy.cuda.driver.check_status (cupy/cuda/driver.cpp:1194)
> cupy.cuda.driver.CUDADriverError: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid
> `

**Comment by unnonouno** [comment]
Did you update CUDA, dirver or something like that recently?

**Comment by delta2323** [comment]
Closed as we do not support v1 any longer. Please reopen it or submit another issue if the problem remains. Thank you.
