### ISSUE TITLE
Want contribution for providing more primitive operations.

### ISSUE THREAD

**Issue by takagi** [chainer/chainer#1448]
## Background

It would be helpful that Chainer had more primitive operations, especially driving novel directions of deep learning research. Providing flexibility in such is one of Chainers most important objectives.
## Goal

Because we have quite restricted development resource, we would appreciate if we had Chainer community's precious contribution to provide more primitive operations.
## What primitive operations Chainer does not support now?

Here shows a list of primitive operations that Chainer does not provide currently compared with other major deep learning frameworks.

https://docs.google.com/spreadsheets/d/1tHQcuKhqYiDUo57uOWOtW_mUqrHmsP9fZzaQRA2dW5k/edit?usp=sharing
## How to implement a primitive operation?

**Sample works**
There are some PRs that implements primitive operations and you can follow with.
- #1007 clip function
- #1262 stack function
- #1401 rollaxis function

**Overall steps**
The following are overall steps to implement a Chainer function.
1. Keep a WIP pull request
   - Keep a work-in-progress pull request to show you are on work for a primitive operations.
   - You can make an empty commit with `git --allow-empty -m "Empty commit to keep PR."` to send an empty pull request to begin with.
2. Implement and test a Chainer function.
   - Implement a Chainer function and its test. You need to implement forward computation and backward computation for CPU and GPU respectively.
   - For detail on how to write a Chainer function, please see the following tutorial.
     http://docs.chainer.org/en/stable/tutorial/function.html
3. Document a Chainer function.
   - Write a documentation for your Chainer function and add it to sphinx source file.
4. Take a review.
   - Ask Chainer team to review your PR. After your PR passes the review, it is merged into Chainer's master branch.

**Comment by entron** [comment]
I am thinking it would be good to make array related operations the same as numpy if possible. This will make chainer easier to learn and port.

**Comment by takagi** [comment]
Yes, it would be good.

**Comment by takagi** [comment]
I added Priority column to the list.

**Comment by aksub99** [comment]
I'd like to implement ELiSH activation function as introduced in this paper.
https://arxiv.org/abs/1808.00783

**Comment by aksub99** [comment]
I've opened issue #6376  to get some suggestions on the operation I can start implementing. Please let me know if any of the mentioned functions could be useful additions at present. Thanks in advance!

**Comment by UmashankarTriforce** [comment]
Is the this document - https://docs.google.com/spreadsheets/d/1tHQcuKhqYiDUo57uOWOtW_mUqrHmsP9fZzaQRA2dW5k/edit?usp=sharing up to date? I wish to implement some of these functions :)

**Comment by UmashankarTriforce** [comment]
> https://docs.google.com/spreadsheets/d/1tHQcuKhqYiDUo57uOWOtW_mUqrHmsP9fZzaQRA2dW5k/edit?usp=sharing

Is this document up to date? I wish to implement some of these functions present in the document

**Comment by takagi** [comment]
I can not have kept the list up to date, but your contribution is still highly welcome. Additionally to the document, please check the latest master if a function is implemented or not. Thanks for your interest to contribute!

Anyway, I will review the list soon.

**Comment by UmashankarTriforce** [comment]
> Anyway, I will review the list soon.
I'm adding whatever I see has changed in chainer to the list too :)

**Comment by takagi** [comment]
Additionally we now have new CPP-based ChainerX engine, and we also want help for implementing its routines: https://github.com/chainer/chainer/issues/6423 . Please check it too if you are interested in.

**Comment by UmashankarTriforce** [comment]
Yes I'll check it out too 👍
