### ISSUE TITLE
Slow split_axis, concat and pack functions because of separate non-async memory copies.

### ISSUE THREAD

**Issue by takagi** [chainer/chainer#1492]
I heard that `split_axis`, `concat` and `pack` functions are slow because of separate non-async memory copies.

> The current GPU implementation of split_axis (and concat) is very slow because it consists of many separate non-async cuda_memcpy calls

These functions uses `cupy.concatenate` and `cupy.split` in their GPU implementation. Among them, I suppose that `cupy.concatenate` does have memory assignment in the following lines, `cupy.split` just makes views.

https://github.com/pfnet/chainer/blob/856ec09f0f38d77d07683f7e913b02d78297639c/cupy/manipulation/join.py#L80

``` Python
skip = (slice(None),) * axis
i = 0
for a in tup:
    aw = a.shape[axis]
    ret[skip + (slice(i, i + aw),)] = a
    i += aw
```

`cupy.ndarray`'s `__setitem__` method is in terms of `elementwise_copy` which is implemented as ufunc, which comes with kernel execution for memory assignment.

I'm not sure if this is "non-async cuda_memcpy calls" he says, at least kernel execution is async respect to CPU and ordinal ufunc calls seem not to use concurrency wit streams specified.

Any advices or corrections on this?

**Comment by jekbradbury** [comment]
Hey, thanks for following up on my comment in the spreadsheet. You're right that cupy.split doesn't do any memcpy -- it's still slightly slower than split_axis on CPU though (I'm not sure why). What I mean by non-async with respect to cupy.concatenate is this (screenshot from NVIDIA Visual Profiler):
![screenshot from 2016-08-15 11 59 09](https://cloud.githubusercontent.com/assets/11729078/17675704/b635e2ca-62df-11e6-8ccd-817dd407c0fd.png)
Basically, only 10% of execution time during a typical cupy.concatenate call is actual GPU computation.
Here's some test code:
```
 #!/usr/bin/python3

import os
os.environ['CHAINER_TYPE_CHECK'] = '0'
import numpy
import chainer
from chainer import functions as F

import time
from contextlib import contextmanager
@contextmanager
def time_block(name, proc=False):
    startTime = time.time()
    print(name, end='', flush=True)
    yield
    elapsedTime = time.time() - startTime
    print(' finished in {0:.2f}ms'.format(elapsedTime*1000), flush=True)

def shuffle_tuple(tup):
    l = list(tup)
    numpy.random.shuffle(l)
    return tuple(l)

x = chainer.Variable(numpy.random.random((1024,1024)),volatile='on')

for i in range(10):
    with time_block('CPU split_axis ...'): x_split = F.split_axis(x,1024,axis=0)
    x_split = shuffle_tuple(x_split)
    with time_block('CPU concat ...'): x = F.concat(x_split,axis=0)
    with time_block('copy to GPU ...'): x = F.copy(x, 0)
    with time_block('GPU split_axis ...'): x_split = F.split_axis(x,1024,axis=0)
    x_split = shuffle_tuple(x_split)
    with time_block('GPU concat ...'): x = F.concat(x_split,axis=0)
    with time_block('copy to CPU ...'): x = F.copy(x, -1)
    print()
```
And some timings:
```
CPU split_axis ... finished in 4.87ms
CPU concat ... finished in 2.54ms
copy to GPU ... finished in 0.97ms
GPU split_axis ... finished in 6.25ms
GPU concat ... finished in 13.55ms
copy to CPU ... finished in 2.28ms

CPU split_axis ... finished in 4.91ms
CPU concat ... finished in 3.29ms
copy to GPU ... finished in 0.96ms
GPU split_axis ... finished in 6.01ms
GPU concat ... finished in 13.23ms
copy to CPU ... finished in 1.05ms
```

**Comment by takagi** [comment]
Thanks! I will try to reproduce your situation with the test code, it is very helpful.
