### ISSUE TITLE
Check if batch statistics have been accumulated for BN in test mode

### ISSUE THREAD

**Issue by tscohen** [chainer/chainer#1522]
Currently, when calling BN with test=True and finetune=False before having accumulated statistics, the output will contain nan/inf values, because we divide by self.avg_var which is initialized to zero. It would be nice to add a flag to check if any statistics have been accumulated, and warn the user if they try to call BN in test mode before having accumulated statistics.

**Comment by delta2323** [comment]
Thank you for reporting the issue. This seems to be related to #879. It is relatively an old issue and I almost forgot it.
