### ISSUE TITLE
cupy support for complex numbers

### ISSUE THREAD

**Issue by boeddeker** [chainer/chainer#1525]
Internally we are interested to use complex numbers in cupy, therefore we are implementing a modified version of cupy for complex numbers. Is there an interest for complex numbers?
If yes, I would prepare a pull request, when all tests are running.

**Comment by tscohen** [comment]
Very interested. Chainer should support as many elementary data types and operations as possible, to support testing of new and unforeseen architectures. In my opinion, complex numbers should be near the top of the list of things to add.

I suppose you know this already, but it seems like numpy supports complex numbers by internally adding a length 2 axis to the end of the array:
```
x = np.random.randn(3, 2)
y = x.view('complex')  # A shape (3, 1) complex array, with y.real = x[:, 0] and y.imag = x[:, 1]
```
I once used this to hack some rudimentary complex number support in Chainer, but it would be preferable to have transparent support in cupy.

Do you plan to add support to Chainer as well? E.g. complex Linear and Convolution operations?

**Comment by LukasDrude** [comment]
Quite a few Chainer links are already working with complex values on the CPU. We just started to add the corresponding GPU code calling our Cupy generalization.

**Comment by tscohen** [comment]
Really? The Linear op doesn't seem to support complex types, as there is no complex conjugate in the backwards() operation (see https://github.com/pfnet/chainer/blob/master/chainer/functions/connection/linear.py).

Is the complex number support documented somewhere?

**Comment by LukasDrude** [comment]
We started writing (new) links for each complex operation we were interested in.

Within this feature discussion, we would like to focus on sharing cupy code first.

**Comment by boeddeker** [comment]
I know, that numpy saves the real and imag near to each other, but it is an interesting conversion with view.

Since many math in cupy is build with universal functions the implementation for complex numbers is not very difficult.

In the following I describe some points, which could be discussed:

For the universal functions the type thrust::complex<float or double> is working and supports many operations.

For casting in cuda/function.pyx it is a bit difficult, because int128 does not exist. But the following works:
```
cdef class CInt128(CPointer):
    cdef:
        double complex val

    def __init__(self, double complex v):
        self.val = v
        self.ptr = <void*>&self.val
```

In core/elementwise.pxi a casting is required, because thrust::complex<T> has no assignment rule for arbitary types (only type T is for assignment allowed). This error appears when there is a unsafe casting for the copy ufunc 
```
         if args_info[i][0] is ndarray:
             op.append(
-                'const in{0}_type in{0} = _raw_in{0}[_ind.get()];'.format(i))
+                'const in{0}_type in{0} = in{0}_type(_raw_in{0}[_ind.get()]);'
+                .format(i))
 
     for i, x in enumerate(out_types):
-        types.append('typedef %s out%d_type;' % (_get_typename(x), i))
-        op.append('{1} &out{0} = _raw_out{0}[_ind.get()];'.format(
-            i, _get_typename(args_info[i + len(in_types)][1])))
+        types.append('typedef %s out%d_type;' % (
+            _get_typename(args_info[i + len(in_types)][1]), i))
+        op.append('out0_type &out{0} = _raw_out{0}[_ind.get()];'.format(i))
```

In the next days I will add the changes to a public repository.

**Comment by delta2323** [comment]
Hi
Thank you for sharing the information. We are interested in your implementation that supports complex numbers. We are wondering to what extent the implementation depends on thrust. As we would like Chainer to be minimal and be dependent on as small number of third libraries as possible.

**Comment by jheymann85** [comment]
AFAIK thrust as we use it here is already included in the CUDA Toolkit (see https://developer.nvidia.com/thrust -> Availability). So no additional libraries would be required.

**Comment by delta2323** [comment]
> AFAIK thrust as we use it here is already included in the CUDA Toolkit 

I see. Thank you for your information. We currently support not only latest one but also CUDA >= v6.5. Is thrust included in the previous version of CUDA toolkit (You do not I would let me know if you know it. you do have to go out of the way to investigate it to answer my question)?

**Comment by jheymann85** [comment]
Thrust is included in all versions >= 6.5. However, ``thrust::complex`` was introduced in thrust 1.8.0 so I think it might only work with CUDA versions >= 7.0.

**Comment by delta2323** [comment]
Thank you for your response. So there are two options

* CuPy supports complex numbers only when CUDA >= 7.0
* Implement complex numbers that does not use thrust and switch the implementation depending on the CUDA version.

**Comment by boeddeker** [comment]
> CuPy supports complex numbers only when CUDA >= 7.0

That is possible, but there is the problem, that we have only the newest CUDA installed and it is not possible to install an old version. Therefore we get problems to implement this. I think the required changes are 
- remove  include of `#include <thrust/complex.h>` in cupy/core/carray.cuh if CUDA < 7
- disable all testcases
- catch exceptions from nvcc and improve exception msg with the information that cupy complex requires CUDA >= 7

> Implement complex numbers that does not use thrust and switch the implementation depending on the CUDA version.

This means, self implement thrust::complex, that is in my opinion the worst case. (Reimplementing something that is part of the standard library)

There is also a third option: Wait until chainer requires CUDA >= 7.0

**Comment by beam2d** [comment]
CuPy now supports complex numbers (see https://github.com/cupy/cupy/releases/tag/v2.0.0rc1).
