### ISSUE TITLE
Add dummy operator methods to Variable

### ISSUE THREAD

**Issue by gwtnb** [chainer/chainer#1573]
`Variable`'s operators are assigned [here](https://github.com/pfnet/chainer/blob/v1.14.0/chainer/functions/math/basic_math.py#L526) but there are no comment in `Variable`'s source. We should write dummy methods with comments in `chainer/variable.py`.

**Comment by gwtnb** [comment]
Ref: #1382 #1527

**Comment by unnonouno** [comment]
Is this problem solved via #1527?

**Comment by beam2d** [comment]
I think the problem is solved at least when we consider the documentation. Please reopen if you find another problem related to this topic.
