### ISSUE TITLE
New Feature Cupy: For Loop 

### ISSUE THREAD

**Issue by arita37** [chainer/chainer#1581]
Hello,

It would be nice to be able to for loop in cupy.

Thanks

**Comment by delta2323** [comment]
Thank you for suggestion. Do you have some idea for the design of for loop in mind. It will be helpful if you write the typical usage of this feature with pseudo code.

**Comment by arita37** [comment]
Hello,

I think one way is to port simple C CUDA code into Python,
using NVDIA C Cuda sample code.

It would allow to match the for loop with GPU thread,....

Think specific only for loop is possible
Usage case: When we cannot replace the calculation by Matrix operation,
we need to use loop.

Thanks
