### ISSUE TITLE
ImageDataset raises ValueError: axes don't match array

### ISSUE THREAD

**Issue by cympfh** [chainer/chainer#1594]
when Color images and Grayscale images are mixed.

i wish to make match the dimentions (to color images').

**Comment by delta2323** [comment]
Thank you for suggestion. You mean it is better to convert the 2-dimensional array of the gray image into the 3-dimensional tensor if two types of images are mixed, don't you? So far as I know, there is no canonical way to do so. Do you have an idea for it?

**Comment by unnonouno** [comment]
The dataset automatically convert 2-dim array to 3-dim array, but its shape is not equal to that of other color images. It causes shape mismatch when `convert` method creates a mini-batch. We can provide additional option such as `n_channel` and make the method to reshape the image when a image is grayscale.
We need to consider specification for other shape of images such as png format containing alpha channel.
