### ISSUE TITLE
Function.backward's docstring says it returns tuple but some functions don't

### ISSUE THREAD

**Issue by muupan** [chainer/chainer#1624]
`Function.backward`'s docstring says it returns tuple: https://github.com/pfnet/chainer/blob/79fbe0338023a8ccab82d71e5dee6171f9b77ad4/chainer/function.py#L362

However, some functions' `backward` return list, not tuple: https://github.com/pfnet/chainer/blob/79fbe0338023a8ccab82d71e5dee6171f9b77ad4/chainer/functions/array/vstack.py#L42

We should fix the docstring to allow other types or fix violating functions.

**Comment by unnonouno** [comment]
It is better to fix functions to return tuples.

**Comment by muupan** [comment]
This is the case for `FunctionNode.backward` as well.
https://github.com/chainer/chainer/blob/master/chainer/function_node.py#L483
https://github.com/chainer/chainer/blob/master/chainer/functions/array/vstack.py#L43

**Comment by niboshi** [comment]
We might instead fix the documentation.
