### ISSUE TITLE
The documents of Standard Function implementations lead to misunderstanding about arguments

### ISSUE THREAD

**Issue by okdshin** [chainer/chainer#1653]
All children classes of Function can get not only Variable but also ndarray as their arguments. (#1221) 
However, the documents of them explain about only Variable. They lead users to misunderstanding and make #1221 meaningless.
The documents should be modified.

<img width="375" alt="2016-09-14 12 42 06" src="https://cloud.githubusercontent.com/assets/1490699/18499336/fc34e2f2-7a78-11e6-97d3-bde882d9dc58.png">

**Comment by delta2323** [comment]
Thank you for reporting the issue. It should be the document bug.

**Comment by beam2d** [comment]
See #3929 for a more general solution.

**Comment by Crissman** [comment]
Seems like implementation of Variable, NumPy, and CuPy arrays is current and sufficient to me. Confirming with @delta2323 why re-opened.

**Comment by delta2323** [comment]
Closed, as I confirmed the problem has been already solved.
