### ISSUE TITLE
Use NVTOOLSEXT_PATH to search nvToolsExt on Windows

### ISSUE THREAD

**Issue by gwtnb** [chainer/chainer#1660]
Use `NVTOOLSEXT_PATH` instead of `CUDA_PATH` to find nvToolsExt on Windows. https://github.com/pfnet/chainer/blob/f13c41ac6111407710d4e3873c65b76199249378/chainer_setup_build.py#L45

**Comment by beam2d** [comment]
Resolved in CuPy, so closed it.

**Comment by kmaehashi** [comment]
Seems to be resolved in https://github.com/chainer/chainer/pull/2423
