### ISSUE TITLE
Implement N-dimensional LSTM

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#169]
- Grid LSTM (with short description of multidimensional LSTM) : http://arxiv.org/abs/1507.01526
- Multidimensional RNN : http://arxiv.org/abs/0705.2011

**Comment by llllaaaa** [comment]
@delta2323 Hi, will Grid LSTM be release soon? Also, is there a plan to implement Gated Feedback LSTM and GRU? Thanks.

**Comment by delta2323** [comment]
@llllaaaa Thank you for your interest to Chainer. I am afraid we do not have some specific release plan to implement variants of LSTM or GRU.

**Comment by delta2323** [comment]
We are now implementing GRU. See #419

**Comment by prajdabre** [comment]
Hi,
I would like to implement this for chainer.

**Comment by arita37** [comment]
Multi-dimensionnal LSTM would be very nice feature in chainer.

**Comment by prajdabre** [comment]
Hi,
Ok... I will try to implement this in the coming weeks and send a pull request.

**Comment by prajdabre** [comment]
Hi,

I finally managed to get around to implementing this.
I have implemented the Grid versions of LSTM, GRU and then one which can mix LSTMs and GRUs.
Let me know if anyone still wants this and I will send a pull request.

**Comment by beam2d** [comment]
@prajdabre Hi, sorry for being late to respond. We are interested in your implementation, so would you send a PR?

**Comment by prajdabre** [comment]
@beam2d I have implemented stacked LSTMS/GRUs and Grid LSTMs/GRUs and sent a pull request about a week ago.
https://github.com/pfnet/chainer/pull/1124
Do you need separate pull requests?
