### ISSUE TITLE
Use HTTPS for the official websites

### ISSUE THREAD

**Issue by beam2d** [chainer/chainer#1695]
`chainer.org` currently does not use HTTPS, while it may have a negative effect on web search ranking (e.g., [Google uses it as a ranking signal](https://webmasters.googleblog.com/2014/08/https-as-ranking-signal.html)). We should consider making the website support/force HTTPS even though we do not have any POST requests. This would also be applied to the official documentation hosted via readthedocs.

**Comment by niboshi** [comment]
What's the blocking factor of this issue?

**Comment by beam2d** [comment]
AFAIK, there is no critical blocking factor, and there is only a matter of human resources.
