### ISSUE TITLE
Clarify how to correctly set up environment and build Chainer with them

### ISSUE THREAD

**Issue by beam2d** [chainer/chainer#1696]
There is a diversity of the CUDA/cuDNN environments, e.g. someone have cuDNN installed at the same directory as CUDA libraries, while one may put it in their home directory. It is unclear what happens when one have multiple versions of CUDA/cuDNN installed (some of my colleagues are confused).

We should make a document that clearly explains the recommended way to set up CUDA/cuDNN, and some case studies of how to correctly build and link Chainer with these libraries within various possible environments (including those that we do not recommend). It is great if we can find and solve issues of installation during writing such a document.

**Comment by unnonouno** [comment]
I found that distutils correctly parse `LDFLAGS` and `CFLAGS`.

```
$ LDFLAGS=-L/path/to/cudnn/lib64 CFLAGS=-I/path/to/cudnn/include pip install chainer
```

**Comment by beam2d** [comment]
Close since it's old. If you have a difficulty on installing Chainer/CuPy, please ask us at forums, StackOverflow, or slack.
