### ISSUE TITLE
Make CPU-mode faster

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#174]
Though currently we are focusing on GPUs, many users want to use Chainer on CPU that is too slow now. We can make it faster.
Here are my ideas:
- OpenBLAS supports multi-threading, but I don't know its performance
- Make `forward_cpu_native` that uses C extension
- Use multi-processing of Python (multi-threading is not fast in Python). How about `multiprocessing.Queue`? https://docs.python.org/3/library/multiprocessing.html

**Comment by MannyKayy** [comment]
+1 on this
