### ISSUE TITLE
Output shape of batch_matmul

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#1765]
batch_matmul function always returns 3-dim array. I always reshape a returned variable.

z = batch_matmul(x, y)
- x.shape = (2, 3, 4) y.shape = (2, 4, 5) -> z.shape = (2, 3, 5)
- x.shape = (2, 4) y.shape = (2, 4, 5) -> error
  - (2, 5) ?
- x.shape = (2, 3, 4) y.shape = (2, 4) -> z.shape = (2, 3, 1)
  - (2, 3)?
- x.shape = (2, 4) y.shape = (2, 4) -> error
  - (2,)?

**Comment by muupan** [comment]
When I design `matmul` and `batch_matmul`, I intended to make its interface consistent in that 1-D arrays are always treated as column Mx1 matrices, but `numpy.matmul`-like interface would be more helpful.

http://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html
> If the first argument is 1-D, it is promoted to a matrix by prepending a 1 to its dimensions. After matrix multiplication the prepended 1 is removed.
> If the second argument is 1-D, it is promoted to a matrix by appending a 1 to its dimensions. After matrix multiplication the appended 1 is removed.

**Comment by unnonouno** [comment]
OK. I think users will expect that a function returns same value when numpy has the same name of method. I want to rename it or fix its behavior. Does anyone have an idea about it?
