### ISSUE TITLE
Test Function.__call__, corresponding python functions and Link.__call__ when inputs are ndarrays

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#1797]
Chainer functions (i.e. the instances of derived class of `chainer.Function`) can accept NumPy and CuPy ndarray (#1221), as well as Variables. But as it is not tested yet, it is risky to add this feature to the document (as proposed by #1653 and implemented by #1687). So we need to add such tests. As Chainer has many `Function` instances, some systematic mechanism to implement tests is needed.

**Comment by unnonouno** [comment]
There are two main reasons for this problem:
- Users doesn't use Function instances directly and instead they use corresponding methods. Some methods check types, shapes or something like that of arguments. It may have a bug.
- Links also treat arguments directly. Some links cannot treat ndarrays.
Note that Function instance itself supports ndarrays. So, we don't need to test with Function instances (and it helps nothing).
