### ISSUE TITLE
Use initializer in NStepLSTM

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#1816]
The initialization method of current `NStepLSTM` link is fixed to sampling from Gaussian distribution (see [here](https://github.com/pfnet/chainer/blob/master/chainer/links/connection/n_step_lstm.py#L62)). One of the possible extension of this link is to add initializers to the argument and use it in `__init__`.

**Comment by MannyKayy** [comment]
Reopening this issue:

![image](https://user-images.githubusercontent.com/7952854/39865715-b23fcaf6-5445-11e8-8060-f50848978401.png)


Runtime Info:

Chainer: 5.0.0a1
NumPy: 1.13.0
CuPy:
  CuPy Version          : 5.0.0a1
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 8000
  CUDA Driver Version   : 9020
  CUDA Runtime Version  : 8000
  cuDNN Build Version   : 7102
  cuDNN Version         : 7102
  NCCL Build Version    : 2104
