### ISSUE TITLE
SerialIterator.is_new_epoch deprecated?

### ISSUE THREAD

**Issue by boeddeker** [chainer/chainer#1825]
The IntervalTrigger was changed to accept float periods, therefore the flag __is_new_epoch__ from the iterators are never used and maybe deprecated.

```
$ grep -r "is_new_epoch" *
dataset/iterator.py:    - ``is_new_epoch``: True if the epoch count was incremented at the last
iterators/multiprocess_iterator.py:        self.is_new_epoch = False
iterators/multiprocess_iterator.py:        self.is_new_epoch = False
iterators/multiprocess_iterator.py:        self.is_new_epoch = serializer('is_new_epoch', self.is_new_epoch)
iterators/multiprocess_iterator.py:                self.is_new_epoch = True
iterators/serial_iterator.py:        self.is_new_epoch = False
iterators/serial_iterator.py:            self.is_new_epoch = True
iterators/serial_iterator.py:            self.is_new_epoch = False
iterators/serial_iterator.py:        self.is_new_epoch = serializer('is_new_epoch', self.is_new_epoch)
training/triggers/interval.py:            return updater.is_new_epoch and updater.epoch % self.period == 0
training/updater.py:    def is_new_epoch(self):
training/updater.py:        return self._iterators['main'].is_new_epoch
```

**Comment by delta2323** [comment]
Thank you for pointing out the issue. There are several things to consider to determine if we should make `is_new_epoch` deprecated or not.

As you mentioned, `IntervalTrigger` doesn't use `Iterator.is_new_epoch` any longer. But users can freely use this attribute for creating their custom triggers. On the other hand, `Trigger.is_new_epoch` is prone to cause the issue that `IntervalTrigger` had and solved in #1423.

**Comment by boeddeker** [comment]
OK, I only wanted to mention this.

I ran in the problem, that I wrote my own evaluator, which push the data to a log reporter for all kind of types (also matrices) and used `is_new_epoch` to ensure that the `IntervalTrigger` does not trigger.

But it is confusing, that there is a flag, that is no longer used and has such a special meaning.

I think this issue can be closed.

**Comment by delta2323** [comment]
Thank you for sharing the problem you encountered. In my opinion, we should keep the issue open because the situation is not ideal and there can be a pitfall.
