### ISSUE TITLE
Support other types of RNNs of cuDNN

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#1843]
cuDNN RNN supports various types of RNNs. Currently Chainer supports only LSTM (NStepLSTM).

- [x] ReLU
- [x] Tanh
- [x] GRU
- [x] Bidirectional

**Comment by ywatanabex** [comment]
I have NStepGRU which wraps cuDNN GRU. I'll send a PR soon.

**Comment by honnibal** [comment]
I am interested in Bidirectional. I'm very glad to see the cuDNN RNN in Chainer. I'd like to use this in spaCy.

**Comment by honnibal** [comment]
I think the `NStepLSTM` class should be generalised to `NStepRNN`. Flags can control direction and mode. There can be subclasses for the combinations if desired. I've started work on this:

https://github.com/honnibal/chainer/commit/73ebedc7c932291f2142c21c9095c64f8ccd8036

I haven't tested this yet. Does the approach look okay? It should be quite easy to finish.

**Comment by unnonouno** [comment]
Thank you! @ywatanabex @honnibal 
Actually we are now developing this feature. And, @honnibal 's implementation is what I want to make! 

Now we are investigating the details of the specification of cudnn-rnn. We found two points:
- `cx` can be `null` when a user selects GRU
- definition of GRU is different from Chainer's one

**Comment by honnibal** [comment]
Okay, so you are developing this in another branch?

**Comment by aonotas** [comment]
Thank you! @honnibal 

I think there is no-branch for this issue.
Please send your PR, I'll help your code.

**Comment by ywatanabex** [comment]
Hi, here is my Bidirectional GRU code:
  https://github.com/ywatanabex/chainer/commit/865f2b6d0c525e80ae78e62ec0c7ca61df300510

Hopefully, this is helpful to implement general cuDNN-RNN wrapper.

**Comment by unnonouno** [comment]
All RNN types are now supported.
