### ISSUE TITLE
N-dimensional pooling on cuDNN v2 not working with inputs other than two-dimensional ones

### ISSUE THREAD

**Issue by takagi** [chainer/chainer#1905]
With cuDNN v2, applying N-dimensional pooling to inputs other than two-dimensional ones returns `CUDNN_STATUS_NOT_SUPPORTED` error.

It looks curious because the situation says that cuDNN v2 provides an API named `cudnnSetPoolingNdDescriptor` besides `cudnnSetPooling2dDescriptor`, but the former works only for two-dimensional inputs.

To avoid the problem, anyway, #1353 currently employs CuPy implementation for N-dimensional pooling for inputs other than two-dimensional ones on environments with cuDNN v2.

**Comment by niboshi** [comment]
Closing because cuDNN v2 is not supported any more.
