### ISSUE TITLE
Replace the direct nvcc call in compiler.py with NVRTC

### ISSUE THREAD

**Issue by mitmul** [chainer/chainer#1918]
Current chainer needs to run nvcc using subprocess module to compile CUDA codes. This process needs to save the source code to the disk to compile it.

Can this part of the runtime compilation of CUDA codes be replaced with NVRTC? NVRTC is an official runtime compilation library for CUDA C++. It can take a CUDA source code in character string form and compile it.

NVRTC: http://docs.nvidia.com/cuda/nvrtc/index.html

It might be more efficient and it can remove `subprocess` module dependency.

**Comment by beam2d** [comment]
This has not been done for supporting CUDA 6.5 environments while keeping the code base simple. We can support it as an optional feature, but I think we can just replace the current nvcc calls by NVRTC in v2 and cut the CUDA 6.5 support.

**Comment by mitmul** [comment]
This PR solved it. https://github.com/cupy/cupy/pull/62
