### ISSUE TITLE
Make a list of APIs to clean up

### ISSUE THREAD

**Issue by beam2d** [chainer/chainer#1932]
In order to tackle with better design of existing APIs for v2, we have to make a list of candidate changes on the APIs. I will prepare the list and keep it updated during the development of v2.

**Comment by beam2d** [comment]
I made a list of possible changes: https://gist.github.com/beam2d/f7b817c3ce6ada32a1f9c8cc7dea4a5a. Any comments are welcome.

**Comment by jekbradbury** [comment]
I would switch the way L.LSTM stores its weights to not use the unintuitive striding of gate weights (i.e. replace _extract_gates with xp.split); that's the main difference

**Comment by unnonouno** [comment]
That sounds good and is more intuitive!

**Comment by delta2323** [comment]
I think it is time to review the list again to check we miss any important issues left.

**Comment by beam2d** [comment]
This issue can be closed now since v2 was already released.
