### ISSUE TITLE
Add docstring of __call__ method of links to the document.

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#1933]
Most users apply concrete links with `__call__`. As base `Link` class does not offer default `__call__` method, it is up to each concrete link how to define its interface. So it is natural the document should offer the document of `__call__` of each link (or at least some exceptional links, as the interface of most links are identical) But current document does not offer them.

**Comment by beam2d** [comment]
It looks most links already has docstring for `__call__`, so I'll close it. Please open a new issue if you find a concrete link class that lacks the docstring.
