### ISSUE TITLE
DilatedConvolution2D is slow

### ISSUE THREAD

**Issue by haqishen** [chainer/chainer#1941]
hello, 
I've tried DilatedConvolution2D and found that it's much slower than Convolution2D with GPU and cudnn.
I supposed that the speed of 5x5 Convolution and 3x3,dilate=2 DilatedConvolution should be the same.
But in this case actually DilatedConvolution is only 1/3  as fast as Convolution.

I guess the usage of for loop have slowed down the forward_GPU and backward_GPU.
However I failed to improve it because 'Advanced Indexing is not supported.'

Any one have idea on it?

Thanks.

**Comment by bordingj** [comment]
maybe this helps [https://github.com/tomlepaine/fast-wavenet]
