### ISSUE TITLE
Why is copy.deepcopy used in the example code of chainer documentation?

### ISSUE THREAD

**Issue by kamo-naoyuki** [chainer/chainer#1953]
At http://docs.chainer.org/en/stable/tutorial/gpu.html#data-parallel-computation-on-multiple-gpus-without-trainer, you mentioned using the Link.copy method but actually copy.deepcopy is used in the following example. Why?

**Comment by delta2323** [comment]
Hi thank you for reporting the problem.

We fixed `example/mnist_data_parallel.py` to use the shape placeholder (i.e. set `None` as the input dimension of MLP) in #1551 and applied the change in the tutorial you mentioned in #1584. But as we do not the shape placeholder, the tutorial went inconsistent.

**Comment by kmaehashi** [comment]
Fixed via #4066.
