### ISSUE TITLE
I got a error on windows 10 during setup 

### ISSUE THREAD

**Issue by tarrabass** [chainer/chainer#1976]
Creating library build\temp.win32-3.5\Release\cupy\cuda\cublas.cp35-win32.lib and object build\temp.win32-3.5\Release\cupy\cuda\cublas.cp35-win32.exp
cublas.obj : error LNK2001: unresolved external symbol _cublasSger_v2@40
cublas.obj : error LNK2001: unresolved external symbol _cublasDgemv_v2@48
cublas.obj : error LNK2001: unresolved external symbol _cublasGetPointerMode_v2@8
cublas.obj : error LNK2001: unresolved external symbol _cublasSnrm2_v2@20
cublas.obj : error LNK2001: unresolved external symbol _cublasIsamin_v2@20
cublas.obj : error LNK2001: unresolved external symbol _cublasSasum_v2@20
cublas.obj : error LNK2001: unresolved external symbol _cublasSdot_v2@28
cublas.obj : error LNK2001: unresolved external symbol _cublasDestroy_v2@4
cublas.obj : error LNK2001: unresolved external symbol _cublasSgemmBatched@60
cublas.obj : error LNK2001: unresolved external symbol _cublasSaxpy_v2@28
cublas.obj : error LNK2001: unresolved external symbol _cublasDger_v2@40
cublas.obj : error LNK2001: unresolved external symbol _cublasSetStream_v2@8
cublas.obj : error LNK2001: unresolved external symbol _cublasGetVersion_v2@8
cublas.obj : error LNK2001: unresolved external symbol _cublasSdgmm@40
cublas.obj : error LNK2001: unresolved external symbol _cublasSgetriBatched@36
cublas.obj : error LNK2001: unresolved external symbol _cublasSscal_v2@20
cublas.obj : error LNK2001: unresolved external symbol _cublasDgemm_v2@56
cublas.obj : error LNK2001: unresolved external symbol _cublasSgemm_v2@56
cublas.obj : error LNK2001: unresolved external symbol _cublasGetStream_v2@8
cublas.obj : error LNK2001: unresolved external symbol _cublasIsamax_v2@20
cublas.obj : error LNK2001: unresolved external symbol _cublasSgetrfBatched@28
cublas.obj : error LNK2001: unresolved external symbol _cublasSgemmEx@68
cublas.obj : error LNK2001: unresolved external symbol _cublasSetPointerMode_v2@8
cublas.obj : error LNK2001: unresolved external symbol _cublasDaxpy_v2@28
cublas.obj : error LNK2001: unresolved external symbol _cublasDdot_v2@28
cublas.obj : error LNK2001: unresolved external symbol _cublasSgemv_v2@48
cublas.obj : error LNK2001: unresolved external symbol _cublasCreate_v2@4
build\lib.win32-3.5\cupy\cuda\cublas.cp35-win32.pyd : fatal error LNK1120: 27 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\link.exe' failed with exit status 1120

Environnement 
Windows 10 
python 3.5

**Comment by chenzhekl** [comment]
It seems that `cuBLAS` library can not be correctly linked. I didn't build `cupy` myself, but checking the installation of `CUDA` might be helpful.
