### ISSUE TITLE
Monitor training parameter statistics

### ISSUE THREAD

**Issue by hvy** [chainer/chainer#2005]
Sharing some experimental code for **monitoring and visualizing the statistics of model parameters during training**. It could for instance be used to detect exploding/vanishing weights and gradients. The interface is quite simple so you should be able to plug it into your existing code. 

Please note that I have not tested this exhaustively. Additionally, it is **not optimized for speed**. If parameters are stored on the GPU, they are copied to the CPU before computing percentiles since CuPy does not yet implement `numpy.percentile()`. 

https://github.com/hvy/chainer-param-monitor

I'd be glad to hear feedback.

**Comment by GeorgieJi** [comment]
Thanks, I'm looking for the tools like that you built. I'll try it later.

**Comment by delta2323** [comment]
@hvy  Does the `ParameterStatistics` extension solve this problem?

**Comment by hvy** [comment]
@delta2323 Yes, the `ParameterStatistics` extension is derived from the above mentioned experimental code. Thank you for pointing this out, I'll close this issue.

@GeorgieJi There is also another similar PR that additionally takes care of the visualizations (saves images). This extension is probably more practical as the log files won't grow and the user doesn't have the parse and plot the collected statistics by themselves. https://github.com/chainer/chainer/pull/3601
