### ISSUE TITLE
Make the number of axes for batch dimensions configurable in Linear

### ISSUE THREAD

**Issue by beam2d** [chainer/chainer#2019]
L.Linear accepts multiple channel dimensions. It is useful in computer vision applications where the output of the final convolution layer can be directly fed to a linear link. This feature can be seen as a flexible number of channel axes.

On the other hand, the number of batch axes is currently fixed to one, which would be cumbersome in some use cases, especially when we have to deal with a sequence of input arrays. In this case, the first two axes may be used to represent the mini-batch and the sequence. We currently need to reshape it before and after feeding it to the linear link, which has overheads both for coding and runtime.

It can be resolved by introducing an option to Linear (and also to the F.linear function) that indicates the number of batch axes.

The same discussions would also be applied to convolution links/functions.

**Comment by muupan** [comment]
Shouldn't the same discussions also be applied to all the other links and functions that assume the first axis is the only batch axis e.g. F.huber_loss and F.select_item?

**Comment by beam2d** [comment]
You're right. It should be applied to other functions that assume the batch axis as well.
