### ISSUE TITLE
Allow ignore_label configurable by init in softmax_cross_entropy

### ISSUE THREAD

**Issue by beam2d** [chainer/chainer#2046]
We need a way to configure the ignore label value only using the softmax_cross_entropy function.

**Comment by bkvogel** [comment]
OK, how about if I add an optional argument `ignore_label` to the function? Do you have any thoughts on constraining the possible values (for example, anything other than a non-negative integer that supports equality comparison). I think it is fine to make this configurable, but maybe I do not understand the motivation. Is it to reduce additional preprocessing work by users who might already have target labels that use some other ignore label other than -1?

**Comment by beam2d** [comment]
`ignore_label` option has been added to `softmax_cross_entropy`.
