### ISSUE TITLE
Make type checking enabled only in debug mode by default

### ISSUE THREAD

**Issue by beam2d** [chainer/chainer#2047]
Type checking and the debug mode are often used for debugging. The former checks the shape and dtype of inputs to each Function, while the latter, for example, checks if NaN appears in the intermediate results (including the backward path). While the former is enabled by default, the latter is disabled, which makes the best practice of taking the trade-off between the performance and debugging capability a bit complicated. I want to align the behaviors and make type checking disabled by default and enabled by enabling the debug mode (or make it enabled by default and disabled by disabling the debug mode).

**Comment by delta2323** [comment]
Do you have any consideration about the relation with Light-weight type checking #1692?

**Comment by beam2d** [comment]
Close since no update is made for a long time. #2136 would be helpful.
