### ISSUE TITLE
Implement separate functions for get_device from id and array

### ISSUE THREAD

**Issue by beam2d** [chainer/chainer#2051]
cuda.get_device accepts both a device id and an object. When an id is given, it returns a device of the corresponding ordinal. When an object is given, it checks the type and returns a device if the type is cupy.ndarray. This behavior is complicated and often introduces bugs when we take care of the performance. I think it is enough to provide two functions: get_device_from_id (which takes an id and returns the corresponding device) and get_device_from_array (which takes an input and returns the device if the argument is cupy.ndarray). It much simplifies the interface and implementation.

**Comment by mitmul** [comment]
Fixed by https://github.com/chainer/chainer/pull/2391 and https://github.com/chainer/chainer/pull/2890
