### ISSUE TITLE
4D-Convolution Error

### ISSUE THREAD

**Issue by jhjacobsen** [chainer/chainer#2065]
I am trying to run a model with 4-dimensional (3D+time) convolutions.
I am using ConvolutionND for this purpose. However, even though it works fine for 3D, I get the following error with 4D convolutions:

```
  File "cupy/cuda/cudnn.pyx", line 515, in cupy.cuda.cudnn.getConvolutionForwardAlgorithm (cupy/cuda/cudnn.cpp:5510)
  File "cupy/cuda/cudnn.pyx", line 525, in cupy.cuda.cudnn.getConvolutionForwardAlgorithm (cupy/cuda/cudnn.cpp:5368)
  File "cupy/cuda/cudnn.pyx", line 323, in cupy.cuda.cudnn.check_status (cupy/cuda/cudnn.cpp:1959)
cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_NOT_SUPPORTED: CUDNN_STATUS_NOT_SUPPORTED
```
I tried to install chainer with pip install and to build from source. The problem occurs in both cases.

cudnn is v5.1
cuda is v7.5 and I tried with v8.0 as well, same issue

**Comment by takagi** [comment]
Could you show the parameters you passed to `ConvolutionND` function? cuDNN seems to have undocumented conditions supported. When I implemented the multi dimensional convolution layer, it caused me some difficulties.

**Comment by jhjacobsen** [comment]
Thanks a lot for your quick answer. I initialize it as follows:

conv=L.ConvolutionND(4, 1, 16, 3, 1, use_cudnn=False)

**Comment by takagi** [comment]
I will try to reproduce the cuDNN error with your parameter set with extending the test of `ConvolutionND` link. It would be in a week or so because I have no access to my machine now.

**Comment by jhjacobsen** [comment]
I am already using the CuPy implementation, it works fine, I was just hoping for a speedup with the cuDNN version. Let me know if you get cuDNN to work at some point and thank you for the quick reply and check!

**Comment by takagi** [comment]
Okay!
