### ISSUE TITLE
Bilateral filtering 

### ISSUE THREAD

**Issue by DianeBouchacourt** [chainer/chainer#2098]
Do you plan on implementing bilateral filtering as activation function ? I would like to use it but in order to compute the gradient I would have to derive the gradient explicitely from the calculated gradient of the loss.

**Comment by delta2323** [comment]
Hi, currently we do not have a plan to implement the function. If you write its forward propagation with a combination of Chainer `Function`s, you can automatically calculate its gradient. Of course, you can  alternatively implement bilateral filtering as a single Chainer `Function`.
