### ISSUE TITLE
No document on usage of extension.name attribute by Trainer.extend

### ISSUE THREAD

**Issue by muupan** [chainer/chainer#2100]
`Trainer.extend` checks `extension.name` attribute before `extension.default_name` when `name` argument is `None`, but its docstring only mentions `extension.default_name`.

https://github.com/pfnet/chainer/blob/f34c20e45dc86dfa6bbc62e080be3fd97aa3f466/chainer/training/trainer.py#L202
https://github.com/pfnet/chainer/blob/f34c20e45dc86dfa6bbc62e080be3fd97aa3f466/chainer/training/trainer.py#L181

**Comment by muupan** [comment]
I think this issue should be fixed because it means the current documentation is wrong.

**Comment by muupan** [comment]
This is not yet resolved
https://github.com/chainer/chainer/blob/master/chainer/training/trainer.py#L194-L197
https://github.com/chainer/chainer/blob/master/chainer/training/trainer.py#L219

**Comment by Crissman** [comment]
Fixed with #4980
