### ISSUE TITLE
Googlenet example crashes when run on 4 gpus with nvprof

### ISSUE THREAD

**Issue by deepali-c** [chainer/chainer#2139]
We have updated `googlenet `example to execute it on `multiple gpus` and executed it on `4 gpus`. 

It worked fine when I executed it without `nvprof`, but next I executed it with `nvprof --print-gpu-trace` and observed that the main process which is being profiled by `nvprof `crashes after some epochs.

**Comment by deepali-c** [comment]
I further observed that it is crashing with 2 and 3 gpus as well when run with `nvprof --print-gpu-trace`. 
Has anyone else observed this ?

**Comment by delta2323** [comment]
Hi, thank you for reporting the problem.
As far as I know, the example that uses GoogLeNet is `examples/imagenet/`, but it basically runs with single GPU. Did you change some part of the example? Also, I would like the command use executed. Thank you.

**Comment by deepali-c** [comment]
Yes I've modified code to support multiple gpus. 

I used my own dataset that had 3072 training images and 384 validation images. The command used was:
`nvprof  --print-gpu-trace  python train_imagenet_data_parallelism.py --arch googlenet --batchsize 64 --epoch 55  --gpu 0,1,2,3 --root <path to the folder that contains the images> --mean my_dataset.npy --out <out_dir> train.txt val.txt`

**Comment by delta2323** [comment]
Then shall we run `train_imagenet.py` with single GPU with `nvprof` to see if the problem is in the original code or in what you have changed?

**Comment by deepali-c** [comment]
The `googlenet` model works fine when used with 1 GPU. However, `alexnet `model shows similar crash with 1 gpu as well and this happens when run with/without `nvprof`. 

The commands I used to execute `alexnet `is:
`python train_imagenet.py --arch alex --batchsize 64 --epoch 55  --gpu 0 --mean my_dataset.npy   --root <path to the folder that contains the images> --out <out_dir> train.txt val.txt `
and 
`nvprof  --print-gpu-trace python train_imagenet.py --arch alex --batchsize 64 --epoch 55  --gpu 0 --mean my_dataset.npy   --root <path to the folder that contains the images> --out <out_dir> train.txt val.txt`

**Comment by delta2323** [comment]
OK, I will try that.

**Comment by delta2323** [comment]
Hi, I ran the code with the command for several days. But it does not stuck with Alexnet in my environment. You mentioned that the problem may be in creating snapshots. But my code does seem to make it successfully.

**Comment by deepali-c** [comment]
Sharing the modified multiGPU version of the code 
[train_imagenet_data_parallelism.py.txt](https://github.com/pfnet/chainer/files/773224/train_imagenet_data_parallelism.py.txt)
which we have used for executing googlenet with more than 1 GPUs. 

The modification is done by @tungld and is similar to the example `train_mnist_data_parallelism.py` for training mnist with multiple GPUs. 

I executed the following command and observed crash after 12th epoch. 
```
nvprof --print-gpu-trace  python train_imagenet_data_parallelism.py --arch googlenet --batchsize 64 --epoch 55  --gpu 0,1,2,3 --root <path to root folder> --mean my_meandataset.npy --out <chainer_train_output> train.txt val.txt
GPU: 0,1,2,3
==53715== NVPROF is profiling process 53715, command: python train_imagenet_data_parallelism.py --arch googlenet --batchsize 64 --epoch 55 --gpu 0,1,2,3 --root <path to root folder> --mean my_meandataset.npy --out <chainer_train_output> 
epoch       iteration   main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  lr
1           48          8.73289                           0.0794271                                0.01
2           96          4.46465                           0.0885417                                0.01
3           144         4.10342                           0.0677083                                0.01
4           192         4.0689                            0.0729167                                0.01
5           240         4.07031                           0.0976562                                0.01
6           288         4.04518                           0.0846354                                0.01
7           336         4.04598                           0.0885417                                0.01
8           384         4.03605                           0.0872396                                0.01
9           432         4.05518                           0.0794271                                0.01
10          480         4.05854                           0.0794271                                0.01
11          528         4.02757                           0.0859375                                0.01
12          576         4.02355                           0.0846354                                0.01
```
