### ISSUE TITLE
a few examples in Jupyter Notebooks ?

### ISSUE THREAD

**Issue by stonebig** [chainer/chainer#2157]
A few Jupyter Notebooks examples may help to get new users and illustrate chainer qualities.

I would have been especially interested by **small** "style transfer" and "fast style-transfer" examples:
- ready-to-use-on-Windows / Python-3.6
- running well on  PC cpu with  4go RAM .

**Comment by LukasDrude** [comment]
I do not recommend this, since users tend to keep the notebook server running and then wonder why there GPU memory is still used after the training finished.
