### ISSUE TITLE
Implement cupy.percentile()

### ISSUE THREAD

**Issue by hvy** [chainer/chainer#2168]
Is it possible to implement `cupy.percentile()` similar to its NumPy counterpart?

It's not critical for training but necessary to run the parameter monitoring extension on the GPU (https://github.com/pfnet/chainer/pull/2166).  

The NumPy implementation can be found here https://github.com/numpy/numpy/blob/master/numpy/lib/function_base.py#L3993-L4111

**Comment by hvy** [comment]
Please see PR https://github.com/cupy/cupy/pull/643 .

**Comment by delta2323** [comment]
Closed, as this issue has been moved to CuPy repository and solved.
