### ISSUE TITLE
Implement cupy.ufunc.at

### ISSUE THREAD

**Issue by JanekEbb** [chainer/chainer#2198]
I would like to implement a take function that allows “fancy” indexing  (indexing arrays using arrays).
To take account of index arrays that index elements multiple times, I need to sum over the corresponding gradients of the output in the backward step.

numpy.ufunc.at (https://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.at.html) perfectly solves this task.

Is it possible to implement cupy.ufunc.at similar to its NumPy counterpart?

**Comment by yuyu2172** [comment]
There is `cupy.scatter_add` that does what you want.
