### ISSUE TITLE
duplicate import in functions/__init__.py

### ISSUE THREAD

**Issue by Hiroshiba** [chainer/chainer#2211]
ex. 
https://github.com/pfnet/chainer/blob/5211507808fa810ad85a59b8bdf5b81c65807b42/chainer/functions/__init__.py#L64
and
https://github.com/pfnet/chainer/blob/5211507808fa810ad85a59b8bdf5b81c65807b42/chainer/functions/__init__.py#L231

Then some chainer function have been warned by my IDE(PyCharm) such as this.
![image](https://cloud.githubusercontent.com/assets/4987327/22465002/ebaeca3c-e7fc-11e6-8697-00ae4721b913.png)

Thank you.

**Comment by niboshi** [comment]
This has been fixed in #2755. Thank you!
