### ISSUE TITLE
Operators in basic_math supports broadcast

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#228]

**Comment by delta2323** [comment]
To make broader ranges of functions applicable to broadcast. We plan to implement broadcast as `function`.

**Comment by entron** [comment]
Agree that when basic_math supports broadcast it could sometimes cause unexpected broadcast when a user makes a mistake. However, isn't making the API compatible to numpy thus making chainer easy to learn/use/port more meaningful?
