### ISSUE TITLE
Chainer CI on Jenkins need to modify .travis.YML file for linux OS

### ISSUE THREAD

**Issue by sudarshanpsl** [chainer/chainer#2295]
HI, 
I am porting chainer on power and need to have CI on jenkins. 
So i am integrating it with jenkis jobs , using Travis YML Plugin. 
While running i found that current travis.yml is written for only osx so need to make it compatible with linux as well. 
SO we may need to add support for linux there, can you help here. 

We are working on our own , will keep you posted.

**Comment by unnonouno** [comment]
We use travis for testing both linux and mac. travis.yml file in Chainer uses both. See the resuls: https://travis-ci.org/pfnet/chainer

BTW, we made test scripts for our jenkins here: https://github.com/pfnet/chainer-test
This script uses nvidia-docker for clean environment. And it tests not only unit test but also installation and examples. Mainly only we chainer developer use the script but it may help you.

**Comment by unnonouno** [comment]
Can i close this issue?
