### ISSUE TITLE
How can I do numpy advanced indexing in chainer?

### ISSUE THREAD

**Issue by speedcell4** [chainer/chainer#2343]
I mean how to do things like this

```python
>>> import numpy as np
>>> a = np.array([1, 2, 3, 4])
>>> b = np.array([True, False, False, True])
>>> c = np.array([2, 0, 1, 3])
>>> a[b]
array([1, 4])
>>> a[c]
array([3, 1, 2, 4])
```

I have tried `F.get_item` but the `slices` parameter was limited to be 
> int, slice, None or Ellipsis or tuple of them

not `np.narray`. 

So how can I do this?

**Comment by yuyu2172** [comment]
Hello.
This PR let's you do that https://github.com/pfnet/chainer/pull/2203.

**Comment by speedcell4** [comment]
Thank you so much, that helps a lot. Hope this PR will be merged soon

**Comment by speedcell4** [comment]
Sorry, but I found your RP is also limited, like numpy we can do this

```python
>>> a = np.array([1, 2, 3, 4])
>>> b = np.array([2, 0, 1, 3])
>>> a[b] += 1
>>> a
array([2, 3, 4, 5])
```

but in your RP

```python
>>> a = Variable(np.array([1, 2, 3, 4]))
>>> b = np.array([2, 0, 1, 3])
>>> a[b] += 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: only integer scalar arrays can be converted to a scalar index
```

**Comment by yuyu2172** [comment]
You are right. `__getitem__` does not support `+=` operation.

I would probably send PR that supports `+=` in the near future. Thanks.

**Comment by boeddeker** [comment]
Is it useful, when chainer Support +=? How is then ensured, that the backward step works?
