### ISSUE TITLE
Switch forward/backward method between the original and external library methods using chainer.config

### ISSUE THREAD

**Issue by mitmul** [chainer/chainer#2410]
We are going to have `chainer.config` to set arbitrary configurations that can be referred from not only user's codes but also from the inside of Chainer, since v2. And now an alternative CPU backend has been developed in https://github.com/intel/chainer.

So, having a new feature that enables us to "switch" the backend used in forward/backward of Chainer's Functions would be useful. And I expect that it's needed to specify the backends of different functions **independently**.

There are many possible designs to achieve this, so I'll make some blueprints here and I'd like to get feedbacks.

**Comment by delta2323** [comment]
Is this issue related to #2048 ?
