### ISSUE TITLE
Replace nose

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#2449]
nose is not maintained now. And, we are now facing an error message problem with multiprocess test. This problem will not be fixed. We need to replace it with another test framework such as nose2.

**Comment by unnonouno** [comment]
I surveyed nose2. 
- Same names of test files are not permitted in nose2. We have test cases which have the same names in functions_test and links_test. http://nose2.readthedocs.io/en/latest/differences.html#test-discovery-and-loading
- Current parameterized test does not work in multi-process condition of nose2. We need to replace them with nose2's parameterized test.

**Comment by kmaehashi** [comment]
We now moved to pytest.
chainer/chainer#3324
cupy/cupy#623
