### ISSUE TITLE
Installation problem for gpu chainer

### ISSUE THREAD

**Issue by AntreasAntoniou** [chainer/chainer#2464]
Hello guys,

I was able to install chainer with gpu support on my local machine in mere seconds. However while trying to install on a cluster I use, I have had lots of trouble, mainly because the CUDA and CUDNN directories are at a non standard location. Nevertheless I did everything as requested step by step and got the chainer setup to see the cuda and cudnn directories, however even then there is a problem generating a stub or something similar. I have the complete installation log [here](https://gist.github.com/AntreasAntoniou/c18f457eb9d5f1224a12738755291694)

Please, can someone help me?

**Comment by unnonouno** [comment]
Oh, sometimes it is difficult to install chainer on a GPU cluster.
As the error message says, the setup script failed to find libcuda.so.
https://gist.github.com/AntreasAntoniou/c18f457eb9d5f1224a12738755291694#file-chainer_installation_log-txt-L61

Please first search libcuda.so and add its location to `LDFLAGS`.
