### ISSUE TITLE
Dump the computational graph on error

### ISSUE THREAD

**Issue by beam2d** [chainer/chainer#252]
When Chainer raises an exception during forward computation, we can see the stack trace to identify which line of the code is the cause. We do not have any other way to identify the point of failure. It has two drawbacks:
1. If the code contains some structure that makes it hard to uniquely identify which node in the graph is the bug. For example, if the code contains a loop, we cannot determine the loop counter value from the error.
2. We cannot identify the node when the error occurs in backward computation, since the backward is not associated to the forward code.

I propose to dump the computational graph on error in forward/backward computation with the erroneous node highlighted. It makes easier to identify the erroneous node.

**Comment by unnonouno** [comment]
It's a good idea, but it's a little difficult to use graphviz in a server machine and to show its result. Visualizing in CUI is cool!

**Comment by beam2d** [comment]
Close. Please reopen or make a new one if anyone is still interested in it.
