### ISSUE TITLE
permutate function sometimes causes cudaErrorIllegalAddress

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#2527]
`permutate` function sometimes causes `cudaErrorIllegalAddress` on backward process when `cupy.take` is called. We need to investigate its detailed condition.

**Comment by Crissman** [comment]
Unno-san, please reconfirm this issue still exists.

**Comment by unnonouno** [comment]
I can't reproduce this error. I'll close it. When I find the situation, I'll reopen it.
