### ISSUE TITLE
Reorgnize tutorial & add new contents 

### ISSUE THREAD

**Issue by mitmul** [chainer/chainer#2576]
Let's improve documentation at the timing of new v2 release.
It's related to #2298, #2337, #1879.

✍️: Need modification
👁: Under review
✅: Done

## New Documentation

👁 Chainer at a Glance (#3127)

Tour of Chainer Code -> PG
- Deep Learning Neural Net
-    ✅ [CNNs -- Visual Recognition Tasks](https://github.com/chainer/chainer/blob/master/docs/source/tutorial/convnet.rst)
-    ✅ [RNNs](https://github.com/chainer/chainer/blob/master/docs/source/tutorial/recurrentnet.rst)
- 👁 LSTM -- language models (#3073)
- ✅ Word2vec (#3040)
- RL (DQN)
- GAN

Components of Chainer
   - ✍️  Define by Run (Part of: [Introduction to Chainer](https://github.com/chainer/chainer/blob/master/docs/source/tutorial/basic.rst))
   - ✅[GPUs -- how to use](https://github.com/chainer/chainer/blob/master/docs/source/tutorial/gpu.rst)
   - ✅[Type Checks -- how to use](https://github.com/chainer/chainer/blob/master/docs/source/tutorial/type_check.rst)
   - ✍️Variables and Derivatives (Part of: [Introduction to Chainer](https://github.com/chainer/chainer/blob/master/docs/source/tutorial/basic.rst))
   - ✅ [Functions](https://github.com/chainer/chainer/blob/master/docs/source/tutorial/function.rst)
   - ✍️Links (Part of: [Introduction to Chainer](https://github.com/chainer/chainer/blob/master/docs/source/tutorial/basic.rst))
   - ✍️Models (Part of: [Introduction to Chainer](https://github.com/chainer/chainer/blob/master/docs/source/tutorial/basic.rst))
   - ✍️Optimizers (Part of: [Introduction to Chainer](https://github.com/chainer/chainer/blob/master/docs/source/tutorial/basic.rst))
   - ✍️Datasets
   - ✍️Iterators
   - ✍️Updaters
   - ✅ Extensions (#3138)
   - ✅ Trainers (#2736)
   - ✍️Serializers -- saving and loading models (Part of: [Introduction to Chainer](https://github.com/chainer/chainer/blob/master/docs/source/tutorial/basic.rst))

Mastering Chainer
- Importing and Augmenting Data Sets
- Improving calculation speed
- Saving and Loading models
- Transfer learning

Cutting Edge Chainer
- Relational Network (Deepmind paper)
- FB Convolutional seq2seq
- SNN

**Comment by Crissman** [comment]
Rewrote outline and created PR#3241 for implementation framework.

**Comment by delta2323** [comment]
This issue is still on going.

**Comment by hvy** [comment]
Bump.

**Comment by Crissman** [comment]
First pass completed with PR #3241. Shall we close this?

**Comment by hvy** [comment]
I think there are topics left, including #3127. 

As for the others, LSTM seems to have been merged but I am not sure about the other `Need modification`s. Were they covered by #3241 ?
