### ISSUE TITLE
Automatic broadcast configuration

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#2578]
```
x = chainer.Variable(numpy.zeros((3, 1), 'f'))
y = chainer.Variable(numpy.zeros((1, 3), 'f'))
with chainer.configuration.broadcast:
    z = x + y
```

**Comment by beam2d** [comment]
IMHO, this kind of specification should not be configured by a flag. How do you think of it? Once one starts refactoring the code, some methods that only run in either of the modes would be made, which might be confusing for the users.
