### ISSUE TITLE
Widen the suport of aggressive buffer release

### ISSUE THREAD

**Issue by beam2d** [chainer/chainer#2579]
In #2452, we implemented the aggressive buffer release (a fancy name of `Function.retain_inputs` and `Function.retain_outputs`). In that PR, we only added the support for a limited number of functions (`relu`, some arithmetics, `concat`, and `split_axis`). We have to widen the support. Most of the activation functions and array manipulation functions can support it.

**Comment by unnonouno** [comment]
- [ ] activation
- [ ] array
- [ ] connection
- [ ] evaluation
- [ ] loss
- [ ] math
- [ ] noise
- [ ] normalization
- [ ] pooling
- [ ] theano
- [ ] util

**Comment by unnonouno** [comment]
Many loss functions can be modified. But, currently we are introducing `reduce` arguments to them. It causes many conflicts. I'll fix loss functions after this fix is finished.
