### ISSUE TITLE
Can not deserialize model

### ISSUE THREAD

**Issue by ikegami-yukino** [chainer/chainer#2593]
I use a model, which trained by GPU, to CPU only machine. 
When executing `examples/ptb/gentext.py` based my program, the error occurs as following:

```python
Traceback (most recent call last):
  File "predict.py", line 104, in <module>
    serializers.load_npz(args.model, model)
  File "/work/venv/py3/lib/python3.6/site-packages/chainer/serializers/npz.py", line 131, in load_npz
    d.load(obj)
  File "/work/venv/py3/lib/python3.6/site-packages/chainer/serializer.py", line 85, in load
    obj.serialize(self)
  File "/work/venv/py3/lib/python3.6/site-packages/chainer/link.py", line 691, in serialize
    d[name].serialize(serializer[name])
  File "/work/venv/py3/lib/python3.6/site-packages/chainer/link.py", line 691, in serialize
    d[name].serialize(serializer[name])
  File "/work/venv/py3/lib/python3.6/site-packages/chainer/link.py", line 691, in serialize
    d[name].serialize(serializer[name])
  File "/work/venv/py3/lib/python3.6/site-packages/chainer/link.py", line 482, in serialize
    serializer(name, d[name].data)
  File "/work/venv/py3/lib/python3.6/site-packages/chainer/serializers/npz.py", line 106, in __call__
    dataset = self.npz[key]
  File "/work/venv/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 237, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'predictor/l1/upward/W is not a file in the archive'
```

My environment is following:

- Python3.6
- chainer==1.23.0
- numpy==1.12.1

**Comment by unnonouno** [comment]
Thank you for reporting a problem. Can you try to run this script with your model file? It shows all keys in the model file.
https://gist.github.com/unnonouno/d53069ca4d5905c4668cc2ef3544df3b

**Comment by ikegami-yukino** [comment]
The result of that script is following:

```
$ python npz_keys.py ../model/0418.model 
['predictor/embed/W', 'predictor/l1/W_r/W', 'predictor/l1/W_r/b', 'predictor/l1/U_r/W', 
'predictor/l1/U_r/b', 'predictor/l1/W_z/W', 'predictor/l1/W_z/b', 'predictor/l1/U_z/W', 
'predictor/l1/U_z/b', 'predictor/l1/W/W', 'predictor/l1/W/b', 'predictor/l1/U/W', 'predictor/l1/U/b', 
'predictor/l2/W_r/W', 'predictor/l2/W_r/b', 'predictor/l2/U_r/W', 'predictor/l2/U_r/b', 
'predictor/l2/W_z/W', 'predictor/l2/W_z/b', 'predictor/l2/U_z/W', 'predictor/l2/U_z/b', 
'predictor/l2/W/W', 'predictor/l2/W/b', 'predictor/l2/U/W', 'predictor/l2/U/b', 'predictor/l3/W', 
'predictor/l3/b']
```

Thank you.

**Comment by unnonouno** [comment]
Hum. Did you use GRU link in your implementation? Did you use correctly the same model on `gentext.py`? It looks that `gentext.py` tries to load LSTM link.
Chainer's serializer does not save model (Link) structure. You need to use the same model structure in both a train script and a test script.

**Comment by ikegami-yukino** [comment]
No, I use same LSTM link both `gentext.py` and `train_ptb.py`.
But, the problem is solved  by downgrading chainer to version `1.7.0`.

**Comment by unnonouno** [comment]
mmm. I can't understand why version `1.7.0` can load it. LSTM link in v1.7.0 also has `upward` and `lateral` link. https://github.com/pfnet/chainer/blob/v1.7.0/chainer/links/connection/lstm.py#L32 It must raises the same error with the model file because it does not have `upward` and `lateral` keys.

**Comment by aspenlin** [comment]
I'm having the same problem with serializers.load_npz(args.parm, model)

args.parm is the .model file generated by training

when I 'print(model)', it gives:
AlexNet(
  (conv1): Convolution2D(in_channels=3, out_channels=96, ksize=11, stride=(4, 4), pad=(1, 1), nobias=False, dilate=(1, 1), groups=1),
  (conv2): Convolution2D(in_channels=96, out_channels=256, ksize=5, stride=(1, 1), pad=(2, 2), nobias=False, dilate=(1, 1), groups=1),
  (conv3): Convolution2D(in_channels=256, out_channels=384, ksize=3, stride=(1, 1), pad=(1, 1), nobias=False, dilate=(1, 1), groups=1),
  (conv4): Convolution2D(in_channels=384, out_channels=384, ksize=3, stride=(1, 1), pad=(1, 1), nobias=False, dilate=(1, 1), groups=1),
  (conv5): Convolution2D(in_channels=384, out_channels=256, ksize=3, stride=(1, 1), pad=(1, 1), nobias=False, dilate=(1, 1), groups=1),
  (fc6): Linear(in_size=9216, out_size=4096, nobias=False),
  (fc7): Linear(in_size=4096, out_size=4096, nobias=False),
  (fc8): Linear(in_size=4096, out_size=14, nobias=False),
)

but I'm having error:
'fc8/b is not a file in the archive'
what's more 'fc8/b' here changes everytime I run serializers.load_npz(), for example it can be conv1/W, fc6/b etc..

Any idea why this is happening? Thank you very much for your help. The chainer version I'm using is 6.1.0.
