### ISSUE TITLE
Uniqueness of Device object

### ISSUE THREAD

**Issue by mitmul** [chainer/chainer#2632]
Current implementation of `chainer.cuda.Device` class produces different objects every time it's instantiated even for the same GPU ID. When different `Device` objects have the same GPU ID, they actually indicate the same physical device (GPU), so that such objects may have to be the same, i.e., be evaluated to be equal with `is` operator.

Currently, different `Device` objects for the same physical device can exist. It is not a serious problem so far, but if we force a `Device` object pointing the same GPU to be always the same object, CPython overhead will be reduced because `Device` object instantiation for the same actual device is performed only once.

**Comment by niboshi** [comment]
I think `is` should not be used for that purpose. `is` is for physical equality (i.e. memory address), not semantic equality. It could be better to override `==` operator  instead. If speed is a concern, you could write like `dev1 is dev2 or dev1 == dev2` (I'm not sure if there's a better way).

Sharing `Device` object might be a good idea, but concurrency will be a problem. If the objects are to be shared globally, we will need to protect with a lock not only device acquisition but also other operations to device objects (e.g. make it current). Another possibility is to share them only within a thread. Then the cost of device lookup using thread local storage could be a concern.

I did brief measurement:
```
from chainer import cuda
import threading
import timeit

thread_local = threading.local()
thread_local.foo = {1: object()}
lock = threading.Lock()

def func0():
    pass

def func1():
    cuda.Device()

def func2():
    cuda.Device(1)

def func3():
    thread_local.foo.get(1)

def func4():
    with lock:
        pass

for func in (func0, func1, func2, func3, func4):
    n = 10000000
    sec = timeit.timeit(func, number=n) / n
    print("{}: {:.2f} nanosec".format(func.__name__, sec * 1e9))
```

Results:
```
func0: 92.88 nanosec   # Empty (for comparison)
func1: 316.35 nanosec  # Device object instantiation
func2: 229.92 nanosec  # Device object instantiation
func3: 232.57 nanosec  # Look up using thread local storage
func4: 323.64 nanosec  # Lock (without race condition)
```

From this result, I would suspect the benefit of device sharing.
(This is Python implementation. It could result differently with Cython implementation)
