### ISSUE TITLE
Testing utilities for training loop abstraction

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#2647]
Currently, the test coverage of modules related to training loop abstraction (Trainer, Updater, etc.) is relatively low. One of the reasons could be that it is relatively difficult to test modules related to them. Dummy objects that mimics their typical behavior could be beneficial to help developers to test training modules. Actually, we have made such dummy objects in several tests.

**Comment by beam2d** [comment]
FYI, I have moved the mocked trainer in `test_trainer.py` to `chainer.testing` in #2639. It is a trainer with a mock updater which only maintains the iteration count, and it can be used for most tests of trainer-related stuff except updaters.

**Comment by delta2323** [comment]
Thank you for your information. Although I have not thought deeply it will be sufficient to test modules related to trainer, it will be helpful. 
By the way, the original motivation of this issue was #2639, in which we created a new extension. Do you plan to merge it soon? If so, we can use the dummy trainer to test the extension.

**Comment by beam2d** [comment]
I cannot decide when to merge it because I am the author, but I want it to be merged as early as possible since it's one of the features that we are planning to release as a part of v2. Note that this PR is targeting v2.
