### ISSUE TITLE
Variable defines __hash__ but does not define __eq__

### ISSUE THREAD

**Issue by thequilo** [chainer/chainer#2670]
`Variable` defines `__hash__` but doesn't define `__eq__`:
```
class Variable(object):
    # ...

    def __eq__(self, other):
        raise NotImplementedError()

    # ...

    def __hash__(self):
        return super(Variable, self).__hash__()
```

But, the python documentation (https://docs.python.org/3.1/reference/datamodel.html#object.__hash__) says:
> If a class does not define an __eq__() method it should not define a __hash__() operation either;

Is there a reason `Variable` is designed like this?

**Comment by beam2d** [comment]
It looks like a mistake. Variable should not be hashable (like ndarrays).
