### ISSUE TITLE
No unit test file exists corresponding to chainer/functions/connection/embeded_id.py

### ISSUE THREAD

**Issue by keisuke-umezawa** [chainer/chainer#2730]
# no test file
No test_embeded_id.py file exists
 under [chainer_tests/functions_tests/connection_tests](https://github.com/pfnet/chainer/tree/master/tests/chainer_tests/functions_tests/connection_tests) .
(But the test coverages are almost enough because of [this test](https://github.com/pfnet/chainer/blob/master/tests/chainer_tests/links_tests/connection_tests/test_embed_id.py)).

If you need the tests under [chainer_tests/functions_tests/connection_tests](https://github.com/pfnet/chainer/tree/master/tests/chainer_tests/functions_tests/connection_tests), I will write. How about it?

# strange behavior
the image's case is very natural. But the following case is a little strange for me.
Is this an expected results? If this case is expected, we should write this test case.

- The result of index of `-1` is equal to that of `1`. (Maybe, this case is made because W[1, :] and W[-1, :] are same.)
```
>>> W = np.array([[1, 1, 1], [2, 2, 2]]).astype('f')
>>> x = np.array([0, 1, -1]).astype('i')
>>> y = F.embed_id(x, W)
>>> y.data
array([[ 1.,  1.,  1.],
           [ 2.,  2.,  2.],
           [ 2.,  2.,  2.]], dtype=float32)
```
<img width="498" alt="2017-05-12 0 21 57" src="https://cloud.githubusercontent.com/assets/1277089/25957362/1dc939c6-36a9-11e7-831e-95423998575a.png">

**Comment by keisuke-umezawa** [comment]
```
>>> x = np.array([0, -3, -2, -1]).astype('i')
>>> W = np.array([[0],[1],[2],[3]).astype('f')
  File "<stdin>", line 1
    W = np.array([[0],[1],[2],[3]).astype('f')
                                 ^
SyntaxError: invalid syntax
>>> W = np.array([[0],[1],[2],[3]]).astype('f')
>>> F.embed_id(x, W).data
array([[ 0.],
       [ 1.],
       [ 2.],
       [ 3.]], dtype=float32)
```

**Comment by delta2323** [comment]
We can invalidate negative indexes in the debug mode.

```
In [7]: chainer.debug(True)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-d304825fe001> in <module>()
----> 1 chainer.debug(True)

AttributeError: module 'chainer' has no attribute 'debug'

In [8]: chainer.set_debug(True)

In [9]: F.embed_id(x, W).data
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-8d632fa5d97b> in <module>()
----> 1 F.embed_id(x, W).data

/Users/oonokenta/dev/chainer/chainer/functions/connection/embed_id.py in embed_id(x, W, ignore_label)
    110 
    111     """
--> 112     return EmbedIDFunction(ignore_label=ignore_label)(x, W)

/Users/oonokenta/dev/chainer/chainer/function.py in __call__(self, *inputs)
    197         # Forward prop
    198         with cuda.get_device(*in_data):
--> 199             outputs = self.forward(in_data)
    200             assert type(outputs) == tuple
    201         for hook in six.itervalues(hooks):

/Users/oonokenta/dev/chainer/chainer/functions/connection/embed_id.py in forward(self, inputs)
     39                 valid_x = xp.logical_or(valid_x, x == self.ignore_label)
     40             if not valid_x.all():
---> 41                 raise ValueError('Each not ignored `x` value need to satisfy'
     42                                  '`0 <= x < len(W)`')
     43 

ValueError: Each not ignored `x` value need to satisfy`0 <= x < len(W)`
```

So far as I remember, we do input validation only the debugging mode for fearing the performance degradation. So, I think we should not think of this behavior as an official document. Rather, we should check that Chainer correctly invalidate negative indexes in the debug mode.
