### ISSUE TITLE
Add version information in the document

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#2735]
There is no version information of interfaces. It is very difficult to find its information and fix old source codes. I propose to add two types of information:

- Which version of chainer first supports an interface
-- For example `broadcast_to` is first supported in v1.10.0 in numpy https://docs.scipy.org/doc/numpy/reference/generated/numpy.broadcast_to.html
- Which version of chainer first obsoletes an interface

There information is very helpful in other libraries i feel.

**Comment by niboshi** [comment]
If this includes removed features (not only obsolete ones), we should decide how long these features are kept documented after removal.

**Comment by unnonouno** [comment]
Ah, yes.
