### ISSUE TITLE
The "Edit on GitHub" links in the document are wrong.

### ISSUE THREAD

**Issue by kiyukuta** [chainer/chainer#2822]
For example, the link is on the top right of this page.
https://docs.chainer.org/en/stable/index.html

We have to remove "origin" from the URL:
https://github.com/chainer/chainer/blob/origin/v2.0.0/docs/source/index.rst .

**Comment by kiyukuta** [comment]
related #1034 (reoccured)

**Comment by delta2323** [comment]
Thank you for reporting. The original issue rtfd/readthedocs.org#1637 is still open. So I think we should wait to see it.

**Comment by niboshi** [comment]
Do we need this link from the beginning?
I often confuse it as a link to `.py` source file...

**Comment by kiyukuta** [comment]
Thanks for the link of original issue !
I hope it will be fixed soon.

@niboshi 
Yeah, I'm also confused sometime. it will be better to jump `*.py` directly :)

**Comment by kiyukuta** [comment]
Since this is not a Chainer's problem, should I close this issue ?

**Comment by niboshi** [comment]
Maybe we can discuss how to deal with the link here. (remove? replace? leave as is? ... etc)
I'd vote for removal.

**Comment by kiyukuta** [comment]
I also think it is OK to remove the links. 

On the other hand, the links will be help when we found some issue on the docs (e.g. typo).
We can easily find which `rst` file has to be changed.

**Comment by niboshi** [comment]
Reopening the issue, because this link is still showing in our documentation.

**Comment by Crissman** [comment]
Fixed by PR #2999?
