### ISSUE TITLE
Upgrading from v1 to v2 not possible on machines with no CUDA

### ISSUE THREAD

**Issue by ilkhem** [chainer/chainer#2828]
I am trying to upgrade chainer from v1 to v2 to use the new no_backprop_mode() on my local macbook machine (no GPUs, so no CUDA..), but the upgrade is not possible because it is not possible to install cupy when CUDA is unavailable.

**Comment by delta2323** [comment]
You do not have to install CuPy when you do not use GPUs. Just installing Chainer via `pip` is enough.
