### ISSUE TITLE
Implement fairseq

### ISSUE THREAD

**Issue by ianupright** [chainer/chainer#2831]
I'd love to see the core parts of this type of sequence model available in Chainer.

https://github.com/facebookresearch/fairseq

**Comment by soskek** [comment]
Fortunately, I implemented a convolutional seq2seq model using gated linear units (GLU) this week.
https://github.com/soskek/convolutional_seq2seq
I am not planning to make PR of parts of them (e.g. GLU) currently, but you can refer to this. For example, GLU is on https://github.com/soskek/convolutional_seq2seq/blob/master/net.py#L62-L82.
Note that this does not aim for complete reproduction of a model used in experiments in the paper. There are some architecture-level or optimization-level differences of which I am aware or not for.

**Comment by ianupright** [comment]
I'm extremely happy about this!  Thank you!
