### ISSUE TITLE
 How to operate other image in this one batch?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#2833]
Because the chainer's Variable has omit Linker's first batch dimension.
According to https://docs.chainer.org/en/stable/tutorial/basic.html#forward-backward-computation
The document said 

> Most functions and links only accept mini-batch input, where the first dimension of the input array is considered as the batch dimension. In the above Linear link case, input must have shape of (N, 3), where N is the mini-batch size.

Why omit first dimension??
If I want to get/operate the other image in this batch, How to write the code?

**Comment by delta2323** [comment]
> Because the chainer's Variable has omit Linker's first batch dimension.

I am afraid I could not get this point. If we instantiate a linear link with `L.Linear(3, 2)`, the weight matrix will be `3x2`. So the weight of a linear link (, which corresponds to a fully-connected layer) does not have batch dimension a priori. If we put an matrix input of `Nx3` (where `N` can be arbitrary), the output will be `Nx2`, which is an ordinal matrix-matrix multiplication.

**Comment by sharpstill** [comment]
@delta2323 Just because what you said, How does it program to use lstm in  vary length batch data, For example , because of each article has vary counts of words. This time training I want to use lstm to process 30 words, Next article I want to use lstm to process  20 words. Because of ommit batch dimension, How to do that?

**Comment by muupan** [comment]
> If I want to get/operate the other image in this batch, How to write the code?

Sorry if I misunderstand your question.
Say, `x` is a `Variable` whose shape is `(5, 3)`, holding a batch of 5 vectors.
If you want to get the first two vectors in `x`, you can write `y = x[:2]`. `y`'s shape is `(2, 3)`.
