### ISSUE TITLE
cycles in the graph

### ISSUE THREAD

**Issue by ianupright** [chainer/chainer#2836]
I noticed when I have a bug where I have cycles in my graph, such that the same variable is used more than once, it often comes up with this type of error:

cupy.cuda.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered

It would be nice if there was some friendlier way of alerting me to the true cause of the problem.
If this is not easily reproducible I can try to construct a simple example.

**Comment by delta2323** [comment]
Hi, we assume that one variable is used in a graph multiple times. For example, `x` is used twice in the following code:

```code:py
x = chainer.Variable(np.array(...))
y = F.sin(x)
z = F.cos(x)
```

But I think such usage does not make the graph cyclic.

**Comment by niboshi** [comment]
@ianupright Could you give example code?
