### ISSUE TITLE
Could you port chainer as DLL which can be used inside C/C++

### ISSUE THREAD

**Issue by Jumabek** [chainer/chainer#2838]
Hi,
I want my application to be called from C/C++.
So far I was using darknet (https://github.com/AlexeyAB/darknet) and compiling it into DLL, so that later other programs can call it.

How can I do the similar thing with chainer?

Thanks!

**Comment by muupan** [comment]
Since Chainer is written in Python, I guess you need to be able to call Python functions from your C/C++ programs as described in https://docs.python.org/3.6/extending/embedding.html.
