### ISSUE TITLE
Safe way to remove links from Chain

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#2842]
Currently we can add links to `Chain` with the combination of `Chain.init_scope` and `Chain.__setattr__` (be aware that `Chain.add_link` is deprecated). But it does not offer safe way to remove them.

Sometimes we do want to remove registered children of a chain. For example, we use only the part of the computational graph represented by `L.CaffeFunction`. In that case, users may want to remove unused chains to reduce memory usage.

Currently we need to hack chains and manipulate undocumented attributes (namely, `Chain._children`) in order to do that. That could increase the risk of breaking internal structures of chains. Actually, we unexpectedly unregister different children of a `Illust2Vec` model in #2813.

Note that we should remove children carefully because they can be in the computational graph and their removal could lead unexpected behaviors (e.g. optimizers miss and do not update them). So, one possible design is to offer `force` option to `Chain.remove_link` that removes specified chain from parent one even it is used in some graphs.

**Comment by Paosder** [comment]
It is really critical problem when we could only use restricted gpu memory. But as you mentioned, chainer doesn't support any option to remove or disable part of model (link). Only we could twick by unusual ways and this may cause confusing errors like I experienced. 

So it would be better if chainer supports option that link in model could on/off when we train/test our model flexible. Chainer v2 now support local flag like,
`with chainer.using_config('train', False):`
(giving train argument into functions are deprecated)
I think it would be great if we could set above options(on/off) into local flag. 
```
with chainer.using_config('train', False):
   model.remove_link('conv1','conv2') #this only affect while testing our model.
   y = model(x)
   ...
```

**Comment by niboshi** [comment]
`Chain` has `__delattr__`. How about it?

**Comment by delta2323** [comment]
I see. I forgot `Link.__delattr__` and `Chain.__delattr__` have been added. To solve the original question, we need `CaffeFunction.__delattr__` as well.

**Comment by delta2323** [comment]
I realized we do not have unit tests for `Link.__delattr__` and `Chain.__delattr__`. I raised an issue.

**Comment by hvy** [comment]
I'll close this issue as #2930 seems to be fixed!
