### ISSUE TITLE
Put musyoku's works in external examples into the right categories

### ISSUE THREAD

**Issue by muupan** [chainer/chainer#2870]
The "External examples" page in wiki (https://github.com/chainer/chainer/wiki/External-examples) has a "musyoku" category, but it is not consistent with other categories such as NLP and Computer Vision. I think it is better to remove the "musyoku" category and put his or her works into the right categories.

**Comment by mitmul** [comment]
I will put a link to [Awesome Chainer](https://github.com/chainer-community/awesome-chainer) and send a PR to fix this problem to the repository.

**Comment by mitmul** [comment]
Done
