### ISSUE TITLE
chainer.utils.type_check.InvalidType

### ISSUE THREAD

**Issue by lizaigaoge550** [chainer/chainer#2875]
when i run the example in tutorial
x = Varible(....)
y = xx+x2+1
the error "Invalid operation is performed in *" was displayed. What is wrong? Please help me, thank you
I use Python3.6

**Comment by lizaigaoge550** [comment]
Were i was wrong?

**Comment by lizaigaoge550** [comment]
i didn't turn the type to float

**Comment by muupan** [comment]
Can you provide the full code and the error message?
