### ISSUE TITLE
Automate slack invitation

### ISSUE THREAD

**Issue by muupan** [chainer/chainer#2904]
I think the slack invitation should be automated for the following reasons:
- the dev team's trouble will be saved
- new users will not have to wait for an invitation
- new users will be able to join more casually

**Comment by beam2d** [comment]
The slack invitation has been already automated, so I close this issue. If you have any troubles on joining our slack, please open a new issue. Thank you.

**Comment by muupan** [comment]
So this statement is wrong? Then it should be removed. And I think it is better to clarify for users that invitation is automated instead.

> 手動で招待連絡をしているので、ご連絡にお時間をいただくことがあります。

https://docs.google.com/forms/d/e/1FAIpQLSfqL9XjnqZUIwLOz4K9Oxm8-Ce246IRP51-vZa7HOrofJT9rA/viewform

**Comment by beam2d** [comment]
Ah, yes. That statement should be fixed. Thank you for reporting it.

**Comment by beam2d** [comment]
The sentence has been removed.

**Comment by beam2d** [comment]
We will clean up the form (#2905) and then add a sentence to clarify that the invitation is fully automated, so please wait for that.

**Comment by beam2d** [comment]
I added a sentence that clarifies the automatic invitation, so close the issue again.
