### ISSUE TITLE
The existence of chainer slack is hard to notice in README

### ISSUE THREAD

**Issue by ir5** [chainer/chainer#2906]
Although chainer slack is a nice opportunity for users, I guess it is not presented appropriately. As far as I could see, description about slack appears only in README.md. But it is easily passed over because it is like embedded in one long line. I believe we can emphasize it in the documentation.

**Comment by beam2d** [comment]
Do you think it's better to add that information to docs.chainer.org? Or just emphasizing it in readme is enough?

**Comment by okdshin** [comment]
Currently, Googling "chainer slack" shows 
![2017-06-23-13_25_26](https://user-images.githubusercontent.com/1490699/27466715-94a1a49a-5817-11e7-87b2-7134cbe5c0bf.png)

The top link(http://anythingcanhappen.hatenablog.com/entry/2016/03/20/190656) includes slack link but it seems already expired...

**Comment by Crissman** [comment]
I contacted @masuoka on the Chainer Slack and asked him to update his blog and also posted on his blog with the correct links.

**Comment by beam2d** [comment]
This issue is not resolved yet and should be improved. Do you have a good idea for the next action?

**Comment by Crissman** [comment]
Slack is probably not the best format for support, given its fast response requirements and low searchability. I recommend we close this issue.

**Comment by Crissman** [comment]
Add chainer.org and chainer.docs and default message for Github issue submission.

**Comment by Crissman** [comment]
Both PRs merged, so closing.
