### ISSUE TITLE
Make it easier to debug code which mixes up Variable and ndarray

### ISSUE THREAD

**Issue by beam2d** [chainer/chainer#2908]
I often encounter a bug caused by mixing up Variable and ndarray. There is one caveat on it; since both have `.data`, an error often occurs far later than the point that we should fix. I want to make it easier to debug such a case.

One idea is to add an alias of `Variable.data`, like `Variable.array`, so that we can avoid such a situation by letting us use the new alias instead of `.data`. If we always use this alias, an error immediately occurs once we try to access the attribute of an ndarray. It is still later than the point we start mixing up Variable and ndarray, though.

**Comment by niboshi** [comment]
I think we should consider writing more `assert` statements.
In my test, `assert isinstance(...)` is as costly as a single method call (~100ns).
(I'm not sure if we can say it's cheap enough)

`assert` statements can also work as additional documentation.
It's much easier to read and debug code with `assert` statements.

**Comment by muupan** [comment]
👍  for adding `.array`. Writing assert is a good practice, but it should not be forced for users to write assert.
