### ISSUE TITLE
what is the best way to embedded c++ code

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#2929]
I have a C++ code which written as a complex algorithm , I want to use it as an neron network layer or chainer function. Which is best way to embeded it in chainer ???
The worst way may be translate it to python language.
PS: I still don't understand chainer's backward  how to write it. Can you tell me more

**Comment by niboshi** [comment]
Hi, thank you for posting!
However, this kind of questions are better posted on [StackOverflow](https://stackoverflow.com/questions/tagged/chainer), etc., where you're more likely to get answers from more developers.

I'm closing the issue. Thank you any way.
