### ISSUE TITLE
NStepBi_xxx 's behaviour is inconsistent with the document

### ISSUE THREAD

**Issue by butsugiri** [chainer/chainer#2944]
I am using Chainer version: 2.0.0

Documents of NStepBi_xxx (like [this](https://docs.chainer.org/en/stable/reference/functions.html#chainer.functions.n_step_bilstm)) says that the variables like `hx` (argument of the function) and `hy` (value returned by the function) have the shape such that `(S, B, N) where S is number of layers and is equal to n_layers, B is mini-batch size, and N is dimention of hidden units.` 

However, the actual shape returned by the function is inconsistent with the document.
For example:

```
x = chainer.Variable(np.random.randn(1,5).astype('f'))
l1 = L.NStepBiLSTM(n_layers=2, in_size=5, out_size=5, dropout=0.0)
h, c, hx = l1(None, None, [x])
print(h.shape) # (S=4,B=1,N=5), thus S != n_layers
```

The actual shape is twice the value of `n_layers` (as it is bi-directional). 
Thus I guess that the document should be fixed.

This inconsistency might be due to the difference between the `L.NStepBiLSTM` and `F.n_step_bilstm`. Still, it should be noted on the document of `L.NStepBiLSTM`.

**Comment by sharpstill** [comment]
L.NStepBiLSTM have bug, I encounter in running output size of L.NStepBiLSTM   is 2 x I pass out_size

**Comment by aonotas** [comment]
@sharpstill 

Do you mean that output size of L.NStepBiLSTM is  2 x out_size? 
(e.g.,)
```
x = chainer.Variable(np.random.randn(1,5).astype('f'))
l1 = L.NStepBiLSTM(n_layers=2, in_size=5, out_size=5, dropout=0.0)
h, c, hx = l1(None, None, [x])
print([_.shape for _ in hx]) # [(1, 10)]   # (1, 2 x 5)
```

I think the output size should be concatenated by the hidden vector.
