### ISSUE TITLE
AttributeError: 'MomentumSGD' object has no attribute 'zero_grads'

### ISSUE THREAD

**Issue by clockwiser** [chainer/chainer#2971]
With old version chainer, there was no problem.
Now updated to newest version, there is this error.
Chainer version:2.0.1
Cupy version:1.0.1

**Comment by clockwiser** [comment]
Tried other optimizers, like AdaDelta, but same error. 

AttributeError: 'AdaDelta' object has no attribute 'zero_grads'

**Comment by clockwiser** [comment]
Figure out to use reallocate_cleared_grads() instead. Seems working.

**Comment by clockwiser** [comment]
reallocate_cleared_grads() is not a right way to replace zero_grads.
Chainer 2 documents say to use  Link.zerograds() instead.

**Comment by delta2323** [comment]
Hi, as you noticed, `Optimizer.zero_grads` has been deleted and it is recommended to use `Link.zerograds()`, or more preferably `Link.cleargrads()`.
