### ISSUE TITLE
Error of softmax_cross_entropy using class_weights

### ISSUE THREAD

**Issue by clockwiser** [chainer/chainer#2975]
In the documents, it says:

class_weight (~numpy.ndarray or ~chainer.cuda.cupy.ndarray): An array
            that contains constant weights that will be multiplied with the
            loss values along with the second dimension. The shape of this
            array should be ``(x.shape[1],)``. 
My training data has 24 classes. So class weights has shape of (24, ).

But it won't work with the following error.

~/anaconda2/lib/python2.7/site-packages/chainer/functions/loss/softmax_cross_entropy.pyc in forward_gpu(self, inputs)
    107             log_y *= cupy.broadcast_to(
    108                 self.class_weight.reshape(shape), x.shape)
--> 109         if self.normalize:
    110             coeff = cupy.maximum(1, (t != self.ignore_label).sum())
    111         else:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by clockwiser** [comment]
Solved by designating parameter name.
After looking into api, class_weights is not a third parameter. So must set parameter name, like class_weight='some weights'.

**Comment by delta2323** [comment]
Thank you for reporting the problem. We will consider if we can more explanatory error messages.
