### ISSUE TITLE
where gone the wscale from Convolution2D?

### ISSUE THREAD

**Issue by clockwiser** [chainer/chainer#2976]
In earlier version of chainer, Convolution2D has a parameter wscale. In chainer 2, where is it gone?

**Comment by muupan** [comment]
See https://docs.chainer.org/en/stable/upgrade.html#wscale-option-is-removed-from-links

**Comment by clockwiser** [comment]
Thank you.

**Comment by delta2323** [comment]
I close this PR. Please reopen it if you have additional questions. Thank you.

**Comment by lychrel** [comment]
In case anyone else runs into this issue, the relevant documentation link has changed. [This one](https://docs.chainer.org/en/stable/upgrade_v2.html#wscale-option-is-removed-from-links) works.

**Comment by delta2323** [comment]
@lychrel Thank you for pointing out the document!
