### ISSUE TITLE
inconsistency to use example module

### ISSUE THREAD

**Issue by fiarabbit** [chainer/chainer#2981]
I found some inconsistent behavior to import classes.

To use SOME_CLASS in chainer/iterators, the following code works.
```importIterator.py
import chainer
some_class = chainer.iterators.SOME_CLASS() # OK
```
However, to use SOME_CLASS in chainer/training/extensions, the following code does not work.
```importExtension.py
import chainer
some_class = chainer.training.extensions.SOME_CLASS() #NG
```

I feel some inconsistency here, because `chainer/__init__.py` contains both of `import iterator` and `import iterators` but `chaner/training/__init__.py` contains only `import extension` and not `import extensions`.

Is there any reason about this inconsistency?

* Conditions
  - Chainer version
    chainer v2.0.1
  - OS/Platform
    ubuntu 16.04
* Code to reproduce
```importModule.py
import chainer
iteratorExamples = chainer.iterators # OK

import chainer
extensionExamples = chainer.training.extensions #NG
```

* Error messages
```error.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'chainer.training' has no attribute 'extensions'
```

**Comment by beam2d** [comment]
Thank you for your report. I feel it's good to fix the inconsistency by importing `extensions` as well as `iterators`.

**Comment by delta2323** [comment]
I made a PR that fixes the problem.
