### ISSUE TITLE
Links to GitHub pages are broken

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#2984]
(Rel. #2758)

Links to GitHub pages do not appear in the  Read-the-Docs build (e.g. https://docs.chainer.org/en/stable/reference/generated/chainer.functions.sigmoid.html#chainer.functions.sigmoid).

It works in locally built documentation.

(Thanks @soskek for reporting)

**Comment by Crissman** [comment]
Should be fixed bye #2995. Please test, confirm fixed, and close.
