### ISSUE TITLE
why does updater can't handle batch of dataset iterator each return with different shape 

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#3001]
when I inherit chainer.dataset.DatasetMixin to define function get_example,  but when my def get_example return different shape of array in each example, In this situation, chainer just raise error.

I found https://github.com/chainer/chainer/blob/master/chainer/dataset/convert.py#L38 can handle this situation in padding . but the caller https://github.com/chainer/chainer/blob/master/chainer/training/updater.py#L182 and https://github.com/chainer/chainer/blob/master/chainer/training/updater.py#L292 just omit the third argument, so the default padding=None and raise error in updater!
Why can't modify this code to handle this different shape in each example situation?

**Comment by beam2d** [comment]
You can pass a customized converter function that passes an appropriate padding value to `concat_example`, like `StandardUpdater(..., converter=lambda batch, device: concat_examples(batch, device, padding))`. The reason why `StandardUpdater` currently does not have an option like `padding` is that this option is not a part of the required interface of `converter` function.
