### ISSUE TITLE
crf1d did not calculate the transition cost of (xs[0], ys[0])

### ISSUE THREAD

**Issue by createmomo** [chainer/chainer#3017]
In the crf1d fuction of chainer-2.0.1/chainer/functions/loss/crf1d.py:

For xs[0], ys[0]:
`score = select_item.select_item(xs[0], ys[0])`

Why did the transition cost not calculate here?

**Comment by unnonouno** [comment]
As the document says, translation cost is calculated between each neighboring label pair `y_{i-1}` and `y_{i}`. We need to skip it for `y_{-1}` and `y_{0}`.
https://docs.chainer.org/en/latest/reference/generated/chainer.functions.crf1d.html#chainer.functions.crf1d
