### ISSUE TITLE
invoke_before_training option exists, but never used

### ISSUE THREAD

**Issue by yuyu2172** [chainer/chainer#3020]
By reading the upgrade guide from v1 to v2, `invoke_before_training` option is abolished https://docs.chainer.org/en/stable/upgrade.html#extension-invoke-before-training-is-removed.
However, there still exists an option to set the parameter.
https://github.com/chainer/chainer/blob/master/chainer/training/trainer.py#L177

Not only that, the parameter is never used in v2 code.

**Comment by niboshi** [comment]
Thank you reporting! I made a PR to remove it.
