### ISSUE TITLE
chainer.iterators.MultiprocessIterator may cause stop training like zombie process

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#3022]
the program when using chainer.iterators.MultiprocessIterator to prefetch batch to train, at first it may speed up to train and I am satisfactory.
Then after several hours training , the chainer.iterators.MultiprocessIterator may stop training and GPU usage is 0% and CPU usage is 0% as well.
**I am currently using OS centos 7.0 and anaconda 3 with chainer v2**
log:

    | NVIDIA-SMI 375.51 Driver Version: 375.51 |
    |-------------------------------+----------------------+----------------------+
    | GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
    | Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
    |===============================+======================+======================|
    | 0 Tesla K40m Off | 0000:01:00.0 Off | 0 |
    | N/A 36C P0 63W / 235W | 9887MiB / 11439MiB | 0% Default |
    +-------------------------------+----------------------+----------------------+
    | 1 Tesla K40m Off | 0002:01:00.0 Off | 0 |
    | N/A 36C P0 62W / 235W | 8854MiB / 11439MiB | 0% Default |
    +-------------------------------+----------------------+----------------------+

    +-----------------------------------------------------------------------------+
    | Processes: GPU Memory |
    | GPU PID Type Process name Usage |
    |=============================================================================|
    | 0 34113 C /usr/local/anaconda3/bin/python3 9883MiB |
    | 1 34113 C /usr/local/anaconda3/bin/python3 8850MiB |
    +-----------------------------------------------------------------------------+

```
[root@hadoop1 m]# ps -A -ostat,ppid,pid,cmd | grep -e '^[zZ]' 
Z     36059  36309 [train.py] <defunct>
```

**Comment by sharpstill** [comment]
I think #3022 is a bug that happened after several hours trained. the subprocess must become zombie process

**Comment by sharpstill** [comment]
I am 100% sure this is bug inside chainer.iterators.MultiprocessIterator . When I change to chainer.iterators.SerialIterator, everything goes normal

**Comment by delta2323** [comment]
Thank you for reporting the problem. Is it possible to share us the code that reproduces the problem?

**Comment by sharpstill** [comment]
@delta2323 I can share you code but my code depend on my currently research dataset which is too big for you, My research project using 100000 image to train. How should I give you? only source code is ok for you ? but you cannot run it because you don't have data.

**Comment by sharpstill** [comment]
@delta2323 Did you encountered this zombie process issue before?

**Comment by delta2323** [comment]
We can try with randomly generated sample data first. So the code and input size are enough.

**Comment by sharpstill** [comment]
@delta2323 may be it is my program bug not yours, I found my read data def get_example method allocate too much CPU memory. May be it cause the OS to kill it to become zombie.

**Comment by delta2323** [comment]
OK, thank you for your investigation. Can we close the issue?

**Comment by sharpstill** [comment]
yes, You can close this issue. I am not sure what the problem is. But I recently encounter deadlock again. You must check chainer.iterators.MultiprocessIterator carefully again.

**Comment by delta2323** [comment]
OK. Thank you.
