### ISSUE TITLE
Optimizer tries to update uninitialized parameters

### ISSUE THREAD

**Issue by tkerola** [chainer/chainer#3041]
MWE: https://pastebin.com/DXp4msHx
Running the code will result in the following error:
```
  File "/home/tommi/.pyenv/versions/2.7.12/lib/python2.7/site-packages/chainer/optimizer.py", line 628, in __call__
    g += self.rate * p
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
```
The issue is that the parameter `p` above is `None` due to `model.l3` having no initialized parameters yet on the first forward pass.
This happens since when we are using shape placeholders, `model.l3.params()` returns an empty set, which the optimizer tries to update. An easy fix for this is to write the code as `self.l3 = L.Linear(n_units, n_units)` instead, but I think it is confusing for Chainer users that this error occurs when using placeholders. Would it perhaps be possible to modify the optimizer so that it will not update links with uninitialized parameters?

**Comment by yuyu2172** [comment]
I came across this issue too.
Another way to fix this issue is by modifying all hook functions.
