### ISSUE TITLE
get_dataset_directory() suppresses OSError if os.makedirs() fails

### ISSUE THREAD

**Issue by tgpfeiffer** [chainer/chainer#3057]
If an `OSError` is encountered while creating the directory for a dataset in `dataset.get_dataset_directory()`, then that error is silently ignored (cf. [code](https://github.com/chainer/chainer/blob/v2.0.1/chainer/dataset/download.py#L63)). I had a [problem](https://github.com/chainer/chainercv/issues/356) that was very hard to track down, caused by the dataset root directory being not writable and directory creation silently failing.

Is there a particular reason why `OSError`s are ignored for the `os.makedirs()` call? I think they should be re-raised (because there is hardly any chance that this error can be recovered gracefully) or at least logged.

**Comment by Hakuyume** [comment]
I think this issue can be solved by #2839 (It is not merged).

**Comment by delta2323** [comment]
Yes, it is solved by #2839. So I close this PR.
