### ISSUE TITLE
How to write bi-direction LSTM and tree structure recurrent LSTM in chainer

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#3071]
I want to write bi-direction LSTM  in my research, How to write the following:
1. bi-direction LSTM 
2. **tree structure recurrent LSTM**.  I want to write a tree structure LSTM, each time step input node in the leaf level node
and two consecutive time step node has a parent node and so on.

**Comment by delta2323** [comment]
For 1 you can use [`L.NStepBiLSTM`](https://docs.chainer.org/en/stable/reference/generated/chainer.links.NStepBiLSTM.html?highlight=NStepLSTM#chainer.links.NStepBiLSTM)

**Comment by unnonouno** [comment]
You can find tree-lstm implementation https://github.com/chainer/chainer/blob/master/chainer/functions/activation/tree_lstm.py

**Comment by sharpstill** [comment]
@unnonouno @delta2323 I would try it! Chainer is so wonderful framework, it seems can do these structurein the simplest way.
If I have any question in my implementation, I will ask you again
Thank you!

**Comment by sharpstill** [comment]
@unnonouno how to write stacked LSTM

**Comment by niboshi** [comment]
Thank you for posting a question!
However, GitHub issues are for bug reports / feature requests.
Please consider asking in [StackOverflow](https://stackoverflow.com/) (with `chainer` tag).
We actively monitor it, and many others can help, too.
