### ISSUE TITLE
is chainer training speed inherently much slower than other framework such as caffe?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#3092]
I recently use chainer to train faster R-CNN for object detection.
I modified chainercv source code because all my image are 512 x 512 , so my batch size is 10.
I am using one **Tesla K40 GPU**, but I found each second can only train 2 image.
I have 500 thousands of image, which means after train 20 epoch it will spend 1 mounth.
It is too slow for me. and my classmate told me he use caffe to train resnet or GoogLenet for classify,
the caffe training speed is 4 times quicker than chainer?
**is my GPU to slow or chainer too slow** or I must write some code to use cudnn? did cudnn automatically used?

**Comment by niboshi** [comment]
>is my GPU to slow or chainer too slow

You can use `nvprof` to find out what is the bottleneck.

>did cudnn automatically used?

Yes. You can check to see if cuDNN is enabled in your environment, by looking at `chainer.cuda.cudnn_enabled`.

**Comment by niboshi** [comment]
If you found a bottleneck in Chainer, it's much appreciated if you raise an issue with detailed information.
