### ISSUE TITLE
Can chainer deal with different layer/function using different device(GPU/CPU) inside one network?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#3094]
I have one unified network, But because time urgent, I did not write code that some layer/function in GPU, only have CPU code. But the rest of this network has component in GPU.
How to train this CPU/GPU mixed network in chainer?

**Comment by niboshi** [comment]
Thank you for posting a question!
However, GitHub issues are for bug reports / feature requests.
Please consider asking in [StackOverflow](https://stackoverflow.com/) (with `chainer` tag).
