### ISSUE TITLE
MultiprocessIterator hangs in Chainer 3.0.0b1 but works in Chainer 2.0.2

### ISSUE THREAD

**Issue by jinjiren** [chainer/chainer#3133]
Related to this issue: chainer/chainercv#386, and finally we figured out it is a problem related to MultiprocessIterator instead of chainercv.transforms.

The code provided by @Hakuyume:
```python
import numpy as np
import chainer


class Model(chainer.Link):

    def __call__(self, x):
        print('called')
        return chainer.functions.sum(x)

dataset = np.random.uniform(size=(10, 3, 300, 300)).astype(np.float32)
iter_ = chainer.iterators.MultiprocessIterator(dataset, 1)

model = Model()
optimizer = chainer.optimizers.MomentumSGD()
optimizer.setup(model)

updater = chainer.training.StandardUpdater(iter_, optimizer)
trainer = chainer.training.Trainer(updater, (1, 'epoch'))

trainer.run()
```

This can successfully exit in chainer 2.0.2, but in chainer 3.0.0b1 it will just hang there.

**Comment by delta2323** [comment]
Thank you for sharing the code. I tried it in my environment and noticed that it hangs both with Chainer 2.0.2 and 3.0.0b1.

**Comment by jinjiren** [comment]
@delta2323 I tried it again in a separate virtualenv, and got the same result with yours...

**Comment by delta2323** [comment]
Sorry for not responding to the issue for a long time. I noticed that the problem does not occur in the latest Chainer. Could you try to update it and check the behavior?

**Comment by delta2323** [comment]
Confirmed it works with Chainer 3.2.0

**Comment by beam2d** [comment]
Closed. Feel free to reopen it if you still find a problem.
