### ISSUE TITLE
how to use chainer.using_config to stop F.dropout in evaluate/predict process in chainer? 

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#3181]
F.dropout is only used in train, I confused how to use chainer.using_config in it? How does it works and chainer how to know it is in training or predict?
I already put on
https://stackoverflow.com/questions/45757330/how-to-use-chainer-using-config-to-stop-f-dropout-in-evaluate-predict-process-in
AND  in stackoverflow why answer to little and respond slow?

**Comment by beam2d** [comment]
Sorry for the late response, but we cannot promise to make response during weekends. For the current question, see the answer made in the SO thread.
