### ISSUE TITLE
Add ability to setup optimizer on model as argument

### ISSUE THREAD

**Issue by Crissman** [chainer/chainer#3211]
Currently, setting up an optimizer requires two lines:

```python
optimizer = chainer.optimizers.Adam()
optimizer.setup(model)
```

To keep parallel structure with the other Classes, I think these steps could be consolidated.

```python
optimizer = chainer.optimizers.Adam(model)
```

This would be an enhancement, and existing functionality would be retained for compatibility.

Good idea?

**Comment by hvy** [comment]
Fixed by #3488.
