### ISSUE TITLE
request : More explanation about self define function in official tutorial

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#3222]
Also the official document is good , but not enough for some explanation.
the question I have also submit on https://stackoverflow.com/questions/45832279/why-in-chainer-define-self-define-function-backward-function-must-return-gradien
Two questions: 
1. https://docs.chainer.org/en/stable/tutorial/function.html written: the `backward `function must return the same shape as the arguments of the `forward `method? because in some cases, the input data and parameter need not to be same shape or length, such as Convolutional2D, which the paramter is less than input image data.  How to deal with input data and parameter have different shape. 

2. because in some cases, such as maxpooling, there is no gradient here. How to define such chainer function?

**Comment by niboshi** [comment]
Answered at https://stackoverflow.com/questions/45832279/why-in-chainer-define-self-define-function-backward-function-must-return-gradien
