### ISSUE TITLE
document bug report: chainer.Link page has incorrect code.

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#3225]
https://docs.chainer.org/en/stable/reference/core/generated/chainer.Link.html?highlight=Link
there is an example:
```
 import chainer
import chainer.functions as F
from chainer import initializers
import numpy as np

class LinearLayer(chainer.Link):

    def __init__(self, n_in, n_out):
        super(LinearLayer, self).__init__()
        with self.init_scope():
            self.W = chainer.Parameter(
                (n_out, n_in), initializers.Normal())
            self.b = chainer.Parameter(
                (n_out,), initializers.Zero())

    def __call__(self, x):
        return F.linear(x, self.W, self.b)
```
but chainer.Parameter constructor function is define as :
class chainer.Parameter(**initializer=None, shape=None, name=None**)
note that the order of argument.
so if we omit the parameter keyword , this is incorrect code.

**Comment by mitmul** [comment]
Thank you for reporting it. It has been fixed with #2814, but it's not been back-ported to v2 yet. I'll make a back-port PR of it. Thanks.
