### ISSUE TITLE
document bug report : forward function np.exp cannot apply to chainer.Variable

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#3229]
in this page : https://docs.chainer.org/en/stable/tutorial/function.html
```
class ExpAdd(Function):
    def forward_cpu(self, inputs):
        x, y = inputs
        z = np.exp(x) + np.exp(y)
        return z,

    def backward_cpu(self, inputs, grad_outputs):
        x, y = inputs
        gz, = grad_outputs

        gx = gz * np.exp(x)
        gy = gz * np.exp(y)
        return gx, gy

    def forward_gpu(self, inputs):
        cupy = cuda.cupy
        x, y = inputs
        z = cupy.exp(x) + cupy.exp(y)
        return z,

    def backward_gpu(self, inputs, grad_outputs):
        cupy = cuda.cupy
        x, y = inputs
        gz, = grad_outputs

        gx = gz * cupy.exp(x)
        gy = gz * cupy.exp(y)
        return gx, gy

def expadd(x, y):
    return ExpAdd()(x, y)
```
[np.exp](url) or `cupy.exp` cannot apply chainer.Variable, this means chainer self define function cannot use the power of numpy or cupy, that we can only use chainer.functions lib??

**Comment by beam2d** [comment]
The inputs and grad outputs of `forward` and `backward` methods of `Function` are all numpy/cupy arrays, so it's valid to apply `np` or `cupy` functions.

**Comment by sharpstill** [comment]
@beam2d oh, may be I don't fully understand Function yet, the document written:"Function acts like a function on Variable objects that returns Variable objects as outputs, whereas these objects do not appear directly in the graph".   When did it convert chainer.Variable to np or cupy before forward or backward function?
