### ISSUE TITLE
The documentation of each link/chain implementation is noisy with base class methods

### ISSUE THREAD

**Issue by beam2d** [chainer/chainer#3233]
The documentation of each link and chain shows all the methods of the base class. It is hard to find the essential interface of each link/chain. For example, `LSTM` has `reset_state()` method, which is buried in the list of base class methods. https://docs.chainer.org/en/stable/reference/generated/chainer.links.LSTM.html#chainer.links.LSTM

**Comment by niboshi** [comment]
I think we need a patch to autosummary (https://github.com/sphinx-doc/sphinx/pull/4029)

**Comment by beam2d** [comment]
Or write an individual rst file for each link/chain manually.

**Comment by niboshi** [comment]
Ah, yes. That can be done (cumbersome, though).

**Comment by niboshi** [comment]
I think manually writing each rst file is not feasible.
We can write each class definition, but we must also write summary table (e.g. in https://docs.chainer.org/en/v2.0.2/reference/links.html).
That means, we would have to write class summary texts by hand. It's impossible to make them up-to-date to the class docstrings.

**Comment by kmaehashi** [comment]
I found numpy and pandas using `numpydoc` Sphinx extension, which provides a nice features (not tested yet)

> numpydoc_show_inherited_class_members: bool
> Whether to show all inherited members of a class in the Methods and Attributes sections automatically. If it’s false, inherited members won’t shown. True by default.

https://pypi.python.org/pypi/numpydoc

**Comment by kmaehashi** [comment]
The bad news is that I tried `numpydoc` but it didn't work well. A good news is that Sphinx 1.8.0 (seems to be planned this August: https://github.com/sphinx-doc/sphinx/issues/4986) will support hiding inherited members in autosummary. https://github.com/sphinx-doc/sphinx/pull/5029

**Comment by kmaehashi** [comment]
I'll try as Sphinx 1.8 is released.
