### ISSUE TITLE
Documentation bug report: Some of the descriptions in the tables are truncated.

### ISSUE THREAD

**Issue by bonprosoft** [chainer/chainer#3234]
Some of the descriptions in the tables are truncated, e.g. `chainer.functions.batch_l2_norm_squared`, `chainer.functions.normalize` in [Standard Function implementations page](https://docs.chainer.org/en/latest/reference/functions.html).

I made the following observations.
- The docstring for each of them is not truncated and written correctly, e.g. [chainer.functions.batch_l2_norm_squared](https://github.com/chainer/chainer/blob/ef10ba098b7bdfb4af3e1e9ae4f53defe4f1c76b/chainer/functions/math/batch_l2_norm_squared.py#L46) .
- The detail page for each of them is rendered correctly, e.g. [chainer.functions.batch_l2_norm_squared](https://docs.chainer.org/en/latest/reference/generated/chainer.functions.batch_l2_norm_squared.html#chainer.functions.batch_l2_norm_squared).
- (The docstring for each of them has the word `a.k.a`.)

**Comment by niboshi** [comment]
Thank you for reporting!
I made a fix: #3235.
