### ISSUE TITLE
RTRL

### ISSUE THREAD

**Issue by jramapuram** [chainer/chainer#324]
Any chance of getting Real-Time-Recurrent-Learning in? 
Seems like there are no libraries that currently support this.

**Comment by beam2d** [comment]
We have no plan about implementing RTRL, since it requires much computational cost compared to backprop. There might be a chance if the fast approximation of RTRL gets competitive to the backprop (e.g. http://arxiv.org/abs/1507.07680), though I do not investigate how to implement it on Chainer.

**Comment by jramapuram** [comment]
It is O(n^4) but is easily parallizable though due to the fact that each element of the Jacobian can be computed on a single core
