### ISSUE TITLE
Doc: Color highlighting is lost in chainer.functions.reshape code example

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#3242]
https://docs.chainer.org/en/v2.0.2/reference/generated/chainer.functions.reshape.html

It's seems the line `chainer.utils.type_check.InvalidType:` is the source of the problem, but I couldn't find why and how to get it fixed.

**Comment by keisuke-umezawa** [comment]
In the below page, it is said that 
http://www.sphinx-doc.org/en/stable/markup/code.html

> There is a “highlighting language” for each source file. Per default, this is 'python' as the majority of files will have to highlight Python snippets, but the doc-wide default can be set with the highlight_language config value.
> 
> Within Python highlighting mode, interactive sessions are recognized automatically and highlighted appropriately. Normal Python code is only highlighted if it is parseable (so you can use Python as the default, but interspersed snippets of shell commands or other code blocks will not be highlighted as Python).

**Comment by hvy** [comment]
@niboshi Can we close this issue as fixed?

**Comment by niboshi** [comment]
Yes, it has been fixed.
