### ISSUE TITLE
Implement mask-creation function

### ISSUE THREAD

**Issue by koreyou** [chainer/chainer#3270]
This is a feature request to implement mask-creation function to Chainer.

We use masking quite often when we have a variable length sequence, e.g. NLP applications (tokens) and ranking applications (series of items to be compared).
It would be very handy to have mask-creation function built-in to Chainer.
What I mean by mask-creation is like the one that is implemented in Tensorflow:

```python
tf.sequence_mask([1, 3, 2], 5) =
  [[True, False, False, False, False],
   [True, True, True, False, False],
   [True, True, False, False, False]]
```
(from https://www.tensorflow.org/api_docs/python/tf/sequence_mask)

My suggestion is that we implement sequence_mask exactly as one implemented in Tensorflow.
It has 4 positive sides compared to directly implementing mask function:

1. You can easily use mask to do masking in values of your choice because you sometimes want to mask values with non-zero values. e.g. ListNet,
2. You can re-use the mask for performance,
3. You can use the mask for indexing with `functions.get_items`, and
4. Compatibility with Tensorflow

This function is non-differentiable to both the inputs and thus extremely easy to implement.
I would love to contribute by implementing and PR-ing this feature.

What you guys think of this feature request?

**Comment by hvy** [comment]
@koreyou thank you for this suggestion. Is it the case that the use case if very different from [chainer.functions.pad_sequence](https://docs.chainer.org/en/stable/reference/generated/chainer.functions.pad_sequence.html)?

**Comment by koreyou** [comment]
No. `chainer.functions.pad_sequence` seems to be absolutely fine for this purpose. Sorry that I didn't notice this function.

**Comment by hvy** [comment]
Great. Again, thank you for the request. Tensorflow seems to have `pad_sequences` under contrib so I'll keep en eye out.
