### ISSUE TITLE
Need documentation of how the names of the reported values are determined

### ISSUE THREAD

**Issue by beam2d** [chainer/chainer#3290]
The name of each entry shown in the log emitted by `LogReport` or `PrintReport` is determined by some rules, which are not clear in the documentation. [The document of `chainer.report()`](https://docs.chainer.org/en/stable/reference/util/generated/chainer.report.html#chainer.report) explains the typical cases, which does not look enough to explain more complicated cases like reporting from a link that is not the root of the link hierarchy. I also think we should explain this rule in more visible place than the document of `chainer.report()`.

**Comment by jinjiren** [comment]
This made me confused for a long time...

**Comment by niboshi** [comment]
Reopening, as seemingly it is not solved yet.

**Comment by kmaehashi** [comment]
Fixed via #3688.
