### ISSUE TITLE
Weights in EmbedID Layer DO NOT Change after Update

### ISSUE THREAD

**Issue by createmomo** [chainer/chainer#3331]
My chainer version is 2.0.0+.

In my code, I initialized my embeddings as below:

self.embed = L.EmbedID(
                in_size = vocab_size,
                out_size = embed_size,
                initialW = embeddings,#embeddings is a np.array 
            )

And I extract the corresponding values like this:
_x = self.embed(_x)#_x is a id list

However, after each optimizer.update(), the weights never change. The values were always the initial ones.

Was there something I did wrong?

**Comment by niboshi** [comment]
Thank you for reporting!
Could you provide full reproducing code?

**Comment by createmomo** [comment]
I am really sorry. After a further analysis today, I found that this is not a BUG. Please remove the BUG label and I will also close the issue.

As for my issue, actually, the weights changed! Because I have a very large vocabulary embeddings, the weights will be updated of which the words were used in my experiments. The weights of words not used will not be updated during the training process.

**Comment by niboshi** [comment]
That's good!
Please feel free to post another bug report :smiley:
