### ISSUE TITLE
Chainer website 

### ISSUE THREAD

**Issue by edmBernard** [chainer/chainer#3353]
I was not a direct user of chainer. 
For potential new user or interested user, it could be cool to add direct link to ChainerCV and ChainerRL on your website. 
I regularly look at chainer and just discover this two repositories.
It's an awsome feature to have complete example and state of art model ready to use.

**Comment by niboshi** [comment]
Thank you for suggestion!
We have put links to extension libraries on our website.
Closing the issue.
