### ISSUE TITLE
Feature request: new fast RNN module request

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#3380]
The author in paper https://arxiv.org/abs/1709.02755 advocate a new RNN, which is faster than even highly optimized cuDNN LSTM. this is the paper.

**Comment by sharpstill** [comment]
By the way . the author has already present source code in PyTorch: https://github.com/taolei87/sru , I think it's natural and simple to convert   to chainer.

**Comment by bkvogel** [comment]
Thank you for the feature request. I think it is always nice to have Chainer implementations of new models. If you are able to port it to Chainer, please let us know and we would be happy to add it to the list of external Chainer examples.

**Comment by unnonouno** [comment]
I implemented SRU here #3426. Note that this implementation is not enough fast because it does not calculate all time steps in one kernel. I'll make optimized version.

**Comment by jekbradbury** [comment]
It's closely related to the QRNN, whose Chainer code (for a timestep-fused kernel) is here: https://gist.github.com/jekbradbury/a3a5ae890328db49d8093c1a5bdc8a1e
