### ISSUE TITLE
Revisit Link tests

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#3387]
Many builtin links are simple wrappers for corresponding functions. In order to test such link, it should be enough to check whether the underlying function is called with correct arguments.

However, currently, the same checks as the corresponding functions are being done in link tests.
For example, `links_tests/connection_tests/test_linear` checks whether forward/backward computations are correct, while the same checks are done in `functions_tests/connection_tests/test_linear`.
Those are duplicated checks which are waste of not only computational resource, but also implementation cost.

**Comment by hvy** [comment]
This is still an issue.

**Comment by hvy** [comment]
We should instead test that corresponding functions are called from the link (mock). Do this separately or in the same PR.

**Comment by hvy** [comment]
I will start working on removing duplicate tests (between links and functions) and check if it'll give some improvements in test running time. Additionally, as mentioned in the above comments we'd ideally want to do some basic tests.

Function tests will be further refactored (overhaul) in separate PRs.
