### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by koreyou** [chainer/chainer#3404]
Very minor typo in the example.

https://github.com/chainer/chainer/tree/master/examples/seq2seq#tarin-with-wmt-dataset

It says

```
Tarin with WMT dataset
```

where it should be

```
Training with the WMT dataset
```

**Comment by okuta** [comment]
Cloud you send a PR?

**Comment by HusainZafar** [comment]
Hi @okuta, could you please review this?
