### ISSUE TITLE
Feature request: logarithmic gamma function

### ISSUE THREAD

**Issue by muupan** [chainer/chainer#3408]
The logarithmic gamma function is missing in Chainer. It is required when parameterizing a Beta distribution.

Tensorflow implementation: https://www.tensorflow.org/api_docs/python/tf/lgamma
Pytorch implementation: https://github.com/rachtsingh/lgamma (unofficial)

**Comment by muupan** [comment]
To implement backward computation of it, digamma and polygamma functions are required. https://github.com/cupy/cupy/issues/865

**Comment by muupan** [comment]
bump

**Comment by mitmul** [comment]
lgamma will come with many probability distribution implementations in this PR #4678:
https://github.com/chainer/chainer/pull/4678/files#diff-714b726ad7916530f4c83de6e33e3e9b

**Comment by muupan** [comment]
Great, but its backward computation (digamma) is implemented only in cpu using scipy. I think it may be good to keep this issue open until its full gpu support. https://github.com/YoshikawaMasashi/chainer/blob/fb71a98cece3d23b73e90ecae4bc024c00dee60f/chainer/functions/math/digamma.py

**Comment by beam2d** [comment]
This issue has been fixed via #4720.
