### ISSUE TITLE
Remove @property  from model.vision.vgg or show a official way to modify pretrained vgg

### ISSUE THREAD

**Issue by apple2373** [chainer/chainer#3473]
A problem happens when we try to delete certain layers (e.g. fully connected layers) from chainer implemented vgg, using pretrained weights. 

In v2.0.0, I was able to do simply
```
vgg = VGG16Layers(pretrained_model=pretrained_model)
del vgg.fc6
del vgg.fc7
del vgg.fc8
```
However because some of the vgg is declared as `@property` after v2.0.1, this no longer works.  Jiren explains the problem here: https://chainer.slack.com/archives/C0LC5A6C9/p1501822862324456

This is from a slack conversation before. I revised this problem and found it's still there. No chainer developer cares it. So I just raise an issue here. 

The whole discussion is posted 
from https://chainer.slack.com/archives/C0LC5A6C9/p1501815339058362
to https://chainer.slack.com/archives/C0LC5A6C9/p1501828268794828

 As far as I know, the current solution is to downgrade to v2.0.0.  Because removing some layers are very common operation, chainer should provide a way to remove layers. I don't know why chaienr's developer added `@ property `.... If there is no significant reason, just delete it! If there is, they should provide official instructions to modify the vgg model. A solution I can think is, to provide an official function to remove, which works like this:
```
vgg = VGG16Layers(pretrained_model=pretrained_model)
vgg.delete("fc6")
vgg.delete("fc7")
vgg.delete("fc8")
```

**Comment by yuyu2172** [comment]
Hi.
ChainerCV is planning to release an implementation of VGG that supports the functionality you are talking about.
The API has changed from `chainer.links.vgg`. Notably, it works with RGB instead of BGR, which is consistent with the convention adopted in ChainerCV.
This feature will be included in the next release, which should happen shortly.
Also, we will write a more friendly tutorial on how to use this class.

https://github.com/chainer/chainercv/tree/master/chainercv/links/model/vgg

```python
from chainercv.links import VGG16
model = VGG16(pretrained_model='imagenet')
model.pick = 'pool5'
model.remove_unused()  # This deletes fc6, fc7 and fc8
```

**Comment by yuyu2172** [comment]
Also, you can check the reason why `@property` was added from here.
https://github.com/chainer/chainer/pull/2810

**Comment by apple2373** [comment]
Sounds good! I'm looking forward to the new chainercv.  Also, thank you for showing the reason of `@property`
