### ISSUE TITLE
AttributeError: module 'cupy.cuda.cudnn' has no attribute 'getTensor4dDescriptor'

### ISSUE THREAD

**Issue by MannyKayy** [chainer/chainer#3512]
I upgraded my nvidia-docker file to use cuDNN7, cuda 8.0 with chainer 3.0.0rc1 on ubuntu 14.04. 
This now causes issues with the BatchNormalization link.
Here is the [full trace in a gist](https://gist.github.com/MannyKayy/a0dfbdb9828b1ad9edbb5bf1accd4067).

I have tried different versions of chainer 3.x and cuDNN, this appears to be an issue with just chainer 3.0.0rc1.

Any help would be useful, thanks.

**Comment by yuyu2172** [comment]
This is probably an issue with the version of CuPy.
If you are using Chainer 3.0.0rc1, CuPy should be 2.0.0rc1.

**Comment by MannyKayy** [comment]
Thanks, looks like that was the problem.

**Comment by ShigekiKarita** [comment]
@yuyu2172 I also met this issue in
```
pip freeze | grep -e cupy -e chainer
chainer==3.1.0
cupy==2.2.0
```
