### ISSUE TITLE
Feature : ONNX support 

### ISSUE THREAD

**Issue by edmBernard** [chainer/chainer#3524]
Everything is in the title.
Is there any plan to support [ONNX](https://github.com/onnx/onnx) in chainer ?

**Comment by masahi** [comment]
Yeah onnx support would be great. 
I'd love to use chainer for training, but I need to deploy my model in C++ only interface.

With onnx support, I can do training in chainer, export the trained model to onnx, and deploy the onnx model using other framework.

**Comment by takagi** [comment]
#3572

**Comment by kmaehashi** [comment]
bump (#3572)

**Comment by mitmul** [comment]
@edmBernard @masahi Now ONNX-Chainer supports exporting Chainer models into ONNX. https://github.com/chainer/onnx-chainer
