### ISSUE TITLE
Probability distribution implementations

### ISSUE THREAD

**Issue by muupan** [chainer/chainer#3622]
Official implementations of various probability distributions that supports batch computation and differentiation would be useful.

Tensorflow has a thorough set of distributions under contrib. https://www.tensorflow.org/api_guides/python/contrib.distributions PyTorch seems to have started supporting distributions very recently, still limited though. http://pytorch.org/docs/master/distributions.html

ChainerRL has a set of distribution implementations, but they are still limited and designed for RL. http://chainerrl.readthedocs.io/en/latest/distributions.html I think it would be better to have a general-purpose and thorough set of distributions in Chainer.

**Comment by muupan** [comment]
PyTorch now supports a lot of distributions: http://pytorch.org/docs/master/distributions.html

**Comment by mitmul** [comment]
- Bernoulli
- Beta
- Binomial
- Categorical
- Cauchy
- Chi2
- Dirichlet
- Distribution
- Exponential
- FisherSnedecor
- Gamma
- Geometric
- Gumbel
- Laplace
- LogNormal
- Multinomial
- Normal
- OneHotCategorical
- Pareto
- StudentT
- Poisson
- Uniform
- TransformedDistribution
- biject_to
- kl_divergence
- register_kl

**Comment by kmaehashi** [comment]
bump
