### ISSUE TITLE
Support variable.repeat() or F.repeat()

### ISSUE THREAD

**Issue by MannyKayy** [chainer/chainer#3632]
Setup:
  - Chainer version 3.0.0.rc1
  - CuPy version 2.0.0rc1
  - OS/Platform Ubuntu 14.04
  - CUDA/cuDNN version CUDA8/cuDNNN6

 F.tile() is limiting when you need fine grained control on how repeats are carried out.

For example:

`a = np.arange(0,64).reshape(1,4,4,4).astype('i')`
`b = a.repeat(4,2).repeat(4,3)`

It would be nice to support this via an F.repeat() function. Or via deeper support for variables within cupy in order to avoid attribute errors like this:

`AttributeError   Traceback (most recent call last)`
`<ipython-input-334-13a244daf06b> in <module>()`
`----> 1 cupy.repeat(b,4,3)`

`/opt/conda/lib/python3.5/site-packages/cupy/manipulation/tiling.py in repeat(a, repeats, axis)`
`     67 `
`     68     """`
`---> 69     return a.repeat(repeats, axis)`

`AttributeError: 'Variable' object has no attribute 'repeat'`
`

**Comment by kmaehashi** [comment]
bump (#3735 review is ongoing)
