### ISSUE TITLE
chainer 3.0.0 has bug in NStepLSTM, but v2.1.0 is OK. and one more question about NStepLSTM

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#3673]
I found that chainer v3.0.0 has NStepLSTM not produce the same results with chainer v2.0
**1. bug example**
My idea is implemented a simple idea, LSTM image classifier. I give you my idea and my jupyter code in zip file of attach file.
In this simple LSTM implement, the v2.1.0 and v3.0.0 has different result.
In this simple example, each row of mnist image represent a time step, and each row's column vector(horizontal line in image)  represent feature vector in this time step. The loss is calculated from out of last row. (this example prove LSTM truly have ability to remember something)
[LSTM_image_classifier.zip](https://github.com/chainer/chainer/files/1413604/LSTM_image_classifier.zip)
attach file is my jupyter book code, you can just run it  from browser and find the bug result of different chainer version.

**2. question**
my paper deadline is 11.08.
My time is urgent, I put my second question in stackoverflow:
https://stackoverflow.com/questions/46915125/how-to-write-bptt-updater-when-using-chainers-l-nsteplstm
My another question is that How do I implemented BPTT updater when using L.NStepLSTM , or just use standard_updater is enough? do not need to implement my self?

**Comment by soskek** [comment]
In regards to your the 2nd question only, I can answer.

NStepLSTM may have no truncation function. If wanna truncate, users will feed separated (truncated) chunks sequentially into NStepLSTM with bridging truncated hidden states.
For example, if you want encode input `[x1, x2, x3, x4, x5, x6]` with 2-length truncation, an example you will do is as follows: (as very rough pseudo code)
```
outputs = []
h, c, out = NStepLSTM(None, None, [x1, x2])
outputs.append(out)
h, c, out = NStepLSTM(h.data, c.data, [x3, x4])
outputs.append(out)
h, c, out = NStepLSTM(h.data, c.data, [x5, x6])
outputs.append(out)
use_outputs(outputs)
```

An example, my code of a language model using NStepLSTM with truncation, is [here](https://github.com/soskek/rnnlm_chainer/blob/master/train.py#L115-L131), and this uses `loss.unchain_backward()` instead of `h.data` and `c.data` shown above.

**Comment by sharpstill** [comment]
@soskek If I want to use `NStepLSTM` of concatenate of all time-steps to calculate loss, I want to use F.sigmoid_cross_entropy. Should I calculate loss at each time-step , and use `loss+=F.sigmoid_cross_entropy(y[t],ts[t])` to sum up all time-step. **OR** just use `F.sigmoid_cross_entropy` to apply all the return of NStepLSTM, one Variable denotes all time-step sequence as its argument is enough and OK?

**Comment by sharpstill** [comment]
In your https://github.com/soskek/rnnlm_chainer/blob/master/nets.py#L75
It seems one call of F.sigmoid_cross_entropy to apply all time-step is OK?

**Comment by soskek** [comment]
Such final concatenation is acceptable as long as you do valid truncation for recurrent hidden states.

**Comment by sharpstill** [comment]
@soskek What do you mean by **"valid truncation for recurrent hidden states."** I can't understand this word you say.

**Comment by sharpstill** [comment]
How to "valid truncation for recurrent hidden states."

**Comment by soskek** [comment]
It was my bad phrasing.
I want to just say that concatenation is OK you truncate them correctly.
