### ISSUE TITLE
unary_math_function_test with non-twice differentiable functions fails

### ISSUE THREAD

**Issue by hvy** [chainer/chainer#3677]
Is it possible to allow the `unary_math_function_test` helper to execute different functions when computing the forward passes for the double backward test?

At the moment, a test will fail if the tested function cannot be differentiated twice. We usually get around this problem by writing a wrapper function that makes it non-linear . Maybe we can achieve the same result this helper that I am not aware of?

There probably exists a better solution, than allowing a different function.

**Comment by takagi** [comment]
It is not possible for the current spec of the helper. How about another argument that specifies the target function is not twice-differentiable and properly gets around?

**Comment by hvy** [comment]
Thanks for the comment! Do you mean adding an option to completely skip the double backward test or to pass a different forward function to it?

**Comment by hvy** [comment]
Adding boolean `check_forward`, `check_backward`, `check_double_backward` arguments would also make a quite clean API.
