### ISSUE TITLE
ChildSumTreeLSTM cannot accept less than 2 children

### ISSUE THREAD

**Issue by soskek** [chainer/chainer#3680]
ChildSumTreeLSTM cannot accept less than 2 children.
For example, for 1 child case,
```
self.encoder(None, None, x)
```
an error
```
Expect: in_types.size >= 3
Actual: 2 < 3
```

occurs.
Modifying [tree_lstm function](https://github.com/chainer/chainer/blob/v3.0.0/chainer/functions/activation/tree_lstm.py#L68) is required.

kc reported this issue on [Chainer Slack](https://chainer.slack.com/archives/C3TDS9QGK/p1508909406000009), thanks.

**Comment by Crissman** [comment]
@soskek Can you make a PR to resolve this issue?

**Comment by soskek** [comment]
I'm done at #4275!
