### ISSUE TITLE
CHAINER_SEED is not used as documented

### ISSUE THREAD

**Issue by kmaehashi** [chainer/chainer#3751]
Currently `CHAINER_SEED` environment variable is only used in `n_step_rnn`.

https://github.com/chainer/chainer/blob/v3.0.0/chainer/functions/connection/n_step_rnn.py#L126

The documentation is a bit misleading, as if it makes all CUDA code deterministic.
https://docs.chainer.org/en/stable/reference/configuration.html?highlight=CHAINER_SEED

**Comment by niboshi** [comment]
I found `CHAINER_SEED` is used in CuPy (`cupy/random/generator.py`).
Maybe the statement in the documentation refers to that.
But I think this implementation is not great and should be fixed any way.

**Comment by niboshi** [comment]
Also, the current implementation sets the same seed for all GPU devices.
That should be fixed, too.

**Comment by kmaehashi** [comment]
bump

**Comment by kmaehashi** [comment]
Will be fixed in https://github.com/chainer/chainer/pull/3662

**Comment by hvy** [comment]
Note also that the CuPy documentations doesn't mention `CHAINER_SEED` although it's being used.

**Comment by kmaehashi** [comment]
Related: https://github.com/chainer/chainer/issues/3754

**Comment by kmaehashi** [comment]
I'll update the docs.
