### ISSUE TITLE
chainer NStepBiLSTM out_size bug report

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#3752]
this bug appears in both v3.0.0 and v2.1.0
The out_size of  L.NStepBiLSTM  I defined is 512, but in actually it output 10 x **1024**
```
>>> import chainer
>>> chainer.__version__
'2.1.0'
>>> import cupy
>>> cupy.__version__
'1.0.3'
>>> import numpy as np
>>> import chainer.links as L
>>> lstm_t = L.NStepBiLSTM(1, 256, 512, dropout=0.0)
>>> a = chainer.Variable(np.arange(10 * 256, dtype=np.float32).reshape(10,256))
>>> _,_,e = lstm_t(None,None,[a])
>>> e[0].shape
(10, 1024)
```

**Comment by chenzhekl** [comment]
SInce you are using bi-directional LSTM, the output size is double the size of hidden state. [Here](https://docs.chainer.org/en/stable/reference/generated/chainer.functions.n_step_bilstm.html#chainer.functions.n_step_bilstm) may be a good clearance.

**Comment by aonotas** [comment]
I agree. 
As @chenzhekl  mentions, the output size is double the size of the hidden state.
When you use Bi-LSTM/GRU/RNN, the output size must be 1024 (512 * 2).

**Comment by Crissman** [comment]
Expected behavior.
