### ISSUE TITLE
Predefined ImageNets `predict` method is inaccurate

### ISSUE THREAD

**Issue by belltailjp** [chainer/chainer#3756]
Hello.
I have been using Chainer predefined ImageNets (`chainer.links.VGG16Layers` etc.) but recently found out that they are inaccurate than one can usually expect.

Specifically, one can basically use either `__call__` or `predict` to run inference and I think the result should be the same if an equivalent preprocessing is appropriately conducted.
However in my quick experiments the results are significantly different. With VGG and GoogLeNet, `__call__` performs better whereas `predict` works better with ResNets.

Here is Top-5 accuracy of single-image (no crop, no oversample, no ensemble) inference
 (I used only 2000 samples)

| CNN | \_\_call\_\_ | predict |
| --- | ------------ | ------- |
| GoogLeNet | **86.75%** | 74.1% |
| VGG16Layers | **85.2%** | 74.0% |
| ResNet50Layers | 12.7% | **78.6%** |
| ResNet101Layers | 15.1% | **78.75%** |
| ResNet152Layers | 14.8% | **80.65%** |

I'm not pretty sure if it's a chainer-side problem or just I'm doing wrong, but as far as I checked the [document](https://docs.chainer.org/en/stable/reference/generated/chainer.links.ResNet50Layers.html) (and briefly read the [source code](https://github.com/chainer/chainer/blob/master/chainer/links/model/vision/resnet.py#L466)) I couldn't find that I'm doing badly.

Here is the reproduction code and the result.
https://gist.github.com/belltailjp/7677987c699b2f3cf766ecc89958dff2
Run `prepare.sh` followed by `python run.py`.
You can change CNN type by just comment out, and switch `__call__` and `predict` by simply changing `use_predict = False` line.
I confirmed this issue with the following environment: Chainer 3.0.0, Cupy 2.0.0, Ubuntu 16.04, CUDA8.0, cuDNN7, Python 3.6.1

**Comment by chenzhekl** [comment]
Have you tried setting [`chainer.config.train`](https://docs.chainer.org/en/stable/reference/core/configuration.html) to `False`?

**Comment by belltailjp** [comment]
You're right, I should have set train mode off... it's a common pitfall...
Now the result becomes a bit different; `predict` is always inaccurate than `__call__` regardless of `oversample` mode.

| CNN | \_\_call\_\_ | predict | predict(oversample) |
| --- | ------------ | ------- | ------------------- |
| GoogLeNet | **88.7%** | 74.1% | 75.5% |
| VGG16Layers | **86.85%** | 74.0% | 74.95% |
| ResNet50Layers | 89.6% | **78.6%** | 79.95% |
| ResNet101Layers | 90.05% | **78.75%** | 80.5% |
| ResNet152Layers | 90.8% | **80.65%** | 81.4% |

**Comment by chenzhekl** [comment]
`predict` center cropped the input images to `[224, 224]`, while `__call__` didn't. This might account for the difference in preformance.

**Comment by belltailjp** [comment]
I actually tried that within the reproduction script, by doing the same as [this](https://github.com/chainer/chainer/blob/master/chainer/links/model/vision/resnet.py#L261) followed by [this](https://github.com/chainer/chainer/blob/master/chainer/links/model/vision/resnet.py#L265) but it doesn't cause of such a big accuracy drop (rather, I got up to 1% improvement).

**Comment by ronekko** [comment]
Hi.
When you use `predict` method, input images must be `RGB` order of color channels.
However, in your script the `BGR` image is used since `cv2.imread` read an image as `BGR`.
Note that input for `__call__` must be `BGR`, so the case of `__call__` in your script is correct.

**Comment by chenzhekl** [comment]
In your script, input images are directly resize the image to `[224, 224]`. Would you mind retesting it with resizing first and then cropping?

**Comment by belltailjp** [comment]
@ronekko 
It solved!!! It's also a common pitfall... (of course I tried both RGB&BGR, but I changed the color order for _both_ `predict` and `__call__`, that's why I couldn't notice..)
This should definitely be properly documented.
