### ISSUE TITLE
Missing document of side-effect on graph visualization of None grads

### ISSUE THREAD

**Issue by hvy** [chainer/chainer#3797]
As a side-effect of defining "non-differentiable" functions (e.g. returning `None` gradients) in favor of performance, unchained nodes won't appear in the visualizations of the [computational graphs](https://docs.chainer.org/en/stable/reference/graph.html).

This may be intuitive or not, depending on the function. We might consider document this behavior.

**Comment by kmaehashi** [comment]
bump

**Comment by mitmul** [comment]
I'll add some descriptions for
- `F.sign`
- `unchain()`
