### ISSUE TITLE
Untested functions in basic_math

### ISSUE THREAD

**Issue by hvy** [chainer/chainer#3798]
Some functions in `basic_math` seem to be missing tests such as the double backward test for the add function.

https://github.com/chainer/chainer/blob/master/tests/chainer_tests/functions_tests/math_tests/test_basic_math.py

**Comment by kmaehashi** [comment]
bump

**Comment by kmaehashi** [comment]
Although we assume there should be no bugs around there, it's obviously better to add tests for it.
