### ISSUE TITLE
Adding option not to copy function on function-call

### ISSUE THREAD

**Issue by bordingj** [chainer/chainer#380]
When a function is only called ones prior to calling the backward method, there is no reason to copy the function on every call, since no duplications in the expression graph will be made if the function is only called ones. 

If you do not copy a given function when it is called we can for example preallocate output arrays of a function as instances of the function and avoid having to delete and reallocate these arrays on every iteration. 

I added the following custom copy-method to the Function-class:

```
def __copy__(self):
    a_copy = self.__new__(type(self))
    for name, value in self.__dict__.items():        
        if name in self.parameter_names or name in self.gradient_names:
            setattr(a_copy, name, value)
        elif hasattr(value, 'shape'):
            setattr(a_copy, name, value.copy())
        else:
            setattr(a_copy, name, copy.copy(value))
    return a_copy
```

and changed the **call**

```
def __call__(self, *inputs, copy_func=True):
    if copy_func:
        self = copy.copy(self)
```

I also added the option to preallocate the outputs of various functions.
Then I created a large recurrent multilayer LSTM network and made copies of every function for every time-step and preallocated their output arrays.

This gave me a 15% speed-up. (which is a lot when you have to train a model for multiple weeks)

I know that this is kind of a hack and should not be the default way to do, but it would be nice to have the option.

**Comment by beam2d** [comment]
Thank you for the suggestion, and sorry for the late reply. I totally agree on your suggestion; we should omit the copy on pure function calls.

I'm now tackling on another issue on redesigning the model structure at #363. It does not only redesign the FunctionSet, but separates parameters from Function, and all Function implementations will become "pure". So, after this issue is done, we do not have to copy each Function object on every call anymore.

Output array preallcation is not covered by the above issue. Your report suggests it introduce much speedup on complex networks. We should further investigate the cause of slowness, in particular the memory pool.

**Comment by bordingj** [comment]
Thank you for the answer. 

I decided to remove the array preallocation from my implementations because I did not believe that the speedup justistied the increased complexity of my implementations. The speedup was also less significant after the #333 update. Moreoever, array preallocation doesnt make sense when working with recurrent models with variable input/output-lengths.

**Comment by beam2d** [comment]
I'm happy to hear that #333 is effective :). We will go on with the dynamic allocation strategy with memory pool, though we might have to think about providing an optional way to allow speedup with preallocation in the future. Anyway, thank you for the further report!

**Comment by tscohen** [comment]
Perhaps an easy way to support preallocation would be to have an optional out parameter in the new functional Function's from #363. Numpy supports this for most operations, e.g. dot: http://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html

When out=None (default), the Function will allocate new memory. That way, the function remains easy to use for prototyping.

**Comment by beam2d** [comment]
This issue should have been solved via a long development after the last comment. Now we do not copy the function at invocation.
