### ISSUE TITLE
Use utils.force_array in function tutorial

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#3808]
It could be a common pitfall to forget to apply `utils.force_array` on output arrays of `FunctionNode.forward`.
I think it's better to use it in the function tutorial: https://docs.chainer.org/en/stable/tutorial/function.html

**Comment by niboshi** [comment]
bump

**Comment by niboshi** [comment]
bump

**Comment by kmaehashi** [comment]
I'll fix this after finish rewrite of Function->FunctionNode
