### ISSUE TITLE
Reorganize reference of  core functionalities and example implementations

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#3811]
Currently, documentation is organized so that **"core functionalities"** part and **"example implementation"** are separated.

For example, `chainer.training.Extension` is documented under Core functionalities > Training loop abstraction > Extension, whereas `chainer.training.extensions.Evaluator` is documented under Trainer extensions.

```
- Reference Manual
    - Core functionalities
        - Training loop abstraction
            - Extension
                - chainer.training.Extension
                - chainer.training.make_extension
    - ...
    - Dataset examples
    - Iterator examples
    - Trainer extensions
        - chainer.training.extensions.dump_graph
        - chainer.training.extensions.Evaluator
        - chainer.training.extensions.ExponentialShift
        - ...
    - ...
```

That's the same for other concepts including datasts, iterators, etc.

While this may match the source code structure, I think it's not necessarily best for users.
For example, a user who reached `chainer.training.Extension` may want to know the concrete extension examples which utilize this class. Conversely, a user who reached `chainer.training.Evaluator` may want to know what's the common interface of trainer extensions. I think they expect those documentation are closely located and easilly browsable.

So I'd like to suggest reorganizing the reference, so that each core entity (e.g. `chainer.training.Extension`) is documented on top of the current "example" documentation.

**Comment by niboshi** [comment]
bump

**Comment by Crissman** [comment]
Done as part of #3241 . Ok to close issue?

**Comment by niboshi** [comment]
@Crissman 
OK. Thanks!
