### ISSUE TITLE
Unified dataset caching test

### ISSUE THREAD

**Issue by hvy** [chainer/chainer#3813]
The caching functionality is currently being tested in multiple dataset tests (`test_cifar.py`, `test_svhn.py`). We could unify this, especially considering the fact that the test are slow (download/remove per test).

**Comment by kashif** [comment]
@hvy I can have a look at this issue if no one has taken it

**Comment by hvy** [comment]
@kashif Thank you for the offer. This issue is still open and no one is working on it at the moment. If you have an idea for how to approach it, I think you are more than welcome to.

Some relevant contexts are
- Tests that are flagged with the `@attr.slow` decorator (e.g. [MNIST download test](https://github.com/chainer/chainer/blob/master/tests/chainer_tests/datasets_tests/test_mnist.py#L43-L47)) are skipped the be regular CI and is instead scheduled to run once a week.
- The general download/caching behavior which the dataset tests depend on is tested [here](https://github.com/chainer/chainer/blob/master/tests/chainer_tests/dataset_tests/test_download.py).

**Comment by hvy** [comment]
@kashif Maybe we lost contact somewhere but do you happen to have any updates on this?

**Comment by kashif** [comment]
@hvy so sorry I also didnt work on it, as some deadlines came up... having a look at it in the next days

**Comment by hvy** [comment]
Thank you for the quick response. That sounds great. I simply wanted to check the status and if you are busy we can work on it as well.
