### ISSUE TITLE
What exactly is the difference between V3 and master version of chainer?

### ISSUE THREAD

**Issue by EmbraceLife** [chainer/chainer#3845]
When I switch from master to V3 of chainer in github, it says V3 is 300 commits ahead and 600 commit behind master. How they exactly differ from each other?

I am new to chainer and plan to explore its internals by reading its source code. for this purpose, which version should I stay with?

Thanks!

**Comment by takagi** [comment]
`master` is the latest development branch for Chainer v4, and `v3` branch includes backporting pull requests which make no incompatible changes after it branched from the master. For your purpose, it would be good to stay with `master`.
