### ISSUE TITLE
QXcbConnection: Could not connect to display localhost:12.0425.

### ISSUE THREAD

**Issue by schelian** [chainer/chainer#3861]
Hi all, new to Chainer but not deep learning.  I have TensorFlow w/ CUDA & CUDNN working on a cluster but no graphics.  When I try to run the MNIST example, I get the error message below.  Can someone please tell me which lines to comment out to prevent the plotting from crashing the program?

```
this epoch [############################     total [##................................................]  4.17%
this epoch [############################X11 connection rejected because of wrong authentication. 0 epoch / 20 epochs
QXcbConnection: Could not connect to display localhost:12.0425.
Aborted (core dumped)
```

**Comment by schelian** [comment]
Handled by #3925.  Thank you @niboshi!

**Comment by niboshi** [comment]
Oh, I'm sorry I didn't notice #3924 was a duplicate of this issue.
Thank you for reporting, anyway!
