### ISSUE TITLE
Gradients of gradients

### ISSUE THREAD

**Issue by tscohen** [chainer/chainer#388]
Would it be possible to implement the computation of gradients of gradients in chainer? Perhaps we can have a special gradFun() that does the same as grad, except that it adds a symbolic version of the backwards operations to the forwards graph. The result would be a normal forward graph that can be differentiated in the usual way.

I'm not very familiar with Chainer yet so there may be obstructions to this idea.

This feature would be useful for second order optimization and backpropping through markov chains (see http://arxiv.org/pdf/1410.6460v4.pdf, where they compute gradients of functions of gradients of functions)

**Comment by beam2d** [comment]
Thank you for the requiest, and sorry for the late reply. Currently, we do not consider the higher order derivatives. It might be required for further flexibility, though it also might introduce more complexity to the framework, so we do not plan to add such feature. AFAIK, [autograd](https://github.com/HIPS/autograd) supports higher order derivatives. We might be able to support higher order derivatives by implementing backward operations by forward operations, though it requires much more complexity on implementing optimized backward methods.

**Comment by oeway** [comment]
Is it possible to include [autograd](https://github.com/HIPS/autograd) into chainer to do backwards operation automatically? It's easy to write a forward function but backward is usually not that easy.

**Comment by beam2d** [comment]
After more than 1 and a half years, we finally decided to restart thinking about this feature and will hopefully include it to v3. I'm now making the first design.

**Comment by beam2d** [comment]
Fixed via #2970.
