### ISSUE TITLE
Numexpr as optional dependency

### ISSUE THREAD

**Issue by mihirparadkar** [chainer/chainer#3908]
I think a lot of the CPU side of inference and training could be sped up by using numexpr (https://github.com/pydata/numexpr) instead of plain numpy. I have some simple benchmarks in this notebook that indicate that 2x-20x speedups are possible on larger arrays: 

https://mihirparadkar.github.io/numexpr/Python%20array%20computations%20and%20the%20need%20for%20speed.html

From the numexpr documentation, the speed-ups come mainly from not allocating temporary arrays for every numpy function, and from being able to use multiple threads. It's another dependency, but I think it could be an optional one like CuPy. I also don't believe there should be any breaking API changes.

I'll be working on a PR, but I wanted to hear some feedback first.

**Comment by niboshi** [comment]
Being implemented in #4395.
