### ISSUE TITLE
Favicon for websites

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#3915]
Currently our websites do not have favicons. They should have them.

- [x] [chainer.org](https://chainer.org/)
- [x] [cupy.chainer.org](https://cupy.chainer.org/)
- [ ] [docs.chainer.org](https://docs.chainer.org/)
- [ ] [docs-cupy.chainer.org](https://docs-cupy.chainer.org/)

**Comment by niboshi** [comment]
bump

**Comment by niboshi** [comment]
bump

**Comment by niboshi** [comment]
PR for chainer.org: https://github.com/chainer/chainer.org/pull/98

**Comment by okuta** [comment]
Merged.

**Comment by niboshi** [comment]
Not all the sites are fixed yet.
