### ISSUE TITLE
ADAM method error

### ISSUE THREAD

**Issue by pradAI** [chainer/chainer#3921]
Hi,

I am trying set Adam optimization algorithm but receiving the following error, can you please help me how to set parameters?

python3.5/site-packages/chainer-1.22.0-py3.5-linux-x86_64.egg/chainer/optimizers/adam.py", line 51, in lr
return self.alpha * math.sqrt(fix2) / fix1
ZeroDivisionError: float division by zero

Please see the below parameters what i have set.

I am traying execute the following script and it is working when I set to **MomentumSGD** but not **Adam**.
https://github.com/mitmul/ssai-cnn/blob/master/scripts/train.py

Thanks for you support.

    # Optimization settings
    parser.add_argument('--opt', type=str, default='Adam', choices=['MomentumSGD', 'Adam', 'AdaGrad'])
    parser.add_argument('--weight_decay', type=float, default=0.0001)
    parser.add_argument('--alpha', type=float, default=0.001)
    parser.add_argument('--lr', type=float, default=0.0001)
    parser.add_argument('--lr_decay_freq', type=int, default=100)
    parser.add_argument('--lr_decay_ratio', type=float, default=0.1)
    parser.add_argument('--seed', type=int, default=1701)
    args = parser.parse_args()
    return args

**Comment by niboshi** [comment]
Thank you for reporting.
It looks the same issue as #3214. Could you take a look at it (and [the answer at StackOverflow](https://stackoverflow.com/questions/46035824/adam-optimizer-report-error-in-chainer)) and see if it helps?

**Comment by pradAI** [comment]
Thank you for the solution. 

I tried it  but got the same error. 

from chainer.optimizers import Adam
optimizer = Adam(alpha=0.001) 

Thank you

**Comment by niboshi** [comment]
I see.
Could you give the full stack trace?

(Also, I think you edited the first post by mistake. Could you revert it?)

**Comment by niboshi** [comment]
Thank you detailed information.
I have not tested, but it seems the problem is that the script you are using evaluates `optimize.lr` before the first update of the optimizer (https://github.com/mitmul/ssai-cnn/blob/master/scripts/train.py#L312).

Could you remove that line and check if it solves the problem?

**Comment by pradAI** [comment]
Excellent, it is working now. 

Thank you niboshi

**Comment by niboshi** [comment]
You're welcome!
