### ISSUE TITLE
Automatic broadcast

### ISSUE THREAD

**Issue by beam2d** [chainer/chainer#3968]
In #228, we have once decided not to support automatic broadcast which is error prone for users. It's now time to rethink; it looks more important to have an array semantics closer to NumPy/CuPy, where the lack of automatic broadcast is one of the major gaps between ndarrays and Variables.

The scope would not be limited to basic math operators, but it seems good to start from functions in `basic_math.py`.

**Comment by kmaehashi** [comment]
bump
