### ISSUE TITLE
Progress bar exceeds 100% in some situation

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#3969]
In some situation, the progress bar in `progress_bar` extension exceeds 100%. We can find such situation in the PTB example. Where the default total epoch number (39) is not divisible by 7, the number epochs consumed in one iteration.

```
%(master)[]./train_ptb.py --test
#vocab = 10000
     total [#####################################################] 107.69%
this epoch [..................................................]  0.00%
         6 iter, 42 epoch / 39 epochs
  0.068392 iters/sec. Estimated time to finish: -1 day, 23:59:53.733622.
```

Detail discussion is found in #1384.

**Comment by ankokumoyashi** [comment]
> (2) Fix ProgressBar so that it accepts the situation in which current epoch number can exceed the number of total epochs.

Can I try this one out?

**Comment by delta2323** [comment]
Yes, go ahead! Let us know if you need this discussion on the specification.
