### ISSUE TITLE
Need to adjust tolerance

### ISSUE THREAD

**Issue by kmaehashi** [chainer/chainer#3986]
Following tests are occasionally failing, maybe because the tolerance is too sensitive.

- [ ] tests.chainer_tests.functions_tests.loss_tests.test_contrastive /TestContrastive_param_21/test_forward_cpu/
- [ ] tests.chainer_tests.functions_tests.loss_tests.test_contrastive /TestContrastive_param_23/test_backward_gpu_no_cudnn/
- [ ] tests.chainer_tests.functions_tests.pooling_tests.test_max_pooling_2d /TestMaxPooling2D_param_1/test_double_backward_gpu_no_cudnn/
- [ ] tests.chainer_tests.links_tests.connection_tests.test_deconvolution_2d /TestDeconvolution2DParameterShapePlaceholder_param_10/test_backward_gpu/
- [ ] tests.chainer_tests.test_gradient_check.TestCheckDoubleBackward.test_double_backward_with_params_gpu
- [ ] tests.chainer_tests.functions_tests.pooling_tests.test_unpooling_nd.TestUnpoolingND_param_3.test_double_backward_cpu
- [ ] tests.chainer_tests.functions_tests.pooling_tests.test_average_pooling_nd.TestAveragePoolingND_param_1.test_double_backward_gpu_no_cudnn

Note: this PR is different from #3766 in the sense that the error (difference) is not "too large".

**Comment by niboshi** [comment]
I think `batch_normalization` and `batch_renormalization` have some problem other than numerical tolerance. #3766

**Comment by kmaehashi** [comment]
Thank you, I removed them from the list.

**Comment by hvy** [comment]
I just noticed a quite large error for `TestAverage_param_26/test_backward_cpu/` https://github.com/chainer/chainer/issues/3766#issuecomment-347757626

**Comment by hvy** [comment]
@kmaehashi We can remove `.../TestAverage_param_26/test_backward_cpu/` from this list as well since it is appended to #3766!

**Comment by kmaehashi** [comment]
I added:
-  tests.chainer_tests.functions_tests.pooling_tests.test_max_pooling_2d/TestMaxPooling2D_param_1/test_double_backward_gpu_no_cudnn/
-  tests.chainer_tests.links_tests.connection_tests.test_deconvolution_2d/TestDeconvolution2DParameterShapePlaceholder_param_10/test_backward_gpu/

**Comment by kmaehashi** [comment]
Added:
* tests.chainer_tests.test_gradient_check.TestCheckDoubleBackward.test_double_backward_with_params_gpu

**Comment by kmaehashi** [comment]
bump

**Comment by toslunar** [comment]
Add `tests.chainer_tests.functions_tests.math_tests.test_matmul.TestMatMul_param_117.test_matmul_forward_gpu` to the list.
`float16` batch matmul seems inconsistent between a `numpy` and the current `cupy`.

**Comment by toslunar** [comment]
```
TestDecorrelatedBatchNormalization_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_0__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_24_{contiguous=None, dtype=float32, eps=2e-05, groups=1, n_channels=8, ndim=1}.test_forward
```
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/145/TEST=CHAINERX_chainer-py3,label=mn1-p100/console

**Comment by niboshi** [comment]
Now these tests are tracked at #6903
