### ISSUE TITLE
How to use activation function "PReLu" 

### ISSUE THREAD

**Issue by superhez** [chainer/chainer#4055]
I have read the information about "chainer.functions.prelu " but still have no idea how to use it. Could anyone give an example as below? Thanks~

`from keras.layers.advanced_activations import LeakyReLU, PReLU
...
model.add(Dense(512, 123, activation='linear')) 
model.add(PReLU((123,)))

**Comment by hvy** [comment]
Hi, 

Is it the case that you want to use PReLU similar to how it's used in Keras?

Unless you explicitly want to keep track of the weights of PReLU on your own, you might want to consider using http://docs.chainer.org/en/stable/reference/generated/chainer.links.PReLU.html which is a `Link`, a wrapper of the PReLU function that you mentioned. 

The `Link` needs to be instantiated and added to the model. It will initializes the weights and "optimize them for you".

**Comment by superhez** [comment]
It works! Thank you for your information.
