### ISSUE TITLE
Request for beam search

### ISSUE THREAD

**Issue by hvy** [chainer/chainer#4089]
We do not offer **beam search** as a function in Chainer. How about implementing it.

The motivation is that beam search is commonly used in NLP, e.g. for generating sequences during inference. Recently, it has also being used for optimization(?). We've also had discussions about including beam search in our NLP examples, such as #4076 and #2344 .

**Comment by crcrpar** [comment]
I want to know what is going on this issue, since implementing beam search is a little bit demanding.

**Comment by kmaehashi** [comment]
Reopened, still open for discussion.

**Comment by hvy** [comment]
Since we do not have an obvious place to put this function, we might want to extend the scope a bit to discuss where we should put this one as well as other utility-like functions for **inference**.

**Comment by crcrpar** [comment]
I usually steal beam search functions from repositories listed on awesome-chainer and closed PullRequest(https://github.com/chainer/chainer/pull/2344).

For me, it's good to adding `chainer.inference`.

**Comment by hvy** [comment]
That sounds reasonable but I think we should list up other similar features that people want first. Do you have any in mind?

**Comment by crcrpar** [comment]
Sorry for being late.

For me, as a newbie, 
beam search and beam search with attention.

**Comment by hvy** [comment]
For the record, we discussed this topic today and decided that we should start with supporting inference for our official examples. Then we could eventually figure out what sorts of features are missing, and hopefully better discuss where to put them.
