### ISSUE TITLE
Link.xp is not documented

### ISSUE THREAD

**Issue by muupan** [chainer/chainer#4111]
`Link.xp` is not documented. It's a very useful property and should be documented.

https://docs.chainer.org/en/latest/reference/core/generated/chainer.Link.html#chainer.Link

**Comment by kmaehashi** [comment]
Now `Link.xp` is documented. (I'm not sure which commit added this) https://docs.chainer.org/en/latest/reference/generated/chainer.Link.html#chainer.Link.xp
