### ISSUE TITLE
Feature request: Variable.xp to get the array module of its data array

### ISSUE THREAD

**Issue by muupan** [chainer/chainer#4113]
I often need to call `chainer.cuda.get_array_module` for `Variable` objects. Like `Link.xp`, `Variable.xp` would be a useful property.

**Comment by kmaehashi** [comment]
I think it is good to have this feature. Any objections from core team?

One small thing to decide is that what we to behave when the Variable is not initialized (e.g., `chainer.Variable(None).xp`).  Links are always on CPU initially.

**Comment by muupan** [comment]
Although `chainer.cuda.get_array_module(chainer.Variable(None))` returns numpy, raising an error for uninitialized Variables makes more sense to me.
