### ISSUE TITLE
Documentation of chainer.links.Linear has room for improvement

### ISSUE THREAD

**Issue by muupan** [chainer/chainer#4115]
https://docs.chainer.org/en/latest/reference/generated/chainer.links.Linear.html

- The `bias` parameter doesn't exist
- Explanation on how `W` and `b` are initialized ignores `initialW` and `initial_bias`
- There's no explanation on how `out_size=None` works (except in the example section)
- There's no explanation on how `initialW=None` works

In addition to the above, I think shapes and dtypes of `W` and `b` should be documented, otherwise they are out of the scope of the compatibility policy. However, this is not specific to `chainer.links.Linear`.

**Comment by Crissman** [comment]
> @Crissman Shapes are documented in some parameters. Please see hx etc. in n_step_gru: https://docs.chainer.org/en/stable/reference/generated/chainer.functions.n_step_gru.html

Next step is to go through the documentation of all of the functions, and add shape and maybe dtype information to them. Reviewing some of the other frameworks to see how they handle this.

**Comment by kmaehashi** [comment]
Let me close this issue and continue discussion in #2182.
