### ISSUE TITLE
output size of 1×1 conv in GoogLeNetBN is different in chainer example and CNTK.

### ISSUE THREAD

**Issue by takaaki82** [chainer/chainer#4120]
In GoogLeNetBN of Chainer example, the output size of of 1×1 conv in  Inc4c and inc4d is the following.

```python
self.inc4c = L.InceptionBN(None, 128, 128, 160, 128, 160, 'avg', 128)
self.inc4d = L.InceptionBN(None, 64, 128, 192, 160, 192, 'avg', 128)
```

However, in CNTK output suze of the same layers is as follows.
(https://github.com/Microsoft/CNTK/blob/5f359c769997e594b171ec3254067bda9c8cc22e/Examples/Image/Classification/GoogLeNet/BN-Inception/BrainScript/BN-Inception.bs#L30-L33)

```python
# 14 x 14 x 576
inception4c = InceptionWithAvgPoolLayer{160, 128, 160, 128, 160, 128, bnScale, bnTimeConst}(inception4b) 
# 14 x 14 x 576
inception4d = InceptionWithAvgPoolLayer{96, 128, 192, 160, 192, 128, bnScale, bnTimeConst}(inception4c) 
```

The same definitions as CNTK are used here as well.(https://github.com/lim0606/caffe-googlenet-bn/blob/d19caf526b7d8cad873ff91ba4cea602eadd58b3/deploy.prototxt#L1621)

I think that Chainer example should also define the same way as CNKT.
That is useful for training model.

**Comment by kmaehashi** [comment]
Fixed via #4121.
