### ISSUE TITLE
Troubles with moving models into devices

### ISSUE THREAD

**Issue by sergsb** [chainer/chainer#4129]
Dear Chainer community. 
I faced with some strange error, I try to do data parallel computation, as  it in the [manual](https://docs.chainer.org/en/stable/tutorial/gpu.html#data-parallel-computation-on-multiple-gpus-without-trainer)

I ran it on four `Tesla V100`:

```
models['model_0'] = MyModel()
models['model_0'].to_gpu(0)

for i in range(1,n_of_gpu):
    models["model_{}".format(i)] = copy.deepcopy(models['model_0'])
    models["model_{}".format(i)].to_gpu(i)
    print("model: {} sent to gpu: {}".format(i,i))
print(models["model_1"].embed.W.data.device)
print(models["model_2"].embed.W.data.device)
print(chainer.__version__)
print(cupy.__version__)
```
The output is:
```
model: 1 sent to gpu: 1
model: 2 sent to gpu: 2
model: 3 sent to gpu: 3
<CUDA Device 0>
<CUDA Device 0>
<CUDA Device 0>
3.2.0
2.2.0

```
So, models don't move into devices `1`  `2` and `3`. What's wrong?

**Comment by sergsb** [comment]
Oh, I found that if I move a line `models['model_0'].to_gpu(0)` below the cycle, it works!
But it looks like `models["model_{}".format(i)].to_gpu(i)` can't work if model is already moved from cpu to gpu, why?

**Comment by kmaehashi** [comment]
> Oh, I just found that if I move a line models['model_0'].to_gpu(0) below the cycle, it works!
> But it looks like models["model_{}".format(i)].to_gpu(i) can't work if model is already moved from cpu to gpu, why?

Sorry for not responding long time.
Currently `Link` (and classes like `Chain` that are inherited from `Link`) ignores `to_gpu` call if the Link is already on GPU.
We're currently trying to address this issue by changing `to_gpu` to perform GPU-to-GPU transfer in Chainer v5 (#4139).

**Comment by kmaehashi** [comment]
You can now use `link.to_device(chainer.backends.cuda.Device(0))` instead of `link.to_gpu(0)` to force transfer between GPU devices.
