### ISSUE TITLE
When and how one can set a random seed for Chainer

### ISSUE THREAD

**Issue by muupan** [chainer/chainer#4134]
I cannot find any guarantee on how to set a random seed to make Chainer deterministic. I want Chainer to clarify when and how it is deterministic.

`numpy.random.seed` and `cupy.random.seed` may work, but there seems no guarantee that Chainer has no other random sources, and I can find some exceptions: cudnn, atomicAdd (https://groups.google.com/forum/#!topic/chainer-jp/JN9H9aF4TA8), https://github.com/chainer/chainer/blob/master/chainer/datasets/sub_dataset.py, https://github.com/chainer/chainer/blob/master/chainer/functions/connection/n_step_rnn.py.

**Comment by kmaehashi** [comment]
We discussed offline:
* We need to document how to make Chainer computation deterministic.
* We need system to show warnings for non-deterministic computations, e.g.,
    * introduce decorator (like `@chainer.non_deterministic`) to annotate known non-deterministic functions (e.g., using `atomicAdd`)
    * introduce configuration option (like `chainer.config.deterministic`)
    * if the configuration is True and the function with the annotation is invoked, raise warning.

**Comment by Crissman** [comment]
@muupan I've made a PR to handle the atomicAdds. I took a look at the two blobs you linked above, and both of them seem not to have atomicAdds, but rather `random` functions. Those functions allow setting the `seed` and already seem fairly well labelled. Do you want to add the `@non_deterministic` decorator to those random functions as well?

**Comment by Crissman** [comment]
After discussion, we've decided that the PRs done covers the issue of flagging code which is non-deterministic, and cannot be given a seed. Closing this issue.
