### ISSUE TITLE
AttributeError: 'module' object has no attribute 'StandardUpdater'

### ISSUE THREAD

**Issue by sunhuaiqiang** [chainer/chainer#4142]
I run mnist example through docker, but it returns no attribute error "AttributeError: 'module' object has no attribute 'StandardUpdater'"

**Comment by kmaehashi** [comment]
Thank you for using Chainer.
This is due to the refactoring (#3037) which will be introduced in v4.0.0b3.
I think you are using example code of master branch (which is going to be released as v4.0.0b3) against `chainer/chainer:latest` Docker image (currently v4.0.0b2).
Could you please try the example code from `v4.0.0b2` tag? https://github.com/chainer/chainer/tree/v4.0.0b2/examples

**Comment by pyotr777** [comment]
I am getting the same error with Chainer 3.2.0.

```
Traceback (most recent call last):
  File "train_cifar.py", line 118, in <module>
    main()
  File "train_cifar.py", line 76, in main
    updater = training.updaters.StandardUpdater(
AttributeError: 'module' object has no attribute 'StandardUpdater'
```

**Comment by kmaehashi** [comment]
@pyotr777 Could you please try example code from v3 branch? https://github.com/chainer/chainer/tree/v3
I think you are trying examples in master branch (which is for Chainer v4).
Chainer v3 examples will work on Chainer v4, but the reverse is not true.

**Comment by pyotr777** [comment]
I clone chainer with `git clone https://github.com/chainer/chainer`
Then if I run `python train_cifar.py -d cifar100` I get the above error.

But if I checkout v4 with `git checkout v4.0.0b2` than `chainer/examples/cifar$ python train_cifar.py -d cifar100` works.

It is possible that you have v4 examples in v3 commit in git repository.

**Comment by kmaehashi** [comment]
> I clone chainer with git clone https://github.com/chainer/chainer
> Then if I run python train_cifar.py -d cifar100 I get the above error.

The master branch (the default branch after git clone) is for v4 development.
Please use the same git tag as the same version as you have installed; in this case use `git checkout v3.2.0` and try running the example.
