### ISSUE TITLE
Test that optimizer hooks are called in registration order.

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#4175]
The document of `Optimizer` ([here](https://github.com/chainer/chainer/blob/master/chainer/optimizer.py#L350)) and `UpdateRule`([here](https://github.com/chainer/chainer/blob/master/chainer/optimizer.py#L103)) says that hooks registered to these modules are called in registration order. But although we know Chainer work as the document says if we look at code, this behavior is not tested.

**Comment by kmaehashi** [comment]
bump
