### ISSUE TITLE
Make functions taking int32 variables also accept int64 variables

### ISSUE THREAD

**Issue by beam2d** [chainer/chainer#4182]
Some functions (e.g. `embed_id`, `softmax_cross_entropy`, `accuracy`) accept `int32` variables as one of the inputs, while they do not allow that argument to be `int64` variables. It may make a subtle bug occurring on Linux/macOS but not on Windows.

Consider that a Python list of Python int is converted to ndarray by `numpy.array` or `cupy.array`. The resulting array is of `int64` on Linux/macOS while `int32` on Windows. If the array is directly passed to these functions, it will pass the type check on Windows while not on Linux/macOS. I think this is problematic because it's very difficult for Windows users to find this "bug". Even if once the user finds that the code does not run on Linux/macOS, it is very hard to find the cause by non-expert of NumPy because it requires the knowledge about how the Python int value is mapped to numpy dtype.

I think this problem should be fixed by modifying the built-in FunctionNodes to accept `int64` inputs as well.

**Comment by kmaehashi** [comment]
Let's list up functions that need to be fixed.
Maybe some can be refactored to use FunctionNode constructor arguments instead of forward inputs.
