### ISSUE TITLE
_transfer_resnet101 (and 152) does not transfer the bias for conv1, while _transfer_resnet50 does

### ISSUE THREAD

**Issue by jonaswgit** [chainer/chainer#4216]
Hi all,

I've noticed that the function _transfer_resnet50() in chainer.links.model.vision.resnet.ResNetLayers does transfer both, weights and bias for the layer conv1 (line 642).
However, the functions _transfer_resnet101() and _transfer_resnet152() in the same file, which look exactly the same on the first glance, transfer only the weights, but not the bias.
I am wondering if this is on purpose, and if yes, why?

**Comment by kmaehashi** [comment]
For later reference: bias is not used in `conv` of ResNet101/152.
https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-101-deploy.prototxt
https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-152-deploy.prototxt
