### ISSUE TITLE
updater not updaters

### ISSUE THREAD

**Issue by SH-Choi** [chainer/chainer#4242]
https://github.com/chainer/chainer/blob/76bc876e1e2c782ed79dd15a8b15c29e6f668706/examples/word2vec/train_word2vec.py#L245

**Comment by kmaehashi** [comment]
Could you please try example code from v3 branch? https://github.com/chainer/chainer/tree/v3
I think you are trying examples in master branch (which is for Chainer v4).
Chainer v3 examples will work on Chainer v4, but the reverse is not true.

**Comment by SH-Choi** [comment]
Oh, I didn't know that. I misunderstood. :D
Cheers mate.
