### ISSUE TITLE
Improve Link interface

### ISSUE THREAD

**Issue by beam2d** [chainer/chainer#4250]
I'm thinking about improving the interface and class organization of Link as follows.

1. Unify Link and Chain. Link will have the almost same interface as Chain (instead of `__init__`: init will accept both parameters, tuple of shape/dtype of parameters, and links). Child/parameter initializations via `__init__`, `add_link`, and `add_param` will be de-deprecated (they will be served for the official support of container-style usage of link, together with the next bullet point).
2. Allow a list/tuple/dict of parameters/links to be registered to Link. Users can then use these standard containers to represent a set of parameters/links. ChainList will be left for backward compatibility.
3. Introduce a way to skip the hierarchy when wrapping a link/parameter by another link. Typical use case will be to use `L.Classifier` without introducing `predictor/` to the link paths.

1 and 2 are relevant to #4106, while 3 is relevant to #2575. These changes will improve the simplicity and flexibility of Link interface, which is made more Pythonic.

I think these changes can be made without breaking most of the compatibility. Unification part of 1 has already been done at my local branch: https://github.com/beam2d/chainer/tree/unify-link-chain. If this direction is acceptable, I will make a PR for it and continue working on other parts.

**Comment by toslunar** [comment]
One difference between `Link` and `Chain` is 
```
>>> l = chainer.Link()
>>> with l.init_scope():
...  l.a = chainer.Link()
...  l.a = chainer.Link()
...
>>> l = chainer.Chain()
>>> with l.init_scope():
...  l.a = chainer.Link()
...  l.a = chainer.Link()
...
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/tos/GitHub/chainer/chainer/link.py", line 802, in __setattr__
    'cannot register a new link %s: attribute exists' % name)
AttributeError: cannot register a new link a: attribute exists
```
