### ISSUE TITLE
Whether Chainer supports Python version later than 3.5.0

### ISSUE THREAD

**Issue by massongit** [chainer/chainer#4304]
Which indicates this code whether Chainer doesn't support Python 3.5.0 only, or it doesn't support Python 3.5.0 or later?
https://github.com/chainer/chainer/blob/62c800e610ef37bffdcd32334d24a120a0641b8c/setup.py#L11-L18

**Comment by kmaehashi** [comment]
We support Python v3.5.1 or later.
See https://docs.chainer.org/en/stable/install.html for details.

**Comment by massongit** [comment]
@kmaehashi Thank you for your information!
