### ISSUE TITLE
Difficult to understand the Skip-gram in word2vec example

### ISSUE THREAD

**Issue by koki0702** [chainer/chainer#4308]
The code of Skip-gram model in the word2vec example is a little bit difficult to understand.

One of the reason is that Skip-gram in the code predicts a center word from a context word.
 (Not a context from a center).

```
class SkipGram(chainer.Chain):
  ....
    def __call__(self, x, contexts):
        e = self.embed(contexts)
        batch_size, n_context, n_units = e.shape
        x = F.broadcast_to(x[:, None], (batch_size, n_context))
        e = F.reshape(e, (batch_size * n_context, n_units))
        x = F.reshape(x, (batch_size * n_context,))
        loss = self.loss_func(e, x)
        reporter.report({'loss': loss}, self)
        return loss
```

I know in Skip-gram model,  predicting the center word from a context word is the same as predicting a context word from the center word.
But I think it's not obvious (especially for beginners) the "center-context reversing". 

I think it's better to implement naturally (predicting a context from a center way).
(Or at least add some comments for the "center-context reversing"? )

Is there any reason for using "center-context reversing" style?
Implement efficiency?

**Comment by unnonouno** [comment]
I just obeyed the original implementation. It is OK to adopt the natural way.

**Comment by beam2d** [comment]
@koki0702 Do you have time to work on it? I think it's ok to modify it to follow the natural formulation.
