### ISSUE TITLE
More test conditions in convolution functions

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#4332]
Currently convolution tests covers only limited subset of argument specification.
For example, in `F.convolution_2d` test, `stride` argument is fixed to `2`.
We should improve it to cover more conditions.

https://github.com/chainer/chainer/pull/4284#issuecomment-365536894 
is one case where this problem comes to the surface.
(and saved by doctest of a sample code)

**Comment by kmaehashi** [comment]
See also: #5278
