### ISSUE TITLE
split_axis in backward of concat when 0-size array exists at the tail

### ISSUE THREAD

**Issue by soskek** [chainer/chainer#4333]
For example, `functions.concat`ing variables with shape `(2, 5)` and `(0, 5)` over axis=0, backward causes an error even though its forward path did not case any error. It is due to `functions.split_axis`, which is used in the backward and cannot accept indices from the shapes of such inputs.
https://github.com/chainer/chainer/blob/d633f11f5a40675edb9625384a7605f19d258a75/chainer/functions/array/concat.py#L50-L54

This is a reproduction code.

```
import chainer
from chainer import functions as F
import numpy as np

x = chainer.Variable(np.random.rand(2, 5))
empty = chainer.Variable(np.random.rand(0, 5))
print(x.shape)
print(empty.shape)

F.sum(F.concat([x, empty], axis=0))
# forward only passes

F.sum(F.concat([x, empty], axis=0)).backward()
# backward causes an error
```

error
```
  File "/home/usr/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/chainer/functions/array/split_axis.py", line 37, in check_type_forward
    type_check.expect(in_types[0].shape[self.axis] > max_index)
  File "/home/usr/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/chainer/utils/type_check.py", line 524, in expect
    expr.expect()
  File "/home/usr/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/chainer/utils/type_check.py", line 482, in expect
    '{0} {1} {2}'.format(left, self.inv, right))
chainer.utils.type_check.InvalidType:
Invalid operation is performed in: SplitAxis (Forward)

Expect: in_types[0].shape[0] > max_index
Actual: 2 <= 2
```

For split_axis, you can see such an error directly with the code below
```
x = chainer.Variable(np.random.rand(2, 5))
F.split_axis(x, [1, 2], axis=0)
```

**Comment by soskek** [comment]
If forward works, backward should work too. For making consistency, we have two options.

1. Add an assertion for such 0-size arrays in `check_type_forward` of `functions.concat`
2. Relax the assertion in `check_type_forward` of `functions.split_axis`

I like the 2nd idea that the existing assertion is relaxed. We can change it as follows:
```
                # type_check.expect(in_types[0].shape[self.axis] > max_index)
                type_check.expect(in_types[0].shape[self.axis] >= max_index)
```
Even with this relaxed assertion, the function works well for several cases in my environments. And, this relaxed behavior is consistent to `numpy.split`.

**Comment by soskek** [comment]
I found that this issue is being fixed by https://github.com/chainer/chainer/pull/4153

**Comment by niboshi** [comment]
Let's keep it open until it's merged.
Thank you for reporting, by the way!

**Comment by okuta** [comment]
This bug was fixed.
