### ISSUE TITLE
Sparse matmul

### ISSUE THREAD

**Issue by anaruse** [chainer/chainer#4377]
I submitted a PR to Chainer-chemistry (https://github.com/pfnet-research/chainer-chemistry/pull/90) on sparse matmul for graph convolution. And now I'm considering how to generalize it for Chainer, because the implementation of sparse matmul in the PR above only supports a use case of "dense C = sparse A * dense B" and it is not general purpose. In addition, computation of gradient of sparse matrix is not supported.

Now, I think following use cases and corresponding APIs are necessary.

1. dense C = sparse A * dense B: `sparse_matmul_sp_dn(a_data, a_row, a_col, a_shape, b)`
2. dense C = dense A * sparse B: `sparse_matmul_dn_sp(a, b_data, b_row, b_col, b_shape)`
3. sparse C = dense A * dense B: `sparse_matmul_dn_dn(a, b, c_row, c_col, c_shape)`

Regarding sparse matrix format, I think that COO format with kind of SoA layout in which data array, row index array and colum index array are kept separately as `xp.ndarray` or `chainer.Variable` is practical choice. I considered a use of `scipy.sparse.coo_matrix`, but I think it is not available here because `chainer.Variable` accepts only `xp.ndarray` and does not accept arbitrary class (including `scipy.sparse.coo_matrix`) as its data. I also considered a use of numpy's structured array but seems it is not supported by cupy.

Regarding use cases, the case 1. and 2. are interchangeable by transpose, but I think it is better to provide two APIs for ease of use. You probably wonder why the case 3. is necessary. This is mainly for computation of gradient of sparse matrix. I'm not sure this should be exposed to users, so a private function might be sufficient for this.

What would you think on this? Any feedback would be appreciated.

**Comment by anaruse** [comment]
Or is it better that it exposes one function `sparse_matmul` for three use cases and let users make sparse matrix object before calling it?

1. dense C = sparse A * dense B:

       sp_a = mk_sparse_matrix(a_data, a_row, a_col, a_shape)
       c = sparse_matmul(sp_a, b)

2. dense C = dense A * sparse B:

       sp_b = mk_sparse_matrix(b_data, b_row, b_col, b_shape)
       c = sparse_matmul(a, sp_b)

3. sparse C = dense A * dense B:

       sp_c = mk_sparse_matrix(None, c_row, c_col, c_shape)
       sp_c = sparse_matmul(a, b, sp_c)

**Comment by kmaehashi** [comment]
Implemented via #4397.
