### ISSUE TITLE
cuDNN not recognized, even if cupy was compiled with it

### ISSUE THREAD

**Issue by DavidNemeskey** [chainer/chainer#4394]
I installed both cupy and chainer from source. When I move something to the GPU, chainer complains that cuDNN is not available (and it is also quite slow). However, the cupy installation log shows that it found the cuDNN version below. Pytorch and TensorFlow both found it, as well.

* Conditions
  - Chainer version: 4.0.0b4
  - CuPy version: 4.0.0b4
  - OS/Platform: Linux _ 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
  - CUDA/cuDNN version: 8.0, 6.0.21

[chainer_install.txt](https://github.com/chainer/chainer/files/1748525/chainer_install.txt)
[cupy_install.txt](https://github.com/chainer/chainer/files/1748526/cupy_install.txt)

**Comment by kmaehashi** [comment]
I guess CuPy you installed is not used by Chainer for some reason.

* Could you please try uninstalling CuPy *multiple times* with `pip uninstall cupy` (until it says `not installed`) then reinstalling CuPy with `pip install cupy --no-cache-dir -vvvv`? Depending on how CuPy has been installed in the past, multiple CuPy may be installed.
* Alternatively you can use [wheels](https://docs-cupy.chainer.org/en/latest/install.html#install-cupy-using-wheel).

**Comment by kmaehashi** [comment]
```
import cupy.cudnn
```

If the above import succeeds, CuPy is correctly built with cuDNN support.

**Comment by DavidNemeskey** [comment]
Thanks for the wheels, those actually seem to work, at least Chainer doesn't complain. Still, it would be great if I could do it by compiling CuPy myself.

Since Chainer has nothing to do with this issue, I opened a [new one in CuPy](https://github.com/cupy/cupy/issues/986).
