### ISSUE TITLE
How to inspect model behavior during training?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#4400]
I used chainer to complete a paper, but My paper is rejected by the CVPR. Please Help me.
One of the reviewers writes:

The main downside of the paper is that the lack of qualitative results. While the steps taken in defining the model sound reasonable and address the 'unsolved' challenges in object detection, **it would be more interesting to see the model's behaviour during learning.** As is, the authors show that the results are better without providing enough insights into 'why'. There is a number of 'deep' papers; what is needed is a clear reasoning what this method brings so that it can be useful.

How to see the model's behaviour? Do I need some neural network visualize technique? How about https://github.com/PaddlePaddle/VisualDL or https://github.com/chainer/chainerui

What is your suggestion about how to use chainer to achieve that goal?

I have submit my question to https://stackoverflow.com/questions/48944286/how-to-inspect-model-behaviour-during-training-when-using-in-chainer

**Comment by kmaehashi** [comment]
Thanks for using Chainer.
As we use GitHub issues to handle feature requests or software issues rather than support requests, I'm closing this issue.
Further discussion should be made on SO.
