### ISSUE TITLE
NStepLSTM return final output ?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#4427]
If I want to **only use last time step**  to calculate loss, because NStepLSTM return 3 variable(final hidden states, final cell states, and the output sequences ) , should I use the the last one or the first one? 
I also ask this question to stackoverflow page **in a comment** : https://stackoverflow.com/questions/45835493/how-to-use-nsteplstm-or-binsteplstm-in-chainer
But has no response?

**Comment by sharpstill** [comment]
2. Does input of NStepLSTM that list of variable: between each variable **inside this list** need to have temporal correlation???

**Comment by sharpstill** [comment]
I ask above question a long time, but there have no response.

**Comment by aonotas** [comment]
Hi @sharpstill 

If you want to use hidden vector at last time step `hy` in following example code.
```
import numpy as np
from chainer import Variable
import chainer.functions as F
import chainer.links as L

# Input data
x_list = [[0, 1, 2, 3], [4, 5, 6], [7, 8]] # varibale length (word ids)
x_list = [np.array(x, dtype=np.int32) for x in x_list] # convert to numpy data

# word embedding
n_vocab = 500
emb_dim = 100
word_embed=L.EmbedID(n_vocab, emb_dim, ignore_label=-1)

# input data
xs_f = []
for i, x in enumerate(x_list):
    x = word_embed(Variable(x)) # Word IndexからWord Embeddingに変換
    x = F.dropout(x, ratio=use_dropout) 
    xs_f.append(x)

use_dropout = 0.25
in_size = 100
hidden_size = 200
n_layers = 1
lstm=L.NStepLSTM(n_layers=n_layers, in_size=in_size, out_size=hidden_size, dropout=use_dropout)
hy, cy, ys =lstm(hx=None, cx=None, xs=xs)

print(hy.shape)
# (1, 3, 200)
```

**Comment by aonotas** [comment]
What do you mean `temporal correlation`?

**Comment by sharpstill** [comment]
@aonotas I mean input of NStepLSTM that list of variable: between each variable in this list.
For example, the first variable in this list is a sentence comes from first article.
the second variable in this list is another sentence comes from second article?
Or we must use the second sentence that is closely after first sentence as a member of second variable in list.?

**Comment by sharpstill** [comment]
If I am doing video classification , because each frame have individual label, do we need use output from all time step of LSTM output, can the label is coming from all video frame's ground-truth label.
Or can we just use the last time-step label but the LSTM output is come from all time-step to calculate loss?

**Comment by sharpstill** [comment]
@aonotas I mean , because NStepLSTM return 3 variable, if I only want last time-step to calculate loss, which variable of returned tuple should I use to calculate loss?

**Comment by aonotas** [comment]
@sharpstill 
Each variable in input list `xs_f` does not have to be `temporal correlation` because each input data in mini-batch is independent.

> I mean , because NStepLSTM return 3 variable, if I only want last time-step to calculate loss, which variable of returned tuple should I use to calculate loss?
Please use `hy` (first returned varialbe) in 
```
hy, cy, ys = lstm(hx=None, cx=None, xs=xs)
```

**Comment by aonotas** [comment]
> If I am doing video classification , because each frame have individual label, do we need use output from all time step of LSTM output, can the label is coming from all video frame's ground-truth label.
Or can we just use the last time-step label but the LSTM output is come from all time-step to calculate loss?

If you want to use all timestep vectors, please use `ys `.
If you want to use last timestep vectors, please use `hy `.

**Comment by aonotas** [comment]
> So we can shuffle between different batch as different input feed to NStepLSTM?
Yes. you can shuffle input data in minibatch or each iteration.

> NStepLSTM does not maintain inner state across mini-batch?
Well, of course, NStepLSTM keep inner LSTM states in minibatch, 
but `IntputData_1` have no effect on `InputData_2` (other data in minibatch).

If you have three input seqeuce and you want three output, 
- `InputData_1`    => NStepLSTM   => `OutputData_1`
- `InputData_2`    => NStepLSTM   => `OutputData_2`
- `InputData_3`    => NStepLSTM   => `OutputData_3`
You can shuffle input data.
- [`InputData_1`, `InputData_2`, `InputData_3`]  => NStepLSTM =>  [`OutputData_1`, `OutputData_2`, `OutputData_3`] 
- [`InputData_2`, `InputData_1`, `InputData_3`]  => NStepLSTM =>  [`OutputData_2`, `OutputData_1`, `OutputData_3`]

**Comment by sharpstill** [comment]
my another question is about here https://github.com/chainer/chainer/issues/4431

**Comment by aonotas** [comment]
OK. I'm not familiar with `Convolution2D `, please wait for the response from other developers.

**Comment by sharpstill** [comment]
@aonotas Very thanks for your generous help, do you have mail? so that I can ask some LSTM question about chainer easier?

**Comment by aonotas** [comment]
OK. 
`nanigashi 03 [at] gmail . com`
(please remove white space, and replace [at] to @)
