### ISSUE TITLE
does L.Convolution2D pad=1 the same as tensorflow padding = SAME?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#4431]
I am reproduce Mobilenet in chainer, I use source code from https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.py to reproduce it.
tensorflow has two types of padding in conv2d, `SAME `and `VALID`.
But chainer  `L.Convolution2D` pad=1 or 0 or some other int value.
How to set this pad when I translate code from mobilenet?

**Comment by jinjiren** [comment]
`VALID` is no padding, I remember.
To achieve `SAME` padding behavior, you need to calculate the padding based on the conv kernel size and stride value. For example, if you use kernel_size=3, stride=1, then padding=1 will behave like `SAME` padding in TensorFlow. Refer to [Conv Arithmetic](https://github.com/vdumoulin/conv_arithmetic) is a good choice.

**Comment by crcrpar** [comment]
FYI: https://www.tensorflow.org/api_guides/python/nn#convolution
SAME do
```
out_height = ceil(float(in_height) / float(strides[1]))
out_width  = ceil(float(in_width) / float(strides[2]))
```

**Comment by kmaehashi** [comment]
Feel free to reopen if the issue still remains. Thanks!
