### ISSUE TITLE
How to skip some dataset item when loading data error happens?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#4460]
Because my data is not clean, some error data item exists in database.
`def get_example` `raise IndexError` will cause the whole program failed.
How to skip across and ignore some bad data?

**Comment by jinjiren** [comment]
Pruning the data first is better, IMO. Otherwise you still have to do it in chainer...

**Comment by kmaehashi** [comment]
After the offline discussion in the team, I made an issue for this case. #5048
