### ISSUE TITLE
There is an error for FunctionSet. How can I solve it?

### ISSUE THREAD

**Issue by miraclewxl** [chainer/chainer#4469]
Traceback (most recent call last):
  File "/media/wxl/00063DAF000FECC3/chainer-example-overfeat-classify-master/classify.py", line 5, in <module>
    from chainer import cuda, Variable, FunctionSet, optimizers
ImportError: cannot import name 'FunctionSet'

**Comment by delta2323** [comment]
Hi, `FunctionSet` is a feature in v1. So I guess the code assumes an older version Chainer.

**Comment by kmaehashi** [comment]
Please refer to the upgrade guide for instructions on rewriting your code to work it on the latest Chainer.
https://docs.chainer.org/en/latest/upgrade.html

**Comment by miraclewxl** [comment]
Thanks for the answers
