### ISSUE TITLE
Why doesn't exist F.mul function(element-wise multiplication)?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#4480]
I mean, `F.mul` is element-wise multiplication.
My network produce two scores, I want to multiply the two scores to produce final score
`score = F.mul(s1, s2)
`I did not find `F.mul` or `F.multiply`
So, I am writing the following code:
`score = s1 * s2`

Can this work and back propagation?

**Comment by kmaehashi** [comment]
> `score = s1 * s2`

Yes, this operation supports backprop. `__mul__` operator is defined for Variables. https://github.com/chainer/chainer/blob/master/chainer/functions/math/basic_math.py#L900
