### ISSUE TITLE
Kill example when incompatible version of Chainer is used

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#4481]
When a user uses old version of Chainer for newer version of an example script, it raises an exception when compatibility is not kept. We need to show an error message and to shut down gracefully.

**Comment by kmaehashi** [comment]
How about introducing version assertion functions like `chainer.require_version('4.0.0')`?
It should also help users.

**Comment by beam2d** [comment]
We are recently observing this type of concerns after introducing ChainerX support to examples. I would like this issue to be resolved.
