### ISSUE TITLE
Add document for performance best practices

### ISSUE THREAD

**Issue by kmaehashi** [chainer/chainer#4491]
It is better to have a official guidance to how to maximize the performance.
I'm thinking about covering these topics, but please feel free to comment if you have other ideas.

* Use the latest Chainer
* Use CuPy
* Use iDeep on CPU
* Install cuDNN
* Set cuDNN workspace size
* Enable auto tuning
* Next Steps (brief introduction of ChainerMN)

**Comment by niboshi** [comment]
* Disable `assert`

**Comment by beam2d** [comment]
- Topics around datasets (e.g. `MultithreadIterator`, `MultiprocessIterator`)
- Topics around updaters (`MultiprocessParallelUpdater` and ChainerMN)
- CUDA profiling (nvvp, how to annotate)

**Comment by kmaehashi** [comment]
* Disable `CHAINER_TYPE_CHECK`
* Use NumPy with MKL support

**Comment by kmaehashi** [comment]
@niboshi

> Disable assert

Do you mean running code via `python -O`? (I didn't know this option disables assertions...!)

**Comment by niboshi** [comment]
@kmaehashi 
Yes. But I'm not sure it's worth mentioning...

If it becomes a common practice, we will be able to include as many `assert`s as we want. I don't think that would happen, though.

**Comment by kmaehashi** [comment]
Thanks for clarification.
I skipped to include it in #4809, as performance difference seems relatively smaller compared to other topics.

**Comment by niboshi** [comment]
OK.
