### ISSUE TITLE
Support for discriminative loss function

### ISSUE THREAD

**Issue by dBeker** [chainer/chainer#4513]
As suggested in contribution guide, I open an issue for a new feature to be implemented and to discuss the design.  
  
I have implemented "discriminative loss function" described in https://arxiv.org/pdf/1708.02551.pdf. This loss can improve the segmentation quality along with some post-processing clustering steps.   

I would like to create a PR following the design discussion.

**Comment by delta2323** [comment]
bump

**Comment by kmaehashi** [comment]
Implemented in #5313
