### ISSUE TITLE
Add multi-GPU tests for Function

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#454]
Related to #418

**Comment by delta2323** [comment]
Functionality to be tested
* Send parameters of FunctionSet to GPU
* Raise an error when `Variable`s in the different devices are passed to `Function`

**Comment by beam2d** [comment]
We are still missing the tests for the second case.

**Comment by kmaehashi** [comment]
> Raise an error when Variables in the different devices are passed to Function

As some users may want to use functions in such way, we decided not to forbid such case.
See also: #4459
