### ISSUE TITLE
Add extra support for different learning rate policy.

### ISSUE THREAD

**Issue by JirenJin** [chainer/chainer#4546]
To reproduce results of other papers, usually we would like to follow exactly the same implementation details reported in their paper (or code, if available). However, the support for the learning rate policy in Chainer is not enough, compared with other frameworks, e.g., Caffe has many learning rate policies:
```
//    - fixed: always return base_lr.  
//    - step: return base_lr * gamma ^ (floor(iter / step))  
//    - exp: return base_lr * gamma ^ iter  
//    - inv: return base_lr * (1 + gamma * iter) ^ (- power)  
//    - multistep: similar to step but it allows non uniform steps defined by  
//      stepvalue  
//    - poly: the effective learning rate follows a polynomial decay, to be  
//      zero by the max_iter. return base_lr (1 - iter/max_iter) ^ (power)  
//    - sigmoid: the effective learning rate follows a sigmod decay  
//      return base_lr ( 1/(1 + exp(-gamma * (iter - stepsize))))  
```

Since Chainer now only supports `ExponentialShift` and `LinearShift`, it is not so convenient to tune the learning rate policy (without writing custom `Trainer` hooks or updaters). IMO, providing common learning rate policy is deserved to be included in the official implementation. 

I would like to submit PRs for implementing some of the above policies if possible.

**Comment by kmaehashi** [comment]
Thank you for the feature request!
We welcome PRs to extend learning rate policies.

**Comment by kmaehashi** [comment]
Refs #4667

**Comment by kmaehashi** [comment]
Refs #4894

**Comment by kmaehashi** [comment]
- [X] fixed
- [ ] step (#4894)
- [X] exp
- [X] inv (#4565)
- [ ] multistep
- [X] poly (#4693)
- [ ] sigmoid

**Comment by niboshi** [comment]
Now that we have several `*Shift` extensions, I think it's a good time to refactor them.
