### ISSUE TITLE
About the unordered behavior of `params`, `namedparams` method.

### ISSUE THREAD

**Issue by jinjiren** [chainer/chainer#4547]
For `Link` class, the implementation of `params` and `namedparams` methods depends on the `self._params` attribute. Similarly, For `Chain` class, the implementation of `params` and `namedparams` also depends on the `self._children` attribute. The problem is that both `_params` and `_children` is type `set`, which causes the unordered behavior when calling `params` or `namedparams` methods.

This problem can be inconvenient when we want to use an exact copy (deepcopy) of a model, expecially when we expect the `params` or `namedparams` are well aligned between the original model and the duplicate version (using copy.deepcopy).

Suppose we have a model composed of three convolutional layers: conv1, conv2, conv3.
```
for name, param in original_model.namedparams():
    print(name)
```
Above code gives us the results:
```
/conv1/W
/conv1/b
/conv2/W
/conv2/b
/conv3/W
/conv3/b
```

However, if we use `copied_model = copy.deepcopy(original_model)`, the results can happen to be:
```
/conv1/W
/conv1/b
/conv3/W
/conv3/b
/conv2/W
/conv2/b
```

For this problem, first, I'm wondering why a `set` is used for storing `_params` and `_children` attribute (maybe for avoiding the duplicate params/child links?). Second, is it possible to change the current code to make the `_params` and `_children` have a definite order? Finally, even if such change is not proper, I think it is necessary to add some note in the documentation to warn users about this kind of behavior.

At least for myself, I was expecting the `params` and `namedparams` to return a fixed order of parameters before reading details in the source code...

**Comment by kmaehashi** [comment]
`self._params` etc. are defined as `set` just to make implementation simple  (https://github.com/chainer/chainer/pull/2657). As the performance does not matter here, I think it can be replaced it with some ordered data structure.

I want to understand the context of this feature request. Could you tell me why you need params to be ordered in your usecase? (e.g. `zip`-ing and comparing params from two models?)

**Comment by jinjiren** [comment]
Hi @kmaehashi, thanks for the reply. 

I use it to add constraints between the parameters of two models (I use `zip` here).

**Comment by toslunar** [comment]
ChainerRL iterates over zipped namedvalues by https://github.com/chainer/chainerrl/blob/c5483009ccf5875e02d2c73592c975ad97680274/chainerrl/misc/copy_param.py#L12-L30

`zip(sorted(link1.namedparams()), sorted(link2.namedparams()))` also works fine if you know the sets of the names are equal.

**Comment by kmaehashi** [comment]
After the discussion in the team, we decided to fix `namedparams` and `param` in sorted (by name) order.
