### ISSUE TITLE
No standardized approach to serialize non-learnable parameter

### ISSUE THREAD

**Issue by fiarabbit** [chainer/chainer#4548]
There is no standardized approach to serialize non-learnable parameter such as a dilation rate of a convolution.

What is official way to include a non-learnable parameter for serialization? "add_persistent()"? or write custom serialize method? 

An official documentation would help this.

**Comment by kmaehashi** [comment]
Thank you for the feedback.
You can use `add_persistent()` for that purpose.
Please see https://docs.chainer.org/en/latest/guides/serializers.html for details.

**Comment by fiarabbit** [comment]
@kmaehashi 
Thanks for the comment. I understood the standardized way for the serialization. However, I wonder why chainer included only `Link.add_param()` to `with self.init_scope()` but did not replace `Link.add_persistent()` to such context managing function?

**Comment by kmaehashi** [comment]
IMO registrations of serializable object should be explicit. If `init_scope()` automatically registers everything `setattr`-ed as persistent, it is will become hard to track down what will be serialized at a glance, especially when other instance method is called from inside `init_scope()` block.

**Comment by fiarabbit** [comment]
I haven't understood your point yet. Do you mean "non-learnable parameters should not be serialized"?

**Comment by kmaehashi** [comment]
What I meant is: I think it is rather unsafe to assume that every user wants to serialize every attributes set in init_scope. For example, it is common to keep constructor arguments as attributes, which should not be serialized.
On the other hand, automatically registering `Parameters` makes sense as it is obviously needed for serialization.

**Comment by fiarabbit** [comment]
Hmm, partially I agree with your opinion that users doesn't have to intend to serialize all members registered within `init_scope()` clause.
Thanks for your kind reply!
