### ISSUE TITLE
How can training with `MultiprocessParallelUpdater` be made deterministic?

### ISSUE THREAD

**Issue by tkerola** [chainer/chainer#4550]
With a single GPU, the following statements are enough to make the training deterministic:
```
np.random.seed(args.random_seed)
cupy.random.seed(args.random_seed)
random.seed(args.random_seed)
chainer.config.cudnn_deterministic = True
```

I tried to add a `random_seed` option to make `MultiprocessParallelUpdater` deterministic in the same way, but it doesn't work:
https://github.com/tkerola/chainer/blob/mpu_seed/chainer/training/updaters/multiprocess_parallel_updater.py#L51-L56
(Unlike in the single GPU case, `cupy.random.seed()` cannot be called before each `_Worker` is run, since the CUDA context cannot be initialized before any call to `fork()`)

Do you have any suggestion on how to make deterministic training with `MultiprocessParallelUpdater` work properly?

**Comment by delta2323** [comment]
If you use Chainer functions that use `atomicAdd` (e.g. `F.embed_id`) internally, you may not make whole behavior deterministic because an order in which thread modify values in a single memory can vary at every invocation of the function. [this post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/chainer/GAQfSR43QFo/dsBCQksPBQAJ) might also be helpful.

**Comment by tkerola** [comment]
Thanks for your response! I am not using any `atomicAdd` as far as I am aware. On a single GPU, the training becomes deterministic, but it is only when I switch to `MultiprocessParallelUpdater` that the training becomes non-deterministic.

**Comment by delta2323** [comment]
> but it is only when I switch to MultiprocessParallelUpdater that the training becomes non-deterministic.

Thank you. That is good information to narrow down the cause.

**Comment by delta2323** [comment]
I'm sorry I could not spare time to investigate this problem. I would appreciate if someone take over the investigation.

**Comment by Jonathan-LeRoux** [comment]
I'd be interested to know a solution to this issue as well.
