### ISSUE TITLE
Policy on whether to use PyTest features

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#4557]
We currently have no policy on whether to use PyTest-specific features in unit tests.
In order to avoid confusion, we want a policy.

(previous discussion: https://github.com/chainer/chainer/pull/4534#discussion_r177633250)

**Comment by kmaehashi** [comment]
My proposal (copied from https://github.com/chainer/chainer/pull/4534#discussion_r177633250):

I come up with the simple policy:

* Keep avoiding `import pytest` in our test code base (as we did in nose)
* Permit use of simple `assert`

Thoughts behind the policy above is that I want to minimize the requirements of test framework when we have to choose another framework to migrate.

* Why avoid `import pytest`?
    * Once we allow `import pytest`, we allow every feature in pytest to be used in future test code.
    * This rule is simple enough for contributors.
* Why simple `assert` can be a exception:
    * It is shorter than `self.assertEqual` and also improves readability. (= cost-effective)
    * Even with simple assert, we can say that the test code is still compatible with standard `unittest` (although without nice dump of arguments)

c.f., In NumPy, it seems that they are paying much effort to abstracting out test framework by their own and gradually moving from nose to pytest.

* https://github.com/numpy/numpy/issues/9352#issue-240027620
* https://github.com/numpy/numpy/tree/master/numpy/testing has pytest_tools and nose_tools, and `assert_raises` is defined for each framework.
  * https://github.com/numpy/numpy/blob/master/numpy/testing/pytest_tools/utils.py#L1190
  * https://github.com/numpy/numpy/blob/master/numpy/testing/nose_tools/utils.py#L1208

**Comment by kmaehashi** [comment]
The conclusion will be written into the contribution guide in #5012.
