### ISSUE TITLE
Add more tests for convolution functions

### ISSUE THREAD

**Issue by kmaehashi** [chainer/chainer#4588]
During the offline discussion we found that it's better to test convolution functions with some more variations, e.g.,
* dilated > 1
* compare convolution results with naive implementation (or hand-calculated results)
* ... (we need to first investigate what variations of tests should be added)

**Comment by niboshi** [comment]
Oh, it seems there's already an issue: #4332

**Comment by kmaehashi** [comment]
Oops I looked over it. Thanks!
