### ISSUE TITLE
Avoid hacking for coding style check

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#4610]
Now that contributors can install style-check tools with `pip install -e .[stylecheck]`, we no longer have to use `hacking` in order to fix the tool versions. We can have finer control over tool versions than `hacking`.

One problem of `hacking` is that it fixes to rather old versions, which means we're unable to benefit from recent bugfixes.

Another problem is that its dependency can conflict with other tools (e.g. the case in #4606).

**Comment by jinjiren** [comment]
Yesterday I actually met some bugs when using the old version of flake8 used in hacking.

**Comment by niboshi** [comment]
(See conversation in #4674) hacking has its own style checks. It's not that simple as replacing hacking with explicit requirements.

**Comment by kmaehashi** [comment]
`hacking` has been updated to use `flake8` 2.6.x.

https://github.com/openstack-dev/hacking/compare/1.0.0...1.1.0#files_bucket (requirements.txt)

Related: #4731
