### ISSUE TITLE
AttributeError in seq2seq example

### ISSUE THREAD

**Issue by crcrpar** [chainer/chainer#4625]
* Conditions
  - Chainer version: 3.5.0
  - CuPy version: 2.5.0
  - OS/Platform: Ubuntu 16.04
  - CUDA/cuDNN version: 9.0/7.0
  - etc.
* Code to reproduce: 
`python seq2seq.py --gpu=0 giga-fren.preprocess.en giga-fren.preprocess.fr \
vocab.en vocab.fr \
--validation-source newstest2013.preprocess.en \
--validation-target newstest2013.preprocess.fr` same as examples/seq2seq/README.md
* Error messages, stack traces, or logs
As in the below picture, `AttributeError: module 'chainer.training.updaters' has no attribute 'StandardUpdater'`.
How about using `training.StandardUpdater` instead?
![screenshot from 2018-04-13 22-30-43](https://user-images.githubusercontent.com/16191443/38738339-eb3511f6-3f6c-11e8-9333-2d792477c115.png)

**Comment by kmaehashi** [comment]
The master branch (the default branch after git clone) is for the development of latest version.
If you are using Chainer v3.x, please refer to the examples in `v3` branch (https://github.com/chainer/chainer/tree/v3).
(BTW we're going to release Chainer v4 tomorrow.)

**Comment by crcrpar** [comment]
Thank you.
From the v4,  calling `Updater`s from `training.updaters` will be recommended? (I know updaters' locations were changed a bit)

**Comment by kmaehashi** [comment]
Yes, we have refactored some namespaces in v4 so that they're consistent with other namespace convention. Please refer to the Upgrade Guide for other changes in v4: https://docs.chainer.org/en/latest/upgrade.html#namespace-changes-for-updaters

**Comment by crcrpar** [comment]
Thank you very much.
New namespace seems more reasonable.
