### ISSUE TITLE
forget_bias_init is not supported in NStepLSTM

### ISSUE THREAD

**Issue by nogu-atsu** [chainer/chainer#4647]
Forget_bias_init is supported in chainer.links.LSTM, and the default value of it is 1.
However, in chainer.links.NStepLSTM, the initial value of the bias in the forget-gate is always set to 0.

The initial value of the forget-bias tends to affect the performance of the model (forget_bias_init=1 often results in better performance than 0).

Is there any possibility to support forget_bias_init for NStepLSTM?

**Comment by beam2d** [comment]
Thanks for the report (and sorry for the late response)! We should work on it. I even think we should consider changing the default forget bias of NStepLSTM for consistency with LSTM. At least, we should provide the same initialization scheme as LSTM in NStepLSTM.

**Comment by kmaehashi** [comment]
* Fix in master & backport to v4:
    * Add `lateral_init`, `upward_init` initializer options to NStepLSTM
    * Add `bias_init`, `forget_bias_init` initializer options to NStepLSTM (default = `0.0`)
    * For each layer,
        * Init `W[0-3]` with `upward_init`
        * Init `W[4-7]` with `lateral_init`
        * Init `b1` with `forget_bias_init`
        * Init `b[0-3]` (except `b1`) with `bias_init`
        * Init `b[4-7]` with `0.` to avoid doubling the effective bias for each gate
* Fix only in master: (to keep reproducibility. Need to add this topic to Upgrade Guide)
    * Change the default value of `forget_bias_init` from `0.` to `1.`
