### ISSUE TITLE
Redirect from old tutorial place to new place

### ISSUE THREAD

**Issue by gwtnb** [chainer/chainer#4650]
The old tutorial https://docs.chainer.org/en/stable/tutorial/ is not found due to #3241. The URL is linked from many websites including the result of Google search, so we must redirect to the new place. Note that we must not only redirect from https://docs.chainer.org/en/stable/tutorial/, but also redirect from any pages of old tutorials.

**Comment by kmaehashi** [comment]
Thanks. I've setup a redirect to https://docs.chainer.org/en/stable/guides/.
