### ISSUE TITLE
Does grouped convolution2D support cudnn to boost speed?

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#4661]
I am using grouped convolution2D layer ( chainer v4.0.0rc1 L.Convolution2D layer has group argument), how does it works??
CuDNN7.0 support grouped convolution
Does it use for-loop to convolve? Or use CuDNN to parallel multiple group convolution to boost speed??

**Comment by kmaehashi** [comment]
Grouped convolution of Convolution2D utilizes cuDNN v7.

**Comment by sharpstill** [comment]
@kmaehashi I notice the document https://docs.nvidia.com/deeplearning/sdk/pdf/cuDNN-Release-Notes.pdf cudnn_v7 : grouped convolution can only accelarate when the input channels and output
channels per group are 1, 2, or 4.
Is it true?? If I use input & output channel other than 1,2 or 4, Can it still accelerate speed?

**Comment by fiarabbit** [comment]
This is just a reminder for those who found this closed issue.

That is, arbitrary omission of a sentence should be avoided...
The original pdf says

> Performance improvements for grouped convolutions when input channels and output
channels per group are 1, 2, or 4 for the following algorithms:
> CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM
> CUDNN_CONVOLUTION_BWD_DATA_ALGO0
> CUDNN_CONVOLUTION_BWD_DATA_ALGO1
> CUDNN_CONVOLUTION_BWD_FILTER_ALGO_0
> CUDNN_CONVOLUTION_BWD_FILTER_ALGO_1

The algorithm is selected automatically by `cudnnGetConvolutionForwardAlgorithm()` and `cudnnGetConvolutionBackwardDataAlgorithm()`, and if there is enough memory space, CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM will not be selected.

Therefore, for the real use cases, there is no need to care about the number of groups.
