### ISSUE TITLE
Write document for deployment

### ISSUE THREAD

**Issue by kmaehashi** [chainer/chainer#4691]
Write docs that covers the following topics:

* Deploy using Chainer
    * For Trainer users (-> save model in addition to trainer snapshot)
    * For custom loop users (-> use saved model)
* Deploy using Caffe
    * Using Caffe exporter (experimental)
* Deploy using ONNX
    * Using onnx-chainer (experimental)

**Comment by Raj-08** [comment]
Any update on Docs for deployment of chainer?

**Comment by Raj-08** [comment]
https://chainer.org/general/2018/06/01/chainer-officially-supported-by-aws.html 
It says chainer is being supported by Amazon Sagemaker , where we can deploy our models. Any update on this ?

**Comment by kmaehashi** [comment]
@Raj-08 For Sagemaker deployments, you can refer to the docs provided by AWS.

* https://docs.aws.amazon.com/sagemaker/latest/dg/chainer.html
* https://github.com/aws/sagemaker-chainer-container/blob/master/README.rst
* https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/chainer/README.rst

**Comment by Raj-08** [comment]
@kmaehashi Thank you :)
