### ISSUE TITLE
coding style mixed in CNN tutorial

### ISSUE THREAD

**Issue by arisliang** [chainer/chainer#4697]
In the tutorial, https://docs.chainer.org/en/stable/examples/cnn.html, the coding style starts to lose the syntax highlight, which is quite nice, from Ways to calculate loss and below.

**Comment by kmaehashi** [comment]
Thanks for the feedback, it'll be resolved in #4714.

**Comment by kmaehashi** [comment]
We usually close issues when the corresponding PR has merged.
