### ISSUE TITLE
add_link still used in tutorial

### ISSUE THREAD

**Issue by arisliang** [chainer/chainer#4699]
I thought add_link has been deprecated, but it's still used in tutorial (https://docs.chainer.org/en/stable/examples/cnn.html, ResNet152).

**Comment by kmaehashi** [comment]
Thanks for the feedback.
`Chain.add_link` is deprecated, but [`ChainList.add_link`](https://docs.chainer.org/en/latest/reference/generated/chainer.ChainList.html) (which is used in the docs) is still an alive API.

**Comment by arisliang** [comment]
There're two add_link, I see. Thanks for the clarification.
