### ISSUE TITLE
chainer conda cupy.cuda.memory.MemoruPointer object has no attribute repeat

### ISSUE THREAD

**Issue by achetouani** [chainer/chainer#4703]
I tried to use GPU and I have the following error  when I tried to execute my program. This program already works on my laptop with CPU.
I installed it using conda.

The error is when the trainer.run is executed:

I used the xp=cuda.cupy
...
t=xp.repeat(y_data.data, 1)

conda cupy.cuda.memory.MemoruPointer object has no attribute repeat

- Chainer version 4.0.0
- CuPy version 4.0.0
- OS/Platform ubuntu 16.04
- cudnn 7.1.2

**Comment by kmaehashi** [comment]
Use `y_data` (type `cupy.ndarray`) instead of `y_data.data`.

**Comment by achetouani** [comment]
Ok Thanks.  I will try it as sion as possible. 




Envoyé depuis un mobile Samsung

-------- Message d'origine --------
De : Kenichi Maehashi <notifications@github.com> 
Date :  
A : chainer/chainer <chainer@noreply.github.com> 
Cc : achetouani <aladine.chetouani@univ-orleans.fr>,Author <author@noreply.github.com> 
Objet : Re: [chainer/chainer] chainer conda cupy.cuda.memory.MemoruPointer object has no attribute repeat (#4703) 
 
Use y_data (type cupy.ndarray) instead of y_data.data.

**Comment by kmaehashi** [comment]
Feel free to reopen the issue if you still have any trouble. Thanks!
