### ISSUE TITLE
Could you provide chainer windows package on PyPI

### ISSUE THREAD

**Issue by PaulaQin** [chainer/chainer#4704]
Hi, I am a chainer user, and I want to install chainer on my windows machine. So could you provide a windows version of chainer 4.0.0 package on PyPI?

Thanks.

**Comment by kmaehashi** [comment]
Chainer is a pure-python module, so just using `pip install chainer` should work fine on Windows.
Do you have any difficulties during installation?

**Comment by kmaehashi** [comment]
We started to provide CuPy wheel in v5.0.0b1.
