### ISSUE TITLE
Suggest to add simple code examples in functions documentation

### ISSUE THREAD

**Issue by arisliang** [chainer/chainer#4707]
Can we add simple code examples in functions documentation? To make it a bit easier to visualize the usage, and the purpose of certain function (such as https://docs.chainer.org/en/stable/reference/generated/chainer.functions.split_axis.html).

**Comment by kmaehashi** [comment]
Thanks for the suggestion!
Currently some functions have examples (e.g., https://docs.chainer.org/en/stable/reference/generated/chainer.functions.hstack.html), but some others don't. I agree with that it is better to add examples to better illustrate usages to users.
Such contributions are always welcomed.

**Comment by keisuke-umezawa** [comment]
Just FYI
We also have the list for improvement. https://github.com/chainer/chainer/issues/2182

**Comment by arisliang** [comment]
Good to see it's already on the list, and some functions already have it. Progress is on the way.

So what should I do with this opened issue? Is it better to close it since it's on #2182 as well?

**Comment by kmaehashi** [comment]
I think it's better to discuss this topic in the original issue #2182, so I'll close this. Thanks again for the feedback!

**Comment by arisliang** [comment]
Thanks, no worries.
