### ISSUE TITLE
performance improvement for data loading in seq2seq example

### ISSUE THREAD

**Issue by arisliang** [chainer/chainer#4710]
In https://docs.chainer.org/en/stable/examples/seq2seq.html, the `load_data` function takes a rather long time (around 9-10 minutes~) to load, and it takes up a lot of main memory (15 GB~ of main ram). Is it possible to improve that speed, reduce the memory usage, or ideally both?

In real world scenarios, the issue of performance and memory will often come up, so if some general approach applicable to seq2seq example may as well help real world scenarios.

It's very good that the data set of this example reveals the performance side of consideration that let us think of.

**Comment by kmaehashi** [comment]
I've updated the example to reduce memory consumption. Please see #4782.

**Comment by kmaehashi** [comment]
Fixed via #4782.
