### ISSUE TITLE
MultiprocessIterator doesn't work.

### ISSUE THREAD

**Issue by cmjdxy** [chainer/chainer#4723]
I am using _MultiprocessIterator_ from _chainer_ to train an NN. The code is [here](https://github.com/cmjdxy/practice-chainer/blob/master/train_mnist.py).

The results are:
nproc = 1,  307.65s
nproc = 4,  318.85s
nproc = 8,  302.91s
nproc = 16, 318.18s

System info:
Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-104-generic x86_64)
CPU(s): 16
Model name: Intel(R) Xeon(R) CPU E5-2695 v4 @ 2.10GHz
VGA compatible controller: Cirrus Logic GD 5446

It seems that _MultiprocessIterator_ doesn't work. Anyone has a clue? Thank you in advance.

PS: I've also pulled this issue on [stackoverflow](https://stackoverflow.com/questions/50224489/multiprocessiterator-doesnt-work).

**Comment by fiarabbit** [comment]
_MultiiprocessIterator_ just (sometimes) speeds up picking up a batch from _Dataset_ and it does not hasten ANY GPU computation.
In most cases, the computational bottleneck is forwarding/backwarding, so it is only natural that _MultiiprocessIterator_ has no effect on the total time.

**Comment by cmjdxy** [comment]
Thank you for the response, @fiarabbit ! Now I know how does _MultiprocessIterator_ works.
