### ISSUE TITLE
(De)Serializing optimizers does not work on update_rule states

### ISSUE THREAD

**Issue by kuenishi** [chainer/chainer#4749]
Found via https://github.com/chainer/chainermn/issues/225 : As ChainerMN's snapshot feature stores whole trainer state it assumes (de)serializing whole trainer store/loads including learning rates, update rule states.

* Conditions

At least Chainer 4.0.0, Linux.

* Code to reproduce

```python
import chainer
# import chainermn
import numpy as np
import os

class DynamicExampleModel(chainer.Chain):

    def __init__(self):
        super(DynamicExampleModel, self).__init__()
        with self.init_scope():
            self.a = chainer.links.Linear(1, 1)

    def __call__(self, x):
        return self.a(x)
        #return {'loss', 0.001}

def make_optimizer(lr):
    model = DynamicExampleModel()
    model.a.W.data[:] = 0
    model.a.W.grad[:] = 0
    optimizer = chainer.optimizers.MomentumSGD(lr=lr, momentum=0.9)
    optimizer.setup(model)
    return optimizer
    
def test_checkpoint_lr():

    original_lr = 0.002
    o1 = make_optimizer(original_lr)
    
    path = '/tmp'
    filename = 'test-checkpoint'
    print('saving', o1.lr)
    #chainermn.extensions.checkpoint._save(path, filename, optimizer)
    filename = os.path.join(path, filename)
    chainer.serializers.save_npz(filename, o1)

    print('loading')
    o2 = make_optimizer(0.00000001)
    #chainermn.extensions.checkpoint._load(path, filename, optimizer)
    chainer.serializers.load_npz(filename, o2, strict=False)
    assert np.testing.assert_almost_equal(o2.lr, original_lr)
```

* Error messages, stack traces, or logs

```
>       assert np.testing.assert_almost_equal(o2.lr, original_lr)
E       AssertionError: 
E       Arrays are not almost equal to 7 decimals
E        ACTUAL: 1e-08
E        DESIRED: 0.002
```

**Comment by toslunar** [comment]
https://github.com/chainer/chainer/blob/v5.0.0a1/chainer/optimizer.py#L276-L279
> Be careful that this method only saves/loads the state of the update rule.

`state` does not contain `hyperparam`.

**Comment by kuenishi** [comment]
Thank you for the comment. I understand how it works and how to fix https://github.com/chainer/chainermn/issues/225 . So the `state` is numbers that is to be used during forward/backward operation and hyperparamters are more meta-paramaters and not supposed to change during forward calculation; is my understanding correct?

**Comment by toslunar** [comment]
I heard, when I discussed #4013 offline, that there's no need to save hyperparameters since they change deterministically and they are easily recomputed as long as the source code is available.  IMHO, however, it's welcome to add the feature to save hyperparameters.

**Comment by toslunar** [comment]
The document would be improved.
