### ISSUE TITLE
Difference in the implementation of rmsprop  with Tensor Flow

### ISSUE THREAD

**Issue by MahdiKalayeh** [chainer/chainer#4754]
There is a small difference between Chainer's implementation of rmsprop and the one in Tensor Flow which I thought worth pointing out. In [TF](https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/python/training/rmsprop.py), the epsilon is inside the sqrt function while this is not the case for Chainer's [implementation](https://github.com/chainer/chainer/blob/v4.0.0/chainer/optimizers/rmsprop.py). This does not make much difference when you pick very small (compared to mean grad**2) values for epsilon but it does when epsilon is large (i.e eps=1.0) as it is used in training Inception [V3](https://arxiv.org/pdf/1512.00567.pdf) and [V4](https://arxiv.org/pdf/1602.07261v1.pdf).

**Comment by kmaehashi** [comment]
Thank you for pointing this out.

* Caffe2 (eps inside sqrt): https://github.com/pytorch/pytorch/blob/v0.4.0/caffe2/sgd/rmsprop_op_gpu.cu#L24
* PyTorch (eps outside sqrt): https://github.com/pytorch/pytorch/blob/v0.4.0/torch/optim/rmsprop.py#L93
