### ISSUE TITLE
initialW and initial_bias option has been removed from NStepLSTM and NStepBiLSTM

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#4755]
`initialW` and `initial_bias` options have been added to `NStepLSTM.__init__` and `NStepBiLSTM.__init__` in #2409, which was available at least in v3.0.0. But they have been removed unintentionally during code refactoring of #4109, merged in v4. We need to restore these options to keep backward compatibility.

This issue was reported by @MannyKayy in #1816 and #2409. Thank you!

**Comment by kmaehashi** [comment]
Oh, sorry I wasn't aware of this issue... I've removed docs for these params via #4991.

**Comment by mitmul** [comment]
@delta2323 Is it OK to implement `lateral_init` and `upward_init` instead of `initialW` because there are multiple linear transformations in a single LSTM module.

**Comment by niboshi** [comment]
I have a concern that `*_init` is not consistent with the existing convention: `initial_*`.

**Comment by delta2323** [comment]
@mitmul I think it is OK, as I wrote in this [comment](https://github.com/chainer/chainer/pull/5091#issuecomment-405539275).

**Comment by delta2323** [comment]
@niboshi I think the existing `L.LSTM` has initializers of the form `*_init` (e.g. `lateral_init`). Which link did you intend you want to align the convention with?

**Comment by niboshi** [comment]
This is the list of links which have `initial_` or `initial*` arguments.

```shell
$ grep 'initial[_A-Z]' chainer/links/**/*.py | sed -r 's/^([^:]*):.*/\1/' | uniq
chainer/links/activation/maxout.py
chainer/links/activation/simplified_dropconnect.py
chainer/links/caffe/caffe_function.py
chainer/links/connection/bilinear.py
chainer/links/connection/convolution_2d.py
chainer/links/connection/convolution_nd.py
chainer/links/connection/deconvolution_2d.py
chainer/links/connection/deconvolution_nd.py
chainer/links/connection/deformable_convolution_2d.py
chainer/links/connection/depthwise_convolution_2d.py
chainer/links/connection/dilated_convolution_2d.py
chainer/links/connection/embed_id.py
chainer/links/connection/gru.py
chainer/links/connection/highway.py
chainer/links/connection/inception.py
chainer/links/connection/inceptionbn.py
chainer/links/connection/linear.py
chainer/links/connection/local_convolution_2d.py
chainer/links/connection/lstm.py
chainer/links/connection/mlp_convolution_2d.py
chainer/links/model/vision/googlenet.py
chainer/links/model/vision/resnet.py
chainer/links/model/vision/vgg.py
chainer/links/normalization/batch_normalization.py
chainer/links/normalization/batch_renormalization.py
chainer/links/normalization/group_normalization.py
chainer/links/normalization/layer_normalization.py
```

**Comment by delta2323** [comment]
I surveyed in more detail to understand the situation.

These are initializers matched with `initial[_A-Z]` (I only consider arguments of `__init__`):
- `initialW`, `initial_bias` (many links)
- `initial_gamma`, `initial_beta` (normalization links such as batch_normalization).

And initializers matched with `[_init]`

- `beta_init` (swish)
- `inner_init`, `bias_init` (GRU)
- `upward_init`, `bias_init`, `forget_bias_init` (LSTM)
- `conv_init`, `bias_init` (mlp_convolution_2d)
- `conv_init` (inception)
- `conv_init`, `bias_init` (inceptionbn)

**Comment by delta2323** [comment]
I feel it is OK to align initializer names of `L.NStepLSTM` to those of `L.LSTM` because it is natural that these two links have same APIs as for initializers. Also, as we see in my previous comment, there are already many other links that have initializers other than `initialW` and `initial_bias`..

I notice that by using the same APIs for initializers as `L.LSTM`, we assume we use a same list of initializers for every LSTM. We cannot use different initializers for e.g. 2nd level LSTM, (not sure it works better, though). But it believe (I do not check) possible to prepare a variant of `NStepLSTM` that has custom initializers APIs by overriding `NStepLSTM`.

I also think it is a bit strange at first sight that there are roughly two kinds of name conventions (`initial***` and `***_init`). But I'm not sure it is so important to align the convention at the cost of backward compatibility.

**Comment by niboshi** [comment]
I see. Thank you for investigating.
Now I think consitency is less important (that doesn't mean not important, of course).

Another point of discussion is that `initialW` and `initial_bias` have been introduced in v3.0.0rc1 and removed in v4.0.0b4. In other words, user code written for v3 may be using these arguments.
But I'm not sure those names were appropriate in the first place.

**Comment by MannyKayy** [comment]
bump
