### ISSUE TITLE
Add Parallel class for easy model definition of parallel-stream computational graph

### ISSUE THREAD

**Issue by hitsgub** [chainer/chainer#4767]
This idea inspired from #2918, `chainer.Sequential`.
Parallel class provides easy module definition of ResNet, DenseNet, InceptionNet, and etc.
And the combination of `chainer.Sequential` and Parallel class makes a lot of NN models to be written easy.
And I guess Parallel class need the option `connect` which define the way to connect outputs of parallel-stream, unlike `chainer.Sequential`. For example, `connect` option is selected from `None` or any function. (If `None`, Parallel class returns `tuple` (or `list`?) of `Variables`.)

I am to implement this class based on `chainer.Sequential`,
and please let's discuss the design of the class for brushup.

And, is this _Parallel_ suitable for the name of this class?

Example of ResNet module is below:
```
import chainer
import chainer.links as L
from chainer import Parallel

model = Parallel(
    L.Convolution2D(ch_in, ch_out, 3, stride, 1),
    lambda x: x,
    connect = sum
)
```
Example of DenseNet module is below:
```
import chainer
import chainer.links as L
import chainer.functions as F
from chainer import Parallel

model = Parallel(
    L.Convolution2D(ch_in, ch_out, 3, stride, 1),
    lambda x: x,
    connect = F.concat
)
```

**Comment by hitsgub** [comment]
Thank you for your reply. I agree with the word "parallel" is confusing with other class and need to be rethought.
Then, how is the word `Branch`?

**Comment by muupan** [comment]
Reopened because I want to use a link like this in ChainerRL too. https://github.com/chainer/chainerrl/pull/427

**Comment by niboshi** [comment]
As for the interface, how about accepting a `list`-like, instead of unpacking arguments (`*`)?
i.e. 
```py
model = Parallel([
        L.Convolution2D(ch_in, ch_out, 3, stride, 1),
        lambda x: x,
    ],
    connect = F.concat
)
```
I know it's inconsistent with `Sequential` but the code with unpacking arguments looks error-prone.

**Comment by muupan** [comment]
As for the name, besides the fact that "Parallel" can be confusing with multithread/process computation,
- "Parallel" can mean n-input-n-output, but this link is 1-input-n-output (before connected), and
- "Branch" as a noun sounds like a single branch.

I think "Branched" can be a better alternative.
