### ISSUE TITLE
Error when building dataset for chainer model manually

### ISSUE THREAD

**Issue by cmjdxy** [chainer/chainer#4783]
There is an error when I train an NN with manual dataset. My code is [here](https://github.com/cmjdxy/practice-chainer/blob/master/train_with_manual_data.py). Run _python train_with_manual_data.py --manual 1_, the output error is:

InvalidType: 
Invalid operation is performed in: SoftmaxCrossEntropy (Forward)

Expect: in_types[1].dtype.kind == i
Actual: u != i

But run _python train_with_manual_data.py --manual 0_, there will be no problem. I don't know why, anyone get a clue? Thank you in advance.
PS: I've also pulled this issue on [stackoverflow](https://stackoverflow.com/questions/50383345/error-when-building-dataset-for-chainer-model-manually).

**Comment by kmaehashi** [comment]
I posted an answer on SO.
https://stackoverflow.com/questions/50383345/error-when-building-dataset-for-chainer-model-manually/50383976

**Comment by cmjdxy** [comment]
It works! Thank you!
PS: I also posted this on [SO](https://stackoverflow.com/questions/50383345/error-when-building-dataset-for-chainer-model-manually/50383976).
