### ISSUE TITLE
Support for setting item in Variable

### ISSUE THREAD

**Issue by cmpute** [chainer/chainer#4795]
Recently I'm implementing a network one of whose layers turns a sparse data representation into a dense data representation. The line to implement this is like `dense[coord[0], coord[1], coord[2], :] = features`. I found that this is supported in cupy array but not supported in `Variable` because it doesn't have `__setitem__`. So right now I have to write a stand-alone `Function` to support this. I hope this could be implemented for `Variable` just like in PyTorch.

**Comment by toslunar** [comment]
#5171 partially addresses this.

**Comment by kmaehashi** [comment]
Bump as the PR is ongoing

**Comment by niboshi** [comment]
@toslunar What do you mean by partially?

**Comment by toslunar** [comment]
#5171 enables
```python
dense = F.set_item(
    dense,
    (coord[0], coord[1], coord[2], slice(None)),
    features,
    inplace=False)
```
while the request is

> `dense[coord[0], coord[1], coord[2], :] = features`

**Comment by niboshi** [comment]
I see.
Whether to support `Variable.__setitem__` is just a matter of interface, but in order to support the original request efficiently, we will need `inplace=True` (which only have to work if `dense` does not require backprop), if my understanding is correct.

**Comment by cmpute** [comment]
> interface

Yes, the coordinates in my situation don't require back-propagation

**Comment by toslunar** [comment]
As Chainer is under the maintenance phase, unfortunately we decided not to implement this feature. Thanks again for your contribution.
