### ISSUE TITLE
CupyMemoryProfileHook crashed

### ISSUE THREAD

**Issue by cmpute** [chainer/chainer#4796]
- Chainer version: 4.0.0
  - CuPy version: 4.0.0
  - OS/Platform: Windows 10.0.16299.431
  - CUDA/cuDNN version: CUDA 9.1 w/o cuDNN

I want to use `CupyMemoryProfileHook` to do some profiling in my network, however the process crashed without any error message when then trainer started. I tried again for several times and once it showed a message `Exception in main training loop: Cannot convert int to cupy.cuda.memory._Chunk` without showing a tracing stack.

I tried to debug the Python process using VS and the calling stack shows
```
>	python36.dll!update_refs(_gc_head * containers) 行 346	C
 	python36.dll!collect(int generation, __int64 * n_collected, __int64 * n_uncollectable, int nofail) 行 956	C
 	python36.dll!collect_with_callback(int generation) 行 1129	C
 	python36.dll!collect_generations() 行 1151	C
 	[内联框架] python36.dll!_PyObject_GC_Alloc(int) 行 1726	C
 	[内联框架] python36.dll!_PyObject_GC_Malloc(unsigned __int64) 行 1736	C
 	python36.dll!PyType_GenericAlloc(_typeobject * type, __int64 nitems) 行 936	C
 	python36.dll!make_new_set(_typeobject * type, _object * iterable) 行 1050	C
 	util.cp36-win_amd64.pyd!00007ffda4d715e7()	未知
 	util.cp36-win_amd64.pyd!00007ffda4d72d83()	未知
 	util.cp36-win_amd64.pyd!00007ffda4d74700()	未知
 	core.cp36-win_amd64.pyd!00007ffd78313a02()	未知
 	core.cp36-win_amd64.pyd!00007ffd78313b19()	未知
 	core.cp36-win_amd64.pyd!00007ffd78223e2f()	未知
 	core.cp36-win_amd64.pyd!00007ffd782bbb1f()	未知
 	core.cp36-win_amd64.pyd!00007ffd782e4290()	未知
```

I'm using the hook with following code:
```python
    with chainer.function_hooks.CupyMemoryProfileHook() as hook:
        trainer.run()
    hook.print_report()
```
Besides, `TimerHook` is usable in my network.

My network is quite complex that I cannot summarize it into a single reproduce case. How can I provide more information for you to look into this issue?

**Comment by kmaehashi** [comment]
Thank you for the feedback. Is the issue always reproducible?
In that case, could you try again using CuPy wheel for Windows and try again?
https://pypi.org/project/cupy-cuda91/5.0.0b1/#files

**Comment by cmpute** [comment]
Cython version is 0.26.1
I'll have a try for the wheel.

**Comment by kmaehashi** [comment]
I just succeed to reproduce this case (on Linux) with Cython 0.27.3.
The error disappeared with Cython 0.28.0. If possible, could you also try updating Cython, then installing cupy from source? (cupy wheels are built with Cython 0.27.3)

**Comment by cmpute** [comment]
I used the latest cython and built cupy, now it works! Thanks for your efforts!
