### ISSUE TITLE
Remove `if gpu_id >=0:` code

### ISSUE THREAD

**Issue by Crissman** [chainer/chainer#4854]
I'd like to remove the `if gpu_id >=0:` requirement to check for `-1` device ID for CPU from Chainer.

Two ideas how to do this:
```
    def to_gpu(self, device=None):
      if device == -1:
         return to_cpu(device)
```

Has advantage of not requiring additional functions. Perhaps not intuitive what `to_gpu(-1)` would do.

Another idea would be to add a cpu/gpu director function, `to_pu`:

```
    def to_pu(self, device=None):
      if device == -1:
         return to_cpu(device)
      return to_gpu(device)
```

Both would require this code in several places, there are several implementations of `to_gpu`, such as for `links`, `variables`, etc.

I can code the PR for either solution.

Good idea? Preference for either approach?

**Comment by beam2d** [comment]
I understand the motivation, but either solution looks ad-hoc (`to_gpu(-1)` is counterintuitive, and `to_pu` that only supports CPU/GPU may limit the possible extensions to another device in the future). I feel it's better to introduce a generalized concept of "device" and name a new method `to_device` or simply `to`.

**Comment by toslunar** [comment]
Chainer v5 will have interface like `chainer.set_default_device('cuda:0')` (see @beam2d's slide).  For tutorial purposes, this change benefits leaners only for a few months.

**Comment by Crissman** [comment]
Understood. Thanks.

**Comment by toslunar** [comment]
Note for v6:
- `to_device` is available since ChainerX is merged.
- Just as suggested here, `to_device` accepts int since v6.0.0rc1 (#6394).
