### ISSUE TITLE
Can the author of L.Convolution2D write an english  article explain us how the code of forward and backward works

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#4878]
Hello:
  I am a PhD student who study on Interpretable CNN rearch, My idea is use a special designd convolution layer to replace a regular/ traditional L.Convolution2D layer. This special design conv2d can explain itself.
Because I am starting using chainer as my major research tool. Can the author of L.Convolution2D write an english article explain to me how the code of forward and backward works?
I will cite chainer and I will use chainer as always my first choice deep learning tool.

My mail is sharpstill@163.com, If you can tell me more, please contact with me.

**Comment by kmaehashi** [comment]
Could you please use StackOverflow for general questions?

**Comment by sharpstill** [comment]
@kmaehashi I post question here: https://stackoverflow.com/questions/51258687/can-the-author-of-l-convolution2d-write-an-english-article-explain-us-how-the-co
