### ISSUE TITLE
Document dtype attribute of initializers

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#4897]
Initializers' `dtype` attributes define supported dtypes, but [it's not documented](https://docs.chainer.org/en/stable/reference/initializers.html).

**Comment by Crissman** [comment]
I took a look at the code, and only `initializers.Normal` limits the `dtypes` to `numpy.float32` or `float16`.

```
 # Only CuPy supports dtype option
if self.dtype == numpy.float32 or self.dtype == numpy.float16:
    args['dtype'] = numpy.float32  
```

The other initializers seem to support any `dtype`. Is it sufficient to document this for `Normal`?

**Comment by niboshi** [comment]
It seems the code you pasted simply falls back the argument of `cupy.random.normal` from `float16` to `float32`, because it does not support `float16`.
It's converted to `float16` after that.

It supports `float16`, `float32` and `float64` as well.

**Comment by Crissman** [comment]
So, basically, all of the initializers support `float16`, `float32`, and `float64`, and you recommend we add that to the `parameter` `dtype` for all of them?

**Comment by niboshi** [comment]
We simply need to document that `initializer.dtype` is used to initialize the array.

**Comment by toslunar** [comment]
#5246 resolved the issue.
