### ISSUE TITLE
LSTM documentation can be improved to mention unchaining

### ISSUE THREAD

**Issue by CupyUser** [chainer/chainer#4898]
HI!

I'd like to report a hard to debug issue - whether this should result in a code change or a bigger warning label, I am unsure. When forgetting to use `reset_state()` on an LSTM, the following behaviour occurs:
Consecutive applications of the LSTM cause an out-of-memory exception to occur.

Code to reproduce:
```
import chainer
import chainer.links as L
from chainer.backends import cuda

size = 3000
rnn = L.LSTM(size, size)
rnn.to_gpu()
x = cuda.cupy.zeros((size, size), dtype=cuda.cupy.float32)

for i in range(1000):
    rnn(x)
```

Error messages, stack traces, or logs:
`cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 144000000 bytes (total 9936097280 bytes)`

Conditions:
  Chainer version: 4.1.0
  CuPy version: 4.1.0
  OS/Platform: Ubuntu
  CUDA/cuDNN version: 8.0/6.0

Keep up the good work!

**Comment by CupyUser** [comment]
Hi Kenichi,

Thank you for the swift answer. I confirm you are correct and this behavior is documented, although it is not immediately obvious that this error comes from that behavior. I think that putting a warning label about this type of memory issue in the `reset_state` documentation for an LSTM would benefit people. I am happy to close this issue now if you want me to. Thank you again.

**Comment by kmaehashi** [comment]
Thanks for the suggestion. We'll consider updating the docs of the method.

**Comment by mitmul** [comment]
I will add more descriptions of `reset_state` and some example code to the documentation.
