### ISSUE TITLE
concat_examples with various batch size causes memory leaks

### ISSUE THREAD

**Issue by ir5** [chainer/chainer#4911]
I found the iterative call of `concat_examples` causes memory leaks of CPU memory when batch size changes among iterations. This behavior is unexpected and quite inconvenient during inference time. The following is code for reproduction.
Does anyone know the reason for this?

```python
import chainer
import numpy as np
import time

chainer.cuda.get_device_from_id(0).use()

print('ready')
time.sleep(3)  # ps aux | grep python  ==>  RSS:113580KB

for i in range(200):
    n = np.random.randint(low=5, high=150)
    batch = [np.zeros(200000, dtype=np.float32) for _ in range(n)]
    chainer.dataset.concat_examples(batch, 0)
    print(i)

print('done')
time.sleep(3)  # ps aux | grep python  ==>  RSS:7030232KB
```

Environment:
- chainer 4.1.0 (installed from pip)
- cupy was installed by `pip install cupy-cuda90`
- CUDA9.0, cudnn=7.0.3
- Ubuntu 16.04

**Comment by kmaehashi** [comment]
CuPy caches the allocated pinned memory in the memory pool. You can avoid this by periodically calling 

```py
chainer.cuda.cupy.get_default_pinned_memory_pool().free_all_blocks()
```

to release all memory in the pinned memory pool.

You can also completely disable the pinned memory pool by calling:

```py
chainer.cuda.cupy.cuda.pinned_memory.set_pinned_memory_allocator(None)
```

**Comment by delta2323** [comment]
I think it is helpful for users to write this practice to somewhere in the CuPy document.

**Comment by kmaehashi** [comment]
We introduced an workaround in CuPy side. https://github.com/cupy/cupy/pull/1372
However documenting the detailed behavior of memory pools would be nice.
