### ISSUE TITLE
`backends.cuda.get_device_from_array` should support variables

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#4950]
Currently it only supports `cupy.ndarray`s.
It may be cumbersome to use it in some cases.

For example, in function wrapper implementation that does not have its own `FunctionNode` class (i.e. implemented with combination of other functions), basically it should set the current device to the one where its input arrays are allocated. Otherwise, arrays newly allocated in the function will be on the incorrect "current" device (which has been set before entering this function), leading to the device mismatch error.

What makes it more complicated is that the function must accept both `ndarray`s and `Variable`s.

General way to do this is something like this:

```
def some_func(x, y, z):
    with backends.cuda.get_device_from_array(*[a.array if isinstance(a, variable.Variable) else a for a in (x, y, z, ...)]):
        ...
```

It's better to allow this:

```
def some_func(x, y, z):
    with backends.cuda.get_device_from_array(x, y, z):
        ...
```

**Comment by kmaehashi** [comment]
Refs https://github.com/chainer/chainer/issues/4595 https://github.com/chainer/chainer/pull/4604

We should decide how `get_device_from_array` should behave for uninitialized Variable (whose data is None), and not-yet-initialized Parameter.

**Comment by beam2d** [comment]
We can extract the device from uninitialized `Parameter` (`_initial_device`). Uninitialized `Variable` does not have its device. In this case, maybe it's enough to just ignore that variable.

The implementation will be kept simple and fast by introducing `device` property to `Variable` and `Parameter`; we can then just use `getattr(x, 'device', None)` without type testing (it also works for np/cp ndarray).
