### ISSUE TITLE
F.split_axis does not work with cupy arrays for indices

### ISSUE THREAD

**Issue by CupyUser** [chainer/chainer#4974]
The Chainer function `split_axis` does not currently support a cupy array for the `indices_or_sections` parameter. 

Code to reproduce:
```
split_idx = cuda.cupy.array([2, 3])
some_array = cuda.cupy.random.rand(3, 2)
segments = F.split_axis(some_array, split_idx, 0)
```

Error messages, stack traces, or logs:
```
TypeError: indices_or_sections must be integer or 1-D array.
Actual: <class 'cupy.core.core.ndarray'>
```

Line causing the issue (line 27 of functions/array/split_axis.py):
```
if isinstance(ios, numpy.ndarray):
```
There is no equivalent check for a `cupy` array and the check falls through.

Conditions:
Chainer version: 4.1.0
CuPy version: 4.1.0
OS/Platform: Ubuntu
CUDA/cuDNN version: 8.0/6.0

Love the framework, keep up the good work!

**Comment by kmaehashi** [comment]
It sounds make sense to support cupy ndarray.
Could you make a PR for this?

**Comment by CupyUser** [comment]
There are two possible things that could be done here:
1) Cast the given argument to a `numpy` ndarray at the specified location, which I can quickly do a PR for. Example:
```
if isinstance(ios, cuda.cupy.ndarray):
  ios = cuda.cupy.asnumpy(ios)
```
2) Keep the array as a `cupy` array and open a pull request to CuPy for [https://github.com/cupy/cupy/blob/v4.2.0/cupy/core/core.pyx#L2228](https://github.com/cupy/cupy/blob/v4.2.0/cupy/core/core.pyx#L2228), which is a bit harder.

Which one do you think is more sensible to do?

**Comment by mitmul** [comment]
All the functions here have the same issue: https://github.com/cupy/cupy/blob/v4.3.0/cupy/manipulation/split.py
And it's a CuPy issue so let's open a new issue in CuPy repository.

**Comment by kmaehashi** [comment]
Moved to https://github.com/cupy/cupy/issues/1861
