### ISSUE TITLE
No module named 'cupy.cudnn'

### ISSUE THREAD

**Issue by rezha130** [chainer/chainer#5019]
Hi all, please help.

I installed CUDA 9.0, cuDNN 7, Chainer 3.2.0, CuPy 2.2.0, Python 3.6 on Ubuntu 16.04 LTS

but when i check `print(chainer.cuda._resolution_error)` in python, i got this message:
`No module named 'cupy.cudnn'`

I also check may installed CuDNN, here the result
```
$ ls /usr/include/cudnn.h
/usr/include/cudnn.h
```
```
$ ls /usr/lib/x86_64-linux-gnu/libcudnn*
/usr/lib/x86_64-linux-gnu/libcudnn.so
/usr/lib/x86_64-linux-gnu/libcudnn.so.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.10
/usr/lib/x86_64-linux-gnu/libcudnn.so.7
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_static.a
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a
```

I also reinstall CuDNN with this in command line
```
$ sudo dpkg -i libcudnn7_7.0.5.15-1+cuda9.0_amd64.deb 
[sudo] password for rezha: 
(Reading database ... 357409 files and directories currently installed.)
Preparing to unpack libcudnn7_7.0.5.15-1+cuda9.0_amd64.deb ...
Unpacking libcudnn7 (7.0.5.15-1+cuda9.0) over (7.0.5.15-1+cuda9.0) ...
Setting up libcudnn7 (7.0.5.15-1+cuda9.0) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
```

but when i check chainer in python, i got this result:
```
>>> import chainer
>>> chainer.cuda.available
True
>>> chainer.cuda.cudnn_enabled
False
```

What should i do?

**Comment by kmaehashi** [comment]
Could you try installing CuPy via wheel?
https://docs-cupy.chainer.org/en/stable/install.html#install-cupy

**Comment by fiarabbit** [comment]
If you install cupy-cuda** as @kmaehashi  suggested, make sure unintall cupy because of name conflict.
Or, if you reinstall cupy, make sure `pip install cupy **--no-cache-dir**`

**Comment by rezha130** [comment]
@kmaehashi i did `pip install cupy-cuda90`, and `pip uninstall cupy`

when i check chainer in python, i got this result:

```
>>> import chainer
>>> chainer.cuda.available
True
>>> chainer.cuda.cudnn_enabled
True
```

But this cupy-pycoda90 not compatible with installed Chainer 3.2.0, i got this error message when running my neural net model:
`module 'cupy.cuda.cudnn' has no attribute 'getConvolutionForwardAlgorithm'`

**Comment by fiarabbit** [comment]
No, _generally_ chainer developers do not leave dependency to the detailed implementation of cupy (I hope so), and your stack trace says you are calling the raw cupy utility of `getConvolutionForwardAlgorithm`, which is now renamed to `getConvolutionForwardAlgorithm_v6`. (In other words, the stack trace you gave says it is not flaw of chainer but of cupy)

Anyway, without any (hopefully short) reproduction code nor the whole stack traces, no one can advise anymore, I think.

**Comment by rezha130** [comment]
solved, i upgraded also chainer version..the train model run 4x faster with cuDNN enabled!

thanks
