### ISSUE TITLE
iDeep 2.0 support

### ISSUE THREAD

**Issue by kmaehashi** [chainer/chainer#5049]
This issue is to aggregate the status of iDeep 2.0 support.

I'm thinking of merging PRs in this order:

- [x] Primary PR (this breaks compatibility with iDeep 1.x): 
- [x] Test script to use iDeep 2.x: ~https://github.com/chainer/chainer-test/pull/434~ https://github.com/chainer/chainer-test/pull/453
- [x] Update installation guide, etc.: #5029
- [x] Use iDeep 2.0 in Adam: #5033

**Comment by toslunar** [comment]
Fixed the test script. (chainer/chainer-test#453)
