### ISSUE TITLE
CPU(iDeep enabled) backward performance shows regression

### ISSUE THREAD

**Issue by mingxiaoh** [chainer/chainer#5055]
@niboshi @toslunar @beam2d 
After we rebased to Chainer 5.0.0b2, we found backward performance show about 10-40% drop for CPU(iDeep enabled). Root cause clear, caused by 2 changes:
1.	in chainer/functions/connection/convolution_2d.py-> Convolution2DGradW-> forward_cpu, iDeep path was removed unexpectedly.
2.	in chainer/functions/math/basic_math.py-> MultiAdd,  broadcast implementation.

after we roll back the changes, perfomance turns to normal.
     
```
=====================details===================================
diff --git a/chainer/functions/connection/convolution_2d.py b/chainer/functions/connection/convolution_2d.py
index d7ba727..5fa5e2e 100644
--- a/chainer/functions/connection/convolution_2d.py
+++ b/chainer/functions/connection/convolution_2d.py
@@ -270,6 +270,10 @@ class Convolution2DGradW(function_node.FunctionNode):
         self._use_ideep = conv2d._use_ideep

     def forward_cpu(self, inputs):
++        x, gy = inputs
++       if self._use_ideep:
++            return self._forward_ideep(x, gy)
++
         self.retain_inputs((0, 1))
         x, gy = inputs

@@ -286,6 +290,14 @@ class Convolution2DGradW(function_node.FunctionNode):
             return self._forward_cpu_core(x, gy)

     def _forward_cpu_core(self, x, gy):
++       col = conv.im2col_cpu(
++            x, self.kh, self.kw, self.sy, self.sx, self.ph, self.pw,
++            cover_all=self.cover_all, dy=self.dy, dx=self.dx)
++        gW = numpy.tensordot(gy, col, ((0, 2, 3), (0, 4, 5))
++                             ).astype(self.W_dtype, copy=False)
++        return gW,
++
++    def _forward_cpu_core(self, x, gy):
         if self._use_ideep:
             return self._forward_ideep(x, gy)

diff --git a/chainer/functions/math/basic_math.py b/chainer/functions/math/basic_math.py
index 015c5c5..085b3f6 100644
--- a/chainer/functions/math/basic_math.py
+++ b/chainer/functions/math/basic_math.py
@@ -192,10 +192,10 @@ class MultiAdd(function_node.FunctionNode):
         if len(xs) == 1:
             return xs
         y = None
--        if intel64.should_use_ideep('>=auto'):
--            bxs = numpy.broadcast_arrays(*xs)
--            if intel64.inputs_all_ready(bxs):
--                y = intel64.ideep.multi_add(bxs)
++        if (intel64.should_use_ideep('>=auto')
++                and intel64.inputs_all_ready(xs)):
++            y = intel64.ideep.multi_add(xs)
++
```

**Comment by kmaehashi** [comment]
> 1. in chainer/functions/connection/convolution_2d.py-> Convolution2DGradW-> forward_cpu, iDeep path was removed unexpectedly.

Could you please check again? I think iDeep path still exists (it's moved to `_forward_cpu_core`).

I confirmed performance using [chainer-benchmark](https://github.com/chainer/chainer-benchmark) (`asv run --python=same --show-stderr -b convolution_2d.Convolution2D.time_backward`) but no regression has been detected.

## master (3be74f5)

```
=========== ========= =========
--                batches      
----------- -------------------
  backend       1         16   
=========== ========= =========
    gpu        n/a       n/a   
 gpu-cudnn     n/a       n/a   
    cpu        n/a       n/a   
 cpu-ideep   11.63ms   95.29ms 
=========== ========= =========
```

## v5.0.0a1

```
=========== ========= =========
--                batches
----------- -------------------
  backend       1         16
=========== ========= =========
    gpu        n/a       n/a
 gpu-cudnn     n/a       n/a
    cpu        n/a       n/a
 cpu-ideep   11.64ms   94.68ms
=========== ========= =========
```

> 2. in chainer/functions/math/basic_math.py-> MultiAdd, broadcast implementation.

Thanks, it will be fixed in #5056.

**Comment by mingxiaoh** [comment]
Yes, you are right, iDeep path is still, the regression is actually caused by 
        if (not (gy.flags.c_contiguous or gy.flags.f_contiguous) and
                1 in gy.shape):
            gy = numpy.ascontiguousarray(gy)
According to my test, if I comment above code, performance will turn to normal.

**Comment by mingxiaoh** [comment]
BTW, don't forget to handle those iDeep unit test cases, there are many failed test case now.

**Comment by kmaehashi** [comment]
Ah, I see, so it's converted back to numpy array in that case. That was not covered by my benchmark. I'll fix it.

**Comment by kmaehashi** [comment]
@mingxiaoh Could you share your experiment code? (I'm proposing fix in #5063 and would like to confirm it works)

**Comment by kmaehashi** [comment]
> BTW, don't forget to handle those iDeep unit test cases, there are many failed test case now.

We're currently testing every PRs with ideep4py 1.0.4 wheels in Jenkins test, but we don't observe failures. Could you share the details of failure?

**Comment by mingxiaoh** [comment]
@kmaehashi 
================iDeep1.0.4====================================
Case1: 
export CHAINER_USE_IDEEP="auto"
pytest -s -v -m "not slow and not gpu and not cudnn" chainer_tests
result see: https://github.com/mingxiaoh/chainer-rebase-test/blob/master/ideep1_lazy0.log

Case2:
export CHAINER_USE_IDEEP="auto"
export CHAINER_LAZY_GRAD_SUM=1
pytest -s -v -m "not slow and not gpu and not cudnn" chainer_tests
result see: https://github.com/mingxiaoh/chainer-rebase-test/blob/master/ideep1_lazy1.log

====================iDeep2.0======================
waiting...., we need import some change in Intelchainer to Chainer/Chainer first.

**Comment by kmaehashi** [comment]
You shouldn't set `export CHAINER_USE_IDEEP="auto"` when running unittest. The configuration is controlled automatically by `chainer.testing` module.

**Comment by kmaehashi** [comment]
Fixes for this issue has been merged. (#5056, #5063)
