### ISSUE TITLE
Support Python 3.7

### ISSUE THREAD

**Issue by kmaehashi** [chainer/chainer#5109]
This issue is a meta issue to track related issues and PRs.

- [x] https://github.com/chainer/chainer/issues/5097
- [x]  #5223
- [x]  CuPy Python 3.7 support: https://github.com/cupy/cupy/issues/1464

After all fixes has been done, we should fix chainer-test against py3.7 and update docs.

**Comment by frankier** [comment]
Related issue: conda will try and install the Python 3.7 version of Chainer along with Python 3.7 itself even if you don't have it already. You want to avoid this until a new release like so:

    conda install chainer=4.2.0=py36_0

**Comment by toslunar** [comment]
matplotlib/matplotlib#11733 hasn't been backported to matplotlib 2.x.

It needs a fix to the test https://github.com/chainer/chainer/compare/master...toslunar:test-py37-matplotlib

**Comment by toslunar** [comment]
- [x] chainer/chainer-test#442
- [x] docs: #5573
- [ ] conda

**Comment by kmaehashi** [comment]
@toslunar  I'd like to close this issue as we now support Python 3.7, and Conda support is not task of ourself (we're asking Anaconda team to build CuPy package). How do you think?

**Comment by toslunar** [comment]
And CuPy can be installed manually.  It seems OK to close the issue, "Support Python 3.7".
