### ISSUE TITLE
GUI tool

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#513]
GUI tool for modeling is useful for beginners. Do anyone have ideas?

**Comment by tscohen** [comment]
I think some visualizations would be useful:
- Plotting of the computational graph
- A training dashboard that shows weight and grad histograms or average magnitudes, as well as loss over time. Perhaps this dashboard could include a clickable computation graph, where if you click a node it shows you stats about that node.

We should think carefully about the intended audience for a full-blown GUI tool. I doubt that someone without any programming experience could do a good job of modeling, even with a GUI. The Chainer API is already so simple that it can be used by novice programmers. How many people are there that can read ML books or papers, know what a convolution is, but can't write y = Convolution2D()(x)? 

Another concern is that the GUI app should not slow down the development of the main codebase. When adding a feature or changing the structure of the API, this should automatically be reflected in the GUI. At this stage that seems like a challenge, given the recent quite drastic changes in the internal structure (#363).

In Chainer, the graph is defined by the computation so it is not static. How would that work in a GUI? Can the GUI create static graphs only?

If you decide to build this GUI, I would suggest to always have an underlying script. This script is either constructed by the GUI app if you start the model from scratch in the GUI, or you write some code first, then inspect the graph in the GUI and make some changes which are then reflected in the script. This could be tricky to implement, but at least you will not "get stuck in the GUI", when you discover after a while that you want to do something that is not supported.

**Comment by sinhrks** [comment]
If GUI means visualization, it is related to #75. For plotting computational graph, I have an local impl using graphviz and am willing to send a PR.

**Comment by delta2323** [comment]
I hear in GTC Japan on September that DIGITS, Deep Learning Training Tools from NVIDIA will support not only Caffe but also other framework including Chainer. I am not sure to what extent this future plan is certain, but I think we should take into consideration of other visualization tools.

**Comment by unnonouno** [comment]
We now released chainerui: https://github.com/chainer/chainerui
