### ISSUE TITLE
About the resolution of figures in "Chainer at a glance".

### ISSUE THREAD

**Issue by jinjiren** [chainer/chainer#5130]
I like this new introduction of Chainer very much, especially new figures explaining the relations between different components for training with `Trainer`. However, I found that the resolution is quite low for several small figures, e.g., 
<img width="897" alt="image" src="https://user-images.githubusercontent.com/8536399/43013038-88ee2100-8c82-11e8-94e2-85b3d991a32f.png">
<img width="865" alt="image" src="https://user-images.githubusercontent.com/8536399/43013047-92647900-8c82-11e8-9525-f576a62f84fb.png">
<img width="865" alt="image" src="https://user-images.githubusercontent.com/8536399/43013052-991825f8-8c82-11e8-92aa-7e6a498183e3.png">
<img width="855" alt="image" src="https://user-images.githubusercontent.com/8536399/43013058-a0580018-8c82-11e8-875b-d38106243b34.png">
<img width="851" alt="image" src="https://user-images.githubusercontent.com/8536399/43013068-a67d4854-8c82-11e8-8ae0-420c4d332d29.png">

I know this is not a big problem, but the doc will definitely look nicer with higher resolution images.

**Comment by toslunar** [comment]
Fixed by #5316.
