### ISSUE TITLE
About the documentation of `Iterator` in "Chainer at a glance".

### ISSUE THREAD

**Issue by jinjiren** [chainer/chainer#5131]
I think the data should be generally (for better practice) shuffled at every training epoch instead of only shuffled at the start of training.

Currently, it's said that 
> shuffling not required since we already shuffled the dataset on reading it in.

And the actual code for loading the data is:
```python
data_array = np.genfromtxt(
    'mushrooms.csv', delimiter=',', dtype=str, skip_header=1)
for col in range(data_array.shape[1]):
    data_array[:, col] = np.unique(data_array[:, col], return_inverse=True)[1]

X = data_array[:, 1:].astype(np.float32)
Y = data_array[:, 0].astype(np.int32)[:, None]
train, test = datasets.split_dataset_random(
    datasets.TupleDataset(X, Y), int(data_array.shape[0] * .7))
```
where the shuffling happens in `train, test = datasets.split_dataset_random(
    datasets.TupleDataset(X, Y), int(data_array.shape[0] * .7))`. This will only randomly construct the train and test dataset, but generate the fixed order of mini-batch examples during the training phase.

Though I think this is a minor problem, maybe it's better to use the common way to shuffle the iterator with `shuffle=True`.

**Comment by fiarabbit** [comment]
I agree that the description was irrational, and the grammar is also confusing (`no repeating not required` contains double negative). I wrote a draft as a PR.

**Comment by fiarabbit** [comment]
The PR is merged now. I think this issue can be closed.

**Comment by Crissman** [comment]
Thanks!
