### ISSUE TITLE
raise warning if cuDNN is not applied for acceleration due to its version

### ISSUE THREAD

**Issue by fiarabbit** [chainer/chainer#5136]
In `F.deconvolution_2d`, depending on the parameter and installed cuDNN version, it switches cuDNN on and off. However, for the user, there is no way to know whether cuDNN acceleration was applied or not for his/her program.
Isn't it more helpful for the users to inform "if you upgrade cuDNN, the computation would be more speedy without any modification of source code"?

**Comment by kmaehashi** [comment]
Thanks for raising an issue.
This may not directly answer your question/requirement, but cuDNN 7.1+ provides API logging feature so that you can check if cuDNN is applied or not.
https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#api-logging

**Comment by fiarabbit** [comment]
@kmaehashi 
Thank you for your comment.

The functionality nvidia gives might be one of solution, but I think it is too cumbersome for the user to check all the function calls. (Especially when he uses a hand-craft function which he did not write).
Because chainer kindly checks whether to use cuDNN or not, it can be easily implemented (just adding `warning.warn("cuDNN is disabled because ...")` to the if-statement) and in contrast with its benefits.

Recently, I also found a tweet that "why chainer has F.convolution_2d(cover_all=True) but does not have L.Convolution2D(cover_all=True)". I think this is also due to the performance decrease caused by disabling cuDNN. Therefore, I think this feature is very useful for many users.
