### ISSUE TITLE
warning if model accidentally contains some empty params and it calls `to_gpu`

### ISSUE THREAD

**Issue by himkt** [chainer/chainer#5161]
I want chainer to warn when it calls `to_gpu` for a empty ndarray in debug mode.

Suppose some neural network `model`.
If model accidentally contains some empty params and I try to train model with Adam or AdaDelta,
it raise the error `Exception in main training loop: object __array__ method not producing an array`.

This error is raised because whole model except for empty params is sent to GPU but empty params is not.
([cuda.get_device_from_array(param.data)] returns `-1` for param.data which is empty,
then optimizer calls `update_core_cpu` in CPU mode. In this way, numpy and cupy are mixed)
(in [update_core](https://github.com/chainer/chainer/blob/master/chainer/optimizer.py#L232))

Here is the example to get cupy ndarray where `int(cuda.get_device_from_array)` returns -1.

```python
import chainer
import numpy


x = chainer.cuda.to_gpu(numpy.empty(0, dtype='f'))
print(int(chainer.cuda.get_device_from_array(x)))
print(chainer.cuda.get_device_from_array(x))
print(x)
```

I think it is natural to return `-1` for empty params because there is no allocation in GPU memory.
But I want to tell me if chainer.cuda.to_gpu is called for empty params.

I want to know what dev-teams think about it...:bow:

**Comment by toslunar** [comment]
According to @okuta, cupy/cupy#946 would fix this issue.

**Comment by himkt** [comment]
Awesome!! Thanks very much for telling me :pray:
I close this issue..:bow:
