### ISSUE TITLE
Time profiler for links

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#5197]
It was being implemented in #4730 using link hook, but dismissed because the features/interface was not well polished.

It should support
* Hierarchical call statistics, such as inclusive/exclusive elapsed time
* Backward propagation (maybe optional in the first implementation)

To support backward propagation, we will need to combine a function hook with a link hook.
Preliminary design overview discussed with @beam2d is like this:

* This pattern (to trigger function backward preprocess/postprocess callbacks within each link) may be common. We will need to factor out this feature.
* It's a link hook implementation. On its `added` / `deleted` callbacks, a function hook is registered/unregistered. 
* Recognize the forward period of each link using link hook's preprocess/postprocess callbacks.
* If function's forward preprocess is triggered within the period, hold the link call stack associated with the function.
* In function's backward preprocess/postprocess callbacks, trigger an event with the link call stack. The event is something like "function backward preprocess/postprocess event within a link".
* We can't trigger "link backward preprocess/postprocess", because there's no way to determine the first/last function to backprop within a link. It's a responsibility of this feature's user to extract required information.
* For symmetry, it will also trigger events for function "forward" preprocess/postprocess, with link call stack.
* Implement this feature in `link_hook.py` in parallel with `link_hook.LinkHook`.

**Comment by crcrpar** [comment]
This issue is partially resolved in #5842 which does not support backward.
