### ISSUE TITLE
Why does learning speed gradually drop?

### ISSUE THREAD

**Issue by superhez** [chainer/chainer#5206]
In my experiments, learning speed started from around 28 s/epoch and gradually dropped from then on. At the time of 3000 epochs, it's already slower than 60 s/epoch. Same phenomenon had happened in another totally different task. Could anybody tell me the reason? Appreciate for help.

**Comment by mitmul** [comment]
Related to https://github.com/chainer/chainer/issues/2554 ?

**Comment by mitmul** [comment]
@superhez Is this about on GPU? or it's happening with CPU?

**Comment by Crissman** [comment]
Thanks for the issue report. What version of Chainer and CuPy are you using?

**Comment by superhez** [comment]
Sorry for my late response.  The current versions are: chainer 3.5.0, cupy 2.5.0. ,but similar trouble also happened when I used chainer 1.23.0 long ago. Both are on GPU platforms.
