### ISSUE TITLE
Request for VGG19

### ISSUE THREAD

**Issue by crcrpar** [chainer/chainer#5209]
In image translation and style transfer, may use VGG19 as a feature extractor or a loss function.

So do you have any plan to add VGG19Layers?

as a side note, I have implemented below
https://gist.github.com/crcrpar/4d3935f5f42b4fdb9d09471e52bc49ef

**Comment by crcrpar** [comment]
I have implemented this in a very casual way, just copy&paste VGG16 and used sed a bit.

If this is not so bad, I will refactor this and write test from tomorrow.
https://gist.github.com/crcrpar/4d3935f5f42b4fdb9d09471e52bc49ef

**Comment by kmaehashi** [comment]
Implemented via #5213
