### ISSUE TITLE
model.to_cuda() throwing errror 139 

### ISSUE THREAD

**Issue by rishabh-09** [chainer/chainer#5244]
Hello everyone!
I have cuda path specified in my bashrc and also my gpu is cuda enabled.
But somehow my model is being not transferred to gpu and it throws error 139. When I run on CPU it works fine. Kinldy see the code snippet and error below.
![e1](https://user-images.githubusercontent.com/42341068/44301385-4d47a280-a333-11e8-9331-f88a557a769b.png)
![e2](https://user-images.githubusercontent.com/42341068/44301386-4de03900-a333-11e8-936d-59bf3751d025.png)
I am using centos 6.5 AND python 2.7 and updated version of chainer with cupy-cuda80.
Thanks

**Comment by kmaehashi** [comment]
Error 139 indicates segmentation fault, so you can try running python under gdb and see backtrace for further diagnosis. However, if you are facing the same issue in another framework (https://github.com/espnet/espnet/issues/352), I suspect this is an issue of your CUDA environment.
