### ISSUE TITLE
Issue with type change and multiprocessing

### ISSUE THREAD

**Issue by feedbackward** [chainer/chainer#5276]
It seems that Chainer does not play well with [multiprocessing](https://docs.python.org/3.6/library/multiprocessing.html). The following simple example illustrates the error.

```
# bug_check.py
import multiprocessing
import chainer as ch
import numpy as np

def worker_good(a):
    t = np.array([1, 0, 2, 1], np.float32)
    t_Var = ch.Variable(t)
    out = ch.functions.cast(t_Var, np.float64)
    return a*out

def worker_bad(a):
    t = np.array([1, 0, 2, 1], np.int32)
    t_Var = ch.Variable(t)
    out = ch.functions.cast(t_Var, np.int64)
    return a*out

if __name__ == "__main__":
    
    # Put all processors to work (at an upper limit).
    cpu_count = multiprocessing.cpu_count()
    mypool = multiprocessing.Pool(cpu_count)

    # Pass the "worker" the name of the algorithm to run.
    myiterable = [0.01, 0.5, 1.0, 10., 100.]
    outputs = mypool.map(func=worker_bad, iterable=myiterable)

    # Memory management.
    mypool.close() # important for stopping memory leaks.
    mypool.join() # wait for all workers to exit.

    for out in outputs:
        print("Output =", out)
```

On Python 3.6 running `python bug_check.py`, we get the following error

```
Traceback (most recent call last):
  File ".../python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File ".../python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File ".../python3.6/multiprocessing/pool.py", line 463, in _handle_results
    task = get()
  File ".../python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 1 required positional argument: 'actual'
```

Going through the Chainer source, utils/type_check.py imports `threading` and in particular uses `threading.local`, for which no analogue exists in `multiprocessing`. I haven't looked at the multiprocessing source and so I don't know exactly what the source of the error is.

This issue pops up all over the place, for example many loss functions which have `check_type_forward` methods also run into the same error. The `multiprocessing` module is very useful for parallelizing over different learning algorithm parameter settings (with a common data set). **Would it be feasible to modify Chainer's type checks to behave better in a multi-subprocess setting?**

**Comment by kmaehashi** [comment]
This issue seems unrelated to the multiprocessing.

> out = ch.functions.cast(t_Var, np.int64)

This line is not valid (`F.cast` does not support casting to integers).

**Comment by feedbackward** [comment]
Thanks very much. I was running into issues with `F.mean_squared_error`, `F.softmax_cross_entropy`, and `F.log_softmax`, though it appears that this was all due to type issues. The former was due to nagging float64's it seems, and the latter two due to uint8 labels, which should have been int8.

I'm quite certain this issue can be closed; I will re-try all my experiments tomorrow in a multiproc setting with tighter type controls added.

**Comment by kmaehashi** [comment]
Ok. I'd recommend you to first try running the code without `multiprocessing`.
For type issues, see here for the meaning of the error message: https://docs.chainer.org/en/stable/tips.html#how-do-i-fix-invalidtype-error
