### ISSUE TITLE
`Chain.children` not returns its children in registered order

### ISSUE THREAD

**Issue by nai62** [chainer/chainer#5293]
## Version
chainer==5.0.0b4

## Problem

In the documentation of `chainer.Chain`, `children` is explained as follows:
```
    The child link is accessible via :meth:`children`
    generator, which returns a generator running through the children in
    registered order.
```

However, `Chain.children` returns its children sorted by their names.

```
    def children(self):
        d = self.__dict__
        for name in sorted(self._children):
            yield d[name]
```

## Cause
I think the documentation is wrong.

**Comment by fiarabbit** [comment]
I confirmed that this phenomenon is from chainer==v5.0.0b4.

```check.py
import chainer
import chainer.links as L

print(chainer.__version__)


class Model(chainer.Chain):
    def __init__(self):
        super(Model, self).__init__()
        with self.init_scope():
            self.a3 = L.Linear(1, 1)
            self.a1 = L.Linear(1, 1)
            self.a2 = L.Linear(1, 1)


model = Model()
for link in model.children():
    print(link.name)

```

```b4.py
5.0.0b4
a1
a2
a3
```

```b3.py
5.0.0b3
a3
a1
a2
```

**Comment by kmaehashi** [comment]
Thanks for reporting. As you suggested, we should update the docs.

It seems we failed to remove the sentence "in registered order" in #2657.
In and after Chainer v2, we are using `set` to keep children, which does not guarantee the order.
