### ISSUE TITLE
[suggestion] Name consistency in chainer.training.extensions

### ISSUE THREAD

**Issue by crcrpar** [chainer/chainer#5295]
I really enjoy using `Trainer` and its `extensions`.
However, I'm confused with different argument names representing a file name.

So how about unifying the argument name if there isn't any philosophy?

- snapshot: filename
- snapshot_object: filename
- LogReport: log_name
- PlotReport: file_name
- dump_graph: out_name
- VariableStatisticsPlot: file_name

**Comment by kmaehashi** [comment]
I think it's better to follow the naming convention recommended in PEP 8, i.e., `file_name`, but I'd like to hear opinions from other team members before actually fixing it.

Also note that:

* Just renaming it is not enough to keep backward compatibility.
* LogReport: `log_name` is a directory name.

**Comment by crcrpar** [comment]
Appreciate your response and glad to hear your opinion and know about the back-compat. 😄 

I also like `file_name`.

> LogReport: log_name is a directory name.

Really? I think `log_name` is a file name or a file name format in my experience and below snippets.

https://github.com/chainer/chainer/blob/a9982a8b426dd07eb1ec4e7695a7bc546ecc6063/chainer/training/extensions/log_report.py#L50-L54

https://github.com/chainer/chainer/blob/a9982a8b426dd07eb1ec4e7695a7bc546ecc6063/chainer/training/extensions/log_report.py#L96-L105

**Comment by kmaehashi** [comment]
Ah, you're true, I confused it with `Trainer(out='dir')`.

**Comment by kmaehashi** [comment]
@crcrpar We discussed in the team and concluded that `filename` is the better choice here as it is frequently used in Python standard library than `file_name`. Do you have interest in making a PR?
To keep backward compatibility, the code should be fixed as follows:

1. Rename `file_name` to `filename` in method argument.
2. Add `**kwargs` to the method.
3. Extract the old argument `file_name` from `kwargs`.
4. Rewrite code to use `filename`.  If `filename` is not specified but `file_name` is specified, use it.
5. Update docs of `filename` argument to say that:
    * `file_name` can be specified for backward compatibility but is now recommended to use new argument `filename`.
    * If `filename` and `file_name` are specified, `file_name` will be ignored.

**Comment by crcrpar** [comment]
Sure, I'll get into this.

**Comment by crcrpar** [comment]
I faced some questions.

1. cupy.percentile in variable-statistics-plot
https://github.com/chainer/chainer/blob/79c22ab5dafaecfb273d4590230dbac01e873074/chainer/training/extensions/variable_statistics_plot.py#L112-L116

Since it seems cupy has percentile function, can I use it here?
https://github.com/cupy/cupy/commit/5dd6a55b0642d4a8c8b153bb4b35ae7a322b2e73

2. rendering images in dump_graph
Should I access this also?
Could you tell me the priority of this?
https://github.com/chainer/chainer/blob/79c22ab5dafaecfb273d4590230dbac01e873074/chainer/training/extensions/computational_graph.py#L90
