### ISSUE TITLE
BatchNormalization: no error on wrong shape or data type of the input

### ISSUE THREAD

**Issue by BloodyD** [chainer/chainer#5355]
If the batch normalization layer uses cuDNN and either the input dimension does not match or the dtype of the input data is not the right one, no error is raised, BUT the outputs are `inf` or `nan`. If one executes the code on the CPU (set `GPU` parameter to -1) or you set `self.use_cudnn = False` manually in line 84 in chainer.functions.batch_normalization, then the error (`ValueError: Broadcasting failed` or `TypeError: Type is mismatched [...]`) is displayed. 

In my case it was also even worse: the data on the GPU was altered and no error was rised there as well. My program crashed, since the data was used as indeces and they were pointing outside the array. Unfortunately, I cannot reproduce my scenario, but I think it would be a nice to have some checks whether the shape and data type are correct.

Runtime Info:
```
Chainer: 4.2.0
NumPy: 1.14.3
CuPy:
  CuPy Version          : 4.0.0
  CUDA Build Version    : 9000
  CUDA Driver Version   : 9010
  CUDA Runtime Version  : 9000
  cuDNN Build Version   : 7102
  cuDNN Version         : 7102
  NCCL Build Version    : 1000
```
Code to reproduce:
```python
import chainer
import chainer.links as L
import numpy as np

######## PARAMS ######## 
GPU = 0
INPUT_TYPE = np.float32
INPUT_DIMS = 1024 # or 512 to make it work
BN_DIMS = 512
########################

class Model(chainer.Chain):
	def __init__(self):
		super(Model, self).__init__()
		with self.init_scope():
			self.bn = L.BatchNormalization(BN_DIMS)

	def __call__(self, X):
		return self.bn(X)

# std=2, mean=1
data = np.random.randn(16, INPUT_DIMS) * 2 + 1

model = Model()
var = chainer.Variable(data.astype(INPUT_DTYPE))


if GPU >= 0:
	var.to_gpu(GPU)
	model.to_gpu(GPU)
	chainer.cuda.get_device(GPU).use()

out = model(var)

print("Input  Mean: {: 8.4f} Std: {: 8.4f}".format(
	float(var.array.mean(axis=1).mean()),
	float(var.array.std(axis=1).mean()))
)
print("Output Mean: {: 8.4f} Std: {: 8.4f}".format(
	float(out.array.mean(axis=1).mean()),
	float(out.array.std(axis=1).mean()))
)
```

**Comment by crcrpar** [comment]
Hi, @BloodyD 

1.
Could you check the version of installed cupy?
I tried to run your snippet (thank you for sharing), but I cannot install cupy==4.0.0 because it is incompatible with chainer==4.2.0.

2.
> some checks whether the shape and data type are correct.

From v5, Chainer checks shapes and dtypes like this.
https://github.com/chainer/chainer/blob/3391a4ad4952134f463d811dfd0a2df58d9ec093/chainer/functions/normalization/batch_normalization.py#L62-L84

**Comment by BloodyD** [comment]
Hi @crcrpar,

thank you for the fast reply! Sorry, that I'm answering so late.

1. My installed cupy version is really 4.0.0 and it works quite fine with chainer 4.2.0. Are there some known issues, that may cause some problems?

2. The same code is actually already present in chainer 4.2.0. This made me curious. And of course the main source of errors sits right behind the monitor >.< In my environment I have disabled type checks to speed up some things:
```bash
export CHAINER_TYPE_CHECK=0
```
After removing this chainer behaves correctly! I'm closing the issue, since it was my own fault.
