### ISSUE TITLE
MobileNet inference with CPU is slow in 5.0.0rc1

### ISSUE THREAD

**Issue by nknytk** [chainer/chainer#5403]
MobileNet inference speed is about 10x slower in 5.0.0rc1 on CPU.  
Could you fix it?

### Environment

* OS: Ubuntu 16.04
* CPU: Core i5-7Y54
* Python: 3.5.2
* numpy:: 1.15.2
* environment variables: `export OMP_NUM_THREADS=1`

### Test Code

```python
from time import time
import chainer
import numpy
from mobilenet import MobileNet

chainer.config.train = False
model1 = MobileNet()
model2 = chainer.links.ResNet50Layers()
dummy_img = numpy.zeros((1, 3, 224, 224), dtype=numpy.float32)

for model_name, model in (('MobileNet', model1), ('ResNet-50', model2)):
    s = time()
    for i in range(10):
        model.predict(dummy_img)
    e = time()
    print('{}: {} ms/image'.format(model_name, (e - s) * 100))
```

[MobileNet chainer implementation](https://github.com/nknytk/ml-study/blob/master/image-classification/mobilenet.py)

### Test Result

chainer==4.5.0
```
MobileNet: 91.46909713745117 ms/image
ResNet-50: 3866.769576072693 ms/image
```

chainer==5.0.0rc1
```
MobileNet: 854.5786619186401 ms/image
ResNet-50: 3936.075806617737 ms/image
```

**Comment by nknytk** [comment]
5.0.0rc1's  `chainer.links.DepthwiseConvolution2D` is slow when `ksize=1` or `stride > 1`.

test code
```python
from time import time
import chainer
from chainer.links import DepthwiseConvolution2D
import numpy

chainer.config.train = False
dummy_img = numpy.zeros((1, 100, 100, 100), dtype=numpy.float32)
test_links = [
    ('ksize=1, stride=1', DepthwiseConvolution2D(100, 1, ksize=1, stride=1, pad=0)),
    ('ksize=1, stride=2', DepthwiseConvolution2D(100, 1, ksize=1, stride=2, pad=0)),
    ('ksize=3, stride=1', DepthwiseConvolution2D(100, 1, ksize=3, stride=1, pad=1)),
    ('ksize=3, stride=2', DepthwiseConvolution2D(100, 1, ksize=3, stride=2, pad=1)),
    ('ksize=5, stride=1', DepthwiseConvolution2D(100, 1, ksize=5, stride=1, pad=2)),
    ('ksize=5, stride=3', DepthwiseConvolution2D(100, 1, ksize=5, stride=3, pad=2)),
]

for link_name, link in test_links:
    s = time()
    for i in range(10):
        link(dummy_img)
    e = time()
    print(link_name, '{:.3f}'.format(e - s))
``` 

test result

| ksize | stride | elapsed sec(chainer==4.5.0) | elapsed sec(chainer==5.0.0rc1) |
| --- | --- | --- | --- |
| 1 | 1 | 0.038 | 0.140 |
| 1 | 2 | 0.075 | 0.126 |
| 3 | 1 | 0.301 | 0.226 |
| 3 | 2 | 0.096 | 0.179 |
| 5 | 1 | 0.611 | 0.297 |
| 5 | 3 | 0.115 | 0.194 |

**Comment by nknytk** [comment]
feature map < (110, 110) : 4.5.0 is faster
feature map > (110, 110) : 5.0.0rc1 is faster

test code
```python
from time import time
import chainer
from chainer.links import DepthwiseConvolution2D
import numpy

chainer.config.train = False
conv = DepthwiseConvolution2D(100, 1, ksize=3, stride=1, pad=1)

for img_size in range(10, 210, 10):
    dummy_img = numpy.zeros((1, 100, img_size, img_size), dtype=numpy.float32)
    s = time()
    for j in range(1000):
        conv(dummy_img)
    e = time()
    print('size={} {:.3f}'.format(img_size, e - s))
```
result
![](https://user-images.githubusercontent.com/3682331/46255352-f22ed100-c4d6-11e8-9e6e-eec96c1f778a.png)

**Comment by kmaehashi** [comment]
Thank you for the detailed report! In Chainer v5.0.0b3, we rewrote DepthwiseConvolution2D with Convolution2D (see #5046), so your usecase may be affected by this change.
Is use of iDeep acceptable for you? https://docs.chainer.org/en/latest/tips.html#how-do-i-accelerate-my-model-using-chainer-backend-for-intel-architecture

**Comment by nknytk** [comment]
In my environment, iDeep certainly accelerated CNNs but 5.0.0rc1+iDeep is still 3x slower than 4.5.0 without iDeep on MobileNet.

MobileNet inference speed (ms/image)

| 4.5.0 | 4.5.0 + iDeep | 5.0.0rc1 | 5.0.0rc1 + iDeep |
| --- | --- | --- | --- |
| 91.5 | 74.1 | 854.6 | 313.6 |

4.5.0 is fastest in small feature map
![fmp](https://user-images.githubusercontent.com/3682331/46296013-58e5e480-c5d4-11e8-9e1e-1640d3a46966.png)

**Comment by nknytk** [comment]
If you include this change into stable releases, can you keep previous version of DepthwiseConvolution2D in another name?  
This change will kill [My Raspberry Pi work](https://nknytk.github.io/presentations/20180929_chainer_mokumoku3/slide.html).

**Comment by beam2d** [comment]
I made a patch #5459. Could you try it?

**Comment by nknytk** [comment]
I re-tested from the begining because I upgraded my environment to Ubuntu 18.04 + Python 3.6.6.
Your patch almost recovered the inference speed of MobileNet.

MobileNet inference speed

| chainer version | inference speed (msec/image) |
| --- | --- |
| 4.5.0 | 85.7 |
| 4.5.0 + iDeep | 71.3 |
| 5.0.0rc1 | 680.7 |
| 5.0.0rc1 + iDeep | 288.0 |
| 5.0.0rc1 + patch | 97.1 |
| 5.0.0rc1 + patch + iDeep | 73.3 |

Patched code has similar behavior in large range of feature map sizes. 
![sc](https://user-images.githubusercontent.com/3682331/46861910-b5f05e80-ce4e-11e8-8ab2-80cd5b1746eb.png)
When feature map size is (80, 80) ~ (100, 100) patched code is still a bit slower, but I think it is not critical.
![sc2](https://user-images.githubusercontent.com/3682331/46862620-3f546080-ce50-11e8-8ac9-a36b0f91311b.png)
