### ISSUE TITLE
Missing documentation of "Assertion and Testing" features

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#5408]
Many of functions in this page are missing:

https://docs.chainer.org/en/v5.0.0rc1/reference/check.html

**Comment by niboshi** [comment]
Also: `chainer.gradient_check.check_double_backward` is missing.

**Comment by knorth55** [comment]
This issue does not notice that all links in this page are correctly generated when you build the doc pages on your laptop as an image below.
I reported it in #5804.
Anyway, I have no idea how to fix it.
![chainer-doc-local](https://user-images.githubusercontent.com/9300063/49648873-c5fd7680-fa6a-11e8-906c-103a4001f5cd.png)

**Comment by beam2d** [comment]
@mitmul will work on this issue.
