### ISSUE TITLE
Link cannot be transferred between GPUs

### ISSUE THREAD

**Issue by chenzhekl** [chainer/chainer#5412]
* Chainer version 4.5.0

Per the code, once a link is already on GPU, no action will be taken when calling `to_gpu()` even if the target device is different.

https://github.com/chainer/chainer/blob/da218995678a106f06f150bdb73caeeee764e394/chainer/link.py#L404

**Comment by beam2d** [comment]
This is the current specification of `Link.to_gpu`, but there is an attempt to change that: https://github.com/chainer/chainer/pull/4139.
