### ISSUE TITLE
Support scalars in functions

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#5414]
Currently `FunctionNode.apply()` does not support scalars.

```
>>> F.maximum(array, 0)
...
TypeError: numpy.ndarray or cuda.ndarray are expected.
Actual: <class 'int'>
```

It may be more convenient if it's supported.

**Comment by toslunar** [comment]
See also #5075 (accidentally merged and then reverted).

**Comment by niboshi** [comment]
Is there new PR?

**Comment by toslunar** [comment]
No.

**Comment by niboshi** [comment]
Do you mean #5075 has been discarded?

**Comment by toslunar** [comment]
I'm interested in the issue, while I no longer endorse `as_variable(scalar)`.
