### ISSUE TITLE
[Suggestion] Numpy version configuration

### ISSUE THREAD

**Issue by crcrpar** [chainer/chainer#5429]
https://github.com/chainer/chainer/blob/ebbc6f5647ac0b9178ec83e72045ca6c8474093f/setup.py#L29
I think this line contradicts [Installation - requirements](https://docs.chainer.org/en/stable/install.html#requirements) because pip automatically install numpy==1.15 now.

This issue is the motivation behind #5413.

**Comment by kmaehashi** [comment]
Thanks for the suggestion! As NumPy 1.15 support is almost coming, and currently there's no known issues specific to NumPy 1.15 so far, we decided not to add this restriction for flexibility.
