### ISSUE TITLE
Fix confusing error of  `with x.device` when x is 0-sized array

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#543]
Related to #528 

Some of possible solutions will be:
- `x.device` returns `DummyDevice` (or any object which has `__enter__` and `__exit__`).
- Show warning message when the interpreter encounter this usage (I do not have any clever idea for now).

**Comment by unnonouno** [comment]
I think, it is about specification of `device` attribute. I mean, "`device` is a `Device` object or `None`". So, a user needs to check if it's `None` when he uses this attribute. If he wants to use `with` statement, we recommend `get_device` function that always returns `Device` object.

**Comment by delta2323** [comment]
I agree with you in that we should recommend user to use `get_device` method in `with` statement. What I am concerning is the situation in which user mistakenly use `x.device` when the size of `x` is 0 and encounter the `AttributionError`. Users cannot figure out the right solution to use `get_device` .
