### ISSUE TITLE
gaussian_nll takes negative number

### ISSUE THREAD

**Issue by npkk** [chainer/chainer#5440]
* Conditions
I tried using gaussian_nll for variational autoencoder.
but I found that this function returns negative number.
this contradicts to likelihood function returns negative number.
what does it mean? is it a bug?

* Code to reproduce
```
from chainer.functions.loss.vae import gaussian_nll
import numpy as np

x = np.array([[ 0.7447, -0.2472, -0.1422,  1.4283, -0.5493],
              [-1.0729,  1.7256, -0.4255, -0.2032,  0.1770],
              [ 1.0486, -0.0203, -0.6579,  1.0881,  0.5992]],dtype='float32')
mean = np.array([[ 0.7442, -0.2477, -0.1422,  1.4270, -0.5493],
                 [-1.0564,  1.6968, -0.4255, -0.2022,  0.1770],
                 [ 1.0484, -0.0214, -0.6579,  1.0880,  0.5992]],dtype='float32')
ln_var = np.array([[-2.9883, -1.4716, -1.8097, -1.5125, -3.2140],
                   [-0.1693, -1.2989, -0.4811, -1.9045,  0.3202],
                   [-3.4957, -2.5788, -3.4621, -2.3956, -3.1281]],dtype='float32')

print(gaussian_nll(x, mean, ln_var))

```
** Output
```
variable(-1.009222)
```

**Comment by crcrpar** [comment]
`nll` is an abbreviation of Negative Log-Likelihood.

**Comment by npkk** [comment]
Thanks for replying.
I fixed miswriting of issue.
Negative Log-Likelihood function should take positive number.

**Comment by tmagara** [comment]
It's a continuous probability distribution.
So probability density can go above 1, which makes -log(P) < 0.
This is just OK, no bugs here.

**Comment by npkk** [comment]
Thanks for answer．
I was misunderstanding.
