### ISSUE TITLE
A TypeError while Running CNN on GPU

### ISSUE THREAD

**Issue by psychopa4** [chainer/chainer#5441]
I'm trying to build a CNN, and the input variable is <class 'cupy.core.core.ndarray'>, while the kernel and bias of the convolution layer are initialized as <class 'numpy.ndarray'>, who are supposed to be <class 'cupy.core.core.ndarray'> on GPU instead.
I use `generator.to_gpu(args.gpu)` to run the model on GPU, but it seems not working.
I also tried
 `updater = chainer.training.updaters.StandardUpdater(iterator, optimizer_generator, device=args.gpu)`
to run the model on GPU, but it came with the same mistake.

* Conditions

  - Chainer version 4.5.0
  - CuPy version 4.5.0
  - OS/Platform Ubantu 16.04
  - CUDA/cuDNN version 8.0.61/5.1.10
  - etc.
* Code to reproduce

```
class MODEL(chainer.Chain):

    def __init__(self):
        super(MODEL, self).__init__()
        self.first=chainer.links.Convolution2D(5, 64, ksize=5, stride=1, pad=2)

    def __call__(self, x: chainer.Variable, test=False):
        x0 = self.first(x)
        return x0
```

* Error messages, stack traces, or logs
```
Traceback (most recent call last):
  File "main.py", line 205, in <module>
    train()
  File "main.py", line 138, in train
    sr = generator(lr)
  File "main.py", line 84, in __call__
    x0 = self.first(x)
  File "/root/anaconda3/envs/tf/lib/python3.6/site-packages/chainer/links/connection/convolution_2d.py", line 175, in __call__
    groups=self.groups)
  File "/root/anaconda3/envs/tf/lib/python3.6/site-packages/chainer/functions/connection/convolution_2d.py", line 582, in convolution_2d
    y, = fnode.apply(args)
  File "/root/anaconda3/envs/tf/lib/python3.6/site-packages/chainer/function_node.py", line 235, in apply
    ', '.join(str(type(x)) for x in in_data)))
TypeError: incompatible array types are mixed in the forward input (Convolution2DFunction).
Actual: <class 'cupy.core.core.ndarray'>, <class 'numpy.ndarray'>, <class 'numpy.ndarray'>
```

**Comment by schliffen** [comment]
I have the same problem in using chainer with GPU

**Comment by ankahira** [comment]
I am having the same problem.

**Comment by Tony-wu0901** [comment]
I have the same problem in using chainer FCN model to GPU.(model.to_gpu())
