### ISSUE TITLE
logging policy

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#5451]
Related: #5418

Chainer currently does not have a unified policy for logging.

**Comment by kmaehashi** [comment]
Currently `print` is used in graph optimization feature.
We need to think about this topic at the time the feature become stable (not experimental).

**Comment by kuenishi** [comment]
Regarding #5418 is this only about tests? In some cases at ChainerMN, Chainer families and some production deployments we may need logging and we did have a small discussion, about a year ago IIRC.

**Comment by niboshi** [comment]
Sorry I should have written in #5418 but test is no longer a problem because we concluded that it's ok to generate debug outputs in tests to make investigation easier.
As we can disucuss general logging scheme here, I think we should close #5418.

Btw, I'm curious how the discussion you mentioned ended up. 
IMO `logging` is the way to go because it's powerful enough and standard.
