### ISSUE TITLE
Here should be resnext50.ResNeXt50 ? 

### ISSUE THREAD

**Issue by Lynkzhang** [chainer/chainer#5467]
https://github.com/chainer/chainer/blob/fc334443a25da1a96e6eaa69346c00a582857cdb/examples/imagenet/train_imagenet_data_parallel.py#L41

Here should be resnext50.ResNeXt50 ?  And need to add import resnext50 first?

**Comment by kmaehashi** [comment]
Thanks for the feedback, you're true. Do you have interest in making a PR for this?

**Comment by Lynkzhang** [comment]
I will do that. :)

**Comment by kmaehashi** [comment]
Fixed in #5469.
