### ISSUE TITLE
Convolutional LSTM

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer#5470]
Convolutional LSTM https://arxiv.org/abs/1506.04214
(feature request from https://groups.google.com/forum/#!topic/chainer-jp/T4L_dopyZTY)

**Comment by MannyKayy** [comment]
A much needed feature. It would be nice to have a Constitutional GRU too for applications that prioritize speed.

**Comment by kmaehashi** [comment]
Please leave a comment with use-case here if you want this feature.
