### ISSUE TITLE
Should `chainer.training.Extension.finalize` be passed `Trainer` or not?

### ISSUE THREAD

**Issue by y1r** [chainer/chainer#5484]
I found a document inconsistency about `chainer.training.Extension.finalize`'s argument.

https://docs.chainer.org/en/stable/guides/extensions.html#finalizer,
> 4. Finalizer
> You can specify a function which takes a Trainer object as an argument to finalize the extension. It is called once at the end of the training loop, i.e., when run() has finished.

On the other hand, https://docs.chainer.org/en/stable/reference/generated/chainer.training.Extension.html#chainer.training.Extension.finalize,
> finalize()
> Finalizes the extension. This method is called at the end of the training loop.

Which is correct?
I think `finalize()` should be passed `Trainer` object to finalize some object which the `Extension` created on `initialize()`.

**Comment by beam2d** [comment]
We will first fix the documentation to follow the current implementation (not passing `trainer`). I also think that it is more consistent to pass `trainer` to `finalize`, so we would like to fix the design, but it would take some time to take care of the compatibility.
