### ISSUE TITLE
Orthogonal initializer dimensions error

### ISSUE THREAD

**Issue by MannyKayy** [chainer/chainer#5485]
Orthogonal Initializer throws an error whenever the first dimension is larger than the second. This could be fixed by transposing the array rather than throwing an error.

e.g. 1. ` dense = L.Linear(64,128, initialW=initializers.Orthogonal())`
![image](https://user-images.githubusercontent.com/7952854/46913383-cd7d3380-cf83-11e8-86c5-4cfe5b6d99c2.png)

e.g. 2 `initializers.generate_array(initializers.Orthogonal(), (20,10), numpy, 'f')`
![image](https://user-images.githubusercontent.com/7952854/46913407-3d8bb980-cf84-11e8-9773-3e3a3c38ac76.png)

System Info:
Chainer: 5.0.0rc1
NumPy: 1.14.2
CuPy:
  CuPy Version          : 5.0.0rc1
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 8000
  CUDA Driver Version   : 9020
  CUDA Runtime Version  : 8000
  cuDNN Build Version   : 7102
  cuDNN Version         : 7102
  NCCL Build Version    : 2213

**Comment by toslunar** [comment]
I'd like to add an optional arg to `Orthogonal`
- `mode='projection'`: the current behavior
- `mode='auto'`: @MannyKayy's proposal
- `mode='embedding'`: assert first >= second
- `mode='basis'`: assert first == second

**Comment by MannyKayy** [comment]
yep, sounds good.
