### ISSUE TITLE
Variations of LSTM

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#559]
A lot of variations of LSTMs are known.
- peep hole connection
- no forget gate
- and more...?

It is hard to make these variations with the current implementation of LSTM.

**Comment by cemoody** [comment]
For completeness, there's also MUT1, MUT2, and MUT3 that are LSTM variants: http://jmlr.org/proceedings/papers/v37/jozefowicz15.pdf

**Comment by unnonouno** [comment]
Thank you for the reference. Is this list enough?
We also need to think about the interface.

**Comment by sw005320** [comment]
Peep hole connection is used at most of LSTM implementations in speech processing (MSR CNTK, TUM currennt, Google tensorflow (LSTMCell)).
It would be great if chainer has it.

**Comment by prajdabre** [comment]
I have already implemented all of these.
Check here if interested: https://github.com/prajdabre/chainer_examples/blob/master/chainer-1.5/LSTMVariants.py
I would not mind helping add all of these to the main chainer repository. So if there is no one doing this already, let me know and I will send a pull request.

**Comment by beam2d** [comment]
We have many variants of RNN units now, so I close it. If you have one that you want but is lacking from the current Chainer, please make a new issue. Thank you!
