### ISSUE TITLE
Request for test utility to compare arrays including dtypes

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#5612]
* `chainer.testing.assert_allclose`
* `numpy.testing.assert_allclose`
* `numpy.testing.assert_array_equal`

All of the above functions succeed even if dtypes of two arrays are different.
Currently we do not have an alternative way, although we almost always want the test to fail if dtypes differ.

Issues like #5607 would not have happened if we had one.

**Comment by toslunar** [comment]
Some ideas related to the issue:
- test shapes
- adjust tolerances (see also #3668)
