### ISSUE TITLE
Support half-precision floating point on CUDA 7.5

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#562]
CUDA 7.5 supports half-precision floating point (float16). http://devblogs.nvidia.com/parallelforall/new-features-cuda-7-5/

**Comment by koki0702** [comment]
Are you planning for support half-precision floating point  in chainer?

**Comment by tapdo** [comment]
Pascal GP100 GPU or GPU102(GTX Titan X, GTX1080 Ti) support fp16 operation by HW. So now we can use this benefit. Are there any plan to support fp16 in Chainer ?

**Comment by beam2d** [comment]
Most functions now support fp16.
