### ISSUE TITLE
[chainermn] - incorrect epoch count on large batchsizes or large number of GPUs

### ISSUE THREAD

**Issue by MannyKayy** [chainer/chainer#5622]
chainermn runs/returns/prints an incorrect number of epochs when dealing with large batch sizes or a large number of GPUs. I noticed this issue with the chainermn [mnist example code](https://github.com/chainer/chainermn/blob/2bc2895f8b506a7cdc3edcfaa10cee496e5d2fbb/examples/mnist/train_mnist.py). The larger the batchsize and the more GPUs used, the lower the number of completed epochs.

**Batch size**: 2048
**GPU Count**: 16
`mpiexec -x LD_LIBRARY_PATH -x LD_RUN_PATH -x PATH --hostfile ~/hostfile_b -np 16 python ~/chainermn/examples/mnist/train_mnist.py --gpu -b 2048 -e 20 --communicator pure_nccl`

![image](https://user-images.githubusercontent.com/7952854/47966057-fdc96680-e045-11e8-8b34-b7abe570b45a.png)

**Batch size**: 2048
**GPU Count**: 32
`mpiexec -x LD_LIBRARY_PATH -x LD_RUN_PATH -x PATH --hostfile ~/hostfile_b -np 32 python ~/chainermn/examples/mnist/train_mnist.py --gpu -b 2048 -e 20 --communicator pure_nccl`

![image](https://user-images.githubusercontent.com/7952854/47966443-44b95b00-e04a-11e8-86ac-caaae89fa0e1.png)

**Batch size**: 4096
**GPU Count**: 16
`mpiexec -x LD_LIBRARY_PATH -x LD_RUN_PATH -x PATH --hostfile ~/hostfile_b -np 16 python ~/chainermn/examples/mnist/train_mnist.py --gpu -b 4096 -e 20 --communicator pure_nccl`

![image](https://user-images.githubusercontent.com/7952854/47966002-74199900-e045-11e8-955c-7bd58e6f70c2.png)

**Batch size**: 8192
**GPU Count**: 16
`mpiexec -x LD_LIBRARY_PATH -x LD_RUN_PATH -x PATH --hostfile ~/hostfile_b -np 16 python ~/chainermn/examples/mnist/train_mnist.py --gpu -b 8192 -e 20 --communicator pure_nccl`

![image](https://user-images.githubusercontent.com/7952854/47966072-31a48c00-e046-11e8-8dab-82835af2c666.png)

**Batch size**: 16384
**GPU Count**: 16
`mpiexec -x LD_LIBRARY_PATH -x LD_RUN_PATH -x PATH --hostfile ~/hostfile_b -np 16 python ~/chainermn/examples/mnist/train_mnist.py --gpu -b 16384 -e 20 --communicator pure_nccl`

![image](https://user-images.githubusercontent.com/7952854/47966106-8c3de800-e046-11e8-94d0-5d76abc31fcb.png)

Increasing the number of GPUs make the problem worse:
**Batch size**: 16384
**GPU Count**:  28
`mpiexec -x LD_LIBRARY_PATH -x LD_RUN_PATH -x PATH --hostfile ~/hostfile_b -np 28 python ~/chainermn/examples/mnist/train_mnist.py --gpu -b 16384 -e 20 --communicator pure_nccl`
![image](https://user-images.githubusercontent.com/7952854/47966186-944a5780-e047-11e8-80d7-10f58fe0aa05.png)

Decreasing the GPU count helps with this problem..
**Batch size**: 16384
**GPU Count**:  4
`mpiexec -x LD_LIBRARY_PATH -x LD_RUN_PATH -x PATH --hostfile ~/hostfile_b -np 4 python ~/chainermn/examples/mnist/train_mnist.py --gpu -b 16384 -e 20 --communicator pure_nccl`
![image](https://user-images.githubusercontent.com/7952854/47966229-0cb11880-e048-11e8-9468-e93fe74e6876.png)

* System Info: *
 `python -c 'import chainer; chainer.print_runtime_info()'

![image](https://user-images.githubusercontent.com/7952854/47966289-9c56c700-e048-11e8-8b16-120204eed301.png)

**Comment by kuenishi** [comment]
Please note that actual batch size in data parallelism is (number of nodes) * (batch size in each node), which is the case the MNIST example, `--batchsize` is actually the batch size in each node. Also, the training data size of MNIST dataset is 60000. For example, `-b 16384` and `-np 18` means actually its batch size is 458752. That is more than 7 times of MNIST dataset and a single iteration includes 3 epochs. For the very now Chainer assumes batchsize is much smaller than the size of dataset, and I believe that is the most case for SGD training, which can be improved in future.

**Comment by MannyKayy** [comment]
I see, alright. Thanks for clearing that up.
