### ISSUE TITLE
Where is chainermn.iterators.create_synchronized_iterator

### ISSUE THREAD

**Issue by Aixile** [chainer/chainer#5628]
[https://docs.chainer.org/en/stable/chainermn/reference/index.html](https://docs.chainer.org/en/stable/chainermn/reference/index.html), 

In the `chainermn.iterators.create_multi_node_iterator` section, it says

> Since this iterator shares batches through network in each iteration, communication might be large. If you train your model-parallel network on extremely large dataset, you can also consider to use chainermn.iterators.create_synchronized_iterator.

But I cannot find `chainermn.iterators.create_synchronized_iterator` either in the document or the repo.

**Comment by toslunar** [comment]
By the way, the links should be ``` `chainer.foo` ``` (not ``` ``chainer.foo`` ```).

**Comment by shu65** [comment]
That is implemented in this PR.
https://github.com/chainer/chainer/pull/5396

It is a document mistake.

**Comment by keisukefukuda** [comment]
The fix is planned. I'm removing the stale label.

**Comment by kuenishi** [comment]
Fixed by #6345
