### ISSUE TITLE
Support Hessian-free optimization

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#563]
To support Hessian-free optimization, maybe we need to implement additional methods for each `Function`.

**Comment by toslunar** [comment]
Chainer supports double-backprop from v3.

**Comment by unnonouno** [comment]
I tried to implement it https://github.com/unnonouno/chainer/blob/hessia-free/chainer/optimizers/hessian_free.py But its convergence is slow (bug?)

**Comment by MannyKayy** [comment]
bump
