### ISSUE TITLE
Remove unnecessary module dependencies that come from backward-compatibility aliases

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#5645]
https://chainer.slack.com/archives/C5P26TUR1/p1541664684018900
>It seems backward-compatibility aliases can sometimes be obstacles.
For example, currently there's `training.trigger.IntervalTrigger` which aliases `training.triggers.interval_trigger.IntervalTrigger`.
That introduces dependency from `trigger` to `triggers`.
Now I'm considering adding a decorator `trigger.iteration_aware` (for #5585 if you're curious) and using it from concrete triggers defined in `triggers`.
I think this design does not seem unnatural but actually interfered by the above dependency.
One possible workaround is to make such aliases (which should not be used by chainer) only after importing everything,  in `chainer/__init__.py`.

### Proposed solutions
1. To make aliases from source (`triggers`) instead of destination (`trigger`)

``` py
# at the end of `triggers/interval_trigger.py`
from chainer.training import trigger 
trigger.IntervalTrigger = IntervalTrigger
```

2.  To register lazy alias from source (actual alises are created later in `chainer/__init__.py`)
``` py
# at the beginning of `triggers/interval_trigger.py`
chainer._register_alias(__name__, 'training.trigger.IntervalTrigger')
```

3.  To register lazy alias from destination (ditto.)
``` py
# at the beginning of `trigger.py`
chainer._register_alias(__name__, 'training.triggers.interval_trigger.IntervalTrigger')
```

4. To directly create aliases in `chainer/__init__.py` after importing everything
```py
chainer.training.trigger.IntervalTrigger = \
    chainer.training.triggers.interval_trigger.IntervalTrigger
```

**Comment by beam2d** [comment]
I like the option 1 (making aliases from source instead of destination) because it is written near the definition so it is easy to find the alias definition from source code, and no trick is used so it is straight-forward to understand the behavior.

**Comment by niboshi** [comment]
We decided to take 1. after discussion.

**Comment by niboshi** [comment]
PTAL

**Comment by niboshi** [comment]
Turned out that the option 1. does not always work.
In #5696, applying the new policy for the alias `chainer.function.FunctionHook` caused a new cyclic dependency (`chainer.function_hook` -> `chainer.function` -> `chainer.function_node` -> `chainer.function_hook`).

Instead of choosing between 1. and old-style policy in ad-hoc manner, I'd suggest sticking with one of 2. 3. and 4.

**Comment by niboshi** [comment]
After another discussion, we have chosen option 4.
