### ISSUE TITLE
Add einops to the list of projects using chainer

### ISSUE THREAD

**Issue by arogozhnikov** [chainer/chainer#5668]
`einops` is a new way to manipulate tensors, flexible and powerful operations for readable and reliable code (developed right for deep learning). 

<img src="http://arogozhnikov.github.io/images/einops/einops_video.gif" alt="einops package examples" width='600' />

Among its backends it supports `chainer` (full support), so could we add `einops` it to the list of projects using chainer?

Link to the project: http://github.com/arogozhnikov/einops

It is great to say that chainer version 5 worked with einops like a charm, so thanks for writing great code!

Is it appropriate to post news about this package at your slack channel?

**Comment by Crissman** [comment]
We don't have a list of Chainer projects right now. We'll add Einops when we make one!

Please feel free to post in our slack Channel.

Thanks!

**Comment by kmaehashi** [comment]
Thank you for supporting Chainer in your framework! Currently we have list of research projects using Chainer https://github.com/chainer/chainer/wiki/Research-projects-using-Chainer, but there's no list for products that supports Chainer. Let me close this issue for now; we'll list einops once we created the list.
