### ISSUE TITLE
why here is comm.rank ?

### ISSUE THREAD

**Issue by Lynkzhang** [chainer/chainer#5674]
In this line, 
https://github.com/chainer/chainer/blob/d3da91cbd8c991854beda159dd465fcac9aa10a7/examples/chainermn/mnist/train_mnist_dual_parallel.py#L124

why use ```comm.rank == 1``` rather than use ```data_axis == 1```
Although in this case these two all stand for the same process,  I think ```data_axis == 1``` is easier to understand.

**Comment by shu65** [comment]
Thank you! 
I agree. I will fix it.
