### ISSUE TITLE
Question about im2col implementation

### ISSUE THREAD

**Issue by kaleidoscopical** [chainer/chainer#5695]
https://github.com/chainer/chainer/blob/e4a0b8fca2fdd893c491de79f0b66129d0d15824/chainer/utils/conv.py#L77

Could anyone give me a hint about why `ph + sy - 1` is required?

**Comment by fiarabbit** [comment]
According to the [contribution guide](http://docs.chainer.org/en/stable/contribution.html), any general question is preferred to be raised at the StackOverflow with a `chainer` tag.

```
Warning

If you have a question on usages of Chainer, it is highly recommended to send a post to
StackOverflow or Chainer User Group instead of the issue tracker. The issue tracker is not a place
to share knowledge on practices. We may suggest these places and immediately close how-to
question issues.
```

In very short, this is to avoid `IndexError` at https://github.com/chainer/chainer/blob/ee0b971547de243077f3afe98bbee45db630de6a/chainer/utils/conv.py#L87

For the further inquiry, please ask it on the stackoverflow.
