### ISSUE TITLE
Feature Request: Spectral Normalization

### ISSUE THREAD

**Issue by crcrpar** [chainer/chainer#5702]
A relevant pull request is #4701.

Now that Chainer supports `LinkHook` which seems very useful to implement Spectral Normalization (SN) that normalizes links' weights before their forward computations.  

If OK, I want to work on implementing this after discussing the design.
As a side note,  my casual SN implementation is this→https://github.com/crcrpar/chainer/blob/eb50f9288b82a20028ecd4aaf4bd39e7b5379f82/chainer/link_hooks/spectral_normalization.py#L80

Miytao-san’s original implementations are https://github.com/pfnet-research/sngan_projection/tree/master/source/links and pytorch’s is https://github.com/pytorch/pytorch/blob/master/torch/nn/utils/spectral_norm.py#L9-L142.

Any comment is welcome.

**Comment by toslunar** [comment]
#5742 added SN linkhook.
