### ISSUE TITLE
"Define your own function" is written for Function and not FunctionNode

### ISSUE THREAD

**Issue by hvy** [chainer/chainer#5707]
The user guide for how to write his/her own function uses `Function`s and not `FunctionNode`s. The latter is the preferred way of implementing a function in Chainer at the moment and the guide should be updated accordingly. This is the page https://docs.chainer.org/en/latest/guides/functions.html

**Comment by kmaehashi** [comment]
Ah, yes, I should complete the WIP PR #4986 ...

**Comment by hvy** [comment]
Although this issue was closed by a bot, it's actually fixed by #4986 (and should have been closed sooner).
