### ISSUE TITLE
Improve performance of optimization step

### ISSUE THREAD

**Issue by shu65** [chainer/chainer#5731]
When using FP16 mode, one of CPU bottlenecks is an optimization step. 
The main reason is that there are many calls of CUDA kernel.

As a method to solve this, I think that it is good to concatenate the array of parameters, then to perform optimization with one CUDA kernel.
What do you think?

**Comment by LennMars** [comment]
At first I will test performance of some possible solutions to reducing the number of CUDA kernels.
