### ISSUE TITLE
When use multiprocessing can't backpropagation

### ISSUE THREAD

**Issue by qby324** [chainer/chainer#5749]
It seems that Chainer does not play well with multiprocessing. Just a very simple example that when I use multiprocessing and can't backprop.

```
import multiprocessing
import numpy as np
import chainer.links as L

l=L.Linear(1,1)
a=ar([[1]],dtype=np.float32)
l.cleargrads()
pool=multiprocessing.Pool(2)
y=pool.apply_async(l,[a,]).get()
y.backward()
print(str(l.W.grad))

```
The result shows that l.W doesn't get the backpropagation result of output.

**Comment by fiarabbit** [comment]
I succeeded to reproduce the situation.

```reproduction.py
import multiprocessing
import numpy as np

from chainer import links as L

l = L.Linear(1, 1, nobias=True, initialW=np.array([[1]]))
a = np.array([[1]], dtype=np.float32)
l.cleargrads()
pool = multiprocessing.Pool(1)
y_pool = pool.apply(l, (a, ))
y_direct = l(a)
print("creator_node: ")
print("y_pool: {}".format(y_pool.creator_node))
print("y_direct: {}".format(y_direct.creator_node))
print("")

y_pool.backward()
print("l.W.grad:")
print("y_pool.backward(): {}".format(l.W.grad))

y_direct.backward()
print("y_direct.backward(): {}".format(l.W.grad))
```

```output.py
creator_node: 
y_pool: None
y_direct: <chainer.functions.connection.linear.LinearFunction object at 0x2b801ec41978>

l.W.grad:
y_pool.backward(): None
y_direct.backward(): [[1.]]
```

As you can see, when using `Pool`, the `y.creator_node` is None.

**Comment by qby324** [comment]
> I succeeded to reproduce the situation.
> 
> ```python
> import multiprocessing
> import numpy as np
> 
> from chainer import links as L
> 
> l = L.Linear(1, 1, nobias=True, initialW=np.array([[1]]))
> a = np.array([[1]], dtype=np.float32)
> l.cleargrads()
> pool = multiprocessing.Pool(1)
> y_pool = pool.apply(l, (a, ))
> y_direct = l(a)
> print("creator_node: ")
> print("y_pool: {}".format(y_pool.creator_node))
> print("y_direct: {}".format(y_direct.creator_node))
> print("")
> 
> y_pool.backward()
> print("l.W.grad:")
> print("y_pool.backward(): {}".format(l.W.grad))
> 
> y_direct.backward()
> print("y_direct.backward(): {}".format(l.W.grad))
> ```
> 
> ```python
> creator_node: 
> y_pool: None
> y_direct: <chainer.functions.connection.linear.LinearFunction object at 0x2b801ec41978>
> 
> l.W.grad:
> y_pool.backward(): None
> y_direct.backward(): [[1.]]
> ```
> 
> As you can see, when using `Pool`, the `y.creator_node` is None.

Yes, the creator and creator node is none when I use Pool. I wonder how to use multiprocessing in chainer.

**Comment by fiarabbit** [comment]
@qby324 You can refer [Data-parallel Computation on Multiple GPUs with Trainer](https://docs.chainer.org/en/stable/guides/gpu.html#data-parallel-computation-on-multiple-gpus-with-trainer) or [ChainerMN documentation](https://chainermn.readthedocs.io/en/stable/).

FYI, this is a specification of `multiprocessing`, and not limited to the chainer.
```multiprocessing.py
import multiprocessing
import numpy as np


class MyClass():
    def __init__(self):
        self.member = np.int32(0)

    def __call__(self):
        self.member += 1
        print(id(self), id(self.member), self.member)


f = MyClass()
pool = multiprocessing.Pool(1)
pool.apply(f)
print(id(f), id(f.member), f.member)
```
```out.py
47349896540568 47349886150192 101
47349517427712 47349886149904 100
```
You can see that `Pool.apply()` copies the input argument.
