### ISSUE TITLE
Publish ChainerX C++ coding style guide

### ISSUE THREAD

**Issue by sonots** [chainer/chainer#5778]
Please publish ChainerX C++ coding style guide.

**Comment by hvy** [comment]
Right, it should probably be added to the contribution guide.

**Comment by hvy** [comment]
Some notes.

- Prefer explicit list initialization for construction, i.e. `MyType mt{};` over `MyType mt;` and `MyType mt();`

**Comment by take-cheeze** [comment]
Just to note that we use clang-format-6.0 for now: https://github.com/chainer/chainer/pull/8242
