### ISSUE TITLE
@fuse causes array copy instead of reference in returned function value

### ISSUE THREAD

**Issue by cems2** [chainer/chainer#5799]
*Description:
in vector ops, often one wants to provide a pre-allocated array to a function to place the output data.   foo( input = x, output = z)

**expected behavior:**
If the output array is also the return value of the function  (return output), then in normal python it is a reference to the array, not a copy of the array (output.copy() ).

**actual behavior**
When a function is decorated with @fuse then _the return value is a copy of the array_, not a reference to the supplied output array.

**discussion:**
I note this behavior is sometimes convenient but it is not expected and it deviates from python, so the behavior changes if @fuse is removed.

* Conditions
- cupy 5.1
- cuda 9.1
- python 3.7 or 3.6
- Linux mint 18
- Anaconda install.

* Code to reproduce
```

#the issue comes up in a context where one wants to do in-place operations or where one is otherwise passing in an array one wants to be used for the output

def  cpy(x,z):   # first test a simple array copy function without fuse
 	z[:] = x    # supplied array is modified.
	return z  # also return supplied array as a reference

x = cupy.arange(3)
z = cupy.ones(3)  # this will serve as the output array

a = z   # keep a reference we can compare later.

c = cpy(x,z)  # c should be a reference to z on output

print ("without fuse",a,z,c)
print (a is z)  # prints true
print (c is z)  # prints true because return value is reference

#Now we do the same thing but add @fuse to the function
# the retrun value will be a new array NOT the reference as above.

@cupy.fuse()
def  cpy_fuse(x,z):
	z[:] = x    #copy into existing array
	return z  #also return a reference THIS IS THE FAIL POINT. 

x = cupy.arange(3)
z = cupy.ones(3)

a = z

c =cpy_fuse(x,z)

print ("with fuse",a,z,c)
print(a is z) # prints True
print(c is z) # prints False, so RETURN VALUE IS COPY NOT REFERENCE


```

* Error messages, stack traces, or logs
No error messages.

* run output
```
python test.py

without fuse [0. 1. 2.] [0. 1. 2.] [0. 1. 2.]
True
True
with fuse [0. 1. 2.] [0. 1. 2.] [0. 1. 2.]
True
False
```

**Comment by Crissman** [comment]
@cems2 Thank you for the issue. Can you please repost this to the [CuPy](https://github.com/cupy/cupy) repository, so we can best review?

Thanks.

**Comment by cems2** [comment]
Will try to do so now

**Comment by grafi-tt** [comment]
@cems2 I wrote a PR to CuPy that enables passing a output buffer explicitly. Though the PR doesn't address unintended array copies, it would provide a workaround for you.

**Comment by cems2** [comment]
I'm unclear on what you mean but can't you do it as it is:

@fuse()
def  foo(x,out):
	out[:] = x+x


THat works, but it may not be as efficient as one might hope because of the way python (and numpy) work.

namely  they first do  x+x
The result is stored in a newly allocated array space.
then it executes  out[:] =
and it copies from the allocated space into out.
then it deletes the transient copy

Thus I believe  that is actually less efficient than just doing:

def foo(x):
	out = x+x
        return x

the gain is that there is no copy into out[:]  and there is no need to delete.  And finally the total space in local memory used is 2*x.size rather than 3*x.size


Thus if there was a strategy to actually use an explicit out array passed in, then one has to do it differently than numpy and python handle the right hand side of the  equation.

Did I get that right?

**Comment by grafi-tt** [comment]
@cems Right, my PR doesn't save temporary memory if NumPy is used.

When CuPy is used, you example is basically compiled as follows. A temporary array disappeared.

```
__global__ void foo(float *x, float *out) {
    int tid = blockIdx.x * gridDim.x + threadIdx.x;
    float x_tmp1 = x[tid];
    float x_tmp2 = x_tmp1 + x_tmp1;
    out[tid] = x_tmp2;
}
```

So, still we can't write an efficient code that works both on CPU and GPU.

I wrote the PR because my impression to `cupy.fuse` is like "custom ufunc definition". I felt it doesn't expect codes that reuses array, optimized for NumPy.

I don't know the design of `cupy.fuse` in detail, so my impression ca be wrong. If such codes also work well, obviously it's better. In practice, implementing such feature may require intricate aliasing and lifetime analysis of variables.

**Comment by grafi-tt** [comment]
Sorry, I move the discussion to https://github.com/cupy/cupy/issues/1248.

**Comment by cems2** [comment]
thanks for your insights.  I am very new to this and am just learning.  

@fuse has dramatic speed ups.  If only it would work more broadly like @numba,jit  it would be crazy.

-----
for example I just discovered  @fuse does not handle cases like the following because of the array indexing.

x = cupy.ones((3,3) )
hx = cupy.empty((4,4))

@fuse()
def dxdt(tmp, hx) : # hx is the output matrix that is passed in 
    hx[1:-1] = tmp[1:] - tmp[:-1] # subtract next door neighbors in x-direction but not y-direction
    hx[0] = hx[-1] = 0.0 # zero boundaries/borders

dxdt(x,hx)


This is taking a derivative of a 2D matrix along the rows but not the columns  (x-derivative of a XY grid).)

to handle the edge effects where the derivative has boundary conditions  it embeds this derivative into an output matrix with an extra column on the front and back that is filled with zeros.
hence the indexing   hx[1:-1]

**Comment by Crissman** [comment]
Thanks! See discussion at: cupy/cupy#1248
