### ISSUE TITLE
Missing links in chainer official doc

### ISSUE THREAD

**Issue by knorth55** [chainer/chainer#5804]
Currently, `Assertion and Testing` page in Chainer official doc have missing links.
I made doc on my laptop, and it generated correct links, so it might be a doc server problem.

https://docs.chainer.org/en/latest/reference/check.html
![chainer-doc](https://user-images.githubusercontent.com/9300063/49630532-fc6acf80-fa31-11e8-84e8-b2a9dfa77fa3.png)

**Comment by toslunar** [comment]
Thanks for reporting.  The issue seems a duplicate of #5408.

**Comment by knorth55** [comment]
Probably true.
#5408 doesn't notice that all links in this page are correctly generated when you build the doc pages on your laptop.
Anyway, I have no idea how to fix it and I really want to fix it.
