### ISSUE TITLE
Pickle error when trying to copy MultiNodeBatchNormalization link

### ISSUE THREAD

**Issue by MannyKayy** [chainer/chainer#5854]
In [BigGAN](https://arxiv.org/abs/1809.11096), they use the standing statistics during evaluation. This can be achieved in chainermn by generating several samples with `finetune` mode enabled. Since finetuning changes the running_mean and running_var of the training model, an evaluation copy is required in order to calculate the standing statistics.

The problem is that the MNBatchNorm link does not support copy(mode=`copy`) and throws 
 a  `TypeError: can't pickle mpi4py.MPI.Intracomm objects` error.

**Screencap:**
![image](https://user-images.githubusercontent.com/7952854/50033932-8c8cb400-fff2-11e8-8c6a-6f8b905e1d75.png)
![image](https://user-images.githubusercontent.com/7952854/50033980-b9d96200-fff2-11e8-8190-4f63e0896cf4.png)
![image](https://user-images.githubusercontent.com/7952854/50033962-a6c69200-fff2-11e8-800e-6b2051e3ca06.png)

**System Info:**
![image](https://user-images.githubusercontent.com/7952854/50034027-e7bea680-fff2-11e8-8b77-52e60e8cf860.png)

**Comment by kuenishi** [comment]
Thank you for reporting! We consider this as a bug and will try to fix, but as next two weeks most of the team members take vacation (in Japan people usually take a longer days off for new-year week celebration) so the fix might be later on, likely January.

**Comment by kuenishi** [comment]
The fix is merged to master and will be included in next release. Feel free to report or reopen if you still have this issue at fixed versions.
