### ISSUE TITLE
Printing error message for huge ChainerX array blocks REPL

### ISSUE THREAD

**Issue by okapies** [chainer/chainer#5885]
When the type of function's argument is incompatible, `chainerx` tries to show `TypeError` with the details of the invoked array `X` in the `Invoked with:` section. If the `X` is huge, ChainerX still shows *all* data contained in `X`. It takes much time and blocks REPL.

```python
>>> import chainerx as chx
>>> X = chx.arange(10000000)  # huge data
>>> x = X.take([0], axis=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: take(): incompatible function arguments. The following argument types are supported:
    1. (self: chainerx.ndarray, indices: chainerx.ndarray, axis: Optional[int]=None) -> chainerx.ndarray

Invoked with: array([[0., 0.],
       [0., 0.]], shape=(2, 2), dtype=float64, device='cuda:0'), [0]; kwargs: axis=1
```

**Comment by beam2d** [comment]
Thanks for the catch! The message is auto-generated by pybind11, so there are two options.

1. Switch to a custom type error message in which the whole array repr is not printed.
2. Fix `__repr__` to omit middle items when the array is too large.

I'm not sure if we can accomplish the option 1 (I think we should anyway have a way to customize it, though...). The option 2 is anyway needed for other places. We can follow NumPy, whose `__repr__` also omits middle items of large arrays.

**Comment by okapies** [comment]
It is related to #6452.

**Comment by okapies** [comment]
It is still a problem in invoking such as ".reshape(-1)".
