### ISSUE TITLE
Confusion about the `note` in dcgan documentation (Section 2.5)

### ISSUE THREAD

**Issue by jinjiren** [chainer/chainer#5908]
> When we define update_core, we usually want manipulate array with numpy library. It should be noted that arrays on CPU should be numpy.ndarray, while arrays on GPU should be cupy.ndarray. But you do not need to write if condition because you can access the appropriate array module by xp = chainer.backends.cuda.get_array_module(array.data). On GPU, xp is cupy, otherwise numpy.

Since `.data` is discouraged and `.array` is preferred now, the explanation here is actually confusing. Also, I guess it's more proper to say `xp = chainer.backends.cuda.get_array_module(variable.array)`, instead of `array.data`. It seems that the actual code is already updated that it's using `x_real.array`.

But I'm not sure whether this is the correct way to make it clear.

**Comment by okuta** [comment]
Thank you for your report.
@jinjiren Cloud you try to fix document?

**Comment by jinjiren** [comment]
@okuta Sure, I'll try sending a PR.

**Comment by mitmul** [comment]
Fixed by #5951.
