### ISSUE TITLE
Bug report: CooMatrix slow to construct

### ISSUE THREAD

**Issue by ericmjl** [chainer/chainer#5921]
Merry Christmas, Chainer team :smile:!

I have profiled the CooMatrix function:

```python
from chainer.utils import CooMatrix
r, c, d = _block_diag([i for i in data['atom_adjs']])  # _block_diag is a utility function I wrote that is much faster than scipy's block_diag.
%time As_Coo = CooMatrix(d, r, c, shape=(int(max(r)+1), int(max(c)+1)))  # in a Jupyter notebook cell
```

Output:

```
CPU times: user 28.4 s, sys: 963 ms, total: 29.3 s
Wall time: 29.3 s
```

On the other hand, the cupyx.scipy.sparse.coo_matrix class takes milliseconds to create:
```python
%time As = coo_matrix((d, (r, c))).astype('float32')
```

Output:

```
CPU times: user 2.47 ms, sys: 187 µs, total: 2.66 ms
Wall time: 2.39 ms
```

This strikes me as being difficult to explain. Is there something that is going on in the CuPy utils version that makes it that much slower?

* Conditions
```
Platform: Linux-4.15.0-36-generic-x86_64-with-debian-stretch-sid
Chainer: 5.1.0
NumPy: 1.15.4
CuPy:
  CuPy Version          : 5.1.0
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 9020
  CUDA Driver Version   : 9020
  CUDA Runtime Version  : 9020
  cuDNN Build Version   : 7401
  cuDNN Version         : 7401
  NCCL Build Version    : None
iDeep: Not Available* Code to reproduce
```

**Comment by niboshi** [comment]
Hi, thank you for reporting!

I tried locally, and it seems that
```py
shape=(int(max(r)+1), int(max(c)+1)
```
this part is taking time.
`max(a)` is much slower than `a.max()`. Please try the latter.

**Comment by ericmjl** [comment]
@niboshi, Merry Christmas from Shanghai!

I can confirm that changing it to:

```python
shape=(int(r.max()+1), int(c.max()+1))
```

Works much faster. Thank you for helping with this!

**Comment by niboshi** [comment]
I'm glad to hear that.
I wish you a Happy New Year! 😊
