### ISSUE TITLE
the backward time of deepspeech2 on deepmark increase when through _backward_main(self, retain_grad, loss_scale) using GPU

### ISSUE THREAD

**Issue by bendanzzc** [chainer/chainer#5934]
When updating chainer from 9108f to 85f6aa, the backward time becomes longer when trough variable.py  _backward_main(self, retain_grad, loss_scale) using GPU. The time of backward increase 6% from 3879ms to 4099ms. 

the GPU is p100, I test 10 steps of deepspeech2 on deepmark and take the average value. the dataset is audio. could you please reduce the time of backward?

**Comment by beam2d** [comment]
Can I get the script you are using?

**Comment by bendanzzc** [comment]
I use this (https://github.com/mingxiaoh/chainer-deepmark) to test  performance. run (python evaluate/train_audio.py g 0) and the backward time become longer when updating chainer from 9108f to 85f6aa. the details can be seen in former comment
