### ISSUE TITLE
Understanding Chainer Memory Usage

### ISSUE THREAD

**Issue by ericmjl** [chainer/chainer#5935]
This is partly a bug report (thought with the same caveat as before that I might not have the right mental model), and mostly a question regarding Chainer's internals.

I am trying to use the CooMatrix in a message passing neural network. I am able to train this network (regardless of however poorly it currently performs). However, one thing I am scratching my head over right now is the memory usage of Chainer.

For an example, please see [this notebook](https://gist.github.com/ericmjl/8ecf5c9f5d1bf4622949dd1d8ad2428f), in particular, referencing Cell 20, which shows the memory usage by Chainer over training epochs. The key curiosity for me is that memory usage keeps increasing.

I don't quite understand why memory usage keeps climbing, rather than staying constant. My use of `autograd` (in NumPy) tells me that the memory usage on my CPU should stay roughly constant as I train my model. Is there an explanation for this phenomena?

**Comment by ericmjl** [comment]
Update: I moved my model off the GPU onto the CPU, and found the same profile of climbing memory usage on the CPU, and managed to crash my system within 200 epochs over my data 🤣. 

On a more serious note, though, I do not understand why memory usage continues to climb, though. Is there something about Chainer memory usage that makes this memory usage non-obvious to us end users?

**Comment by ericmjl** [comment]
@beam2d thank you for your help! Yes, that looks like the issue, and changing:

```python
losses.append(loss)
```

to

```python
losses.append(loss.array)
```

allowed me to preserve memory usage.

**Comment by beam2d** [comment]
Good to hear that :)
