### ISSUE TITLE
Chainer datasets: how to do graph matrices?

### ISSUE THREAD

**Issue by ericmjl** [chainer/chainer#5953]
I am trying to feed graph datasets into a chainer module. I have successfully built a set of 3 matrices: two sparse and one dense. 

Unlike most other datasets, where one row is one example to be indexed, here, the input matrices are such that multiple rows correspond to one example. This is because we are mapping a set of node features (multiple rows) to a single number (output/target).

The Iterator interface expects a single dataset to be fed in. Is there a "correct" DataSet type to feed this type of data data into an iterator, especially when the inputs are many more rows in size than the outputs, which is what is expected with graph data?

**Comment by fiarabbit** [comment]
According to the [contribution guide](http://docs.chainer.org/en/stable/contribution.html), any general question is preferred to be raised at the StackOverflow with a `chainer` tag.

```
Warning

If you have a question on usages of Chainer, it is highly recommended to send a post to
StackOverflow or Chainer User Group instead of the issue tracker. The issue tracker is not a place
to share knowledge on practices. We may suggest these places and immediately close how-to
question issues.
```

By the way, Chainer does not require the dataset to be a _matrix_. (Taking classification as an example, 
the dataset feeds a tuple of an image and an label.) You only have to define a child class of `chainer.dataset.DatasetMixin`, and define `__len__` and `get_example` as you want.

For the further support, raising a question in StackOverflow would help. Chainer team monitors the questions with `chainer` tag.
