### ISSUE TITLE
Document mypy type hinting

### ISSUE THREAD

**Issue by hvy** [chainer/chainer#5963]
mypy type hints have been introduced but needs to be documented in the contribution guide.

- Optional to write type hints?
  - Maintain existing type hints.
  - Adding hints is optional.
- How should I write the type hints, Python 3 type annotations, comments or in stub files (.pyi)?
  - Comments, in general. For edge cases that fail with e.g. Python 3.5.0/3.5.1, skip writing type hints at all.

**Motivation behind type hints**

- Helps developers using IDEs.
- Helps developer in general in terms of readability.

**Comment by niboshi** [comment]
It seems type hint is not always optional.
Mypy complains if it cannot infer the type without hint. In that case we need write it explicitly.

https://mypy.readthedocs.io/en/latest/type_inference_and_annotations.html#explicit-types-for-collections
