### ISSUE TITLE
`chainer.grad` may ignore `grad_outputs`

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer#5978]
```
>>> x = chainer.Variable(numpy.zeros((), 'f'))
>>> chainer.grad([x], [x], [chainer.Variable(numpy.array(3, 'f'))], [chainer.Variable(numpy.array(4, 'f'))])
[variable(4.)]
```

I'd like to get `[variable(7.)]`.

**Comment by niboshi** [comment]
Is the `grad_inputs` argument needed in the first place 🤔?
It seems it's just the offsets to the return values?

**Comment by toslunar** [comment]
Variables in `grad_inputs` may depend each other.  I don't know it's intended but the following example returns `(1248., 124.)`, not `(1048., 124.)`.

https://github.com/chainer/chainer/blob/9f70ea6b328adbe06e633dc25242e6cdda773483/tests/chainer_tests/test_function_node.py#L1062-L1080
