### ISSUE TITLE
ChainerX support in `ParallelUpdater`

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#6000]
It is reported that they do not work with ChainerX.

(edit)
This issue was originally intended to cover `ParallelUpdater` and `MultiprocessParallelUpdater`, but we decided not to support the latter.

**Comment by niboshi** [comment]
`MultiprocessParallelUpdater` is dependent on CUDA, in both implementation and design (e.g. `MultiprocessParallelUpdater.available()`).
We need an entirely new class for supporting ChainerX.

**Comment by beam2d** [comment]
How about supporting it for CUDA backend?

**Comment by hvy** [comment]
That sounds fair assuming we want `MultiprocessParallUpdater` to support the new devices as arguments.

**Comment by niboshi** [comment]
That should work, but only as long as `chainer` on `chainerx` depends on `cupy`.

**Comment by niboshi** [comment]
We are not going to fix `MultiprocessParallelUpdater` as it's not trivial. We will make ChainerMN work with ChainerX instead.

**Comment by kshitij12345** [comment]
@niboshi I would be interested in resolving this issue. However I would need some guidance as to how it should be approached. Let me know if this is fine with you. 
Thank You.

**Comment by emcastillo** [comment]
I have done a quick test by forcing the two devices in examples/mnist/train_mnist_data_parallel.py 
which relies in ParallelUpdater to use chainerx.

The mnist training worked without issues and performs 25% faster than chainer.

**Comment by niboshi** [comment]
@kshitij12345 Thank you for having an interest in this issue.
I also confirmed `ParallelUpdater` works with ChainerX in `train_mnist_data_parallel.py`.
It looks it has been fixed since originally reported.
I'm closing the issue.
