### ISSUE TITLE
AttributeError: module 'chainer.training.extensions' has no attribute 'DumpGraph'

### ISSUE THREAD

**Issue by NoDirective** [chainer/chainer#6004]
Python 3.6.7

Device: <GpuDevice (cupy):0>
unit: 1000
 Minibatch-size: 100
epoch: 20

Downloading from http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz...
Downloading from http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz...
Downloading from http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz...
Downloading from http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz...
Traceback (most recent call last):
  File "train_mnist.py", line 153, in <module>
    main()
  File "train_mnist.py", line 113, in main
    trainer.extend(extensions.DumpGraph('main/loss'))
AttributeError: module 'chainer.training.extensions' has no attribute 'DumpGraph'

**Comment by kmaehashi** [comment]
`DumpGraph` will be added in the next release.
Please use example code from tagged branch that matches with your Chainer installation.
https://github.com/chainer/chainer/tree/v6.0.0b1/examples

**Comment by NoDirective** [comment]
> `DumpGraph` will be added in the next release.
> Please use example code from tagged branch that matches with your Chainer installation.
> https://github.com/chainer/chainer/tree/v6.0.0b1/examples

Thank you for your help
