### ISSUE TITLE
How to install chainerx in windows

### ISSUE THREAD

**Issue by kritdikoon** [chainer/chainer#6009]
I try to install Chainer X in windows.

Anaconda Python3.6

From my understanding I need to have some setting before pip install --pre chainer

$ export CHAINER_BUILD_CHAINERX=1
$ export MAKEFLAGS=-j8  # Using 8 parallel jobs.
$ pip install --pre chainer

where should I run above command in?
I cannot run it on anaconda prompt.

Many thanks in advance

KW

**Comment by toslunar** [comment]
ChainerX does not support Windows yet.  Please wait #5932.

**Comment by kritdikoon** [comment]
Many thanks for prompt reply.  toslunar
