### ISSUE TITLE
`argpartition` method

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#602]
I need this method to get top-k elements. This method is required for a lot of algorithms such as kNN.

**Comment by bordingj** [comment]
The CUDA Thrust library which is included in the CUDA toolkit provides efficient sorting algorithms. It would probably be a lot easier to make some wrappings around those algos instead of implementing sorting algorithms from scratch.

**Comment by unnonouno** [comment]
How about CUB?
https://nvlabs.github.io/cub/

**Comment by unnonouno** [comment]
https://github.com/cupy/cupy/pull/294

**Comment by kmaehashi** [comment]
Implemented in https://github.com/cupy/cupy/pull/294.
