### ISSUE TITLE
`check_backward` with `dtype` may call forward with inconsistent dtype

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer#6020]
`dtype` option casts inputs, while the forward func can use other data.

The inconsistency of dtype hasn't been visible because (failing) type_check is disabled in `numerical_grad`.

* Code to reproduce
`pytest tests/chainer_test` after `s/False/True` on
https://github.com/chainer/chainer/blob/ec78921ef406d1e5e4b0a668e57569f1f315102f/chainer/gradient_check.py#L320

**Comment by toslunar** [comment]
- [ ] `chainer_tests/distributions_tests/test_bernoulli.py`
- [ ] `chainer_tests/functions_tests/array_tests/test_resize_images.py`
- [ ] `chainer_tests/functions_tests/connection_tests/test_bilinear.py`
- [ ] `chainer_tests/functions_tests/loss_tests/test_softmax_cross_entropy.py`
- [ ] `chainer_tests/links_tests/connection_tests/test_tree_lstm.py`

**Comment by kmaehashi** [comment]
Offline discussions:
* Isn't it acceptable to turn on `type_check` in `numerical_grad`? We should measure the overhead.

**Comment by toslunar** [comment]
I found this issue in #5619.  An example to fix testcase: https://github.com/chainer/chainer/pull/5619/commits/241256bee1d0443e5c6b63faa102dac61f38c228

**Comment by toslunar** [comment]
It's possible that #7753 has to be aware of this kind of issue.
