### ISSUE TITLE
Consider moving `Notebook Examples` documentation link to be easier for new users to find

### ISSUE THREAD

**Issue by bkvogel** [chainer/chainer#6056]
In the current Chainer documentation, `Chainer at a Glance` is followed by `Installation` and then `Guides`. I think it would be good if we could provide some additional tutorials/examples for new users before jumping into the reference guide.

Actually, there already seem to be some nice examples in the hands-on which are currently linked to near the bottom of the main documentation page: `Community` -> `Notebook Examples`.
However, with the current organization, it is easy for new users not to notice them. I therefore suggest moving the `Notebook Examples link to somewhere near or immediately following the `Chainer at a Glance` section.

**Comment by niboshi** [comment]
How about something like this?

* Created "Tutorials" and "Examples" sections.
* "Guides" could be more informative. Replaced with "Concepts Walkthrough".
* "Other" section could be more organized. But I also think too many sections is something to be avoided.
* Probably out of scope of this issue, but removed "Comparison with Other Frameworks". I don't think we have to maintain this table by ourselves.

Any comments would be welcome.

![montage](https://user-images.githubusercontent.com/635436/51561618-102ba180-1ecb-11e9-90f2-058c8d59d9fd.png)

**Comment by bkvogel** [comment]
I think that looks nice and also agree about "Comparison with Other Frameworks".

**Comment by niboshi** [comment]
PR submitted. #6142

("Comparison with Other Frameworks" is left, as it's out of scope.)
