### ISSUE TITLE
Implementation of top-k accuracy function

### ISSUE THREAD

**Issue by hokuto-k** [chainer/chainer#606]
Current accuracy function can't show top-k accuracy for voluntary k.
My simple implementation using numpy follows.

``` python
# by this line, same as accuracy.py
# xp == numpy
# if you use gpu, use cupy.asnumpy(x)

# Assuming that module of t and y is numpy
argsorted_y = xp.argsort(y)[:,-self.top_k:]
return xp.asarray(xp.any(argsorted_y.T == t, axis=0).mean(dtype='f')),
```

Do you plan to implement argsort() for CuPy?

**Comment by wkentaro** [comment]
related to https://github.com/pfnet/chainer/issues/602?

**Comment by hokuto-k** [comment]
@wkentaro 
I cannot judge it, but as you mean, I think #602 is generalization of this issue.

**Comment by unnonouno** [comment]
Yes, #602 is related to yours, and you can use `argpartition` to get top-k elements.
This issue is about Chainer function, and #602 is related to CuPy, isn't it?

By the way, I **made** the issue, but we don't have a plan. Implementation of effective sort program in GPU is difficult for me :-(
@okuta knows about it.

**Comment by funtusov** [comment]
Until we have a cupy-supported solution, a naive implementation is to run use chainer.functions.softmax(x), argsort it and search for a match within the k top results.

**Comment by MannyKayy** [comment]
There is currently a [pull request](https://github.com/pfnet/chainer/pull/2057) for CuPy argsort.

**Comment by hokuto-k** [comment]
This PR should be closed because of https://github.com/cupy/cupy/pull/67 and https://github.com/chainer/chainer/pull/2057. Thanks.
