### ISSUE TITLE
chainermn cupy.cuda.runtime.CUDARuntimeError: cudaErrorInvalidDevice: invalid device ordinal

### ISSUE THREAD

**Issue by NoDirective** [chainer/chainer#6073]
I have two nodes. And when I use cpu was successful  with two nodes. But when I want to use gpu.
it seems not work

mpiexec -n 2 --allow-run-as-root --mca btl_tcp_if_exclude docker0,lo  --hostfile hostfile  python3 train_mnist.py --gpu

num process (COMM_WORLD): 2
Using GPUs
Using hierarchical communicator
Num unit: 1000
Num Minibatch-size: 100
Num epoch: 20

Traceback (most recent call last):
  File "train_mnist.py", line 123, in <module>
    main()
  File "train_mnist.py", line 77, in main
    chainer.cuda.get_device_from_id(device).use()
  File "cupy/cuda/device.pyx", line 118, in cupy.cuda.device.Device.use
  File "cupy/cuda/device.pyx", line 124, in cupy.cuda.device.Device.use
  File "cupy/cuda/runtime.pyx", line 185, in cupy.cuda.runtime.setDevice
  File "cupy/cuda/runtime.pyx", line 137, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorInvalidDevice: invalid device ordinal

code:
https://github.com/chainer/chainer/blob/v5/examples/chainermn/mnist/train_mnist.py

**Comment by kuenishi** [comment]
Looks like that some of python processes failed to find right number of GPU. Please make sure the hostfile is correctly described with number of slots, and each nodes have right number of GPUs  by listing device files. `/dev/nvidia[0-9]` . Maybe printing `device` variable may help.

**Comment by kuenishi** [comment]
Also I'd recommend posting this type of support questions to mailing list ( https://groups.google.com/forum/#!topic/chainer/N-4Ba65dEWA ) or going to [Slack](https://chainer.slack.com/join/shared_invite/enQtMjk4ODE3NjA4MzM3LTNiMzM4YmY3ZTFjMmE3YWZlY2IzMTg3NGZiMzE2OGExMTExYTcxNzRjNGM3Mjc4ZjY3MjZlOTNlNzZmMTE2M2M) .

**Comment by NoDirective** [comment]
@kuenishi 
Thank you very much . I missed slots in hostfile. thank you for help

**Comment by keisukefukuda** [comment]
Maybe you can try `mpiexec -n 2 --allow-run-as-root --mca btl_tcp_if_exclude docker0,lo --hostfile hostfile nviida-smi` 

There should be 2 outputs from `nvidia-smi` (which are possibly mixed). You can make sure that the GPUs are available from your MPI program.
