### ISSUE TITLE
`ndarray.take` is relatively slow

### ISSUE THREAD

**Issue by okapies** [chainer/chainer#6088]
ChainreX's `ndarray.take()` method is relatively slower than ones in NumPy and CuPy.

Related to #6081.

# Benchmarks
- Data: mnist train images (`(6000, 784)`)
- Epochs: `20`

The benchmark script is [here](https://gist.github.com/okapies/fac7bf4a5971c092bccadb2face4284f).

```python
# numpy.ndarray.take(indices=<numpy.ndarray>) (batch_size=100)
0.5389023162424564

# cupy.ndarray.take(indices=<numpy.ndarray>) (batch_size=100)
0.864742174744606

# chainerx.ndarray.take(indices=<chainerx.ndarray>) (device=native:0, batch_size=100)
18.46649692207575

# chainerx.ndarray.take(indices=<chainerx.ndarray>) (device=cuda:0, batch_size=100)
2.645330995321274
```

**Comment by niboshi** [comment]
ChainerX native backend  is currently not optimized at all.
CUDA backend shoud be (at least almost) as fast as cupy, though.

**Comment by niboshi** [comment]
It seems the device is not synchronized in the benchmark script.
What if it's done?

Also, nvvp might be useful to investigate this kind of multi-kernel performance issue.

**Comment by niboshi** [comment]
@okapies Is it ok to leave this issue closed?

**Comment by okapies** [comment]
Np. Reopen it when I hit the problem again.
