### ISSUE TITLE
Variable and Parameter specification details

### ISSUE THREAD

**Issue by okapies** [chainer/chainer#6116]
This issue is to discuss the behavior of `Variable` and `Parameter`.

## 1. Lazy initialization of `Parameter`
The constructor of `Parameter` (`__init__`) receives `initializer` and `shape` arguments. It initializes an internal `_data` with the specified `initializer` when its type is array even if `shape` is unknown (`None`). 

It can be initialized *lazily* when once the `shape` is specified.

## 2. Initialization of initialized `Parameter`
The current implementation allows us to `initialize` a `Parameter` even if `shape` is already specified in the constructor. In this case, `initialize` configures `_grad` as `None` because `_grad_initializer is None`.

[Some tests](https://github.com/chainer/chainer/blob/4b45ece4f24af63b417e4a4b7544626d3f04517e/tests/chainer_tests/test_link.py#L925) validates `grad` is to be `None` in this setting, but it seems it is not optimal behavior.

## 3. Handling of `Variable(None)`
At the moment, `Variable(None).to_chainerx().xp` (and `get_array_module(None)`) returns `numpy` because `Variable` treats `numpy` [as a default device](https://github.com/chainer/chainer/blob/b0aff000d5ac40d61b1d47a439e821a3fd28cecf/chainer/variable.py#L669-L671).

This behavior makes it a little bit difficult to keep the consistency of the internal attributes because they can be configured against `chainerx.ndarray` while `xp is numpy.ndarray` (equivalent to `self._data[0] is None`).

## 4. Reassigning array coming from another device (#6058)
At the moment, the setter of `array` accepts an array located on *any* device. It can be a problem, for example, if `array` receives `chainerx.ndarray` while it has a `cupy.ndarray` because `Variable` handles its internal attributes in different manners depending on `_data[0]` is a ChainerX array or not.

There are several options to deal with this issue:

1. Raise an error when it receives an array from a different device
2. Fix to handle the case when the device is changed

2nd option has been implemented in #6072, but it is unclear how to handle `grad` when reassigning `array` in this situation (can we overwrite `grad` in ChainerX array with the existing variable's `grad`?).

## 5. `copydata` implementation (#4074)
`Variable.copydata()` cannot be used against `Variable` because the [implementation](https://github.com/chainer/chainer/blob/ea24d6c1fb6185732cf5e17311150755f5abc47d/chainer/variable.py#L1199-L1209) uses `initialize` method in `Parameter`. It should be fixed or moved to `Parameter` class.

## 6. `requires_grad` semantics not well documented/defined (#5454)
> One point was that requires_grad is used mostly to optimize performance, not creating graphs when unnecessary. However, the semantics could be clarified somewhat; exactly when the requires_grad can be expected to be True or False and by whom.

**Comment by niboshi** [comment]
Regarding 1, there's a discussion on slack:
https://chainer.slack.com/archives/C5P26TUR1/p1548344215041600

>Or perhaps we could change the behavior like this:
>```
>chainer.Parameter(3.)  # broadcasted
>chainer.Parameter(np.array(3.))  # NOT broadcasted
>chainer.Parameter(initializers.Constant(3.))  # broadcasted
>chainer.Parameter(initializers.Constant(np.array(3.)))  # NOT broadcasted
>```
>In order to do this, we could check `shape` attribute of the initializer: if it has non-None `shape`, immediately initialized (without broadcast). Otherwise delayed (broadcasted). We need to fix `initializers.Constant` to have appropriate `shape` attribute.

**Comment by okapies** [comment]
IMO, `Variable` should have an attribute independent from `array` and `xp` which expresses three states like `uninitialized`, `initialied_with_non_chainerx` and `initialized_with_chainerx`, and fix the methods to raise an error when they receive an invalid argument in the invalid state. (e.g. `array(<cupy.ndarray>) raises `TypeError` when the variable is in `initialized_with_chainerx` state`). Any idea?

**Comment by okapies** [comment]
As said in https://github.com/chainer/chainer/issues/6058#issuecomment-458539184, reassignment of `array` from the different device will be forbidden.

**Comment by hvy** [comment]
@okapies Should the `requires_grad` be covered in this issue as well you think? This issue addresses that fact that it's not very well documented (although being a public interface) https://github.com/chainer/chainer/issues/5454

**Comment by okapies** [comment]
Added to the description.

**Comment by okapies** [comment]
I'm getting trapped in 3 when implementing #6072. `copy.deepcopy` tries to assign a value to `array` of an uninitialized `Variable(data=None)` but it is *invalid* because its `device` is not configured yet.

https://github.com/chainer/chainer/blob/53fe553010576baad82e0118a9450bc71c38c524/chainer/variable.py#L1873-L1879

**Comment by okapies** [comment]
Through the offline discussion with @niboshi and @hvy, I'd like to change that `Variable` must have non-`None` array and doesn't accept `__init__(None)` and `variable.array = None` anymore other than uninitialized `Parameter`. How do you think about it? @beam2d
