### ISSUE TITLE
Implementation of multi-dimensional bincount in cupy

### ISSUE THREAD

**Issue by hillbig** [chainer/chainer#612]
Current cupy doesn't support [bincount](http://docs.scipy.org/doc/numpy/reference/generated/numpy.bincount.html) function.

To support k-means and similar hard-clustering algorithms in gpu, we need multi-dimensional bincount function. 

Suppose that we have n examples X[0:n] where X[i] is tensor and want to cluster them.
In k-means, we calculate assignments of X, A[0:n] where A[i] denotes the cluster id of X[i].
We then calculate new cluster centers by U[c] = 1/C[c]  \sum_{A[i] = c} X[i] where C[c] is |{i | A[i]=c}|

The first step (assignments) can be efficiently done by cupy.dot + argmin, howerver the second cannot be efficiently supported.

Original numpy bincount only supports 1d array weight.
However, if we support multi-dimensional array weight, k-means update can be written as 

``` python
U = bincount(A, weights=X, minlength=cluster_num)
U /= bincount(A) # normalize
```

Do you have a plan to support multimensional bincount in cupy?

**Comment by unnonouno** [comment]
How about this code?
```
xp = cupy
x = xp.array([[3, 2], [2, 1]], dtype=numpy.int32)
shape = xp.max(x, -1) + 1
xw = xp.dot(xp.array([shape[1], 1], numpy.int32), x)
y = xp.bincount(xw, minlength=xp.prod(shape)).reshape(shape.tolist())
```
