### ISSUE TITLE
Travis macOS Py34 is failing

### ISSUE THREAD

**Issue by hvy** [chainer/chainer#6132]
The Travis job for macOS (runs only with the `master` branch) is failing when NumPy is used with the Accelerate backend in `numpy.polynomial.polynomial.polfit` in the gradient check. It is confirmed that this failure does not occur with Python 3.5.1, nor with NumPy with OpenBLAS.

**Comment by hvy** [comment]
Won't become an issue if Python 3.4 support is dropped https://github.com/chainer/chainer/issues/6131.

**Comment by niboshi** [comment]
We decided to drop Python 3.4. This issue will be tracked via #6131.

**Comment by hvy** [comment]
Worked around by https://github.com/chainer/chainer/pull/6495. Closing this ticket.
