### ISSUE TITLE
static_graph context manager

### ISSUE THREAD

**Issue by MannyKayy** [chainer/chainer#6151]
Context managers may provide a more intuitive interface to the cache sub-graph operation than decorators. This feature would be simpler and easier to integrate into existing code than the current static sub-graph interface.  I guess that the focus on decorators is because sub-graph is applied to the `__call__()` function; but updating code to support static-subgraphs this way is very restrictive.

For example, it would be easier, clearer and offer more flexibility to cache a resnet sub-graph as shown below:
```
with static_graph:
       for i in range(8):
            h = self.blocks[i](h, ys[i], **kwargs)
```

**Comment by toslunar** [comment]
Do you have an idea to distinguish input/output/other variables?  Unless the interface requires users to do so, Chainer has to guess.

**Comment by MannyKayy** [comment]
I have been giving this quite some thought and as mentioned in #6403, the eventual goal is to allow more flexibility with the use of static sub-graph operations. For the purposes of performance, it should be okay to require that the user provide the relevant information to the interface. Guessing what should be done is non-trivial in some cases and may lead to sub-optimal performance.
