### ISSUE TITLE
FP16 support in various functions and links of ChainerMN

### ISSUE THREAD

**Issue by shu65** [chainer/chainer#6161]
Related to https://github.com/chainer/chainer/pull/4510 and https://github.com/chainer/chainer/issues/4582. It looks the following functions and links of ChainerMN should be fixed somehow to support fp16.

functions:

- [x] allgather (https://github.com/chainer/chainer/pull/7456)
- [x] alltoall (https://github.com/chainer/chainer/pull/7456)
- [x] bcast (https://github.com/chainer/chainer/pull/7456)
- [x] gather (https://github.com/chainer/chainer/pull/7456)
- [x] scatter (https://github.com/chainer/chainer/pull/7456)
- [x] send/recv (https://github.com/chainer/chainer/pull/6552)
- [x] pseudo_connect (see comment below)

links:
- [x] MultiNodeBatchNormalization (https://github.com/chainer/chainer/pull/6619)
- [x] MultiNodeChainList (bugfix (https://github.com/chainer/chainer/pull/7165) test (https://github.com/chainer/chainer/pull/6575))
- [x] _MultiNodeNStepRNN (https://github.com/chainer/chainer/pull/7483)

**Comment by belldandyxtq** [comment]
The pseudo_connect seems supporting fp16 already

https://github.com/chainer/chainer/blob/131d5e6f4b0141c3f343e07905a751eae4fe7d6a/tests/chainermn_tests/functions_tests/test_pseudo_connect.py#L16

**Comment by belldandyxtq** [comment]
All done
