### ISSUE TITLE
Support mixed precision training in chainer examples

### ISSUE THREAD

**Issue by MannyKayy** [chainer/chainer#6168]
Not technically an issue but it maybe worthwhile to warn users of overflow issues if they enable fp16 and have exponential functions in their model.

The older VAE example code directly calls [F.gaussian](https://github.com/chainer/chainer/blob/ef13d538969768497d7a0cfb4aec58ec0f3dac25/examples/vae/net.py#L58) resultings in NaNs with FP16.

The latest VAE example code relies on chainer.distributions, which doesn't yet support FP16 and throws an error whenever [D.Normal()](https://github.com/chainer/chainer/blob/master/examples/vae/net.py#L68) is called, because cupy's random.normal function only operates with float32's. But once/if it does support FP16, similar issues will be encountered. Just as with the Adam FP16 warning, the F.exp overflow issues may be worth noting somewhere.

**Comment by MannyKayy** [comment]
After testing some more of the chainer examples (specifically those with functions that support all dtypes), it appears that most of them are unstable to train with anything but "float32".

**Comment by takagi** [comment]
Thanks for your suggestion. I will check the examples with FP16 enabled and make a plan to provide them work properly.

**Comment by takagi** [comment]
Example|FP16 supported|Work with FP16|Note
--|--|--|--
caffe_export|||
chainermn|||
cifar|||
dcgan|||
glance|||
image_captioning|||
imagenet|||
memnn|||
mnist|||
modelzoo|||
pix2pix|||
pos|||
ptb|||
reinforcement_learning|||
sentiment|||
seq2seq|||
serialization|||
static_graph_optimizations|||
text_classification|||
vae|||
wavenet|||
word2vec|||

**Comment by anaruse** [comment]
I've just run imagenet example with RN50 in fp32 and fp16, and found loss value became `NaN` soon when fp16.  This is a bit strange, since it worked fine when I did similar test a few month ago.  

```
config.dtype: float32
epoch       iteration   main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  lr
1           32          4.461       38.1201               0.0458984      0.0414201                 0.01
2           64          3.93517     3.80036               0.0710449      0.0815921                 0.01
3           96          3.37447     3.25447               0.125732       0.151766                  0.01
```

```
config.dtype: float16
epoch       iteration   main/loss   validation/main/loss  main/accuracy  validation/main/accuracy  lr
1           32          nan         nan                   0              0                         0.01
2           64          nan         nan                   0              0                         0.01
3           96          nan         nan                   0              0                         0.01
```

**Comment by takagi** [comment]
I will update my table following #6442.

**Comment by takagi** [comment]
On this issue, I made a table that indicates if the examples work with FP16 and fixed ones that caused some errors as the dtype mismatch (except ones using L.NStepLSTM). Now I think of what to address this issue further to reasonably close.

- Can we close this issue when it will cause no errors on dtype, even if some examples will result NaNs with FP16?
- Should we implement additional NaN check in `F.exp`, though we already have NaN check facility in Chainer's debug mode?

**Comment by takagi** [comment]
I will make the following things on this issue:
- Adding warnings to examples that result in NaN or Inf in FP16 mode to inform users that such values are currently expected and not caused by wrong setup or environment.
- Leaving comparison between FP32 and FP16 accuracy on the table for examples that don't cause NaN but make worse values.
