### ISSUE TITLE
Inconsistent returns from `to_{cpu,gpu,chainerx,device}`

### ISSUE THREAD

**Issue by hvy** [chainer/chainer#6181]
Return "types" are inconsistent between `to_{cpu,gpu,chainerx,device}` in `Variable` but also between `Variable` and `Link`. Some return `self` and some are missing return statement entirely.  See e.g. https://github.com/chainer/chainer/blob/master/chainer/variable.py#L1712-L1718. 

How about always retuning `self`? That would for instance allow `cpu_arrays = {v.to_cpu().array for v in gpu_vars}`).

**Comment by toslunar** [comment]
> See e.g. https://github.com/chainer/chainer/blob/c089d8b8b9bfe0bb79795e67b866f3e3f41011d1/chainer/variable.py#L1712-L1718

cause: https://github.com/chainer/chainer/commit/8eacd20e35f31f124da36759953a21b29871e72f#diff-e131a8dfc2ea641e7e7c63597b9b0d8eR951

**Comment by toslunar** [comment]
> Some return `self`

Which method of `Variable` (or its subclass)?

**Comment by hvy** [comment]
The `Link` methods do, e.g. https://github.com/chainer/chainer/blob/master/chainer/link.py#L537.

**Comment by hvy** [comment]
Discussed offline and confirmed that this is expected behavior. However, it's worth discussing. For instance if the link needs to return `self` (while `Variable` doesn't). It's also possible to generalize this to methods in Chainer in general, whether we should discourage returning `self`.

**Comment by niboshi** [comment]
I'm negative about stateful method chain because it could be confusing.
