### ISSUE TITLE
Revive trainer image in doc

### ISSUE THREAD

**Issue by kuenishi** [chainer/chainer#6188]
The review comment here https://github.com/chainer/chainer/pull/2620#issuecomment-337485866 a new image was added at the PR. But the newer image has been lost sometime since then until the latest master today: https://docs.chainer.org/en/stable/glance.html

**Comment by toslunar** [comment]
Do you want to replace https://docs.chainer.org/en/latest/_images/trainer1.png with that image?

**Comment by kmaehashi** [comment]
https://github.com/chainer/chainer/blob/e55612b8ec4f4775e442e4f8b55cbdeff906d49c/docs/image/trainer/trainer.png

**Comment by Crissman** [comment]
How about this?

<img width="1021" alt="screen shot 2019-02-27 at 3 48 40 pm" src="https://user-images.githubusercontent.com/4338467/53471234-49959500-3aa7-11e9-9552-4ea8779b0bb5.png">

Showing highlight to start discussion about Dataset.

**Comment by kmaehashi** [comment]
I feel it's better to use arrows in reverse way. (ie, "use" instead of "used by", like as in UML)
How do you think?
