### ISSUE TITLE
`F.triplet` test still fails sometime

### ISSUE THREAD

**Issue by takagi** [chainer/chainer#6190]
The test of `F.triplet` sometime fails because of unreasonably large value of numerical grad result in FP16 double backward test. It may be because that input of the second order backward would contain some values around non-differentiable points.

**Comment by crcrpar** [comment]
I rewrote the test just now using `chainer.testing.FunctionTestCase` with `dodge_nondifferentiable` = `True` and it looks stable (I ran the test >100 times w/o failures).
ref: https://github.com/crcrpar/chainer/blob/rewrite-triplet/tests/chainer_tests/functions_tests/loss_tests/test_triplet.py

**Comment by takagi** [comment]
Thanks!

**Comment by crcrpar** [comment]
Ah, I overlooked https://github.com/chainer/chainer/pull/5819

**Comment by crcrpar** [comment]
@takagi 
I do not think this issue deserves `stale` because https://github.com/chainer/chainer/pull/6855 has been merged.
Rather this has to be just closed or kept open.

What do you think?

**Comment by toslunar** [comment]
A recent example (float32): https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1487/TEST=chainer-py35,label=mn1-p100/testReport/junit/tests.chainer_tests.functions_tests.loss_tests.test_triplet.TestTriplet_param_14_%7Bdtype=float32,%20reduce='mean',%20input_dim=3,%20batchsize=5,%20margin=0/5%7D/test_double_backward_gpu/

**Comment by toslunar** [comment]
The issue is now tracked by #8024.
