### ISSUE TITLE
chainer.grad does not support chainerx.ndarrays

### ISSUE THREAD

**Issue by hvy** [chainer/chainer#6191]
`chainer.grad` does not support backprop with variables with `chainerx.ndarray`s. A similar backprop function for ChainerX is available through `chainerx.grad` so we should make sure it is called from `chainer.grad`.

- [x] Call chainerx.grad from chainer.grad
- [x] Support input grads initialization on chainerx.grad
- [x] Support output grads initialization on chainerx.grad
- [x] Support set_grad option on chainerx.grad
- [x] Support retain_grad on chainerx.grad
- [x] Support loss_scale on chainerx.grad?

**Comment by hvy** [comment]
This is still an issue.

**Comment by emcastillo** [comment]
Worked on a PR to start addressing this. Right now its only an adapter between both implementations. 
There is the need of discuss how to proceed from now on #7464

**Comment by emcastillo** [comment]
We discussed on last chainerx daily that maybe loss_scale should be taken care of on the optimizer?.
