### ISSUE TITLE
PTB custom loop examples are broken

### ISSUE THREAD

**Issue by takagi** [chainer/chainer#6196]
The custom loop version of PTB example causes the following error:
```
AttributeError: 'ParallelSequentialIterator' object has no attribute 'reset'
```

`ParallelSequentialIterator` is a custom iterator that is defined in the example and does not implement `reset` method.

PTB example of the static graph optimization also has the same problem.

- [examples/ptb/train_ptb_custom_loop.py](https://github.com/chainer/chainer/blob/master/examples/ptb/train_ptb_custom_loop.py)
- [examples/static_graph_optimizations/ptb/train_ptb_custom_loop.py](https://github.com/chainer/chainer/blob/master/examples/static_graph_optimizations/ptb/train_ptb_custom_loop.py)

It looks that the change in #5834 was not enough.

**Comment by niboshi** [comment]
We need to test these examples.

**Comment by niboshi** [comment]
@kmaehashi Is this ongoing?

**Comment by toslunar** [comment]
Let me paste the log.
```
$ ./train_ptb_custom_loop.py --test --device @cupy:0
Downloading from https://raw.githubusercontent.com/wojzaremba/lstm/master/data/ptb.train.txt...
Downloading from https://raw.githubusercontent.com/wojzaremba/lstm/master/data/ptb.valid.txt...
Downloading from https://raw.githubusercontent.com/wojzaremba/lstm/master/data/ptb.test.txt...
#vocab = 10000
epoch: 7
Traceback (most recent call last):
  File "./train_ptb_custom_loop.py", line 176, in <module>
    main()
  File "./train_ptb_custom_loop.py", line 158, in main
    evaluate(model, val_iter)))
  File "./train_ptb_custom_loop.py", line 77, in evaluate
    iter.reset()
AttributeError: 'ParallelSequentialIterator' object has no attribute 'reset'
```
