### ISSUE TITLE
ChainerX conformance test, optimization and migration with ChainerMN

### ISSUE THREAD

**Issue by kuenishi** [chainer/chainer#6200]
Learn, Survey, test, and Optimize.

 * [x] Basic implementation for MNIST(#7844)
 * [ ] Unit tests (#8031)
 * [ ] More examples (#8261 )

**Comment by kuenishi** [comment]
see also: https://github.com/chainer/chainer/issues/7476

**Comment by keisukefukuda** [comment]
Since Chainer has gone into maintenance mode, this issue is not longer developed.
