### ISSUE TITLE
`Optimizer` runs unnecessary state array conversion

### ISSUE THREAD

**Issue by okapies** [chainer/chainer#6207]
#6171 has been introduced for the specific `Optimizer` which replaces its state arrays such as `SMORMS3`. But it is also executed for every `Optimizer` which have `states` attribute (e.g. `Adam`) and generates additional overhead.

**Comment by niboshi** [comment]
The comparison with `arr` should be replaced with `st` at line 295.

**Comment by niboshi** [comment]
Oops..., not `st` but `self.state[state_name]` at line 297, before calling `update_core()`.
