### ISSUE TITLE
Difficulty finding `type_check` documentation

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#6257]
I experienced a bit of difficulty reaching [type_check documentation](https://docs.chainer.org/en/v6.0.0b2/reference/check.html#type-checking-utilities).

* Searching for `"type_check"` in the search bar resulted in irrelevant pages.
* Searching for "chainer type_check" at Google resulted in very old documentation (like v1.5.1).
* Finally I went to `FunctionNode` first and find "check_type" within the page.

**Comment by kmaehashi** [comment]
> * Searching for "chainer type_check" at Google resulted in very old documentation (like v1.5.1).

It was unintended. I fixed `robots.txt` to hide docs of older versions.

**Comment by Naba7** [comment]
I am new to chainer.I am interested in contributing here and participating in gsoc 19 as well.Can I be assigned this issue?
