### ISSUE TITLE
`type_check` can cause assertion failure

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#6258]
Version: current master

### Problem
```py
# Note that dtype of the second argument is int64.
F.where(y.array < 0, numpy.array(0), y)
```

This code causes an error like this:
```
Traceback (most recent call last):
  File "/home/niboshi/t/a.py", line 12, in <module>
    y = F.where(y.array == 0, numpy.array(0), y)
  File "/data2/work/w/repos/chainer/chainer/functions/array/where.py", line 87, in where
    z, = Where(condition).apply((x, y))
  File "/data2/work/w/repos/chainer/chainer/function_node.py", line 297, in apply
    self._check_data_type_forward(in_data)
  File "/data2/work/w/repos/chainer/chainer/function_node.py", line 400, in _check_data_type_forward
    self.check_type_forward(in_type)
  File "/data2/work/w/repos/chainer/chainer/functions/array/where.py", line 23, in check_type_forward
    x_type.dtype == y_type.dtype,
  File "/data2/work/w/repos/chainer/chainer/utils/type_check.py", line 545, in expect
    assert isinstance(expr, Testable)
AssertionError
```

#### Cause
`F.where`'s forward type check:
```py
        type_check.expect(
            condition.dtype == numpy.bool_,
            x_type.dtype == y_type.dtype,
        )
```
The above code fails at the second condition, causing `InvalidType` in the light-mode type check.
`FunctionNode` then catches the error and triggeres the non-light-mode type checking. The `assert` statement is evaluated only in this mode, and it fails because the first condition, `condition.dtype == numpy.bool_` is of type `bool`.

**Comment by toslunar** [comment]
Let me clarify the example.  `type_check.expect` does not support testing `condition.dtype == numpy.bool_` where `condition` is not type but an array, which is an argument of `Where.__init__`.  At the moment:
- `F.where` has a bug;
  - bugs of this kind are hardly found by the available tests; and
- Chainer does not seem to provide a way to check `condition.dtype == numpy.bool_` and raise `InvalidType` on failure.  (Instead some functions additionally check the arguments if `is_debug`, in `__init__` or in `forward`.)

**Comment by niboshi** [comment]
@toslunar That's correct.
IMO we can simply support `bool` expressions in `type_check`.

**Comment by Naba7** [comment]
can I be assigned this issue?
Proposed changes:
I think adding .item() to the condition variable will change its dtype from ndarray to int.
