### ISSUE TITLE
Why `F.dropout` usually does not use CuDNN?

### ISSUE THREAD

**Issue by fiarabbit** [chainer/chainer#6266]
Currently, `F.dropout` uses cudnn only when `using_config('use_cudnn', 'always')`
https://github.com/chainer/chainer/blob/d7adbfb45d46fafa6bd0bbb9f0cebe5894489437/chainer/functions/noise/dropout.py#L46

But IMO, cudnn should be enabled when `>=auto`.

**Comment by kmaehashi** [comment]
It seems it's ok to enable it by default, but I'd like to see the benchmark result first.

@bonprosoft Let me know if you have any special reason to use `==always` in #3369.

**Comment by bonprosoft** [comment]
I don't have any special reason for the code.
I think it is OK to use cuDNN dropout if it doesn't decrease performance.

**Comment by kmaehashi** [comment]
I confirmed that enabling cuDNN is better.

```
Forward
=========== =============
  backend                
----------- -------------
    gpu      7.29±0.02ms 
 gpu-cudnn   2.64±0.04ms 
    cpu       1.49±0.1s  
 cpu-ideep     80.6±4ms  
=========== =============

Backward
=========== =============
  backend                
----------- -------------
    gpu      3.16±0.03ms 
 gpu-cudnn   2.68±0.02ms 
    cpu       109±0.8ms  
 cpu-ideep     47.1±3ms  
=========== =============
```
(https://github.com/chainer/chainer-benchmark/pull/31)
