### ISSUE TITLE
Activation function implementation choice

### ISSUE THREAD

**Issue by aksub99** [chainer/chainer#6376]
This issue is with regard to #1448 .

Some of the activation function implementations recently added to other frameworks like Pytorch, Tensorflow and MXNet that don't have an implementation in Chainer are:
1)**CeLU** - Pytorch, MXNet
https://arxiv.org/abs/1704.07483 (Introduced in this paper)

2)**GLU** - Pytorch
https://arxiv.org/abs/1612.08083 (Introduced in this paper)

3)**ReLU6** - Pytorch, Tensorflow
https://arxiv.org/pdf/1803.08607.pdf (Application)

I'm looking to try and start implementing one of the above in chainer. Could I have some suggestions on which (if any) of the above will be a particularly helpful addition to the framework at the moment?

**Comment by toslunar** [comment]
On ReLU6, Chainer could add an alias to `F.clipped_relu(x, 6)`.

**Comment by Crissman** [comment]
@aksub99, usually, we would implement new activation functions when several papers had referenced them or when someone needed to use them for some work they were doing.

If you'd like to implement new functions into Chainer, try looking at functions that are available in Numpy but not yet implemented in Chainer.

Thanks,

**Comment by aksub99** [comment]
@Crissman Thanks for the suggestion! I'll do that.

**Comment by aksub99** [comment]
@toslunar I'd like to work on ReLU6 which as you pointed out is a special case of 'F.clipped_relu' . Could you please elaborate on what you mean by adding an alias and how I can proceed?

> On ReLU6, Chainer could add an alias to `F.clipped_relu(x, 6)`.

**Comment by aksub99** [comment]
@Crissman '**numpy.negative**', '**numpy.power**' and '**numpy.reciprocal**' are available in Numpy but not in Chainer. Would any of these be useful additions?

**Comment by toslunar** [comment]
For example, how about defining a function `relu6` in `chainer/functions/activations/clipped_relu.py` and import the function to `chainer/functions/__init__.py`?

> @toslunar I'd like to work on ReLU6 which as you pointed out is a special case of 'F.clipped_relu' . Could you please elaborate on what you mean by adding an alias and how I can proceed?
> 
> > On ReLU6, Chainer could add an alias to `F.clipped_relu(x, 6)`.

**Comment by aksub99** [comment]
Thanks for the clarification. I'll work on it!
