### ISSUE TITLE
Support for `chainerx.ndarray` in ChainerMN

### ISSUE THREAD

**Issue by shu65** [chainer/chainer#6386]
ChainerMN does not support `chainerx.ndarray`.
So, we need to improve to use it in chainermn.

Relate https://github.com/chainer/chainer/issues/6200

**Comment by shu65** [comment]
ToDo:

- [ ] support for `chainerx.ndarray` in `allreduce_grad()`
- [ ] support for `chainerx.ndarray` in functions and links of ChainerMN

**Comment by keisukefukuda** [comment]
As this issue is covered by #8031 (in particular, links and functions tests), considered to be duplicated and closed.
