### ISSUE TITLE
[suggestion] Make examples more consistent

### ISSUE THREAD

**Issue by crcrpar** [chainer/chainer#6398]
There are a wide variety of examples.
However, they are not consistent for me from the perspective of
1. Support for resuming training from a snapshot of `training.Trainer` or a pair of model and optimizer
    - custom loop examples sometimes ignore `args.out` and/or `args.resume`
2. Use of `extensions.PlotReport`

**Comment by shreyas-kowshik** [comment]
I have gone through the tutorials of Chainer and am ready to work on this. Can you help me get stated? @crcrpar

**Comment by crcrpar** [comment]
@shreyas-kowshik 
The below will be almost done in #6399. 
>     1. Support for resuming training from a snapshot of `training.Trainer` or a pair of model and optimizer
>        
>        * custom loop examples sometimes ignore `args.out` and/or `args.resume`

So, how about working on 2: make examples with `Updater` and `Trainer` to use `extensions.PlotReport` like mnist example?

Here are code blocks from mnist example that are related to `PlotReport`:
- https://github.com/chainer/chainer/blob/aea60d8ac7777c3e57d9b8c19dc5146c75275e51/examples/mnist/train_mnist.py#L68-L69
- https://github.com/chainer/chainer/blob/aea60d8ac7777c3e57d9b8c19dc5146c75275e51/examples/mnist/train_mnist.py#L122-L130
