### ISSUE TITLE
Rewrite ChainerX routines tests in the new style (unified test tool) and remove existing C++ tests

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#6401]
* [x] activation #6553
* [x] connection #6424 
* [ ] ~creation~
* [x] indexing #6438
* [x] linalg #6469
* [x] logic #6551
* [x] manipulation #6556
* [x] math (arithmetics) #6566
* [x] math (others) #6568 
* [x] normalization https://github.com/chainer/chainer/pull/6542 https://github.com/chainer/chainer/pull/6558 
* [x] pooling #6560
* [x] sorting  #6550

**Comment by hvy** [comment]
Closing as all subtasks are finished.
