### ISSUE TITLE
ChainerX needs to support more routines

### ISSUE THREAD

**Issue by hvy** [chainer/chainer#6423]
**_Update_**
We've introduced an `Op` registration and dispatch mechanism. This practically means that `Device` methods will be replaced by `Op` implementations. E.g. `Device::Arange` -> `ArangeOp : public Op`. The following description will soon be updated to take this into account.

``` cpp
class FuncOp : public Op {
public:
    static const char* name() { return "Func"; }
    // Call is overridden per device. Does not create a graph but merely performs device computations such as calling a kernel in case of CUDA.
    // Call can have any signature.
    virtual void Call(..., const Array& out) = 0;  
    // Another definition would be
    // virtual Array Call(..., const nonstd::optional<Array>& out) = 0;  
};

class CudaFuncOp : public FuncOp {
// Override Call.
};

CHAINERX_REGISTER_OP_CUDA(FuncOp, CudaFuncOp);  // Allows backend.CallOp<FuncOp>(...);

Array Func(...) {  // A routine called `Func`.
    Array out = ....;
    {
        NoBackpropModeScope scope{};
        device.backend().CallOp<ArangeOp>(..., out);
    }
    // Create graph.
    return out;
}

```

---

The current repository of  backpropable operations, or ["routines"](https://github.com/chainer/chainer/tree/master/chainerx_cc/chainerx/routines) in ChainerX is still limited. We'd like to open this as a "contribution-welcome"-labeled issue for any contributor to introduce new routines and take part in the early development of ChainerX. 

### References

- [ChainerX routines spreadsheet](https://docs.google.com/spreadsheets/d/1B4E78tw9Awgpcdn5G7zsQ8NVFYJdOoJlIQg42QxKNfU) including statuses and priorities.
- [Available device methods](https://github.com/chainer/chainer/blob/master/chainerx_cc/chainerx/device.h) (low-level data manipulating operations)

### What kinds of routines are missing?

Routines that need to be implemented probably fall into either of the following two categories.

- NumPy compatible `{numpy,chainerx}` functions and `{chainerx,numpy}.ndarray` methods.
- Deep learning routines such as convolutions, pooling, RNN-type routines, etc.

Please make sure that it's not already implemented by checking the list of available routines.

### How do you start implementing routines?

1. Make sure you can build ChainerX. [Instructions here](https://docs.chainer.org/en/latest/chainerx/install/index.html).

1. If you are unsure which routine to start working on, refer to [this list](https://docs.google.com/spreadsheets/d/1B4E78tw9Awgpcdn5G7zsQ8NVFYJdOoJlIQg42QxKNfU/edit) or create an issue suggesting or asking for one. Some routines will require device implementation (for each backend, i.e. native and CUDA) while for some, it might be sufficient to use existing device methods. The latter is easier to work on but it might not be obvious at first which routine that applies to unless you know the implementation details beforehand and what device methods are already available (see list above).

1. Implement the routine. 
  - Check if the routine is temporarily made available via the [NumPy/CuPy fallback mechanism](https://github.com/chainer/chainer/blob/master/chainerx/_fallback_workarounds.py). If it is, delete the fallback.
  - Declare a routine interface.
  - Define forward pass using device methods. If device methods are missing, implement them.
  - Define backward pass using `chainerx::BackwardBuilder`.
  - Declare the routine as a `chainerx::Array` method if appropriate. 
  - Write Python bindings and tests using [test utilities](https://github.com/chainer/chainer/blob/master/tests/chainerx_tests/op_utils.py).

## Getting familiar with the ChainerX code base

Here are some starting points.
 
- [ChainerX documentation](https://docs.chainer.org/en/latest/chainerx/index.html)
- [ChainerX source code root directory](https://github.com/chainer/chainer/tree/master/chainerx_cc)

To get familiar with the C++ code base.

### Array (with autograd)

- [`chainerx::Array`](https://github.com/chainer/chainer/blob/master/chainerx_cc/chainerx/array.h): The interface to arrays.
- [`chainerx::ArrayBody`](https://github.com/chainer/chainer/blob/master/chainerx_cc/chainerx/array_body.h): The actual array implementation.

### Routines
   
- [`chainerx/routines`](https://github.com/chainer/chainer/tree/master/chainerx_cc/chainerx/routines) : Defines "routines", i.e. forward/backward operations on the `Array` such as taking the sum or applying a convolution.
- [`chainerx::BackwardBuilder`](https://github.com/chainer/chainer/blob/master/chainerx_cc/chainerx/backward_builder.h): Extends the computation graph and is used by routines.
- [`chainerx::Device`](https://github.com/chainer/chainer/blob/master/chainerx_cc/chainerx/device.h): A device interface with operations on arrays. The device interface is currently implemented by `chainerx::native::NativeDevice` and `chainerx::cuda::CudaDevice`. A routine delegates the actual computation to these devices. Note that these operations only operate on the raw data and should not involve any graph operations (this might change). 
- [`chainerx/native`](https://github.com/chainer/chainer/tree/master/chainerx_cc/chainerx/native): Contains native implementations including `chainerx::native::NativeDevice`.
- [`chainerx/cuda`](https://github.com/chainer/chainer/tree/master/chainerx_cc/chainerx/cuda): Contains CUDA implementations including `chainerx::cuda::CudaDevice`.

### Graph

- [`chainerx::ArrayNode`](https://github.com/chainer/chainer/blob/master/chainerx_cc/chainerx/array_node.h): A node representing an array in the computational graph. It is owned by an `chainerx::ArrayBody`.
- [`chainerx::OpNode`](https://github.com/chainer/chainer/blob/master/chainerx_cc/chainerx/op_node.h): A node representing an operation in the computational graph. 

### Other

- [`chainerx::Context`](https://github.com/chainer/chainer/blob/master/chainerx_cc/chainerx/context.h): Manages the runtime state. A context has backends, which have devices.
- Units tests are written next to their source files being tested, i.e. `chainerx/routines/logic.h` is tested by `chainerx/routines/logic_test.cc`. You can take a look at the routine tests to see how arrays are used.
- [Python bindings](https://github.com/chainer/chainer/tree/master/chainerx_cc/chainerx/python) are created with pybind11.
- [ChainerX C++ MNIST example](https://github.com/chainer/chainer/blob/master/chainerx_cc/examples/mnist/train_mnist.cc).

Please note that the descriptions above may change as ChainerX is being developed.

## Coding style

Please refer to https://github.com/chainer/chainer/issues/5778

## Ongoing / Status 

**NOT UPDATED (since there are more PRs than expected and it's difficult to maintain the status here)**

- [x] `Minimum` https://github.com/chainer/chainer/pull/6477 (_Missing Python bindings and tests. Open for contribution_)
- [x] Array-Array `Minimum` https://github.com/chainer/chainer/pull/6541
- [ ] Array-Array `Maximum` https://github.com/chainer/chainer/pull/6570
- [x] `Sigmoid` https://github.com/chainer/chainer/pull/6472
- [x] `Square` https://github.com/chainer/chainer/pull/6486 
- [x] `Dot` for ndim > 2 https://github.com/chainer/chainer/pull/6476
- [ ] `Power` https://github.com/chainer/chainer/pull/6496
- [x] `SquaredDifference` https://github.com/chainer/chainer/pull/6501 
- [ ] `Pad` https://github.com/chainer/chainer/pull/6597/
- [x] `Sin`, `Cos` https://github.com/chainer/chainer/pull/6601
- [x] `ArgMin` ~https://github.com/chainer/chainer/pull/6650~ https://github.com/chainer/chainer/pull/6740
- [ ] `Meshgrid` https://github.com/chainer/chainer/pull/6668
- [x] `Ceil` https://github.com/chainer/chainer/pull/6705
- [x] `Floor` https://github.com/chainer/chainer/pull/6707
- [x] `Tan,ArcSin,ArcCos,ArcTan` https://github.com/chainer/chainer/pull/6703
- [ ] `Min/AMin` https://github.com/chainer/chainer/pull/6752

**Comment by dido1998** [comment]
Hi @hvy,  I have built ChainerX and gone through the code base. I would like to start working on this issue. Could you suggest a routine that I could start with?

**Comment by hvy** [comment]
@dido1998 , thanks for showing interest. How about element-wise power? Other quite frequent routines that we need are for instance pad, sigmoid and maximum.

**Comment by hvy** [comment]
We also need random creation routines but that scope is a bit larger.

**Comment by dido1998** [comment]
@hvy, I will first start working for sigmoid. Once, it's done I will start with some of the other routines you mentioned.

**Comment by hvy** [comment]
@dido1998 Great, feel free to open a draft PR if you want to prevent duplicates and get some early review.

**Comment by dido1998** [comment]
@hvy, I have implemented sigmoid and sent a PR. I will now start working on dot for higher dimensions and then element-wise power.

**Comment by aksub99** [comment]
@hvy @dido1998 I'd like to work on implementing maximum.

**Comment by vermashresth** [comment]
Hi @hvy 
I compared the [list of routines](https://docs.scipy.org/doc/numpy/reference/routines.html) in numpy with the ones [already implemented in ChainerX](https://docs.chainer.org/en/latest/chainerx/reference/routines.html). I noticed that currently,  the `chainerx.random.normal` and `chainerx.random.uniform` routines are just wrappers around their numpy counterparts [(here)](https://docs.chainer.org/en/latest/chainerx/reference/generated/chainerx.random.normal.html#chainerx.random.normal), so, by random creation routines, did you mean the Distributions functions?

As a start I would like to implement padding. Should it have all the modes as in [numpy.pad](https://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html)?

**Comment by aksub99** [comment]
> @hvy @dido1998 I'd like to work on implementing maximum.

@hvy Seems like maximum has already been implemented but minimum hasn't. I'll start working on minimum.

**Comment by dido1998** [comment]
@hvy I am now working on element-wise power.

**Comment by hvy** [comment]
Hi @vermashresth, they are indeed wrappers and will most likely be implemented in ChainerX in the future in favor of performance and to control seed. So I did not mean the Distributions functions (although we might want this in the future too).

Padding sound like a good idea. You can start with a minimal set and don't have to support all of the modes. CuPy doesn't for instance and only support a subset. You could start from there https://docs-cupy.chainer.org/en/latest/reference/generated/cupy.pad.html#cupy.pad.

**Comment by aksub99** [comment]
@hvy I've implemented square in PR #6486 .

**Comment by hvy** [comment]
Discussed offline with the team and we thought that it's better to basically always include the Python bings in each PR. There are some benefits to it, please let us know if you have some thought about it.
- Python tests are easier to parameterize using [helpers])https://github.com/chainer/chainer/blob/master/tests/chainerx_tests/op_utils.py).
- Do not have to write C++ tests.

**Comment by hvy** [comment]
Appended a `Ongoing / Status` section in the description.

**Comment by vishalgolcha** [comment]
@hvy  could you suggest some more routines that we can take up ?

**Comment by shinh** [comment]
@aksub99 FYI, `chainerx.maximum` does not work for array vs array case. Try

```
import numpy as np
import chainerx as chx
>>> np.maximum(np.array([2,3]), np.array([4,1]))
array([4, 3])
>>> chx.maximum(chx.array([2,3]), chx.array([4,1]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: maximum(): incompatible function arguments. The following argument types are supported:
    1. (x1: chainerx.ndarray, x2: chainerx.Scalar) -> chainerx.ndarray
    2. (x1: chainerx.Scalar, x2: chainerx.ndarray) -> chainerx.ndarray

Invoked with: array([2, 3], shape=(2,), dtype=int64, device='native:0'), array([4, 1], shape=(2,), dtype=int64, device='native:0')
```

**Comment by hvy** [comment]
Other than the one suggested above,  we could need tensordot-likes, ReLU-likes and more creation routines such as linspace, meshgrid and tile, to mention a few. Other more complex routines include LSTM, unpooling, local response normalization, bilinear interpolation (`F.resize_images`) but those are more involved and will take longer time to implement and review.

**Comment by aksub99** [comment]
@shinh I did realize that `chainerx.maximum` did not support the array vs array case and so did not implement the functionality in `chainerx.minimum` as well. I could create another PR to implement the functionality to `chainerx.maximum` and `chainerx.minimum` if it is a necessary addition. I'll start working on it now.

**Comment by vishalgolcha** [comment]
@aksub99  I was working on implementing the array vs array case, i came across this error :
2: [ RUN      ] ForEachBackend/MathTest.MaximumArrayArrayBackward/0
2: unknown file: Failure
2: C++ exception with description "Numerical error in backward on inputs (out of 2): 0
2: Backprop ID: <default>
2: Atol: 1e-05  Rtol: 0.0001
2: Error[0]:
2: array([[-0.05000000, 0.        , 0.05000000],
2:        [0.10000000, 0.14999999, 0.19999999]], shape=(2, 3), dtype=float64, device='cuda:0')
2: Backward gradients[0]:
2: array([[-0.1, 0. , 0.1],
2:        [0.2, 0.3, 0.4]], shape=(2, 3), dtype=float64, device='cuda:0')
2: Numerical gradients[0]:
2: array([[-0.05, 0.  , 0.05],
2:        [0.1 , 0.15, 0.2 ]], shape=(2, 3), dtype=float64, device='cuda:0')
2: Eps[0] (perturbation in numerical gradients):
2: array([[0.00100000, 0.00100000, 0.00100000],
2:        [0.00100000, 0.00100000, 0.00100000]], shape=(2, 3), dtype=float64, device='cuda:0')
2: " thrown in the test body.
2: [  FAILED  ] ForEachBackend/MathTest.MaximumArrayArrayBackward/0, where GetParam() = "cuda" (3 ms)
2: [ RUN      ] ForEachBackend/MathTest.MaximumArrayArrayBackward/1
2: unknown file: Failure
2: C++ exception with description "Numerical error in backward on inputs (out of 2): 0
2: Backprop ID: <default>
2: Atol: 1e-05  Rtol: 0.0001
2: Error[0]:
2: array([[-0.05000000, 0.        , 0.05000000],
2:        [0.10000000, 0.14999999, 0.19999999]], shape=(2, 3), dtype=float64, device='native:0')
2: Backward gradients[0]:
2: array([[-0.1, 0. , 0.1],
2:        [0.2, 0.3, 0.4]], shape=(2, 3), dtype=float64, device='native:0')
2: Numerical gradients[0]:
2: array([[-0.05, 0.  , 0.05],
2:        [0.1 , 0.15, 0.2 ]], shape=(2, 3), dtype=float64, device='native:0')

The numerically computed gradients seem to match but it's still giving me an error.

**Comment by kshitij12345** [comment]
@hvy Hi, I would like to be a part of this.
* Will implementing `sin`, `cos` and similar functions make sense? I can do them with reference to the `Tanh` implementation.
* Also, I see that Relu and Sigmoid don't have C++ implementation. Will it make sense to have them in C++ as mentioned in the [comments](https://github.com/chainer/chainer/blob/79a3e8c113534162611e9a841539b7bc14d712d7/chainerx/activation.py#L17). I have already tried out Relu with reference to `Tanh`.

**Comment by Harshan01** [comment]
@hvy Hi, I have noticed that ArgMin function is missing. I think ArgMin could be implemented. Can I work on this?

**Comment by hvy** [comment]
Hi @Harshan01, I replied to your issue https://github.com/chainer/chainer/issues/6623. Can you take a look?

**Comment by Harshan01** [comment]
#6650 @hvy I have implemented ArgMin for ChainerX.

**Comment by hvy** [comment]
Thanks for quick implementation, we'll take a look at it.

**Comment by aksub99** [comment]
@hvy The missing Python bindings and tests in `Minimum` are being implemented in PR #6541 .

**Comment by IvanYashchuk** [comment]
Hello @hvy, I've added a few new triginometric routines in PR #6703 .

**Comment by hvy** [comment]
`Chainerx::Absolute` would be useful.

**Comment by dido1998** [comment]
@hvy,  I implemented Absolute PR #6715

**Comment by Harshan01** [comment]
@hvy, I have implemented Amin function #6752

**Comment by Harshan01** [comment]
@hvy, I have re-implemented ArgMin function due to recent changes mentioned in #6740

**Comment by aksub99** [comment]
@hvy PR #6501 for squared difference is ready for review now. Please review at your earliest convenience.

**Comment by hvy** [comment]
Just sharing some information that we've stopped backporting routine PRs to v6, now that the master has been bumped to v7.0.0a1. That's first of all not how backports are defined but we noticed that it's also costly.

**Comment by hvy** [comment]
Thanks @kshitij12345 for pointing out that some routines are temporarily implemented using a NumPy/CuPy fallback mechanism in Python, that for which corresponding routine must be removed when implemented in C++. I updated the `How do you start implementing routines?` section to mention this.

**Comment by hvy** [comment]
Just a heads up but we should to for each ChainerX routine that has a corresponding Chainer function (`chainer.functions.*`) also override `forward_chainerx` in that Chainer function. This should improve the performance of the Chainer function when used with ChainerX since fallback is avoided.

**Comment by hvy** [comment]
`(Python) scalar / chx.ndarray` is required for `GradientClipping`.

**Comment by hvy** [comment]
This issue is still ongoing.

**Comment by UmashankarTriforce** [comment]
I would like to know how much implementation has been covered regarding this issue. I would like to work on implementing some of Chainer X functions
