### ISSUE TITLE
Abbreviate output of str() for large ChainerX arrays

### ISSUE THREAD

**Issue by shinh** [chainer/chainer#6452]
Unlike numpy or cupy, ChainerX outputs a lot for `str(chx.ones((100,100)))`, though we can workaround the issue by using `chx.to_numpy`.

**Comment by kmaehashi** [comment]
NumPy follows the print configuration defined via https://docs.scipy.org/doc/numpy/reference/generated/numpy.set_printoptions.html and CuPy just uses NumPy's `ndarray.__repr__`.
