### ISSUE TITLE
`F.dropout` unexpected gradient when 'train' is set to False

### ISSUE THREAD

**Issue by notogawa** [chainer/chainer#6467]
Version: 5.3.0

Code:
~~~~python
import chainer
from chainer import functions as F
import numpy as np

def test(train):
    print('train: {}'.format(train))
    with chainer.using_config('train', train):
        x = chainer.Variable(np.array([7], np.float32))
        y1 = F.dropout(x)
        y2 = F.dropout(x)
        z = y1 + y2
        gy1, gy2 = chainer.grad([z], [y1, y2], [np.ones_like(z.array)])
        print(gy1)
        print(gy2)

test(True)
test(False)
~~~~

Result:
~~~~
train: True
variable([1.])
variable([1.])
train: False
variable([2.])
variable([2.])
~~~~

This issue is caused by the same reason of https://github.com/chainer/chainer/issues/5810 . Not only `F.dropout` and `F.case`, some function which works as an identity function (means a function returns the input `chainer.Variable` object directly) in certain condition may have the same issue. I think it is an exhaustive way to fix this issue that `chainer.as_variable` must return the copy of input `chainer.as_variable` object. On the other hand, it may cause performance problem.

**Comment by niboshi** [comment]
Thank you for reporting!
I'm going to fix this in the following way:
* Fix `FunctionTestCase` to check that input and output variables are never identical.
* If any functions are violating this check, fix them by applying `F.identity` to outputs.

**Comment by notogawa** [comment]
Looks Good,

`F.cast` with its source data type equals to result data type case should be refactored to use `F.identity` too.

**Comment by notogawa** [comment]
There is no `Reopen issue` button.
