### ISSUE TITLE
[document] The input argument name in `F.rrelu` is inconsistent

### ISSUE THREAD

**Issue by fiarabbit** [chainer/chainer#6503]
https://docs.chainer.org/en/stable/reference/generated/chainer.functions.rrelu.html#chainer.functions.rrelu

The slope for x < 0 is named `a` in the body text, but `r` is used for the input argument.

> Randomized Leaky Rectified Liner Unit function.
> This function is expressed as
> f(x)=max(x,ax),
> where a is a random number sampled from a uniform distribution U(l,u).
> ...
> ・r (N-dimensional array or None) – The r to be used for rrelu. The shape and dtype must be the same as x[0] and should be on the same device. If r is not specified or set to None, a r will be generated randomly according to the given l and u. If r is specified, l and u will be ignored.

**Comment by fiarabbit** [comment]
According to the original paper (https://arxiv.org/pdf/1505.00853.pdf), `a` is the correct one.

However, if the name of the input argument is modified, the users may have to amend their code.
I don't have an idea which one should be fixed...

**Comment by kmaehashi** [comment]
We discussed this issue and concluded that:
* Keep name of the input argument as is.
* Add notes like ``This value corresponds to `a` in the original paper.`` to the description of `r`.

@fiarabbit Do you have interest in making a PR?

**Comment by fiarabbit** [comment]
@kmaehashi Thanks for your kind reply. I sent a PR.
