### ISSUE TITLE
Typo in docstring for classification_summary

### ISSUE THREAD

**Issue by yewang** [chainer/chainer#6514]
There appears to be a typo in the docstring for the "classification_summary" function (located in functions/evaluation/classification_summary.py).

The correct definition for recall is TP / (TP + FN), however the current docstring writes "TN" instead of "FN".

Also, after amending the definition, a few lines later should mention the definition of "FN" alongside "TP", "FP", and "TN".

The actual code seems to make the correct calculation.

**Comment by toslunar** [comment]
Fixed in #6515.
