### ISSUE TITLE
Slight inaccuracy in NStepGRU docs

### ISSUE THREAD

**Issue by euler16** [chainer/chainer#6521]
in the part where the input dimension has been described , I think it should be L_t instead of L_i

**Comment by euler16** [comment]
if u could tell me the procedure to make the changes, I can make the correction and do a PR myself.

**Comment by toslunar** [comment]
It seems #5979 missed some fixes.  Could you make a PR?  The contribution guide is https://docs.chainer.org/en/latest/contribution.html.

**Comment by euler16** [comment]
sure I will

**Comment by euler16** [comment]
while trying to build the documentation, I am getting the following error

'source file: {}'.format(source_abs_path))
RuntimeError: Couldn't parse root directory from source file: /home/rajivratn/anaconda2/envs/chain/lib/python3.6/site-packages/chainer/serializer.py

after searching the codebase, i think the error is emanating from conf.py in doc/src.
could you tell me how to fix this?

**Comment by euler16** [comment]
I overcame the above issue

**Comment by euler16** [comment]
I have sent a PR for the same. made sure I ran autopep8 and flake8 before sending PR.
