### ISSUE TITLE
no link for ReLU

### ISSUE THREAD

**Issue by euler16** [chainer/chainer#6523]
though chainer supports complex activation functions like PReLU. It's odd that ReLU isn't available as a link.

**Comment by fiarabbit** [comment]
@euler16 In Chainer, `Function` denotes a _function_ which does not have a trainable parameter as its internal state, while `Link` denotes a _function_ which has an internal states which is parameterized by a trainable `Parameter`.

`F.relu` is a _function_ which substitute x_i < 0 by 0, therefore there is no trainable parameter in it.
Thus, `F.relu` exists while `ReLU` as `Link` does not.

**Comment by euler16** [comment]
@fiarabbit agreed. But in the absence of a link.ReLU its difficult to use Sequential.

**Comment by fiarabbit** [comment]
@euler16 The official API refrerence of [chainer.Sequential](https://docs.chainer.org/en/stable/reference/generated/chainer.Sequential.html) tells how to use `F.relu` for `chainer.Sequential`. Is not this sufficient for your use-case?

**Comment by euler16** [comment]
Ah I see. I had used PyTorch before and for that reason got confused if functions API could be used with Sequential. Thank you for your response
