### ISSUE TITLE
`to_dense` in `CooMatrix` does not take duplicate indices into account

### ISSUE THREAD

**Issue by ir5** [chainer/chainer#6543]
It seems that `to_dense` method in `CooMatrix` does not handle a sparse matrix with duplicate indices appropriately.

```python
from chainer.utils import CooMatrix
import numpy as np

data = np.array([[10, 20, 30]], dtype='f')
row = np.array([[0, 0, 0]])
col = np.array([[0, 0, 0]])
shape = (2, 3)
sp = CooMatrix(data, row, col, shape)
print(sp.to_dense())
```

Output:
```
[[[30.  0.  0.]             # <-- "30." should be "60."
  [ 0.  0.  0.]]]
```

Note that `scipy.sparse.coo_matrix` can handle duplicate indices. https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html

Further, current `to_dense` takes non-zero elements as somewhat special thing. https://github.com/chainer/chainer/blob/master/chainer/utils/sparse.py#L60
But I believe that this implementation outputs wrong result when zero element is placed at the intermediate of an array `data`.

**Comment by hvy** [comment]
Reopening as this is still an issue.

**Comment by hvy** [comment]
Thanks @ir5 for the report and sorry for dragging out so tremendously, this issue along with the problem of intermediate 0s should be fixed by https://github.com/chainer/chainer/pull/8187.

**Comment by Saanidhyavats** [comment]
I want to contribute on this issue, can I start with it?
