### ISSUE TITLE
OpenCL support in ChainerX?

### ISSUE THREAD

**Issue by cmpute** [chainer/chainer#6545]
As mentioned in #99, I think it's now easier to implement this since we have a C++ interface. Any plan for OpenCL or ROCm for AMD gpu support please?

**Comment by crcrpar** [comment]
[clpy](https://github.com/fixstars/clpy) seems useful.
https://github.com/fixstars/clpy/releases/tag/v2.1.0rc1

**Comment by cmpute** [comment]
FYI
- https://github.com/srossross/Clyther/
- https://github.com/inducer/pyopencl
- https://github.com/lebedov/scikit-cuda
- https://github.com/jroose/pyclblas
- https://github.com/geggo/gpyfft
- https://github.com/KhronosGroup/OpenCL-Headers
- https://github.com/clMathLibraries
- https://github.com/ROCmSoftwarePlatform/rocBLAS

**Comment by CaiusTSM** [comment]
+1
