### ISSUE TITLE
Use large eps in test for linear functions (not only for Linear)

### ISSUE THREAD

**Issue by gwtnb** [chainer/chainer#6574]
When calculating numerical differentiation

(f(x + eps) - f(x)) / eps
of linear functions, large eps stabilizes the calculation. The value of eps does not affect the result except for rounding error, and f(x + eps) - f(x) with small eps tends to have large error.

This stabilization can be used not only for Linear, but Convolution2D, etc.

#6547 is the PR for `Linear`. Note that large eps can be used on not only for function tests but also for link tests.

**Comment by niboshi** [comment]
The motivation is to reduce the numeric tolerances which are a bit too large, is that correct?

https://github.com/chainer/chainer/blob/v6.0.0b3/tests/chainer_tests/functions_tests/connection_tests/test_linear.py#L41
