### ISSUE TITLE
Links in concept walkthrough of Optimizer are broken

### ISSUE THREAD

**Issue by crcrpar** [chainer/chainer#6598]
Links to `cleargrads`, `setup` and `update` in [Concepts Walkthrough -> Optimizer](https://docs.chainer.org/en/stable/guides/optimizers.html?highlight=optimizer) are broken as the below capture shows.
<img width="576" alt="image" src="https://user-images.githubusercontent.com/16191443/54800504-a7339080-4ca5-11e9-8ed4-76e3b5b9d675.png">

**Comment by kmaehashi** [comment]
Will be fixed in #6450
