### ISSUE TITLE
Performance difference between chainer5.3.0, chainer6.0.0b2 and chainer6.0.0b3 with SSD300

### ISSUE THREAD

**Issue by GuillaumeSmaha** [chainer/chainer#6606]
* Conditions
I used pip to switch between chainer/cupy verrsion: `pip3 install chainer==6.0.0b3 cupy-cuda100==6.0.0b3`
```
Platform: Linux-4.15.0-46-generic-x86_64-with-Ubuntu-18.04-bionic
Chainer: 5.3.0
NumPy: 1.16.2
CuPy:
  CuPy Version          : 5.3.0
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 10000
  CUDA Driver Version   : 10010
  CUDA Runtime Version  : 10000
  cuDNN Build Version   : 7402
  cuDNN Version         : 7500
  NCCL Build Version    : 2307
  NCCL Runtime Version  : 2402
iDeep: Not Available
```
or
```
Platform: Linux-4.15.0-46-generic-x86_64-with-Ubuntu-18.04-bionic
Chainer: 6.0.0b2
NumPy: 1.16.2
CuPy:
  CuPy Version          : 6.0.0b2
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 10000
  CUDA Driver Version   : 10010
  CUDA Runtime Version  : 10000
  cuDNN Build Version   : 7301
  cuDNN Version         : 7500
  NCCL Build Version    : 2307
iDeep: Not Available
```
or
```
Platform: Linux-4.15.0-46-generic-x86_64-with-Ubuntu-18.04-bionic
Chainer: 6.0.0b3
NumPy: 1.16.2
CuPy:
  CuPy Version          : 6.0.0b3
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 10000
  CUDA Driver Version   : 10010
  CUDA Runtime Version  : 10000
  cuDNN Build Version   : 7402
  cuDNN Version         : 7402
  NCCL Build Version    : 2307
  NCCL Runtime Version  : 2307
iDeep: Not Available
```
* Code to reproduce
Use demo.py from chainercv for SSD300: https://github.com/chainer/chainercv/blob/master/examples/ssd/demo.py
I used the logo of chainercv to run ssd300 it: https://raw.githubusercontent.com/chainer/chainercv/master/docs/images/logo.png

* Error messages, stack traces, or log
Here the profiling files with nvprof:
![sdd300_chainer-compare](https://user-images.githubusercontent.com/1287922/54868370-238ba980-4d62-11e9-8a7e-3f179e6f6a45.png)
[profiling-ssd300.zip](https://github.com/chainer/chainer/files/2999590/profiling-ssd300.zip)

It seems a new CUDA instruction was added in 6.0.0b3: `conv2d_group_direct_kernel`.
In the first example with `demo.py`, the difference doesn't seem big but I am running ssd300 on a camera flow (realtime) and it made a big difference.
You can also find the cam*.nvvp files from my real example.
![ssd300_chainer-compare-cam](https://user-images.githubusercontent.com/1287922/54868750-48821b80-4d66-11e9-9726-4355a1ec5077.png)

Thank you!

**Comment by GuillaumeSmaha** [comment]
Profiling files: [profiling-ssd300.zip](https://github.com/chainer/chainer/files/2999590/profiling-ssd300.zip)

**Comment by kmaehashi** [comment]
It seems you are using cuDNN 7.5 for 5.3.0 / 6.0.0b2 and cuDNN 7.4.2 for 6.0.0b3.
How about trying cuDNN 7.5 with 6.0.0b3?

**Comment by GuillaumeSmaha** [comment]
Hi,
This is weird, I didn't change the version of cuddn7 installed. I only used `pip install cupy chainer` to switch between the version.
The version installed in my container is `7.5.0.56-1+cuda10.1`.

I double checked the runtime information and the cuddn version with 6.0.0b3 becomes `cuDNN Version         : 7402` whereas the cudnn version is still the same in the container.

If you want, I can try to run more tests to find the chainer function which becomes slower.

**Comment by GuillaumeSmaha** [comment]
Ok, I just installed `cupy==6.0.0b3` instead of `cupy-cuda100==6.0.0b3` and now it seems good:
```
CuPy Version          : 6.0.0b3
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10000
CUDA Driver Version   : 10010
CUDA Runtime Version  : 10000
cuDNN Build Version   : 7500
cuDNN Version         : 7500
NCCL Build Version    : 2402
NCCL Runtime Version  : 2402
```

I am going to relaunch the profiler

**Comment by GuillaumeSmaha** [comment]
With cudnn 7.5, the call to `conv2d_grouped_direct_kernel` is gone.

I update demo.py to run SDD300. I forgot that the first call could be slower due to the compiling and caching.
My change to `demo.py`:
```
    cnt = 250 # or 5000 without profiler
    stats = []

    for i in range(cnt):
        t0 = time.time()
        img = utils.read_image(args.image, color=True)
        bboxes, labels, scores = model.predict([img])
        bbox, label, score = bboxes[0], labels[0], scores[0]
        delta = time.time() - t0
        stats.append(delta)

    np_stats = np.array(stats)

    print("Median = " + str(np.percentile(np_stats, 50.0, interpolation="nearest")))
    print("P90 = " + str(np.percentile(np_stats, 90.0, interpolation="nearest")))
    print("P99 = " + str(np.percentile(np_stats, 99.0, interpolation="nearest")))
```

So here my results for 250 iterations with profiler:
![ssd300_chainer-and-cudnn-compare](https://user-images.githubusercontent.com/1287922/55012745-3f8b8700-4fbe-11e9-9b98-b80e7b294fbe.png)
```
chainer 5.3.0 (cudnn 7402 from precompiled build):
Median = 0.040129661560058594
P90 = 0.0413975715637207
P99 = 0.04566025733947754

chainer 5.3.0 (with cudnn 7500):
Median = 0.040084123611450195
P90 = 0.041477203369140625
P99 = 0.045408010482788086

chainer 6.0.0b2 (with cudnn 7301 from precompiled build):
Median = 0.042163848876953125
P90 = 0.04331088066101074
P99 = 0.04760479927062988

chainer 6.0.0b2 (with cudnn 7500):
Median = 0.04237699508666992
P90 = 0.043634653091430664
P99 = 0.0479886531829834

chainer 6.0.0b3 (with cudnn 7402 from precompiled build):
Median = 0.05548262596130371
P90 = 0.056322574615478516
P99 = 0.06150412559509277

chainer 6.0.0b3 (with cudnn 7500):
Median = 0.03980565071105957
P90 = 0.04055023193359375
P99 = 0.04583287239074707
```


Results for 5000 iterations WITHOUT profiler:
```
chainer 5.3.0 (cudnn 7402 from precompiled build):
Median = 0.03699612617492676
P90 = 0.03774261474609375
P99 = 0.039260149002075195

chainer 5.3.0 (with cudnn 7500):
Median = 0.036872148513793945
P90 = 0.03756999969482422
P99 = 0.03920912742614746

chainer 6.0.0b2 (with cudnn 7301 from precompiled build):
Median = 0.03895831108093262
P90 = 0.039749860763549805
P99 = 0.041445255279541016

chainer 6.0.0b2 (with cudnn 7500):
Median = 0.03874015808105469
P90 = 0.0396275520324707
P99 = 0.041322946548461914


chainer 6.0.0b3 (with cudnn 7402 from precompiled build):
Median = 0.052252769470214844
P90 = 0.05299687385559082
P99 = 0.05450439453125

chainer 6.0.0b3 (with cudnn 7500):
Median = 0.03640317916870117
P90 = 0.03710222244262695
P99 = 0.03879857063293457
```

It is even better with chainer6.0.0b3 and cudnn 7500.

Sorry for the false issue and thank you for the good direction to solve it.


PS: Just in case, I upload the profiling files for the 6 tests:
[ssd300_chainer_loop_5.3.0-cudnn7402.nvvp.gz](https://github.com/chainer/chainer/files/3008955/ssd300_chainer_loop_5.3.0-cudnn7402.nvvp.gz)
[ssd300_chainer_loop_5.3.0-cudnn7500.nvvp.gz](https://github.com/chainer/chainer/files/3008958/ssd300_chainer_loop_5.3.0-cudnn7500.nvvp.gz)
[ssd300_chainer_loop_6.0.0b2-cudnn7301.nvvp.gz](https://github.com/chainer/chainer/files/3008959/ssd300_chainer_loop_6.0.0b2-cudnn7301.nvvp.gz)
[ssd300_chainer_loop_6.0.0b2-cudnn7500.nvvp.gz](https://github.com/chainer/chainer/files/3008960/ssd300_chainer_loop_6.0.0b2-cudnn7500.nvvp.gz)
[ssd300_chainer_loop_6.0.0b3-cudnn7402.nvvp.gz](https://github.com/chainer/chainer/files/3008961/ssd300_chainer_loop_6.0.0b3-cudnn7402.nvvp.gz)
[ssd300_chainer_loop_6.0.0b3-cudnn7500.nvvp.gz](https://github.com/chainer/chainer/files/3008962/ssd300_chainer_loop_6.0.0b3-cudnn7500.nvvp.gz)

**Comment by GuillaumeSmaha** [comment]
@kmaehashi I am closing this issue since the result is better with cudnn7.5.

Maybe you should re-distribute cupy-cuda10==6.0.0b3 built with cudnn7.5 instead of cudnn 7.4

**Comment by kmaehashi** [comment]
Recently we made some changes regarding cuDNN library discovery:

* In v6.0.0b2 or earlier (including v5.x series), bundled cuDNN library can be overridden with locally-installed one by using `LD_LIBRARY_PATH`. (I guess you have cuDNN 7.5 installed locally).
* In v6.0.0b3 or later, bundled cuDNN library cannot be overridden by using `LD_LIBRARY_PATH`.

Regarding cuDNN v7.5 redistribution,
* v6.0.0b3 / v5.3.0 wheels comes with cuDNN v7.4.2.
* v6.0.0rc1 / v5.4.0 wheels comes with cuDNN v7.5. v6.0.0rc1 / v5.4.0 is the first version that supports cuDNN 7.5.
