### ISSUE TITLE
Leave array nodes when cutting graph in ops like Dot, Floor, etc.

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#6612]
This behavior is not intuitive:

```py
import chainerx as xp

x = xp.ones((2, 3), 'float32').require_grad()
ys = xp.split(x, (3,), axis=1)
zs = [y.dot(xp.ones((y.shape[-1], 5), 'float32')) for y in ys]

zs[0].backward()  # ok
zs[1].backward()  # error, because dot cuts the graph for zero-sized inputs
```

**Comment by niboshi** [comment]
Fix:
* Ops may cut the graph, but even then always leave array nodes.
* Omit array nodes only in functions like `AsGradStopped`.

**Comment by kshitij12345** [comment]
Hi,

I do understand roughly how back-prop and computation graphs are formed. However I didn't understand why the `zs[1]` computation is not tracked after dot. 
Interested to know more about how auto-diff is implemented in ChainerX.
Thank You.

**Comment by niboshi** [comment]
Sorry, maybe it was not clear enough.

In the current implementation, computational graphs are formed by using `BackwardBuilder`.
https://github.com/chainer/chainer/blob/aa3cfc300eeb4b95a1b7ba624b4e459f890cb6b0/chainerx_cc/chainerx/routines/connection.cc#L349

`BackwardBuilder` installs `ArrayNode`s in the output arrays and spans edges to input array nodes with `OpNode`. (more precisely it's done in `BackwardTarget::Define`() just below).

But it's allowed for op implementations to skip `BackwardBuilder` in case backprop is meaningless, like `Dot` on zero-sized arrays:
https://github.com/chainer/chainer/blob/aa3cfc300eeb4b95a1b7ba624b4e459f890cb6b0/chainerx_cc/chainerx/routines/connection.cc#L329-L334

In this case `ArrayNode`s will be absent from the output array and suceeding arrays resulting from it.
Calling `Array::Backward` on such arrays would be an error, like the example in the first post.

**Comment by kshitij12345** [comment]
Oh I see, makes sense to me now.

Thank you for taking your time and explaining it.

**Comment by niboshi** [comment]
Discussed with @beam2d 

By simply leaving array nodes, that would result in unwanted consequences.
Say we apply `astype` to an array twice like `float32` -> `int32` -> `float32`, and do some computation after that.

```py
a1 = chainerx.array([1, 2], 'float32').require_grad()
a2 = a1.astype('int32')
a3 = a2.astype('float32')
a4 = func(a3)
```

`a3` and `a4` would be connected by a computational graph despite we never want to calculate `a3`'s grad (since we didn't call `a3.require_grad()`). This would be suboptimal in memory consumption.
In order to avoid this situation, we need a mode such that `a3` has a graph ID but its node is empty.

**Comment by hvy** [comment]
Clarification of a snippet from the comment above:
> we need a mode such that a3 has a graph ID but its node is empty.

This is due to the fact that we don't want to raise an error when backward is called on such arrays (not very user friendly). Errors are otherwise raised when calling backward on arrays without array nodes.

With that in mind, the bookkeeping required in order to correctly raise/not raise the error might be complex and it'd be worth considering never raising errors when calling backward on arrays without array nodes in the first place? Then, we'd not need the bookkeeping. However, we need to consider the followings from a user perspective.

- Is this behavior unfriendly, i.e. having a "NOOP" instead of an error?
- Should gradient be required "by default"?
- Consistent in C++, consistent in Python?

**Comment by niboshi** [comment]
After discussion, we decided to make the implementation simpler by ceasing errors when backward is called from a non-backprop-required-array.

* The error was intended to notify users that they forgot calling `ndarray.require_grad()`.
* If ChainerX will introduce something like `chainer.Link` in Chainer, the problem will be gone for parameters. `Link` will automatically call `ndarray.require_grad()`.
* For algorithms that require gradients of data, even if users don't get an error when calling backward, they will get one when retrieving `grad` from the data array on which `require_grad` is not called.
* Thus, in almost all of the typical use cases we can think of, users will be able to receive comprehensible errors.

**Comment by niboshi** [comment]
The above has already been implemented.
