### ISSUE TITLE
[feature request] Add documentation about chainer-benchmark

### ISSUE THREAD

**Issue by fiarabbit** [chainer/chainer#6613]
I want to do some benchmarking between machines (hopefully with chainer). I found [chainer-benchmark](https://github.com/chainer/chainer-benchmark) and I think it is the exact one I hoped to use. However, there is too little documentations about the repository so that I cannot find any how-to-use.

For example,
- how to run on a specific ID of GPU in multi-GPU environment
- etc...

Is there any plan to write the documentation about it?

**Comment by kmaehashi** [comment]
Thanks for the feedback. Generally it is a set of benchmark code written for ASV. I think ASV documentation well-covers the usage.
https://asv.readthedocs.io/en/stable/using.html#running-benchmarks

Currently we're using it internally and the priority for documentation enhancement is not very high. Feel free to post issues in chainer-benchmark repo (e.g., "Need documentation for XYZ") if you have questions.

> how to run on a specific ID of GPU in multi-GPU environment

ASV just runs the benchmark code using installed Python. You can use `CUDA_VISIBLE_DEVICES` to select the device as you usually do in Chainer.

**Comment by fiarabbit** [comment]
@kmaehashi OK, thanks! If I have trouble, I'd like to post it on `chainer-benchmark`.
