### ISSUE TITLE
Implementation of ArgMin in ChainerX

### ISSUE THREAD

**Issue by Harshan01** [chainer/chainer#6623]
ArgMin (similar to ArgMax) can be implemented in ChainerX

**Comment by Harshan01** [comment]
Can I work on this issue?

**Comment by hvy** [comment]
Thanks for asking and yes sure. I think it can be implemented using `ArgMax`, just negating the inputs, which might be fine for an initial implementation.

**Comment by Harshan01** [comment]
Updated ArgMin Implementation in ChainerX #6740

**Comment by niboshi** [comment]
Fixed via #6740
