### ISSUE TITLE
How should we handle warnings raised during tests?

### ISSUE THREAD

**Issue by kmaehashi** [chainer/chainer#6638]
Currently limited set of warning classes are treated as errror.
https://github.com/chainer/chainer/blob/2615ab68923d0cc55dc3b5c0708f9fdcd48d6b03/setup.cfg#L10-L13

However other warnings are just ignored. Maybe it is better to treat all warnings as error.

**Comment by toslunar** [comment]
The severity differs.  Unexpected warnings of type `FutureWarning`, `DeprecationWarning`, or `PendingDeprecationWarning` show inevitable issues of the package.  Other warnings usually show no more than immature tests.

**Comment by toslunar** [comment]
Removing the `stale` label, because #6653 closed the issue.
