### ISSUE TITLE
In examples, use device spec instead of gpu id

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer#6661]
Examples with `--gpu` does not support chainerx and intel64 backends.
Add `--device` option to the examples and use `chainer.get_device` to support all the backends.

See [examples/mnist/train_mnist.py](https://github.com/chainer/chainer/blob/master/examples/mnist/train_mnist.py) for an example with `--device`.

**Comment by hvy** [comment]
For the record, all examples are fixed except for the ones that are located under `examples//chainermn`.

**Comment by hvy** [comment]
@toslunar Are ChainerMN examples within the scope of this PR?

**Comment by toslunar** [comment]
> Are ChainerMN examples within the scope of this PR?

No.
