### ISSUE TITLE
Communicator API improvement

### ISSUE THREAD

**Issue by kuenishi** [chainer/chainer#6670]
- The name `allreduce_grad` is not right because it is only for models and also does division. Would be a good time to update its name.
- Make communicator contextmanager - https://github.com/chainer/chainer/pull/6636 revealed an issue that object lifecycle (the timing GC'd) cannot be controlled.

**Comment by kuenishi** [comment]
- maybe I had a case I needed `scatter_obj` for re-inventing `scatter_dataset`

**Comment by kuenishi** [comment]
I had a case for supporting more operators in `allreduce_obj()`  for calculating max and min.

**Comment by shu65** [comment]
I made a todo list.
- [ ] rename `allreduce_grad()` and functions related with it
- [ ] add `finalize()`
- [ ] support for more operators in allreduce() and allreduce_obj() for calculating max and min.
- [ ] support for batched copy mode in all communicators

**Comment by kuenishi** [comment]
It's not an API improvement, but let me add another TODO:
- [ ] removed deprecated communicators / functions

**Comment by belldandyxtq** [comment]
`support for batched copy mode in all communicators`
is related to #7543

**Comment by kuenishi** [comment]
We've changed our mind that we won't work on "allreduce() and allreduce_obj() for calculating max and min" so soon as we don't need it right now.

**Comment by shu65** [comment]
done
