### ISSUE TITLE
Do clang-tidy check only for modified source files in Travis CI

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#6690]
Travis-CI's queue is a bit too long lately and clang-tidy takes quite a time.
It could be shortened by only checking modified source files in each PR.

#6682 removes the check entirely from Travis CI but we may be able to restore it once this will be implemented.

**Comment by take-cheeze** [comment]
memo: Command to list changed files in travis:
```bash
git diff --name-only $TRAVIS_COMMIT_RANGE chainerx_cc
```

**Comment by niboshi** [comment]
Even a change in a header file could introduce a new clang-tidy failure.
Now I doubt it's that easy to do it.
