### ISSUE TITLE
Rewrite device functions using dynamic op registration

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#6692]
* Rewrite existing op implementations with dynamic op registry #6675.
* Remove the corresponding `Device` virtual functions.
.
* [x] connection #6833
* [x] creation https://github.com/chainer/chainer/pull/6745
* [x] indexing #6718 
* [x] linalg #6746
* [x] logic #6727 
* [x] manipulation https://github.com/chainer/chainer/projects/2#card-20071153
* [x] math
  * [x] arithmetic #6723 
  * [x] trigonometric #6729 
  * [x] other #6842
* [x] normalization https://github.com/chainer/chainer/pull/6719
* [x] pooling https://github.com/chainer/chainer/pull/6800
* [x] sorting #6675
* [x] statistics https://github.com/chainer/chainer/projects/2#card-20071812
* [x] `Array` member functions #6834

**Comment by niboshi** [comment]
TODO: after finishing above tasks, we should review them once again. We introduced some additional convension after merging some of them.

**Comment by niboshi** [comment]
Also, we should rename macros:
* `CHAINERX_REGISTER_OP_CUDA` -> `CHAINERX_CUDA_REGISTER_OP`
* `CHAINERX_REGISTER_OP_NATIVE` -> `CHAINERX_NATIVE_REGISTER_OP`

**Comment by hvy** [comment]
Renamed in https://github.com/chainer/chainer/pull/6865.

**Comment by hvy** [comment]
Renamed "op" to "kernel" in https://github.com/chainer/chainer/pull/6944.

**Comment by niboshi** [comment]
Seems like this issue has been resolved.
