### ISSUE TITLE
Provide feature to automatically annotate NVVP profile results

### ISSUE THREAD

**Issue by kmaehashi** [chainer/chainer#6708]
https://github.com/lazykyama/chainer_profutil is useful tool and I would like to provide this feature by default.

**Comment by lazykyama** [comment]
Thanks for the attention for my tool and I'm really happy to see this issue. As mentioned, this functionality should be provided by Chainer itself. Let's discuss this topic here.

I'm attaching 2 images, first is before applying nvvp annotation and second is after applying the annotation.

<img width="479" alt="profiling_example_without_mark" src="https://user-images.githubusercontent.com/1679090/56106275-56007f00-5f7b-11e9-9abf-70fe3cead16f.png">

<img width="477" alt="profiling_example_with_mark" src="https://user-images.githubusercontent.com/1679090/56106286-5ef15080-5f7b-11e9-9711-54cf9c10fbc0.png">

Right now, this implementation is not reasonable to support multiple use cases (i.e., `StandardUpdater`, `MultiprocessParallelUpdater` and ChainerMN's multi node optimizer).
Need to add appropriate hooks for the all above cases.

**Comment by lazykyama** [comment]
To make it easy to analyse workloads, important hook timing are:
* before/after each iteration,
* before/after each forward/backward/update,
* before/after each layer.

In addition, IO pipeline and communication between GPUs should have corresponding markers. These are typical and it's helpful to analyze major bottlenecks if the makers are added.
