### ISSUE TITLE
[chainerx] Expression Template Possible?

### ISSUE THREAD

**Issue by kshitij12345** [chainer/chainer#6741]
[Expression Templates](https://en.wikipedia.org/wiki/Expression_templates) can provide performance gain by fusing operations and avoid temporaries.

To test this with a simple expression,
```python
import chainerx as chx

SIZE = 700
DEIVCE = 'cuda'

a = chx.random.normal(size=(SIZE, SIZE), device = DEIVCE).astype(chx.float32)
b = chx.random.normal(size=(SIZE, SIZE), device = DEIVCE).astype(chx.float32)
c = chx.random.normal(size=(SIZE, SIZE), device = DEIVCE).astype(chx.float32)
d = chx.random.normal(size=(SIZE, SIZE), device = DEIVCE).astype(chx.float32)
e = chx.random.normal(size=(SIZE, SIZE), device = DEIVCE).astype(chx.float32)

def compressed_compute(a,b,c,d,e):
    chx.compressed_compute(a,b,c,d,e)

def compute(a,b,c,d,e):
    return a + b + c - d + e
```
and timed it with 
```python
import timeit


print('Without Fused Operation :',timeit.timeit("f.compute(f.a,f.b,f.c,f.d,f.e)", "import f" ,number=100))
print('With Fused Operation :', timeit.timeit("f.compressed_compute(f.a,f.b,f.c,f.d,f.e)", "import f" ,number=100))
```

`compressed_compute` is just the binding for Kernels with 
```c++
struct Impl {
      void operator()(int64_t /*i*/, T a, T b, T c, T d, T e, T& out) { out = a + b + c -d + e; }
};
```

With Native, times are
```
Without Fused Operation : 0.37222791799968036
With Fused Operation : 0.17480791500020132
```
i.e. roughly half the time.

With CUDA, times are 
```
Without Fused Operation : 0.003559598000265396
With Fused Operation : 0.0008502600003339467
```
.i.e. roughly quarter the time.

I wonder if it would be possible to integrate this with Python Bindings to lazily evaluate and fuse ops.

Any thoughts?

**Comment by beam2d** [comment]
Where are the numbers coming from? Do you already have implementations for fusing operations?

**Comment by kshitij12345** [comment]
No I don't have an implementation.
Just to check if the hypothesis is correct, I manually added the function which did the same operation in a fused way with
`void operator()(int64_t /*i*/, T a, T b, T c, T d, T e, T& out) { out = a + b + c -d + e; }`.
