### ISSUE TITLE
ChainerX batch normalization may fail with CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by shinh** [chainer/chainer#6743]
If you use `chainerx.batch_norm` for a 2D/3D array, it fails with `CUDNN_STATUS_BAD_PARAM`. For users, it's hard to identify the reason of the failure. We could improve the error message like what we are doing for conv/pool.

```
Traceback (most recent call last):
  File "bn.py", line 14, in <module>
    print(chx.fixed_batch_norm(x, g, b, m, v))
chainerx.ChainerxError: CUDNN_STATUS_BAD_PARAM
```

Repro:

```
import chainerx as chx
import numpy as np

device = 'cuda:0'

def array(*shape):
    return chx.array(np.random.rand(*shape), device=device)

x = array(2, 5)
g = array(5)
b = array(5)
m = array(5)
v = array(5)
print(chx.fixed_batch_norm(x, g, b, m, v))
```

**Comment by crcrpar** [comment]
In my environment which lacks GPUs, this script worked.
I mean, CPU/native implementation seems not to have this bug.
