### ISSUE TITLE
cupy.asarray() bug

### ISSUE THREAD

**Issue by hokuto-k** [chainer/chainer#676]
I found cupy.asarray()'s bug when asarray() method try to convert a list of cupy.ndarray to single cupy.ndarray. In numpy, this operation is allowed.

``` python
In [1]: from chainer.cuda import cupy as cp

In [2]: a = cp.asarray([1,2])

In [3]: b = cp.asarray([3,4])

In [4]: c = [a,b]

In [5]: c
Out[5]: [array([1, 2]), array([3, 4])]

In [6]: cp.asarray(c)
Segmentation fault (コアダンプ)
```

**Comment by okuta** [comment]
Segmentation fault bug is fixed #665.
But, it is necessary to fix #667 in order to correct behavior.

**Comment by hokuto-k** [comment]
OK, it is duplicate so I'll close it.

**Comment by okuta** [comment]
`cupy.asarray()` can take array like object.
