### ISSUE TITLE
Snapshot consistency discussion

### ISSUE THREAD

**Issue by kuenishi** [chainer/chainer#6763]
When using GPU most computations are concurrent with main thread. Also, several snapshot writers are concurrent with main thread, e.g. `ThreadWriter` or `ProcessWriter` . There are some cases that's okay for consistent snapshot, but others may or may not be okay. Here's the table for potential inconsistency depending on combination of compute backend and snapshot writers by my survey.

| array\Writers | Simple | Thread | Process |
| ------------- | ------ | ------ | ------- |
| numpy         | ○     | ×     | ○      |
| cupy          | △     | △     | ×      |
| ChainerX/cpu  | ○     | ×     | ○      |
| Chainerx/gpu  | △     | △     | ×      |

- ○: Model-wide consistent snapshot ok
- △: Array-wide consistent snapshot
- ×: Not consistent potentially

This potential issue could be more apparent when writing to remote and slow storage.

Potential solution for this situation would be 
1. Add option to copy everything to on memory buffer at `__call__` call of writers.
2. Force copy at `__call__` call of writers.
3. Add option to copy everything to local temporary file and then move to remote.
9. Don't care.

As we can't avoid addition of another copy, the cost for this work would be performance and memory consumption of temporary snapshots. I want to discuss how do we fix this issue.

**Comment by niboshi** [comment]
@kuenishi We discussed today. Probabily we don't have to care about the performance implication of making copies, because I/O should always be a bottleneck. So how about (2), which is the safest solution?

By the way, why is cupy-Simple combination "△"? I think in this case copies are always made.

**Comment by kuenishi** [comment]
> By the way, why is cupy-Simple combination "△"? I think in this case copies are always made.

Although copying arrays happens at main thread, GPU computations are to be done asynchronously. There could be a time where updating params in CUDA streams *and* copying at main thread are in race. Copying each array are atomic but as a whole model updating each array may interleave copying multiple arrays.

> So how about (2), which is the safest solution?

I also have found another idea, which is adding a copy option flag passed to snapshot object. It might not be intuitive, but it would give the room for best choice to people keen at both performance and consistency, with the cost that leaving people a room to possibly make wrong choice.

**Comment by kuenishi** [comment]
But (2) is also fine to me, of course.

**Comment by niboshi** [comment]
>>By the way, why is cupy-Simple combination "△"? I think in this case copies are always made.
>
>Although copying arrays happens at main thread, GPU computations are to be done asynchronously. There could be a time where updating params in CUDA streams and copying at main thread are in race. Copying each array are atomic but as a whole model updating each array may interleave copying multiple arrays.

Ah, I see. Thank you for explanation. Hmm, it sounds it would be a non-trivial fix.

**Comment by kuenishi** [comment]
Yes, in that case we have to synchronize CUDA stream before making a copy. I might think it's worth paying the cost ... only when taking snapshots are rare enough.
