### ISSUE TITLE
Add Linear Algebra routines in ChainerX

### ISSUE THREAD

**Issue by IvanYashchuk** [chainer/chainer#6764]
I'd like to work on adding linear algebra routines to ChainerX during GSoC. Most of the `numpy.linalg` functions listed in [_ChainerX routines_ spreadsheet](https://docs.google.com/spreadsheets/d/1B4E78tw9Awgpcdn5G7zsQ8NVFYJdOoJlIQg42QxKNfU/edit#gid=0) have low priority, so their implementation probably can wait for the summer.

Many linalg operations have optimized implementations in various open source alternatives,
for example in LAPACK (there is a [C++ interface](https://github.com/michael-lehn/FLENS)).
Is it expected to implement forward operations from scratch, or link to existing implementations?

For autodiff, derivatives for some routines are described [here ](https://people.maths.ox.ac.uk/gilesm/files/NA-08-01.pdf)

Ref. #6423

**Comment by IvanYashchuk** [comment]
Here is the table to track the progress

| Routine           | Forward CUDA | Forward Native   | Backward | 
|----------------|---------------|---------------|----------------|
| [linalg.cholesky](https://github.com/chainer/chainer/pull/7329) | &#9745; |  |  | 
| [linalg.qr](https://github.com/chainer/chainer/pull/7379) | &#9745;  |  |  | 
| [linalg.svd](https://github.com/chainer/chainer/pull/7411) | &#9745;  |  |  | 
| [linalg.eigh]   | in progress |  |  | 
| [linalg.solve](https://github.com/chainer/chainer/pull/7474) | &#9745;|  |  | 
| [linalg.inv](https://github.com/chainer/chainer/pull/7474) | &#9745;|  |  | 
| [linalg.pinv](https://github.com/chainer/chainer/pull/7411)   | &#9745;|  |  |

**Comment by hvy** [comment]
#7474 has now been merged :)

**Comment by hvy** [comment]
It might be worth tracking in the above table whether the routine has been merged or not.

**Comment by hvy** [comment]
#7411 also merged.

**Comment by IvanYashchuk** [comment]
Notes Linear Algebra on several matrices at once:

Since NumPy 1.8 several of the `numpy.linalg` routines are able to compute results for several matrices at once, if they are stacked into the same array.
This generalizes the linear algebra operations to work on higher-dimensional arrays: the last 1 or 2 dimensions of a multidimensional array are interpreted as vectors or matrices, as appropriate for each operation.

cuSOLVER has specialized batched versions of a few routines
- [cusolverDn<t>potrfBatched](https://docs.nvidia.com/cuda/cusolver/index.html#cuds-lt-t-gt-potrfBatched)
- [cusolverDn<t>gesvdjBatched](https://docs.nvidia.com/cuda/cusolver/index.html#cuds-lt-t-gt-gesvdjbatch)
`cusolverDn<t>gesvdjBatched` requires that all matrices are not greater than 32x32
- [cusolverDn<t>syevjBatched](https://docs.nvidia.com/cuda/cusolver/index.html#cuds-lt-t-gt-syevjbatch)
`cusolverDn<t>syevjBatched` requires that all matrices are not greater than 32x32
As last two specialized GPU routines are restricted on allowed size it might be better to have them separately.
---
NumPy has this feature implemented using [`gufunc`](https://docs.scipy.org/doc/numpy-1.13.0/reference/c-api.generalized-ufuncs.html).

In ChainerX this can be done just looping over matrices on the routine level:
```
for (int64_t i = 0; i < batch_size; i++) {
  Array& a = batched_input.At(...)
  Array& out = batched_output.At(...)
  device.backend().CallKernel<LinalgKernel>(a, out);
}
```

Linalg routines make a working copy inside kernels, it might be better to create a copy once for the whole batched array and pass this working copy to the kernel. Some routines require transposed input matrix (because of column major ordering), then only last two dimensions of array has to be transposed.

Backward mode for many routines requires matrix-matrix multiplication.
Before going and implementing batched support for forward mode, `numpy.matmul` needs to be implemented in ChainerX first. `dot` and `matmul` work differently on higher-dimensional arrays.

Error handling needs to be done so that it is easy to identify and inform which input matrix in the stack is problematic.

**Comment by IvanYashchuk** [comment]
#7503 has now been merged.

**Comment by hvy** [comment]
I noticed that we've left the failing test to rely on `forward_accept_errors` but it's probably better to rewrite them using `pytest.raises`.
