### ISSUE TITLE
Improve Device.__str__

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#6772]
Currently device classes (`CpuDevice`, `GpuDevice`, `ChainerxDevice`, `Intel64Device`) only override `__repr__`. The resulting string is a bit cryptic for users.

https://github.com/chainer/chainer/blob/v6.0.0rc1/examples/mnist/train_mnist.py#L58

```
Device: <ChainerxDevice cuda:2>
```

**Comment by nishnik** [comment]
Hi @niboshi ,
I did some background research and there are four `Device` types we use:
- [CpuDevice](https://github.com/chainer/chainer/blob/master/chainer/backends/_cpu.py)
- [GpuDevice](https://github.com/chainer/chainer/blob/master/chainer/backends/cuda.py)
- [ChainerxDevice](https://github.com/chainer/chainer/blob/master/chainer/backends/_chainerx.py)
- [Intel64Device](https://github.com/chainer/chainer/blob/master/chainer/backends/intel64.py)

So we will need to define `__str__` for these classes.
What do you propose to add in those?

Currently, they return the following for `__repr__`:
- `CpuDevice`: <CpuDevice (numpy)>
- `GpuDevice`: <GpuDevice (cupy):{device.id}>
- `ChainerxDevice`: \<ChainerxDevice cuda:2\>
- `Intel64Device`: \<Intel64Device\>

**Comment by niboshi** [comment]
@nishnik 
Yes, there are the four device classes.

For concrete outputs, it would nice to match the device specifier as follows:

`CpuDevice`: `@numpy`
`GpuDevice`: `@cupy:2`
`ChainerxDevice`: `cuda:2`
`Intel64Devicd`: `@intel64`
