### ISSUE TITLE
Reorganize Chainer examples and make it runnable

### ISSUE THREAD

**Issue by kmaehashi** [chainer/chainer#6818]
Related to #6771.

Currently our example codes are copied to multiple locations:

* Examples (under `examples/`)
* Documentation (under `docs/source/examples`, some uses `literalinclude`)
* Chainer Colab Notebook (maintained by chug, https://chainer-colab-notebook.readthedocs.io/en/latest/official_examples.html)

Using [sphinx-gallery](https://sphinx-gallery.github.io/), we can build HTML and Jupyter notebook from the original python code (with embedded reST comments).

Note that when using sphinx-gallery, the code needs to be run during documentation build to generate output of each code (or cell). Maybe we need to separate examples and other docs.

**Comment by crcrpar** [comment]
>     * Documentation (under `docs/source/examples`, some uses `literalinclude`)

Do you mean `docs/source/guides`?

**Comment by kmaehashi** [comment]
No, I mean these examples:
https://docs.chainer.org/en/stable/examples/index.html

**Comment by crcrpar** [comment]
Ok.

I think it also be good if tutorials are runnable.
Or is there a plan to translate chainer/tutorials repo into English?

**Comment by mitmul** [comment]
We discussed this offline and decided to start from trying sphinx-gallery for the `train_mnist.py` example first. Then we'll see how good the approach is and discuss again the final way to deal with this issue. cc/ @Crissman
