### ISSUE TITLE
`test_huber_loss` is flaky

### ISSUE THREAD

**Issue by imos** [chainer/chainer#6906]
This is part of https://github.com/chainer/chainer/issues/6903 effort.

- Failure example: https://ci.preferred.jp/chainer.py27and35/2312/
- Failure test: chainer_tests/functions_tests/loss_tests/test_huber_loss.py
- Failure test case: `TestHuberLoss_param_14_{double_backward_options={'eps': 0.01, 'atol': 0.1, 'rtol': 0.1}, forward_options={}, reduce='no', backward_options={'eps': 0.01, 'atol': 0.01, 'rtol': 0.01}, shape=(4, 10), dtype=float64}.test_double_backward_gpu`
- Tolerance:
```
E           Not equal to tolerance rtol=0.1, atol=0.1
E           
E           Mismatch: 100%
E           Max absolute difference: 0.13130243
E           Max relative difference: 1.99520297
```

**Comment by niboshi** [comment]
Reoccurred
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1657/TEST=chainer-py3,label=mn1-p100/console
