### ISSUE TITLE
`test_tensordot` is flaky

### ISSUE THREAD

**Issue by imos** [chainer/chainer#6907]
This is part of https://github.com/chainer/chainer/issues/6903 effort.

- Failure example: https://ci.preferred.jp/chainer.py27and35/2328/
- Failure test case: `TestTensorDot_param_216_{gc_shape=(5, 6), axes=([1, 3, 2], [0, 1, 3]), a_dtype=float16, b_dtype=float16, a_shape=(5, 4, 2, 3), b_shape=(4, 3, 6, 2)}.test_tensordot_backward_gpu`
- Tolerance:
```
E           Not equal to tolerance rtol=0.01, atol=0.01
E           
E           Mismatch: 100%
E           Max absolute difference: 0.01180549
E           Max relative difference: 1.43404194
```

**Comment by hvy** [comment]
Hm, I cannot reproduce this locally. 🤔

**Comment by imos** [comment]
I will reopen this issue when I see this issue again. This issue has not observed since Apr 22, so this seems quite rare.
