### ISSUE TITLE
`test_normalization` is flaky

### ISSUE THREAD

**Issue by imos** [chainer/chainer#6913]
This is part of https://github.com/chainer/chainer/issues/6903 effort.

- Failure example: https://ci.preferred.jp/chainer.py37/2261/
- Failure test: chainerx_tests/unit_tests/routines_tests/test_normalization.py
- Failure test case: `test_BatchNorm_param_0_{contiguous=None}_param_0_{decay=None}_param_0_{eps=2e-05}_param_2_{param_dtype='float64'}_param_2_{x_dtype='float64'}_param_1_{x_shape=(2, 3, 4, 5), reduced_shape=(3, 4, 5), axis=(0,)}[native:0]`
- Tolerance:
```
E           Not equal to tolerance rtol=0.005, atol=0.0005
E           
E           Mismatch: 100%
E           Max absolute difference: 0.00113984
E           Max relative difference: 0.73910334
```

**Comment by imos** [comment]
Friendly ping. This flakiness still sometimes happens.

**Comment by hvy** [comment]
I also verified locally that this still happens, sorry for the delay. The cause is however not clear yet and  I'll have to investigate.

**Comment by hvy** [comment]
It only seems to occur when `eps=2e-5` (and not when `eps=5e-1`).

**Comment by hvy** [comment]
Hm, computed gradients are identical to Chainer.
