### ISSUE TITLE
`test_pooling` is flaky

### ISSUE THREAD

**Issue by imos** [chainer/chainer#6914]
This is part of https://github.com/chainer/chainer/issues/6903 effort.

- Failure example: https://ci.preferred.jp/chainer.py37/2131/
- Failure test: chainerx_tests/unit_tests/routines_tests/test_pooling.py
- Failure test case: `test_MaxPool_param_0_{cover_all=True}_param_3_{x_shape=(2, 3, 4, 4), ksize=(3, 3), stride=1, pad=0}[float16-cuda:0]`
- Tolerance:
```
E           Not equal to tolerance rtol=0.05, atol=0.001
E           
E           Mismatch: 100%
E           Max absolute difference: 0.02809935
E           Max relative difference: 3.95447233
```

**Comment by hvy** [comment]
Similar instability for Chainer's max pooling is fixed in https://github.com/chainer/chainer/pull/6917. Leave it for reference.
