### ISSUE TITLE
[chainerx] update Amin op registration

### ISSUE THREAD

**Issue by kshitij12345** [chainer/chainer#6923]
The build is crashing due https://github.com/chainer/chainer/blob/1e3b666a2eb3c7d327ed059188a086313423da8f/chainerx_cc/chainerx/cuda/cuda_device/reduction.cu#L149

and

https://github.com/chainer/chainer/blob/1e3b666a2eb3c7d327ed059188a086313423da8f/chainerx_cc/chainerx/native/native_device/reduction.cc#L126

**Comment by hvy** [comment]
Should be fixed https://github.com/chainer/chainer/pull/6922.

**Comment by hvy** [comment]
Should be fixed now that https://github.com/chainer/chainer/pull/6922 is merged.
