### ISSUE TITLE
Don't install cupy when core module is not compiled correctly

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#707]
When cupy is not compiled correctly, `import cupy` shows this error message:

```
ImportError: cannot import name core
```

`core` is a Cython module. When configuration is invalid, for example when CUDA is not found, this module cannot be compiled.

We need to stop install CuPy itself in such case. Or, we need to split repositories and packages.

**Comment by unnonouno** [comment]
Changing install packages after build is not easy. This issue is automatically solved when we split Chainer and CuPy, because we can stop installing CuPy when core is not correctly built.

**Comment by beam2d** [comment]
CuPy is separated out to another package, and Chainer does not install it automatically now, so this issue has been fixed.
