### ISSUE TITLE
Variable.addgrad with mismatched dtype might not cause error

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#7136]
Version: current mater 8565bad9334f6cc32cd70a9d79fd42f74eeec3c2
```py
import chainer
import numpy as xp

a = chainer.Variable(xp.array([1, 1], 'float32'))
#a.grad = xp.array([3, 5], 'float32')

b = chainer.Variable(xp.array([2, 2], 'float64'))
b.grad = xp.array([4, 7], 'float64')

a.addgrad(b)

print(a.dtype, a.grad.dtype)
```

An error is expected but it results in the following output (indicating mismatched gradient dtype)
```
float32 float64
```

If the comment-out is removed, it becomes an error:
```
chainer.utils.type_check.InvalidType: 
Invalid operation is performed in: _ + _ (Forward)

Expect: lhs.dtype == rhs.dtype
Actual: float64 != float32
```

**Comment by niboshi** [comment]
It seems the `Link` test relies on this behavior (probably unintentionally) :
https://github.com/chainer/chainer/blob/v6.0.0rc1/tests/chainer_tests/test_link.py#L543

`self.link.u.dtype` is `float64` whereas `l.u.dtype` is `float32`.

**Comment by hvy** [comment]
For the record, although the error message can be improved (and is by #7140), the expected error in the above example is now raised as expected, in the current master.
