### ISSUE TITLE
math.cc is large

### ISSUE THREAD

**Issue by asi1024** [chainer/chainer#7143]
Split large routines/math.cc into several files.

- [x] arithmetic.cc #7415 
  - chainerx.negative
  - chainerx.add
  - chainerx.subtract
  - chainerx.multiply
  - chainerx.divide
  - chainerx.reciprocal

- [x] explog.cc #7317
  - chainerx.exp
  - chainerx.log
  - chainerx.log10

- [x] reduction.cc #7270
  - chainerx.sum
  - chainerx.logsumexp
  - chainerx.logsumexp
  - chainerx.log_softmax

- [x] trigonometric.cc #7171 
  - chainerx.sin
  - chainerx.cos
  - chainerx.tan
  - chainerx.arcsin
  - chainerx.arccos
  - chainerx.arctan
  - chainerx.arctan2

- [x] hyperbolic.cc #7171
  - chainerx.sinh
  - chainerx.cosh
  - chainerx.tanh
  - chainerx.arcsinh
  - chainerx.arccosh

- [x] rounding.cc #7407
  - chainerx.ceil
  - chainerx.floor

- [x] misc.cc #7298
  - chainerx.sqrt
  - chainerx.square
  - chainerx.squared_difference
  - chainerx.absolute
  - chainerx.fabs
  - chainerx.sign
  - chainerx.maximum
  - chainerx.minimum

- [x] binary.cc #7128 
  - chainerx.bitwise_and
  - chainerx.bitwise_or
  - chainerx.bitwise_xor

- [x] activation.cc #7496
  - chainerx.relu
  - chainerx.sigmoid

- [x] statistics.cc #7222 
  - chainerx.amin
  - chainerx.amax
  - chainerx.mean
  - chainerx.var

- [x] logic.cc #7444 
  - chainer.isnan
  - chainer.isinf
  - chainer.isfinite

**Comment by hvy** [comment]
Finished!
