### ISSUE TITLE
Is any generated date&time related info included in the body of a trained model?

### ISSUE THREAD

**Issue by superhez** [chainer/chainer#7286]
Could anyone tell me if there is any generated date&time related information included in the body of a trained model? If there is, how to read it out? Thanks.

**Comment by kmaehashi** [comment]
Currently such record is not included in the model. May I ask for what purpose did you need it?

**Comment by superhez** [comment]
> Currently such record is not included in the model. May I ask for what purpose did you need it?

Sorry for late reply. I am just wondering if there were mentioned record included, it might be used to manage the trained models  as a much reliable evidence than file's created/modified properties or the filename.
