### ISSUE TITLE
Strict scatter_dataset and more flexible multinode evaluator

### ISSUE THREAD

**Issue by kuenishi** [chainer/chainer#7305]
The rationale behind https://github.com/chainer/chainercv/pull/868 is

- Current `scatter_dataset` implicitly appends duplicate data for odd number of test dataset to communicatgor size
- Some evaluators does not allow naive summation or average of results of scattered test data

The case above is calculating standard mAP in object detection but not easy with current MultiNodeEvaluator.

We have to understand more about above case and other cases such as object segmentation, NLP and so on. RL is not using Chainer's trainer scheme so far, could be out of scope.

**Comment by iwiwi** [comment]
FYI: duplicate with the former one https://github.com/chainer/chainermn/issues/274

**Comment by kuenishi** [comment]
I want to discuss the design with ...
- WIP branch: https://github.com/chainer/chainer/compare/master...kuenishi:strict-multinode-evaluator
- ChainerCV's example: https://gist.github.com/kuenishi/fa20a88881beffd3cccbd6c15d62522e

On...
- converter, eval_func, aggreation funcs are to be injected as function
- Design simplicity and level of abstraction (too close to ChainerCV's apply_to_iterator?)

**Comment by kuenishi** [comment]
After offline discussion:
- inheritance style is more preferred than plugging callable objects on callbacks
- no need for generator; debuggable is preferred and give a list to aggregator
- ProgressHook to be given from users
- naming: eval_func & aggregate -> calc_local & aggregate

**Comment by kuenishi** [comment]
Additional requiest:

- Hope it works in non-MPI env dummy-like single proc communicator or `comm=None`
