### ISSUE TITLE
`chainer.get_device(10)` does not cause error

### ISSUE THREAD

**Issue by corochann** [chainer/chainer#7309]
Testing under chainer==6.0.0 with chainerx built and cupy installed.
Testing environment has only 1 GPU.

```
import chainer


device = chainer.get_device(10)          # NOT Cause error!
print('device', device)  # @cupy:10
device2 = chainer.get_device('cuda:10')  # Cause error!
print('device2', device2)
```

When we try to get GPU device with id more than allowed, the behavior is different between cupy & chainerx cuda device.
 - cupy: does not raise error 
 - chainerx cuda: raise error

I think raising error is more convenient for users. How do you think?

**Comment by hvy** [comment]
Note that if we query the device count, the CUDA environment will be initialized and the `MultiprocessParallelUpdater` can no longer be used https://github.com/chainer/chainer/blob/master/chainer/training/updaters/multiprocess_parallel_updater.py#L136-L140 ?

**Comment by niboshi** [comment]
Pytorch's way of multiprocessing:
https://gist.github.com/colesbury/606e3838d56ca33996cc40ef00bcdb6b

Much cleaner.

**Comment by emcastillo** [comment]
@hvy the device count can be queried when initializing chainer by doing a fork,  that way the cuda context is destroyed and `MultiprocessParallelUpdater` can be used, #7413 tries to do this.

**Comment by niboshi** [comment]
@emcastillo I don't think we should do such a trick. Even if we can avoid CUDA context creation in `chainer.get_device()`, CUDA context can be created anywhere else.  It's just one instance of such possibilities. The problem won't be gone by fixing only `chainer.get_device()`.

`MultiprocessParallelUpdater` can produce comprehensible error, so it's OK to just let `chainer.get_device()` create CUDA context. See also #7470.

**Comment by niboshi** [comment]
The above comment assumes users can easily avoid such error by doing [something like this](https://discuss.pytorch.org/t/a-call-to-torch-cuda-is-available-makes-an-unrelated-multi-processing-computation-crash/4075/2).

I thought the following snippet in user's script would solve the problem, but tried in imagenet data parallel example, it does not avoid CUDA context and causes another error related to `ForkingPickler`.
```python
import multiprocessing
if __name__ == '__name__':
    multiprocessing.set_start_method('spawn')
``` 
Am I missing something?

**Comment by emcastillo** [comment]
In my case the multiprocessing.set_start_method('spawn') keeps failing with the cuda context issue

**Comment by niboshi** [comment]
@emcastillo Did you remove the `_cuda_initialized` check in `MultiprocessParallelUpdater.__init__()`? Presence of CUDA context in the main process is not essential.

**Comment by emcastillo** [comment]
Ok! I will try it now, thanks!

**Comment by emcastillo** [comment]
#7486 correct the pickle behavior by re-creating the lock when the object is deserialized.
