### ISSUE TITLE
Add to `StandardUpdater` an option to skip model transfer

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#7322]
Background: #7220

>* [ ] c. `StandardUpdater` transfers the model parameters, which causes device mismatch.
>   - Add `model_device` and `input_device` options to `StandardUpdater` (the existing `device` option will be an alias of the former), to specify the devices to transfer the model and the input data respectively. If `model_device` is omitted, it skips the model transfer. If `input_device` is omitted, `model_device` is used to transfer the data.

**Comment by hvy** [comment]
Fixed by https://github.com/chainer/chainer/pull/7472.
