### ISSUE TITLE
Is there any future plan to include a wrapper to interfac with Scikit Learn's Model Selection for grid search of hyperparams?

### ISSUE THREAD

**Issue by xylee95** [chainer/chainer#7348]
Are there any future plans to include a wrapper to interface with Scikit Learn's Model Selection for grid search of hyperparams?

**Comment by emcastillo** [comment]
Thank you for your feedback!

Unfortunately we do not plan to directly interface chainer models with sklearn.
However it is not difficult to do it from the user side, I share a gist here that shows how to wrapper a chainer classifier inside a sklearn estimator interface for grid search and other hyper parameter tuning strategies to work. Please note that GridSearchCV relies on cross-validation with multiple train/test data splits and it might be difficult to completely adapt it to chainer model training. 

https://gist.github.com/emcastillo/f483cdfc6486a34e5b9dfdb203f930db

If you are interested on doing hyper parameter search with chainer, we strongly recommend you to try Optuna 

https://github.com/pfnet/optuna

Here is a example using a chainer model

https://github.com/pfnet/optuna/blob/master/examples/chainer_simple.py
