### ISSUE TITLE
Buffer Protocol Support in ChainerX ndarray

### ISSUE THREAD

**Issue by y1r** [chainer/chainer#7476]
I want to use `mpi4py allreduce` in ChainerX ndarray in order to support use of MultiNodeEvaluator in ChainerX network model.
However, ChainerX doesn't support buffer protocol so mpi4py couldn't handle ChainerX object.

(Actually, I found ChainerX.ndarray wants to support bufferprotocol (https://github.com/chainer/chainer/blob/master/chainerx_cc/chainerx/python/array.cc#L160), but there is no `def_buffer`)

You can try below simple script.

```py
import chainerx as chx
import numpy as np

from mpi4py import MPI

def check_bp(array):
    try:
        memoryview(array)

        return True
    except BufferError:
        return False


if __name__ == '__main__':
    comm = MPI.COMM_WORLD
    print("MPI_WORLD_SIZE: ", comm.size)

    # NumPy
    rank_np = np.asarray([comm.rank])
    print("NumPy: ", rank_np)
    print("Buffer Protocol Support of NumPy: ", check_bp(rank_np))

    rank_np = comm.allreduce(rank_np)

    print("NumPy AllReduce: ", rank_np)

    # ChainerX
    rank_chx = chx.asarray([comm.rank])
    print("ChainerX: ", rank_chx)
    print("Buffer Protocol Support of ChainerX: ", check_bp(rank_chx))

    rank_chx = comm.allreduce(rank_chx)

    print("ChainerX AllReduce: ", rank_chx)
```

```
$ mpiexec -N 2 python test.py
MPI_WORLD_SIZE:  2
MPI_WORLD_SIZE:  2
NumPy:  [1]
Buffer Protocol Support of NumPy:  True
NumPy:  [0]
Buffer Protocol Support of NumPy:  True
NumPy AllReduce:  [1]
NumPy AllReduce:  [1]
ChainerX:  array([0], shape=(1,), dtype=int64, device='native:0')
ChainerX:  array([1], shape=(1,), dtype=int64, device='native:0')
Buffer Protocol Support of ChainerX:  False
Buffer Protocol Support of ChainerX:  False
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    rank_chx = comm.allreduce(rank_chx)
  File "mpi4py/MPI/Comm.pyx", line 1289, in mpi4py.MPI.Comm.allreduce
  File "mpi4py/MPI/msgpickle.pxi", line 1216, in mpi4py.MPI.PyMPI_allreduce
  File "mpi4py/MPI/msgpickle.pxi", line 1168, in mpi4py.MPI.PyMPI_allreduce_intra
  File "mpi4py/MPI/msgpickle.pxi", line 1018, in mpi4py.MPI.PyMPI_reduce_p2p
  File "mpi4py/MPI/msgpickle.pxi", line 950, in mpi4py.MPI.PyMPI_copy
  File "mpi4py/MPI/msgpickle.pxi", line 104, in mpi4py.MPI.Pickle.dump
  File "mpi4py/MPI/msgpickle.pxi", line 91, in mpi4py.MPI.Pickle.cdumps
RuntimeError: return_value_policy = copy, but the object is non-copyable!
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    rank_chx = comm.allreduce(rank_chx)
  File "mpi4py/MPI/Comm.pyx", line 1289, in mpi4py.MPI.Comm.allreduce
  File "mpi4py/MPI/msgpickle.pxi", line 1216, in mpi4py.MPI.PyMPI_allreduce
  File "mpi4py/MPI/msgpickle.pxi", line 1168, in mpi4py.MPI.PyMPI_allreduce_intra
  File "mpi4py/MPI/msgpickle.pxi", line 1018, in mpi4py.MPI.PyMPI_reduce_p2p
  File "mpi4py/MPI/msgpickle.pxi", line 950, in mpi4py.MPI.PyMPI_copy
  File "mpi4py/MPI/msgpickle.pxi", line 104, in mpi4py.MPI.Pickle.dump
  File "mpi4py/MPI/msgpickle.pxi", line 91, in mpi4py.MPI.Pickle.cdumps
RuntimeError: return_value_policy = copy, but the object is non-copyable!
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[3381,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by keisukefukuda** [comment]
Thanks for creating the issue.
There are several design choices to solve the issue and we need further discussion on this.

FYI, CuPY's array does not support BufferProtocol on purpose for some reasons.
If ChainerX has a plan to support BufferProtocol, then it's ChainerX's issue.
Otherwise, it is ChainerMN's issue. It needs to support ChainerX buffer in the same manner for 
CuPy array.

**Comment by emcastillo** [comment]
Hello,
We were just discussing this issue, we dropped BufferProtocol support due to conflicts with numpy array conversion. We thought that the most appropriate way is to work on the support for ChainerMN.

Thanks.

**Comment by keisukefukuda** [comment]
After offline discussions, we will fix this issue by modifying communicator's functions.

**Comment by leofang** [comment]
Just came across this issue. I am not familiar with ChainerX ndarray, but if it has `__cuda_array_interface__`, then a recent change we made to mpi4py (starting at commit https://github.com/mpi4py/mpi4py/commit/a52ac168c38bdd6f820ab221a19e53c6813621df) would allow it to be used directly with MPI calls such as `Allreduce` as you needed, provided that mpi4py is built against a CUDA-aware MPI. Then, the need for supporting buffer protocol might be eliminated. 

For more information, see the following links:
- https://mpi4py.readthedocs.io/en/latest/overview.html#support-for-cuda-aware-mpi
- https://docs-cupy.chainer.org/en/latest/reference/interoperability.html#mpi4py
- https://github.com/cupy/cupy/pull/2270

To use this feature, for the time being please build mpi4py from source. We plan to roll it out in mpi4py v3.1.0 later.

**Comment by keisukefukuda** [comment]
@leofang thanks for the info! We'll consider using it.

**Comment by keisukefukuda** [comment]
After some offline discussions, we decided that ChainerMN will handle ChainerX array, so buffer protocol support is no longer necessary. 
So I will close this issue and continue ChainerX support in other issues and PRs.
