### ISSUE TITLE
Avoid hardcoded hyperparameter correction in `MultiprocessParallelUpdater`

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#7481]
`MultiprocessParallelUpdater` has hardcoded hyperparameter correction. This is not very flexible and can cause unexpected malfunction.

https://github.com/chainer/chainer/blob/v7.0.0a1/chainer/training/updaters/multiprocess_parallel_updater.py#L145

**Comment by emcastillo** [comment]
Should we add a method to the optimizer to delegate this?

class Optimizer:
    def multidevice_hyperparameter_correction(self, num_devices):

**Comment by niboshi** [comment]
That approach seems good.

**Comment by emcastillo** [comment]
Ok, I will take care of this :)

**Comment by emcastillo** [comment]
#7494 is a first implementation
