### ISSUE TITLE
Live monitoring

### ISSUE THREAD

**Issue by sinhrks** [chainer/chainer#75]
Thanks for sharing the great package. It's nice if we can monitor the real-time progress like othe DL packages, though I only know some of them.
- http://daemonmaker.blogspot.ca/2014/12/monitoring-experiments-in-pylearn2.html
- http://blocks.readthedocs.org/en/latest/plotting.html

I've created an example using [`Bokeh`](http://bokeh.pydata.org/en/latest/) in sinhrks/chainer@fbc933f4001fb51295bf5fd25694463affc93d0a :
1. Install `Bokeh`
   
   `pip install bokeh`
2. Run `bokeh-server`
   
   `$ bokeh-server&`
3. Run `examples/mnist/train_mnist_monitoring.py`
4. Web-browser is automatically open displaying the real-time progress of the training.
   
   ![2015-06-21 18 10 43](https://cloud.githubusercontent.com/assets/1696302/8271199/c04c48ac-1845-11e5-8fc2-23899d503291.png)
   
   `Bokeh` allows us to perform zoom/move charts interactively.
   
   ![2015-06-21 18 25 02](https://cloud.githubusercontent.com/assets/1696302/8271201/c5b84c1e-1845-11e5-91e9-26f9fb5f57a5.png)

If this can be a focus of the project, would like to discuss how this can be handled (standardize or put it to example / document, etc).

**Comment by beam2d** [comment]
Thank you for sharing the beautiful plotting! We think it's very useful, though we want to keep the library compact and examples in the repository simple. We are now thinking about providing a list of useful external examples. It must include your plotting example.

**Comment by unnonouno** [comment]
I made a list of external examples as a wiki page. I want to refer your example code from the list. Could you make an independent repository for live monitoring example? I'll add the repository to the list.

https://github.com/pfnet/chainer/wiki/External-examples

**Comment by sinhrks** [comment]
Thanks for your consideration. Will do.
