### ISSUE TITLE
`StandardUpdater` with `GpuDevice` `device` argument skips D2D transfer

### ISSUE THREAD

**Issue by hvy** [chainer/chainer#7504]
This is mostly due to a historical reason, to support multi-device training. If the model is transferred and split into multiple devices, the `StandardUpdater` given the model should not transfer the model at all. But the converter used inside the updater must know to which device input data should be transferred and hence the `device` argument was needed for that purpose. The issue basically was that the model device and the input data device was controlled through the same `device` argument.

We've discussed to fix it using a new `input_device` argument.

- [x] Introduce `input_device` to allow specifying separate devices for the model and the data. Then `device` can be used only to control the model, meaning it can be omitted to allow the above multi-device scenario. https://github.com/chainer/chainer/pull/7472
- [ ] Change `device` to always transfer since the "hack" is not needed.
   - [x] Raise `FutureWarning`. #7952
   - [ ] Change behavior. **(won't fix)**

**Comment by kmaehashi** [comment]
@niboshi Could you update the status?

**Comment by niboshi** [comment]
As there will be no major release any more, I close this issue.
