### ISSUE TITLE
feature request: Variable.to_cpu() returns self.

### ISSUE THREAD

**Issue by F-Tag** [chainer/chainer#7568]
Link.to_cpu() and Parameter.to_cpu() return self. 
Is there any reason why the variable.to_cpu() does not?

If so, the code to get numpy.array from Variable on GPU can be written in one line as follows:
```
np_arr = var.to_cpu().array
```

**Comment by crcrpar** [comment]
I do not know the reason nor the context.

Though, I would use following functions when I want the numpy.ndarray from a `chainer.Variable`
- `np_arr = chainer.backends.cuda.to_cpu(var.array)` if chainerx is not enabled.
- `np_arr = chainer.backends.cuda.to_cpu(chainer.backend.from_chx(var.array)` if chainerx is enabled.

ref

- https://docs.chainer.org/en/stable/reference/backends.html#concrete-device-classes

best regards

**Comment by hvy** [comment]
Possible a duplicate of https://github.com/chainer/chainer/issues/6181.

**Comment by toslunar** [comment]
> Though, I would use following functions when I want the numpy.ndarray from a `chainer.Variable`
> 
>   * `np_arr = chainer.backends.cuda.to_cpu(var.array)` if chainerx is not enabled.
> 
>   * `np_arr = chainer.backends.cuda.to_cpu(chainer.backend.from_chx(var.array)` if chainerx is enabled.

I'd write `np_arr = chainer.get_device('@numpy').send(var.array)` since v6.
