### ISSUE TITLE
feature request: NstepLSTMP 

### ISSUE THREAD

**Issue by F-Tag** [chainer/chainer#7569]
LSTMP(LSTM with Recurrent Projection Layer) is often used in acoustic modeling.
Cudnn seems to support LSTMP.
Do you have the plan to support LSTMP?

LSTMP paper:
https://static.googleusercontent.com/media/research.google.com/ja//pubs/archive/43905.pdf

**Comment by beam2d** [comment]
We currently do not have any plan to support it. Contributions are always welcome!
