### ISSUE TITLE
`SerialIterator` ChainerX support

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#7583]
Part of #7541

**Comment by niboshi** [comment]
It seems no additional change/test are needed.
Can we just close the issue?

**Comment by hvy** [comment]
Looking at the class definition and the existing tests for it (and the fact that it's "tested" by examples), I think that's okay.

**Comment by niboshi** [comment]
@hvy 

>and the fact that it's "tested" by examples

It sounds to be something I should correct.
Examples are not tests. If there are anything that must be tested, that should be done by tests, not examples.

In the case of `SerialIterator`, no test is needed because its specification is ignorant of backends.
