### ISSUE TITLE
Grad of weight decay is wrong when using `update_rule.add_hook`

### ISSUE THREAD

**Issue by shu65** [chainer/chainer#7597]
Thank you for fixing this issue https://github.com/chainer/chainer/issues/7335 
But, the grad of wight decay is wrong with this modification when using `update_rule.add_hook` .

The flow of the update is as follows.
1. call hook of an optimizer https://github.com/chainer/chainer/blob/5289f671411b7eaf90492df6463ff51dd0724e91/chainer/optimizer.py#L810
2. divide grad by loss scale https://github.com/chainer/chainer/blob/5289f671411b7eaf90492df6463ff51dd0724e91/chainer/optimizer.py#L206
3. call hook of an `UpdateRule` https://github.com/chainer/chainer/blob/5289f671411b7eaf90492df6463ff51dd0724e91/chainer/optimizer.py#L208
4. update parameters

so, grad of weight decay is `loss_scale` times larger than the expected value when using `update_rule.add_hook`

**Comment by shu65** [comment]
I found a note.
when using fp32_update mode, this line is performed.
https://github.com/chainer/chainer/blob/master/chainer/optimizer.py#L208

But, weight decay with loss scale is wrong because `fp32_param.__loss_scale` is always `None`.
I think loss scale is copied from `param` to `fp32_param`.

Sample code is here:
```
        if self._use_fp32_update and param.dtype == numpy.float16:
            if self._fp32_param is None:
                self._fp32_param = variable.Variable(
                    param.array.astype(numpy.float32),
                    name=param.name)
            fp32_param = self._fp32_param
            fp32_param.grad = param.grad.astype(numpy.float32)
            fp32_param._loss_scale = param._loss_scale
            if fp32_param.data is not None:
                self._prepare(fp32_param)
```
when using dynamic loss scaling, loss scale is changed every iteration. So, loss scale requires to be copied every iteration.

**Comment by gwtnb** [comment]
Could you replace URLs of the master branch to URLs of the specific commit? The master branch is not fixed, so one cannot understand what you said after the master branch is updated.

**Comment by toslunar** [comment]
> Could you replace URLs of the master branch to URLs of the specific commit?

Done.
