### ISSUE TITLE
ChainerX routines never raise Python primitive exception

### ISSUE THREAD

**Issue by asi1024** [chainer/chainer#7613]
Currently, ChainerX routines raise only ChainerX specific exceptions.  However, if a NumPy's function raises a Python primitive exception, the corresponding ChainerX routine also should the same exception.

I have started wanting this compatibility when I was extending `__getitem__` (https://github.com/chainer/chainer/pull/7561#issuecomment-505424397).

**Comment by take-cheeze** [comment]
Seems we need an exception policy in C++ code and binding code.
I've faced the same problem when implementing clip function( https://github.com/chainer/chainer/pull/7285 ):
https://github.com/chainer/chainer/blob/139de248629a3efccf6734565f64ab39a2fabbfb/chainerx_cc/chainerx/python/routines.cc#L674-L676

**Comment by take-cheeze** [comment]
I think we shouldn't raise `ChainerxError` directly so that to handle all ChainerX error `ChainerxError` could used in `catch` and the specific type of exception to handle the specific error.
We should add exception translator from C++ to python too.

**Comment by hvy** [comment]
These C++/Python exception policies are probably topics that has not been discussed enough. Some random thoughts to share.

- We should at least provide the same level of exception granularity in C++ as the Python/NumPy API is designed for to address this original issue.
- Currently,`ChainerxError` is used quite casually as a general purpose error (i.e. as a `std::runtime_error`) but we should reconsider the purpose/necessity of this class if we allow throwing std exceptions. If we don't then all exception types in ChainerX could derive this class which would be useful if we'd add functionality(?) to it but this would also increase the maintenance cost along with the number of custom exception types needed.
