### ISSUE TITLE
F.concat fails with an error with one chainer.Variable

### ISSUE THREAD

**Issue by knorth55** [chainer/chainer#7626]
Chainer: `master` branch
Probably, this error is caused by this commit https://github.com/chainer/chainer/commit/34c3ab29b7526d36e03a8560073f30dffbe31c55 ?

```python
$ ipython
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import chainer
In [2]: import numpy as np
In [3]: a = chainer.Variable(np.random.random((2, 3, 4)).astype(np.float32))
In [4]: chainer.functions.concat(a, axis=0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-04bc1911ca70> in <module>()
----> 1 chainer.functions.concat(a, axis=0)

~/projects/chainer/chainer/functions/array/concat.py in concat(xs, axis)
    106 
    107     """
--> 108     y, = Concat(axis).apply(xs)
    109     return y

~/projects/chainer/chainer/function_node.py in apply(self, inputs)
    262         chainerx_in_data = None
    263         chainerx_device = None
--> 264         is_chainerx, in_data = _extract_apply_in_data(inputs)
    265 
    266         if is_chainerx:

~/projects/chainer/chainer/function_node.py in _extract_apply_in_data(inputs)
   1197     # If at least one of the arrays is a ChainerX array, all other NumPy/CuPy
   1198     # arrays are converted to ChainerX arrays without copy.
-> 1199     if not inputs:
   1200         return False, ()
   1201 

~/projects/chainer/chainer/variable.py in __bool__(self)
   1602         # Python 3.x
   1603         raise TypeError(
-> 1604             'Variables cannot be evaluated as Python bool.')
   1605 
   1606     __array_priority__ = 200  # type: int

TypeError: Variables cannot be evaluated as Python bool.
```

**Comment by knorth55** [comment]
https://docs.chainer.org/en/latest/reference/generated/chainer.functions.concat.html
according to the documentation, API supports multi-array variable, too.

**Comment by crcrpar** [comment]
While the documentation assumes `xs` to be a tuple of `chainer.Variable`/`ndarray`s, the function does not assert this. 🤔 
https://github.com/chainer/chainer/blob/9350c4bd51aef8c22d707b2bc8ddaaeac4d2f440/chainer/functions/array/concat.py#L80

**Comment by knorth55** [comment]
Oh, it only supports multi-dimension array not multi-dimension variable.
I didn't realize that.
Anyway, 
- 1. `concat` functions doesn't assert its input type
- 2. I think it would be convenient if we can do `F.concat`  with multi-dimension variable (I always do so until v6)

**Comment by crcrpar** [comment]
> Oh, does it only support multi-dimension array, not multi-dimension variable?

No, it does support `chainer.Variable`s also.

**Comment by knorth55** [comment]
i mean not tuple of Variables, but just one Variable.
But in my case, i can use `reshape` function, anyway.

**Comment by crcrpar** [comment]
Ah, my bad.

Yes, the behavior depends on the inputs types.

**Comment by knorth55** [comment]
Yes.
However, 1) it is better to check input type before `_extract_apply_in_data` and 2) it would be good to support one Variable.
