### ISSUE TITLE
Check warnings in test

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#767]
Chainer uses deprecated methods in its code. Change warning level and check warnings in its test.
related to #755

**Comment by delta2323** [comment]
Could you write in more detail what is the desirable behavior? I mean, how should we change the warning level and check the warning?

**Comment by delta2323** [comment]
Do the following changes agree with your intent?

* Not to use deprecated methods in Chainer's implementation.
* To suppress deprecation warnings when we test methods that are deprecated.
* To show explicitly deprecation warnings otherwise (i.e. the method tested is not deprecated).

**Comment by unnonouno** [comment]
Chainer itself must not use deprecated methods. Current implementation uses deprecated methods and no one check it.

And, we need to check if deprecated methods actually show deprecation warning. This is another issue.

**Comment by delta2323** [comment]
OK. I understand that #769 prevents test cases from suppressing warning messages if they emit and does not check functions tested actually show messages.

**Comment by unnonouno** [comment]
In #769 I fixed all deprecated warnings from chainer, but other types of warnings remain.
I also fixed the configuration file for travis to show warning messages. We can check warning message in logs of travis.
Next, we need to remove all warnings related to numpy from tests.

**Comment by delta2323** [comment]
I see. I had not cared the type of warnings. Now I think I can check #769. If you have already noticed some warnings about numpy show up, could you register the issue about it?

**Comment by unnonouno** [comment]
- ptorobuf shows a lot of warnings
- boolean subtract is deprecated in numpy https://github.com/numpy/numpy/blob/v1.10.2/numpy/core/src/umath/ufunc_type_resolution.c#L386
- ufunc shows deprecated warnings (it'll be fixed in #781)
