### ISSUE TITLE
Avoid `np.empty` in unit tests

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#7672]
Some tests (particularly those checks for in-place operations) fail to catch incorrect implementation, because it can allocate just-freed memory which holds the "correct" data.

Example: https://github.com/chainer/chainer/pull/7548#discussion_r299316261

**Comment by sameshl** [comment]
@niboshi I would love to work on this. Can you elaborate a bit on what I am supposed to do?

**Comment by niboshi** [comment]
@sameshl Thank you for your interest!
What's supposed to be done is to grep for `"empty"` under `tests/chainer_tests/` and replace `numpy.empty` (and `numpy.empty_like`) with something else, like `numpy.random.randn`.
