### ISSUE TITLE
Flaky test: `chainerx_tests/unit_tests/routines_tests/test_connection.py::test_ConvTransposeTensorCore`

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#7686]
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1479/TEST=CHAINERX_chainerx-py3,label=mn1-p100/console

**Comment by niboshi** [comment]
cc: @asi1024

**Comment by asi1024** [comment]
In this Jenkins test, ChainerX was built with compute_capability=60, so TensorCore was disabled.

**Comment by emcastillo** [comment]
Merged
