### ISSUE TITLE
Flaky test: tests/chainer_tests/functions_tests/connection_tests/test_convolution_nd.py

### ISSUE THREAD

**Issue by emcastillo** [chainer/chainer#7695]
[Jenkins](https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1493/TEST=chainer-py2,label=mn1-p100/testReport/tests.chainer_tests.functions_tests.connection_tests.test_convolution_nd/TestConvolutionND_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_0__use_cudnn_always__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_80_%7Bb_dtype=float32,%20dims=(3,%204,%203),%20autotune=False,%20cover_all=False,%20groups=1,%20dilate=1,%20nobias=True,%20contiguous='C',%20W_dtype=float32,%20x_dtype=float32%7D/test_backward/)

cuDNN & CUDA versions for Jenkins tests

`chainer` tests
| chainer | CUDA | CUDNN |
| --- | ---- | --- |
| py2     | 8.0  | 5.0   |
| py3     | 10.1 | 7.5   |
| py35    | 9.2  | 7.1.4 |

imosci uses cuDNN 7.5.0
cupy included cuDNN is 7.5.0

**Comment by emcastillo** [comment]
I have been working into this issue and found the following.

After setting the test with the same parameters as Jenkins (copying all the random generated arrays).
I verified that the gradient of the test was similar to the one appearing on jenkins.
```
gradients (numeric):  -0.017547332620302745
gradients (backward): -0.017547559696397153
```
Gradients numeric is calculated in chainer/gradient_check.py using finite differences, while backward is obtained by calling the backward method of a function

However, in jenkins the output was:
```
gradients (numeric):  -0.0176546986054
gradients (backward): -0.0175476312237
```

This seems to indicate that the problem is actually happening in the numerical gradients.

**Comment by emcastillo** [comment]
Several things I have found:

Jenkins `TEST=CHAINERX_*` uses docker with `cuda:9.2-cudnn7-devel-ubuntu16.04` as the base image while `TEST=chainer-* ` doesn't seem to rely on docker.

`TEST=CHAINERX_chainerx-py3` seems to be using CuPy version 6.0.0b3 according to the output log???. Other CHAINERX tests doesnt rise that warning.

Close inspection on the `TEST=chainer-*` outputs shows that jenkins is installing cupy v6?

```
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.5/dist-packages (from cupy==6.1.0) (1.13.3)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.5/dist-packages (from cupy==6.1.0) (1.12.0)
Collecting fastrlock>=0.3 (from cupy==6.1.0)
```

**Comment by emcastillo** [comment]
CUDNN & CUDA versions for Jenkins tests

`chainer` tests
| chainer | CUDA | CUDNN |
|---------|------|-------|
| py2     | 8.0  | 5.0   |
| py3     | 10.1 | 7.5   |
| py35    | 9.2  | 7.1.4 |

**Comment by emcastillo** [comment]
[Jenkins](https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1493/TEST=chainer-py2,label=mn1-p100/testReport/tests.chainer_tests.functions_tests.connection_tests.test_convolution_nd/TestConvolutionND_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_0__use_cudnn_always__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_33_%7Bb_dtype=float32,%20dims=(3,%204,%203),%20autotune=True,%20cover_all=False,%20groups=1,%20dilate=1,%20nobias=False,%20contiguous='C',%20W_dtype=float32,%20x_dtype=float32%7D/test_backward/)

In this other test (same PR!??) Jenkins gives a wrong value for the numerical gradient too:

pg00
```
gradients (numeric):  -0.18220901963086378
gradients (backward): -0.1822091187772657
```
Jenkins
```
gradients (numeric):  -0.181999856626
gradients (backward): -0.182209047527
```

**Comment by emcastillo** [comment]
Reproduced on local environment installing cuda8 & cudnn 5.0

**Comment by emcastillo** [comment]
We decided to test the numerical gradients on the cpu.

**Comment by emcastillo** [comment]
Update CuDNN to 5.1 for python2 jenkins tests should solve this issue.
@kmaehashi volunteered to do it.

**Comment by kmaehashi** [comment]
Fix in https://github.com/chainer/chainer-test/pull/514

**Comment by niboshi** [comment]
Reoccurred: https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1707/TEST=chainer-py2,label=mn1-p100/console

**Comment by emcastillo** [comment]
Got the numbers in my machine, but I cant reproduce the error with cudnn 5.0 or cudnn 5.1 :(

**Comment by emcastillo** [comment]
reproduced, there was an issue with my cupy environment ...

```
gradients (numeric):  -0.40878489518665345
gradients (backward): -0.4084860521330623
```
Both cudnn 5~5.1 Fail on this test.
cudnn 7 for cuda 8 works.

**Comment by emcastillo** [comment]
@niboshi whats your opinion on the solution for this.
Should we enable numerical gradient cpu calculation only for this tests?

**Comment by niboshi** [comment]
@emcastillo 
Did you confirm there's numerical issues before cuDNN 7?
What's the probability of failure before 7? How many times did you repeated without error in 7?
If it's actually confirmed, it sounds reasonable to increase the tolerance before 7.

**Comment by emcastillo** [comment]
I am currently running 1000 test cases on backward of convolution_nd with cudnn 5.1 and cudnn 7
I will post the failure rates during the day.

**Comment by niboshi** [comment]
Should be fixed by #7864

**Comment by emcastillo** [comment]
Reocurred https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1828/testReport/

**Comment by niboshi** [comment]
@emcastillo Let's paste the log here. Links are volatile.

```
18:57:11 FAIL tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py::TestDeconvolution2DFunction_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_0__use_cudnn_always__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_26_{dilate=2, contiguous=None, W_dtype=float16, x_dtype=float16, stride=1, test_outsize=True, nobias=False, groups=2}::test_double_backward
18:57:11 FAIL tests/chainer_tests/functions_tests/connection_tests/test_deconvolution_2d.py::TestDeconvolution2DFunction_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_0__use_cudnn_always__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_8_{dilate=1, contiguous=None, W_dtype=float16, x_dtype=float16, stride=1, test_outsize=True, nobias=False, groups=1}::test_double_backward
```

```
TestDeconvolution2DFunction_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_0__use_cudnn_always__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_26_{dilate=2, contiguous=None, W_dtype=float16, x_dtype=float16, stride=1, test_outsize=True, nobias=False, groups=2}.test_double_backward _
18:57:10 
18:57:10 self = <chainer.testing._bundle.TestDeconvolution2DFunction_use_chainerx_false__chain...=1, test_outsize=True, nobias=False, groups=2} testMethod=test_double_backward>
18:57:10 args = (), kwargs = {}
18:57:10 e = FunctionTestError('double backward is not implemented correctly\n\n(caused by)...ce: 0.00103606851056\nx: -0.03715174015635242\ny: -0.03606851055800786\n\n\n',)
18:57:10 s = <StringIO.StringIO instance at 0x7f730bd39c68>, k = 'groups', v = 2

:
:

18:57:10 E           FunctionTestError: Parameterized test failed.
18:57:10 E           
18:57:10 E           Base test method: TestDeconvolution2DFunction_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_0__use_cudnn_always__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never.test_double_backward
18:57:10 E           Test parameters:
18:57:10 E             dilate: 2
18:57:10 E             contiguous: None
18:57:10 E             W_dtype: <type 'numpy.float16'>
18:57:10 E             x_dtype: <type 'numpy.float16'>
18:57:10 E             stride: 1
18:57:10 E             test_outsize: True
18:57:10 E             nobias: False
18:57:10 E             groups: 2
18:57:10 E           
18:57:10 E           
18:57:10 E           (caused by)
18:57:10 E           FunctionTestError: double backward is not implemented correctly
18:57:10 E           

:
:

18:57:11 E           gradients (numeric):  -0.0371517401564
18:57:11 E           gradients (backward): -0.036068510558
18:57:11 E           
18:57:11 E           x: numeric gradient, y: backward gradient
18:57:11 E           Not equal to tolerance rtol=0.001, atol=0.001
18:57:11 E           
18:57:11 E           (mismatch 100.0%)
18:57:11 E            x: array(-0.03715174015635242)
18:57:11 E            y: array(-0.03606851055800786)
18:57:11 E           
18:57:11 E           assert_allclose failed: 
18:57:11 E             shape: () ()
18:57:11 E             dtype: float64 float64
18:57:11 E             i: (0,)
18:57:11 E             x[i]: -0.0371517401564
18:57:11 E             y[i]: -0.036068510558
18:57:11 E             relative error[i]: 0.0300325569752
18:57:11 E             absolute error[i]: 0.00108322959834
18:57:11 E             relative tolerance * |y[i]|: 3.6068510558e-05
18:57:11 E             absolute tolerance: 0.001
18:57:11 E             total tolerance: 0.00103606851056
18:57:11 E           x: -0.03715174015635242
18:57:11 E           y: -0.03606851055800786
```
