### ISSUE TITLE
Flaky Test: tests/chainerx_tests/unit_tests/routines_tests/test_loss.py

### ISSUE THREAD

**Issue by emcastillo** [chainer/chainer#7696]
https://travis-ci.org/chainer/chainer/jobs/554071717

test_HuberLoss_param_244_{out_dtype='float64', delta=0.5, shape=(4, 1, 2, 4), in_dtypes=('float64', 'float32')}[native:0]

**Comment by asi1024** [comment]
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/2188/TEST=chainer-py2,label=mn1-p100/

tests.chainer_tests.functions_tests.loss_tests.test_huber_loss.TestHuberLoss_param_5_{backward_options={'rtol': 0.1, 'eps': 0.1, 'atol': 0.1}, double_backward_options={'rtol': 0.1, 'eps': 0.1, 'atol': 0.1}, dtype=float16, forward_options={'rtol': 0.005, 'atol': 0.005}, reduce='sum_along_second_axis', shape=(2, 5, 3, 3)}.test_backward_cpu
