### ISSUE TITLE
Flaky test: `chainerx_tests/unit_tests/routines_tests/test_arithmetic.py::test_Power`

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#7702]
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1507/TEST=CHAINERX_chainerx-py3,label=mn1-p100/console

**Comment by emcastillo** [comment]
Another [example](https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1674/TEST=CHAINERX_chainerx-py3,label=mn1-p100/consoleText)

**Comment by niboshi** [comment]
Could be fixed by #7874.
