### ISSUE TITLE
`chainerx.flip` returns incorrect value for non-contiguous inputs

### ISSUE THREAD

**Issue by asi1024** [chainer/chainer#7726]
`chainerx.flip` (supported in #7065) sometimes returns incorrect value for non-contiguous inputs.
```py
>>> import chainerx
>>> chainerx.flip(chainerx.array([1, 2, 3, 4], dtype='int32')[::-1])
array([32534,    33,     0,     1], shape=(4,), dtype=int32, device='native:0')
```

**Comment by emcastillo** [comment]
Do you think that we should add a test for this behavior to prevent a regresion?
The use case above should be fine :).

**Comment by emcastillo** [comment]
This bug appeared in #7065
