### ISSUE TITLE
Interface to search & replace descendants of `Link`

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer#7743]
Chainer does not have a way to search for `Link`s in `Link`, `Chain`, `ChainList`, `Sequential`, and etc.  Moreover how to replace a found `Link` is not trivial.

A feature to search and replace model trees would simplify the following implementations.

- `chainermn.links.create_mnbn_model` replaces all the occurrences of `L.BatchNormalization` by `chainermn.links.MultiNodeBatchNormalization`. https://github.com/chainer/chainer/blob/34655eff5986522eae56f47fc82a8cc2b78e1617/chainermn/links/create_mnbn_model.py#L6-L66
- `chainerrl.links.to_factorized_noisy` replaces all the occurrences of `L.Linear` by `chainerrl.links.FactorizedNoisyLinear`. https://github.com/chainer/chainerrl/blob/a5556d3247bd3b615ac89e92d54d4e6f1a76cc62/chainerrl/links/noisy_chain.py#L13-L63

These functions are often applied to existing models whose codes we'd rather not edit.  Another way to implement the functions is to patch `L.BatchNormalization` or `L.Linear` before models are loaded.

According to @shu65, the feature would also help using fused ops of cuDNN.

**Comment by niboshi** [comment]
It should suffice to (1) add an interface to retrieve the parent link of a given link, and (2) ensure `Link.__setattr__` works to replace a child link (esp, `Sequential`).

With those you will be able to write like:
```python
for link in model.links(skipself=True):
    if isinstance(link, L.BatchNormalization):
        new_link = create_new_link(link)
        setattr(link.parent, link.name, new_link)
```

**Comment by niboshi** [comment]
Or even only with (2), you can write

```python
for link in model.links(skipself=False):
    for child in self.children():
        if isinstance(child, L.BatchNormalization):
            new_link = create_new_link(child)
            setattr(link, child.name, new_link)
```

**Comment by niboshi** [comment]
> `setattr(link, child.name, new_link)`

This does not work for `ChainList` either.
Perhaps we may as well introduce a simple function like `Link.replace_child(link, new_link)`.
