### ISSUE TITLE
Convention for name of variables to represent numbers

### ISSUE THREAD

**Issue by himkt** [chainer/chainer#7882]
This issue is partially related to https://github.com/chainer/chainer/pull/7871.
In Chainer, there are some ways to represent numbers.

- `n_{prural noun}`: https://github.com/chainer/chainer/blob/master/chainer/links/rnn/n_step_lstm.py#L119
- `n_{singular noun}`: https://github.com/chainer/chainer/blob/master/chainer/datasets/sub_dataset.py#L233
- `num_{prural noun}`: https://github.com/chainer/chainer/blob/master/chainer/training/extensions/_snapshot.py#L77

(It seems most examples using `n_{prural_noun}`.)

I think it would be better to unify the way for them.
(Determining the policy would help to keep consistency, I think.)

**Comment by sameshl** [comment]
@himkt I would love to work on this. Do you want me to wait a bit till the policy is agreed upon or should I start with `n_{plural_noun}` ?

**Comment by himkt** [comment]
@sameshl It sounds great! :+1:

So, could you please wait several days?
I think we should determine the naming policy at first.

**Comment by sameshl** [comment]
Cool :+1: . Just ping here when the policy is decided.

**Comment by beam2d** [comment]
Another example:
- `{plural_noun}`: https://docs.chainer.org/en/stable/reference/generated/chainer.links.Convolution2D.html?highlight=convolution2d#chainer.links.Convolution2D (`in_channels`, `out_channels`, `groups`)

**Comment by beam2d** [comment]
Other possibly related examples are `{singular noun}_size`, `{singular noun}_count`.

**Comment by beam2d** [comment]
Among the originally mentioned three cases, `n_{plural noun}` looks simplest and less confusing, so I would like to push this choice (I also consulted other core dev members, and they also agreed upon it). As for the cases I raised above, the issue could be more complicated, so it is good to put them out of the scope of this issue.

**Comment by himkt** [comment]
Thanks, @beam2d.

@sameshl 
Thank you for waiting,  could you please start with `n_{prural_noun}`?

> As for the cases I raised above, the issue could be more complicated, so it is good to put them out of the scope of this issue

If we find some examples which don't match this convention,
it's good not to include the PR for this issue and discuss individually.

**Comment by himkt** [comment]
@sameshl Friendly ping. (If you are busy, I will work on. 👍)

**Comment by sameshl** [comment]
@himkt I have not been able to contribute from about a week or so due to a laptop issue. I am still fixing my laptop :sweatsmile: . I would be happy if you could take this up and thanks for keeping up with me despite me not able to contribute!

**Comment by Saanidhyavats** [comment]
I would like to contribute on this issue, is this issue still open?

**Comment by himkt** [comment]
@Saanidhyavats 
Thank you for your interest!

> is this issue still open?
Yes, it is still open. (`n_{singular_noun}` has not been finished)

**Comment by Saanidhyavats** [comment]
I have sent a PR, hope this solves the issue

**Comment by Saanidhyavats** [comment]
@himkt shall I continue with n_prural?

**Comment by himkt** [comment]
As we [announced](https://chainer.org/announcement/2019/12/05/released-v7.html), Chainer will go on to the maintenance phase.
Further development will be limited to bug-fixes and maintenance.

Therefore, we removed the label `contribution-welcome` from this issue
and we will not work on non-bug issues.

**Comment by Saanidhyavats** [comment]
Thank you for the information.
