### ISSUE TITLE
Implementation of the Transformer

### ISSUE THREAD

**Issue by Bartzi** [chainer/chainer#7893]
Hi,

I've implemented the [Transformer](https://arxiv.org/abs/1706.03762) model based on the code supplied by [OpenNMT](http://nlp.seas.harvard.edu/2018/04/03/attention.html). I would like to contribute this implementation to Chainer since I think this could be useful for many people that want to do natural language processing, or even computer vision (as I'm doing).

I created an example project showcasing the current state of the implementation and also an example that shows how the transformer could be used for a very easy task. You can find the code [here](https://github.com/Bartzi/chainer-transformer).

If you think that this implementation could be useful for the project, I'm happy to integrate it into Chainer and create a PR, including more documentation and tests.

I was thinking that it makes sense to integrate the Transformer as a link, the same way the implementations for `ResNet`, `VGG` and `GoogleNet`. Do you think that makes sense?

Is there anything else I should keep in mind while preparing the PR, or anything else that needs to be discussed?

**Comment by hvy** [comment]
Just sticking in here but thanks for raising this ticket. Indeed, I think this is a needed model. I haven't looked into your implementation in detail but just want to leave a record that we have MultiHead Attention being worked on in this PR https://github.com/chainer/chainer/pull/7879. I find it reasonable to proceed with this issue independently, as there's no estimate for either, but it might be worth considering using the components introduced in that PR in your model in the future.

**Comment by beam2d** [comment]
I looked through the implementation. Great work!!

As a contribution, I recommend you to send the full implementation to https://github.com/chainer/models, which is a collection of reproduction work for various research papers. Chanier package should concentrate on small reusable, fundamental components that are difficult or cumbersome to implement with computational efficiency (multi-head attention is an example of such components). `ResNet`, `VGG`, and `GoogleNet` are included in Chainer core package for historical reasons (these are added before ChainerCV was made, which is a better place to add these domain-specific fat modules).

**Comment by Bartzi** [comment]
Thanks for having a look at my implementation!

As suggested, I've opened a PR in [chainer/models](https://github.com/chainer/models/pull/37).

I will close this issue, since this does not concern the main chainer package anymore.
