### ISSUE TITLE
TransformDataset multithreading support

### ISSUE THREAD

**Issue by manhon** [chainer/chainer#7902]
I am testing a github code,
https://github.com/corochann/chainer-pointnet/blob/master/experiments/modelnet40/train.py

In the code, it uses TransformDataset with custom TransformKDTreeCls to Transform the 3D data point sorted by KDtree. 

However, when I ran "top" command, apparently, it used only single thread to do so. So, it was very slow. 

My question is, how can I use all CPU threads to do the TransformDataset operation? Is it a missing feature? 

Thank you.

**Comment by kmaehashi** [comment]
It seems the original code is using `SerialIterator`. Please consider using `MultiprocessIterator` or `MultithreadIterator` if you need concurrency.
https://docs.chainer.org/en/stable/reference/iterators.html
