### ISSUE TITLE
Uninitialized parameters cannot be restored using deserializer

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#7916]
Code:
```py
import chainer
from chainer import links as L
import io
import numpy


def serialize():
    link = L.Linear(10)
    assert link.W.data is None  # Uninitialized

    # Serialize
    b = io.BytesIO()
    chainer.serializers.save_npz(b, link)
    b.seek(0)

    return b


def deserialize(b):
    link = L.Linear(10)
    link(numpy.ones((2, 3), 'float32'))
    assert link.W.data is not None  # Initialized

    # Deserialize
    chainer.serializers.load_npz(b, link)

    assert link.W.data is None  # Should be uninitialized (this does not pass)


b = serialize()
deserialize(b)

```

I expect `link.W` is uninitialized after deserialized from an uninitialized link.

**Comment by emcastillo** [comment]
https://github.com/chainer/chainer/blob/master/chainer/link.py#L658

If a parameter was saved as None or a current parameter is initialized then it wont be loaded ...

**Comment by niboshi** [comment]
If it's a bug, I doesn't seem easy to fix.

**Comment by emcastillo** [comment]
I don't see a clear way to do it which doesn't break compatibility or semantics, maybe someone can be treating this as a "feature".

The only approach I can think of is to raise a warning when trying to deserialize an object that has already been initialized.
