### ISSUE TITLE
Performance of ChainerX Linear Algebra routines

### ISSUE THREAD

**Issue by IvanYashchuk** [chainer/chainer#7919]
Some `chainerx.linalg` routines (tracked at #6764) run more slowly compared to `numpy.linalg` and `cupy.linalg`.
Performance results & code to obtain them is available in [this gist](https://gist.github.com/IvanYashchuk/96492ec43136e441284ee4eb3ecf9184).

The reason for slowness of `qr`, `solve`, `inv` is allocating temporary arrays in the kernel and copying data from them to routine level arrays. Also repeated transpose-copy operations (because of ChainerX's row-major vs column-major ordering of LAPACK/cuSOLVER) have an effect. Routines that don't require such manipulations run almost one to one with NumPy/CuPy.

**Comment by hvy** [comment]
This is a linalg kernel design matter by the way. For the record, @IvanYashchuk and I have discussed this matter outside GitHub and decided to wait with addressing this issue until all ongoing linalg PRs have been merged. The reasons is that some routines are already merged, and they basically all share the same routine-kernel delegation

**Comment by Saanidhyavats** [comment]
Is this issue open? I want to contribute on this issue.
