### ISSUE TITLE
Introduce `python_requires` in `setup.py`

### ISSUE THREAD

**Issue by kmaehashi** [chainer/chainer#7936]
After dropping Python 2 support, use `python_requires=` to declare supported Python version to let `pip` automatically the choose the correct (latest) package depending on users' Python version.

https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

(This is a reminder issue; same thing should be done for CuPy too)

**Comment by himkt** [comment]
This will be done at https://github.com/chainer/chainer/pull/8517.

**Comment by kmaehashi** [comment]
Fixed in #8517.
