### ISSUE TITLE
chainerx.array is not picklable

### ISSUE THREAD

**Issue by keisukefukuda** [chainer/chainer#7974]
It is often convenient if we can pickle chainerx arrays when we save/restore/communicate them. 

```
>>> import pickle
>>> import chainerx as chx
>>> a = chx.array(10)
>>> a
array(10, shape=(), dtype=int64, device='native:0')
>>> pickle.dumps
<built-in function dumps>
>>> pickle.dumps(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: return_value_policy = copy, but the object is non-copyable!
```

**Comment by niboshi** [comment]
There's a test to ensure `chainerx.ndarray` is picklable:
https://github.com/chainer/chainer/blob/v7.0.0b2/tests/chainerx_tests/unit_tests/test_array.py#L695

But I confirmed the error as reported, and the test passes as well.

**Comment by niboshi** [comment]
### Works:
```py
device = chainerx.get_device('cuda:0')
arr = chainerx.array([1, 2], chainerx.float32, device=device)
s = pickle.dumps(arr)
```

### Does not work:
```py
arr = chainerx.array([1, 2], chainerx.float32, device='cuda:0')
s = pickle.dumps(arr)
```
```py
arr = chainerx.array([1, 2], chainerx.float32, device=chainerx.get_device('cuda:0'))
s = pickle.dumps(arr)
```

**Comment by cloudhan** [comment]
Why make it device dependent. In the early days, torch (lua) and mxnet dumps a array with their device by default. Some times paper author dumps their weights originally live on GPU8, which make it very hard (if not impossible) to load if you are not rich enough $$$. IIRC, this also makes a deadlock/hang when you want to get a GPU mxnet's ndarray from a multiprocessing queue.

**Comment by emcastillo** [comment]
This works
```
arr = chainerx.array([1, 2], chainerx.float32, device='cuda:0')
dev = arr.device
s = pickle.dumps(arr)
```
Seems like if the device object is directly created on C++ is not being binded to the python device wrapper which defines the pickle serialization function

**Comment by niboshi** [comment]
I assume the associated device is bound to a Python wrapper here, but I'm not sure:
https://github.com/chainer/chainer/blob/master/chainerx_cc/chainerx/python/array.cc#L196

**Comment by emcastillo** [comment]
The problem seems to be this `py::return_value_policy::reference`, probably is setting something in the python side of the wrapper the first time the corresponding python object is created.

**Comment by niboshi** [comment]
Introducing a Python wrapper class (#7983) does seem to fix the problem.

```py
arr = chainerx.array([1, 2], chainerx.float32, device='cuda:0')
s = pickle.dumps(arr)
```

Now this variant works with the patch.
