### ISSUE TITLE
Remove Python 2 support in code

### ISSUE THREAD

**Issue by kmaehashi** [chainer/chainer#7999]
- Code
    - Eliminate `six`
    - Eliminate `__future__` imports
    - Eliminate py2-specific fixes (e.g. `chainer.utils.collcetions_abc`, `_pickle_load`, code using `sys.version_info`)

**Comment by UmashankarTriforce** [comment]
Is this issue still open?

**Comment by kmaehashi** [comment]
I'm closing this issue as there's no strong motivation to do this in Chainer v7.
c.f. https://github.com/cupy/cupy/issues/2994
