### ISSUE TITLE
Release Tasks for v7.0.0b4 / v6.4.0

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#8005]
- Drop Python 2 CI configurations for master branch
  - Chainer
    - [x] Travis CI #8013
    - [x] AppVeyor #8014
    - [x] PFN CI #8017
  - CuPy
    - [x] Travis CI cupy/cupy#2428
    - [x] ~AppVeyor~ (not tested on Py2)
    - [x] PFN CI cupy/cupy#2429

After release:
- [x] Rebuild CI image

**Comment by beam2d** [comment]
We postpone https://github.com/chainer/chainer-test/pull/523 to [the next release](https://github.com/chainer/chainer/issues/8006) because it is not a blocker of this beta release.
