### ISSUE TITLE
Release Tasks for v7.0.0rc1

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#8006]
- [x] #7952
- [x] Do not test against Python 2 / 3.4 for master branch https://github.com/chainer/chainer-test/pull/523
- [x] Revert tentatively removed example tests https://github.com/chainer/chainer-test/pull/533
- [x] Make arguments keyword-only (for those introduced in v7 and not backported)
  - [x] #8009
  - [x] #8010
  - [x] #8011
  - [x] #8064
  - [x] #8065
  - [x] #8066
  - [x] #8067
- [x] ONNX-Chainer integration  #8229
- [x] `DeviceResident.to_gpu/to_cpu/to_intel64` deprecation #8058

**Comment by niboshi** [comment]
- [ ] #7952

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by beam2d** [comment]
We removed NHWC support #7620 from this RC due to the tight schedule. We will consider how we can eventually include it to the v7.x series.
