### ISSUE TITLE
ChainerX build failure with macOS

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer#8038]
It fails to be built because of the warning
```
In file included from /path/to/chainerx_cc/chainerx/native/native_device/misc.cc:12:
/path/to/chainerx_cc/chainerx/numeric.h:72:52: error: taking the absolute value of unsigned type 'unsigned char' has no effect [-Werror,-Wabsolute-value]
```
after #7319 is merged (https://travis-ci.org/chainer/chainer/jobs/575281021#L3288-L3311).

I have no idea on whether the warning is valid.

**Comment by niboshi** [comment]
This warning may be useful to detect an erroneous code like this: https://stackoverflow.com/questions/27833289/does-absunsigned-long-make-any-sense

Btw, what's your compiler?
I think it's better to make CIs detect it if possible.

**Comment by toslunar** [comment]
> Btw, what's your compiler?

```
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- The C compiler identification is AppleClang 9.1.0.9020039
```
(https://travis-ci.org/chainer/chainer/jobs/575281021#L3088-L3089)

> I think it's better to make CIs detect it if possible.

Travis CI for `master` branch detected it.

**Comment by hvy** [comment]
Fixed by https://github.com/chainer/chainer/pull/8045. [`-Wabsolute-value`](https://releases.llvm.org/8.0.0/tools/clang/docs/DiagnosticsReference.html#wabsolute-value) is only available for clang and we must run the CI with clang for each PR in order to really prevent these kinds of failures.
