### ISSUE TITLE
Travis job for macOS exceeds maximum time limit

### ISSUE THREAD

**Issue by toslunar** [chainer/chainer#8073]
The maximum time limit is 50 mins.  Compared to Linux jobs, `before_install` costs because of it updates `pyenv`.
https://travis-ci.org/chainer/chainer/builds/579405196

**Comment by kmaehashi** [comment]
How about installing Python 3.7 using Homebrew instead of building by our own? As the Mac support is best-effort basis, I think there's no strict reasons to stick with Python 3.5 which is the lowest supported version.

**Comment by toslunar** [comment]
Fixed by #8361.  Reopen the issue if further speed-up is required.
