### ISSUE TITLE
Possibly inappropriate use of `OptionalAxes` and `Axes` to represent one-sized axes

### ISSUE THREAD

**Issue by hvy** [chainer/chainer#8079]
ChainerX routines that accept a single optional integer as an axis (not a tuple) currently accepts `absl::optional<int8_t>`. Although this is fine, its cast to an `OptionalAxes` (container type) before being passed to the C++ routine. The C++ routine may thus accept multiple axes but lengths larger than 1 are not tested since there are no tests in C++. 

E.g. `chainerx.argmax` only takes a single integer for its axis and not a tuple of integers. However, the kernel takes a tuple. https://github.com/chainer/chainer/blob/master/chainerx_cc/chainerx/native/native_device/reduction.cc#L36.

**Comment by hvy** [comment]
Some thoughts
- Accept in the Python binding layer a `py::object` and define a converter to `OptionalAxes`, then raise errors in C++. 
- Allow something along `OptionalAxes<1>` to guarantee a one-sized axes to represent an optional int axis.

**Comment by niboshi** [comment]
`OptionalAxes` and `Axes` are (as can be seen from them being plural form) for multiple-axes arguments.
I think they do not fit the `ArgMax` case: simply using `absl::optional<int8_t>` is better.
