### ISSUE TITLE
Non-pure-reduction routines in ChainerX to be excluded

### ISSUE THREAD

**Issue by hvy** [chainer/chainer#8106]
The intent of this issue is to clarify or discuss the motivation behind keeping a minimal set of backpropable routines in ChainerX for the sake of simplicity.

Non-pure-reduction routines*, although common in the field of DL, such as _mean squared error_, might better be excluded from ChainerX as long as the non-reduction variant, in this case _squared error_ is provided. Please see this [comment](https://github.com/chainer/chainer/pull/7063#issuecomment-496087996). To elaborate, basically any routine in ChainerX might be a candidate for any reduction (not just mean, but max, min, etc.). As pure-reduction routines such as _mean, max, min_, etc. are provided in ChainerX, this is possible without any dedicated non-pure-reduction routines.

Also note that when performing a reduction, it should be possible to specify over which axes the reduction should take place. This further complicates interfaces.

*_Pure-reduction routines: Routines that by definition perform reduction. Non-pure-reduction routines: Routines that are well defined without reduction._

**Comment by hvy** [comment]
I noticed that the above was never really clarified. For instance, `mean_squared_error` (https://github.com/chainer/chainer/pull/8051) was merged because of that. I definitely don't mean to deny any great routine contribution but would like to raise an issue to make this clear and possibly open up for discussion. How do you see this @sky58, @emcastillo ?

**Comment by emcastillo** [comment]
I wasn't aware of this design decision. 
I agree on keeping them separated, the benefits are clear enough.

**Comment by emcastillo** [comment]
Bluntly speaking, I think we should keep some kind of meta-issue or wiki page summarizing all these decisions. Currently, all this knowledge is disseminated and is not easy to retrieve.
The community would likely appreciate some kind of API design guidelines.

**Comment by hvy** [comment]
Absolutely. let's rewrite this in our GitHub Wiki https://github.com/chainer/chainer/wiki/Development-policies. Was actually planning to do so.

**Comment by hvy** [comment]
Confirmed with @sky58 on Slack and moved it to the Wiki https://github.com/chainer/chainer/wiki/Development-policies#chainerx. There might be a better section in the Wiki in which we can document this but I'll leave it as a TODO (See also https://github.com/chainer/chainer/issues/5778).

**Comment by hvy** [comment]
Let me close this issue as the discussion is.
