### ISSUE TITLE
Latest and greatest optimizers

### ISSUE THREAD

**Issue by Crissman** [chainer/chainer#8153]
I think RAdam and Lookahead are becoming standard optimizers we should implement in Chainer.

https://medium.com/@lessw/new-deep-learning-optimizer-ranger-synergistic-combination-of-radam-lookahead-for-the-best-of-2dc83f79a48d

**Comment by emcastillo** [comment]
I will implement Radam

**Comment by emcastillo** [comment]
#8159 attempts to implement RAdam, whether is correct or not is a different story :)

**Comment by andy6975** [comment]
Hi, is this issue still open? I would like to work on this. Thanks!

**Comment by emcastillo** [comment]
@andy6975 try to do the Lookahead :)

**Comment by hvy** [comment]
I have been looking into Lookahead too, mostly out of curiosity and maybe more like an example. 🙂

**Comment by hvy** [comment]
An attempt #8171.

**Comment by Saanidhyavats** [comment]
I want to contribute on this issue. How can I start with it

**Comment by Saanidhyavats** [comment]
is this issue open? I want to contribute on this issue.
