### ISSUE TITLE
Order of Registration for Sequential Chains

### ISSUE THREAD

**Issue by MannyKayy** [chainer/chainer#8158]
It should be noted somewhere that the Sequential Chains and their parameters do not respect the expected order of registration. This causes confusion when returning parameters from the associated generators.

```
class TestChain(Chain):
    def __init__(self):
        super().__init__()
        ndf = 2
        with self.init_scope():
            self.l0 = L.Convolution2D(ndf, ndf, ksize=3, nobias=True)
            self.l1 = L.Convolution2D(ndf, ndf, ksize=3, nobias=True)
            self.l2 = L.Convolution2D(ndf, ndf, ksize=3, nobias=True)
            self.main = Sequential(
                L.Convolution2D(ndf, ndf, nobias=True),
                F.leaky_relu,
                L.Convolution2D(ndf, ndf, nobias=True),
                F.leaky_relu,
                L.Convolution2D(ndf, ndf, nobias=True),
                F.leaky_relu,
                L.Convolution2D(ndf, ndf, nobias=True),
                F.leaky_relu,
                L.BatchNormalization(ndf, use_beta=False),
            )
            self.l3 = L.Convolution2D(ndf, ndf, ksize=3, nobias=True)
            self.l4 = L.Convolution2D(ndf, ndf, ksize=3, nobias=True)
            self.l5 = L.Convolution2D(ndf, ndf, ksize=3, nobias=True)



```
```
t =  TestChain()
for p in t.namedparams():
    print(p[0])
```

```
/l0/W
/l1/W
/l2/W
/l3/W
/l4/W
/l5/W
/main/0/W
/main/1/gamma
/main/2/W
/main/3/W
/main/4/W
```

```
chainer.print_runtime_info()


Platform: Linux-4.4.0-98-generic-x86_64-with-debian-buster-sid
Chainer: 7.0.0b3
ChainerX: Available
NumPy: 1.17.2
CuPy:
  CuPy Version          : 7.0.0b3
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 10000
  CUDA Driver Version   : 10020
  CUDA Runtime Version  : 10000
  cuDNN Build Version   : 7602
  cuDNN Version         : 7600
  NCCL Build Version    : 2402
  NCCL Runtime Version  : 2402
iDeep: 2.0.0.post3

```

**Comment by beam2d** [comment]
Thank you for the report. The current implementation iterates over the parameters ordered by name lexicographically (introduced by #5119). Do you have a case that iterating in the registration order is useful? I don't think the default behavior can be changed (for the compatibility), but we may add an option to iterate in the registration order.

**Comment by MannyKayy** [comment]
I actually came about this issue as I was writing trainer extensions to catalog and analyse weight dynamics for different chains. I guess in this scenario, the way parameters are ordered in sequential links is not clear from the outset and leads to confusion. 

For example, i expected the generator associated with the sequential link to return parameters in forward/reverse sequential order, instead it does something different.

```
for p in t.main.namedparams():
    print(p[0])
```

```
/0/W
/1/gamma
/2/W
/3/W
/4/W
```

In this scenario, i would expect the batchnorm parameters to be returned last, (or first assuming that the generator returns parameters in reverse order). Instead, the batchnorm parameters are returned second which is confusing.

**Comment by beam2d** [comment]
The inconsistent order of links in `Sequential` is another problem. There is an existing issue for that: #6053.

**Comment by MannyKayy** [comment]
Alright.. I'll close this issue since #6053 deals with the remaining issue.
