### ISSUE TITLE
Chainer 1.18.0 pip installation issue

### ISSUE THREAD

**Issue by andreaBassich** [chainer/chainer#8183]
Hi,

I'm trying to install Chainer 1.18.0 on my venv via pip, however i get the following error message: 

```
error: Command '/home/andrea/PycharmProjects/rllab-curriculum/venv/bin/python' failed:
    
      command: /home/andrea/PycharmProjects/rllab-curriculum/venv/bin/python /home/andrea/PycharmProjects/rllab-curriculum/venv/lib/python3.5/site-packages/cython.py --fast-fail --verbose --cplus --directive linetrace=False --directive profile=False cupy/core/core.pyx
      return code: 1
      output:
    
    Compiling /tmp/pip-install-obccxqgu/chainer/cupy/core/core.pyx
/home/andrea/PycharmProjects/rllab-curriculum/venv/lib/python3.5/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-obccxqgu/chainer/cupy/core/core.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
    void* data
    int size
    int shape_and_strides[MAX_NDIM * 2]


cdef class CArray(cupy.cuda.function.CPointer):
                                   ^
------------------------------------------------------------

cupy/core/carray.pxi:14:36: First base of 'CArray' is not an extension type

    cython path:/home/andrea/PycharmProjects/rllab-curriculum/venv/lib/python3.5/site-packages
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ltzqyjjn/chainer/
```
OS: Ubuntu 14.04 LTS
Python: 3.5
Cuda: 8.0
Cudnn: 5.1

Any idea on how to fix this?

**Comment by emcastillo** [comment]
Hello,

The error seems to be building cupy, probably a Cython version issue.
https://docs.chainer.org/en/v1.18.0/install.html

Can you share the cmd lines you are using to install it?
If you don't plan to modify the source, you can get the binary wheel directly by doing `pip install chainer==1.18.0`.

Also, I guess you are aware of it but just for reference, that version is too old and is not mantained anymore. If you can we suggest you to install the latest stable version `6.4.0` which was released yesterday.

**Comment by andreaBassich** [comment]
Hi @emcastillo,

I was installing it using `pip install chainer==1.18.0` but as I had already installed other libraries cython 0.29 was installed; as you suggested the problem was in the version of cython I was using, I downgraded to 0.22 from 0.29 and everything runs smoothly now.

many thanks
