### ISSUE TITLE
Add "jenkins" extras requirements

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#8228]
https://github.com/chainer/chainer-test/blob/b1b40421a2d7c73b86590575b19b82c801a12778/run_combination_test.py#L54-L66

Move these requirements defined in [chainer-test](https://github.com/chainer/chainer-test) (there are some more files which has the same definition) to a new extras "jenkins" in `setup.py`.

**Comment by kmaehashi** [comment]
Implemented in #8241
