### ISSUE TITLE
Fix imagenet for windows to use if __name__ == "__main__" idiom

### ISSUE THREAD

**Issue by delta2323** [chainer/chainer#825]
According to Sikon-san's report on Google Group, imagenet example does not run properly on Windows environment. If the main scripts uses multiprocessing module, we need to disable side effects in main scripts by using `__name__ == "__main__"` idiom.
See [the official document](https://docs.python.org/2/library/multiprocessing.html?highlight=multiprocessing#windows) for details.

Related to #483

**Comment by beam2d** [comment]
Fixed already.
