### ISSUE TITLE
Memory leak in `chainerx_tests`

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#8254]
* Monotonical increase of memory consumption is observed during ChainerX tests (a).

* It looks like a problem of ChainerX tests, not ChainerX itself, because (b) the problem is not observed in Chainer function tests with ChainerX backends.

* There's a flat plateau in the plot (a) in the middle of the run. This is `chainerx_tests/unit_tests/routines_tests/test_rnn.py`, where each test takes much larger time than other tests. It doesn't  mean these tests don't have the memory leak issue.

\* x-axis = seconds

(a) `CHAINERX_TEST_CUDA_DEVICE_LIMIT=0 python -m pytest  tests/chainerx_tests/unit_tests/routines_tests/`

![chainerx-tests](https://user-images.githubusercontent.com/635436/66298860-65aac000-e92d-11e9-9824-583ece362f74.png)

(b) `python -m pytest -m 'chainerx and not gpu and not cudnn' tests/chainer_tests/functions_tests/`

![chainer-functions-tests-only-chainerx](https://user-images.githubusercontent.com/635436/66299004-a4d91100-e92d-11e9-88de-9437dad2d2e5.png)

**Comment by niboshi** [comment]
Related: #8082

In this PR parallelization using xdist has not been successful. I suspect the memory leak is the cause of that.

**Comment by emcastillo** [comment]
I have observed that some of the test files are being executed several times upon running 
``python -m pytest tests/chainerx_tests/unit_tests/routines_tests/``
Maybe some of the test fixtures are being retained until the completion of those tests?
``tests/chainerx_tests/unit_tests/routines_tests/test_arithmetic.py`` appears several times on pytest output.

**Comment by niboshi** [comment]
It seems this is actually a problem of pytest.

(In the following figures the test is repeated using pytest-repeat (`--count 10000`))

(c)
```py
import pytest

@pytest.fixture
def skipme(request):
    pytest.skip()

def test_skip(skipme):
    pass
```
![skipme-fixture](https://user-images.githubusercontent.com/635436/66365153-fbdef480-e9c6-11e9-80b0-247e166ed5bf.png)

(d)
```py
import pytest
def test_skip():
    pytest.skip()
```
![skip](https://user-images.githubusercontent.com/635436/66365160-00a3a880-e9c7-11e9-90cb-46d637abc122.png)

(e)
```py
import pytest

@pytest.fixture
def skipme(request):
    pass

def test_skip(skipme):
    pass
```

![fixture](https://user-images.githubusercontent.com/635436/66365362-a5be8100-e9c7-11e9-864f-cab89ae06b1f.png)

**Comment by emcastillo** [comment]
Periodic calls to the garbage collector might release memory

**Comment by niboshi** [comment]
Hm, `gc.collect()` did free the memory.

**Comment by emcastillo** [comment]
Pytest seems to hold the test objects that creates on collection till the end of the execution, probably thats why gc didnt work 😥

**Comment by niboshi** [comment]
Pytest 5.2.1 has the same problem.

**Comment by emcastillo** [comment]
https://github.com/pytest-dev/pytest/issues/5642

**Comment by emcastillo** [comment]
Before #8155 
![image](https://user-images.githubusercontent.com/15824382/66368033-c095f300-e9d1-11e9-86d2-ecaf17665e34.png)

After 
![image](https://user-images.githubusercontent.com/15824382/66368046-c68bd400-e9d1-11e9-8b86-f95f4814c5bc.png)

Total memory doesn't change at all, just the increase rate.
