### ISSUE TITLE
chainerx.ascontiguousarray() does not preserve the backend of the array

### ISSUE THREAD

**Issue by keisukefukuda** [chainer/chainer#8259]
`chainerx.ascontiguousarray()` function is expected to keep the backend of the original array.

```
import chainer
import chainerx as chx

a1 = chx.arange(10)
a2 = a1.to_device('cuda:0')
a3 = chx.ascontiguousarray(a2)
print(a1.device.backend.name)
print(a2.device.backend.name)
print(a3.device.backend.name)
=>
native
cuda
native  # <== expected to be 'cuda'
```

**Comment by take-cheeze** [comment]
Seems related to:
https://github.com/chainer/chainer/blob/eb59b5265e49fb81a270850f12d4654967e629cf/chainerx_cc/chainerx/python/routines.cc#L130

**Comment by take-cheeze** [comment]
MakeArray -> GetDevice -> GetDefaultDevice
https://github.com/chainer/chainer/blob/152cdb7b599460f1fae01e96c4fed6a2b70085fb/chainerx_cc/chainerx/python/array.cc
https://github.com/chainer/chainer/blob/3c96c2d29b00b544c3b6d30883aaf6683a47ebc5/chainerx_cc/chainerx/python/device.cc#L20

**Comment by take-cheeze** [comment]
Don't know a good way to fix this.
Maybe we need a `GetDevice` that refers input ndarray device.

**Comment by take-cheeze** [comment]
Current workaround would be pass device explicitly to 3rd argument.
