### ISSUE TITLE
Add ChainerX support to ChainerMN examples

### ISSUE THREAD

**Issue by belldandyxtq** [chainer/chainer#8261]
ChainerMN has already supported ChainerX. We need to add ChainerX to all the ChainerMN examples, following is the todo list

-  ~cifar~

-  ~dcgan~

- [ ] imagenet

- [x] mnist (#7844)

-  ~parallel_convolution~

-  ~seq2seq~ 

Related to #7844, #8031

**Comment by keisukefukuda** [comment]
Since Chainer has gone into maintenance mode, this issue is not longer developed.
