### ISSUE TITLE
ChainerMN tutorial: misleading description about `scatter_dataset`

### ISSUE THREAD

**Issue by nai62** [chainer/chainer#8267]
The tutorial of ChainerMN about `scatter_dataset` says as follows:

* The dataset is split into sub datasets of **almost equal sizes** and scattered to the workers.

https://github.com/chainer/chainer/blob/master/docs/source/chainermn/tutorial/step2_datasets_evaluators.rst#scattering-datasets

I think this description misleading because by default, `scatter_dataset` splits it into sub datasets of exactly the same sizes.

It may be a good idea to replace the description to something like: `exactly the same sizes with some duplications as necessary`.

**Comment by nai62** [comment]
@keisukefukuda What do you think about it?

**Comment by keisukefukuda** [comment]
Sorry for the late response. I think you are right. I'll fix it. 🙏
