### ISSUE TITLE
Inherit source array possible in python/routines.cc in ChainerX

### ISSUE THREAD

**Issue by take-cheeze** [chainer/chainer#8269]
rel: https://github.com/chainer/chainer/issues/8259

Since current python binding uses default device instead of source array's device like C++ API.

Random Idea: add API like
```c++
Device& GetDevice(pybind11::handle array, pybind11::handle handle); 
```
to
https://github.com/chainer/chainer/blob/e319dcb1cb5d44793c79a251427329596264be43/chainerx_cc/chainerx/python/device.h#L11

**Comment by niboshi** [comment]
What are routine functions besides `ascontiguousarray` that would benefit from it?

**Comment by niboshi** [comment]
Note that functions like `ZerosLike` do never take the device from the original array.

Also, C++ `chainerx::AsContiguousArray` does not have `device` argument.
Maybe we could remove the argument from Python `chainerx.ascontiguousarray` as well?

**Comment by take-cheeze** [comment]
Discussed offline and device arguments should be avoided so moving to this issue: https://github.com/chainer/chainer/issues/8273
