### ISSUE TITLE
Flaky test: `chainerx_tests/unit_tests/routines_tests/test_arithmetic.py::test_IRemainder`

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#8366]
Occurred in #8364

https://jenkins.preferred.jp/job/chainer/job/chainer_pr/2391/TEST=CHAINERX_chainerx-py3,label=mn1-p100/

`15:28:57 FAIL ../../../repo/tests/chainerx_tests/unit_tests/routines_tests/test_arithmetic.py::test_IRemainder_param_206_{in_dtypes=('float16', 'float32'), in_shapes=((2, 3), (2, 3)), input_lhs=2, input_rhs=2, out_dtype='float32', skip_backward_test=True, skip_double_backward_test=True}[native:0]`

```
15:28:57 E       chainer.testing.function_link.FunctionTestError: Outputs do not match the expected values.
15:28:57 E       Indices of outputs that do not match: 0
15:28:57 E       Expected shapes and dtypes: (2, 3):float16
15:28:57 E       Actual shapes and dtypes:   (2, 3):float16
15:28:57 E       
15:28:57 E       
15:28:57 E       Error details of output [0]:
15:28:57 E       
15:28:57 E       Not equal to tolerance rtol=0.001, atol=0.001
15:28:57 E       
15:28:57 E       Mismatch: 16.7%
15:28:57 E       Max absolute difference: 0.001953
15:28:57 E       Max relative difference: 0.012344
15:28:57 E        x: array([[-1.083 , -1.611 ,  2.746 ],
15:28:57 E              [ 0.1562,  0.858 ,  2.852 ]], dtype=float16)
15:28:57 E        y: array([[-1.083 , -1.611 ,  2.746 ],
15:28:57 E              [ 0.1582,  0.858 ,  2.852 ]], dtype=float16)
15:28:57 E       
15:28:57 E       assert_allclose failed: 
15:28:57 E         shape: (2, 3) (2, 3)
15:28:57 E         dtype: float16 float16
15:28:57 E         i: (1, 0)
15:28:57 E         x[i]: 0.15625
15:28:57 E         y[i]: 0.158203125
15:28:57 E         relative error[i]: 0.0123443603515625
15:28:57 E         absolute error[i]: 0.001953125
15:28:57 E         relative tolerance * |y[i]|: 0.000158203125
15:28:57 E         absolute tolerance: 0.001
15:28:57 E         total tolerance: 0.001158203125
15:28:57 E       x: [[-1.083  -1.611   2.746 ]
15:28:57 E           [ 0.1562  0.858   2.852 ]]
15:28:57 E       y: [[-1.083  -1.611   2.746 ]
15:28:57 E           [ 0.1582  0.858   2.852 ]]
```

**Comment by emcastillo** [comment]
Reproduced,

~1 Failure every 1000 iterations

Reason behind it seems to be type castings

The failure happens when a is float16 and b is float32.
In ChainerX seems like both operands are being casted down to 16 bit and then up to 32 to do the operation and then back to 16 again. This makes the operand b lose precision and might alter the result when comparing to numpy.

https://github.com/chainer/chainer/blob/master/chainerx_cc/chainerx/native/native_device/arithmetic.cc#L293-L295

**Comment by emcastillo** [comment]
There a subtle difference in the fp16 calculation between numpy and chainerx :)
