### ISSUE TITLE
flaky test (timeout): `chainerx_tests/unit_tests/routines_tests/test_linalg.py`

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#8425]
Ocurred in #8424

https://travis-ci.org/chainer/chainer/jobs/611185694?utm_medium=notification&utm_source=github_status

`[2019-11-13 04:00:10] [TIMEOUT] /home/travis/build/chainer/chainer/tests/chainerx_tests/unit_tests/routines_tests/test_linalg.py (60 seconds)`

**Comment by toslunar** [comment]
Due to #8361.  [scripts/ci/travis/xpytest-hint-chainerx.pbtxt](https://github.com/chainer/chainer/blob/master/scripts/ci/travis/xpytest-hint-chainerx.pbtxt) needs a fix.
