### ISSUE TITLE
Support Rollaxis in ONNX-Chainer

### ISSUE THREAD

**Issue by tkanmae** [chainer/chainer#8427]
Currently, ONNX-Chainer doesn't support Rollaxis. I see that [`chainer.functions.rollaxis`](https://docs.chainer.org/en/stable/reference/generated/chainer.functions.rollaxis.html) is in Chainer's API only for backward compatibility, but it is better to be supported in ONNX-Chainer.

**Comment by disktnk** [comment]
fixed by #8428
