### ISSUE TITLE
flaky test: `chainermn_tests/extensions_tests/test_multi_node_snapshot.py::test_multinode_autoload`

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#8430]
Occurred in  #8420

https://travis-ci.org/chainer/chainer/jobs/610809007?utm_medium=notification&utm_source=github_status

```
[2019-11-12 11:34:58] >               sock.connect(sa)
[2019-11-12 11:34:58] E               TimeoutError: [Errno 110] Connection timed out
```

**Comment by Crissman** [comment]
Seems like this might be a one off, with a socket connection error. If it re-occurs, let's reopen.

Closing for now.
