### ISSUE TITLE
Get Weight

### ISSUE THREAD

**Issue by Charlo26** [chainer/chainer#8528]
Hello, I'm looking through the documentation to find a way to get weight of neurons.

I build a Sequential network, for example 
`model = chainer.Sequential()
bias = False
layer = chainer.links.Linear(5, 10, nobias=bias)
model.append(layer)`

If I Use print(model)
it return : 
Sequential(
  (0): Linear(in_size=5, out_size=10, nobias=False),
)

but i'm not able to find a way to get the wieght of this layer.

Do you know a solution?

Thank you, have a nice day

**Comment by Charlo26** [comment]
Sorry, i found....

model[0].W 

have a nice day

**Comment by tks-reply** [comment]
To be honest,I am new to chainer,I need your help. I would very appreciate if you could help me.

Here is my code:
x = self.conv1(x)
x = self.conv12(x)
x = F.clip(x, -1., 1.)
x_stage1 = x
for i in range(5):
stage1 = cupy.asnumpy(x_stage1)
img_Guassian = cv2.GaussianBlur(stage1, (3, 3), 0)

File "/home/fl/cdf/src/model.py", line 374, in get_loss
img_Guassian = cv2.GaussianBlur(a, (3, 3), 0)
cv2.error: /io/opencv/modules/core/src/matrix.cpp:991: error: (-215) dims <= 2 && step[0] > 0 in function locateROI

Thank you very much!
