### ISSUE TITLE
Can't use chainer in W10 with CUDA 11.1

### ISSUE THREAD

**Issue by Ber1** [chainer/chainer#8582]
When trying to run chainer, I get the following error message:

```
Traceback (most recent call last):
  File "train_dcgan.py", line 178, in <module>
    main()
  File "train_dcgan.py", line 65, in main
    chainer.cuda.get_device_from_id(args.gpu).use()
  File "C:\Users\Beri\miniconda3\envs\ganDemo\lib\site-packages\chainer\backends\cuda.py", line 279, in get_device_from_id
    check_cuda_available()
  File "C:\Users\Beri\miniconda3\envs\ganDemo\lib\site-packages\chainer\backends\cuda.py", line 142, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/chainer/chainer#installation).No module named 'cupy.util'
```

This works fine if using CUDA 10.2, but it has no support for the most recent NVIDIA GPUs.

* Conditions:

Platform: Windows-10-10.0.19041-SP0
Chainer: 7.7.0
ChainerX: Not Available
NumPy: 1.19.3
CuPy: Not Available
iDeep: Not Available

  - Chainer version: 7.7.0
  - CuPy version: cupy-cuda111==8.1.0
  - OS/Platform: Windows 10 x64
  - CUDA/cuDNN version: CUDA 11.1/cuDNN 8.0.4.30

**Comment by DiKorsch** [comment]
I needed also to add this [line](https://github.com/chainer/chainer/blob/v7.7.0/chainer/backends/cuda.py#L122) `import cupy.cuda.cudnn`, so that `libcudnn` was assgined properly

**Comment by kmaehashi** [comment]
Merging to #8601

**Comment by iegorval** [comment]
@DiKorsch either this did not work for me, or I misunderstood what I should do. Did you mean that I should add `import cupy.cuda.cudnn` to `cuda.py` between lines 121 and 122? I have tried to do so, but the error message (the same as in the first message in this issue) did not change for me. Do you know what I could do to fix it? Thanks.

**Comment by DiKorsch** [comment]
@iegorval, yes, this is the change, that fixed the problem for me :shrug:

**Comment by iegorval** [comment]
@DiKorsch ok, thank you for the fast reply. I guess I will open a new issue then.
