### ISSUE TITLE
cupy_9.0.0a1 support

### ISSUE THREAD

**Issue by mor2code** [chainer/chainer#8584]
added support for cupy_9.0.0a1,
backend code ignores cupy because of name change cupy.util to cupy._util, attached patch to fix it.

[cupy_9.0.0a1.patch.txt](https://github.com/chainer/chainer/files/5494675/cupy_9.0.0a1.patch.txt)

**Comment by emcastillo** [comment]
We merged a similar patch a few days ago.
Thanks for the contribution!
