### ISSUE TITLE
module 'cupy.cuda' has no attribute 'cudnn'

### ISSUE THREAD

**Issue by fnando1995** [chainer/chainer#8596]
Hello,

I just installed in a virtual environment chainer an cupy  for using a neural network. I've been having this warning output:

```
ambiente/lib/python3.8/site-packages/chainer/backends/cuda.py:146: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
```

Even if the warn says that Cudnn is not enabled, I can use the GPU for inference (nvidia-smi shows and up in vram usage when executed the script).

**How can  I get rid of this warnning?**

**Environment:**

```
Ubuntu 20.04
python 3.8.5
chainer==7.7.0
cupy-cuda110==8.3.0
```

**note:** I change this in chainer/backends/cuda.py since this problem is a bit old and there has been a reformating in the newe chainer version. (problem was that cupy.util couldn't be improted.

```
comment lines 69,114,115, 

    # from cupy.util import PerformanceWarning as _PerformanceWarning  # NOQA

    ...

    # Dummy class for ignoring cupy.util.PerformanceWarning in setup.cfg.
    # class _PerformanceWarning(Warning):
    #    pass

```

**Comment by kmaehashi** [comment]
Merging to #8601
