### ISSUE TITLE
Experimental support for CuPy v8 in Chainer v7

### ISSUE THREAD

**Issue by kmaehashi** [chainer/chainer#8601]
We received several requests regarding CuPy v8 support in Chainer v7, mainly from those who want to use CUDA 11.1+. Currently Chainer v7 do not support CuPy v8, but we are planning to make a release that experimentally support CuPy v8.

**Comment by nicobieber99** [comment]
Hi I am having this issue where chainer doesn't support cupy, and I need them both to test out some code. Are there any workarounds?

**Comment by kmaehashi** [comment]
Resolved via v7.8.0 release.
