### ISSUE TITLE
can't use chainer with new cupy, can't install old cupy

### ISSUE THREAD

**Issue by AlexiaJM** [chainer/chainer#8623]
Chainer officially only support cupy == 7.8.0. Sadly, I can't install older cupy and when installing newer cupy, cupy is not recognized by chainer.

Option 1:
`pip install Cython` # works and installs Cython 0.29.31
`pip install cupy==7.8.0` # fails

>         CUDA_PATH       : /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/cudacore/11.0.2
>         NVTOOLSEXT_PATH : (none)
>         NVCC            : (none)
>         ROCM_HOME       : (none)
> 
>       Modules:
>         cuda      : Yes (version 11000)
>         cusolver  : Yes
>         cudnn     : Yes (version 8003)
>         nccl      : No
>           -> Include files not found: ['nccl.h']
>           -> Check your CFLAGS environment variable.
>         nvtx      : Yes
>         thrust    : Yes
>         cutensor  : No
>           -> Include files not found: ['cutensor.h']
>           -> Check your CFLAGS environment variable.
>         cub       : Yes
> 
>       WARNING: Some modules could not be configured.
>       CuPy will be installed without these modules.
>       Please refer to the Installation Guide for details:
>       https://docs.cupy.dev/en/stable/install.html
> 
>       ************************************************************
> 
>       NOTICE: Skipping cythonize as cupy/core/_dtype.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_kernel.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_memory_range.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_routines_indexing.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_routines_logic.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_routines_manipulation.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_routines_math.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_routines_sorting.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_routines_statistics.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/_scalar.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/core.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/dlpack.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/flags.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/internal.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/fusion.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/core/raw.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/cublas.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/cufft.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/curand.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/cusparse.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/device.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/driver.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/memory.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/memory_hook.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/nvrtc.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/pinned_memory.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/profiler.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/function.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/stream.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/runtime.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/texture.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/util.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/cusolver.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/cudnn.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cudnn.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/nvtx.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/thrust.pyx does not exist.
>       NOTICE: Skipping cythonize as cupy/cuda/cub.pyx does not exist.
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/tmp/pip-install-3nvzj2jg/cupy_b0144fd6a6cf445885b7f609ca09f2cc/setup.py", line 156, in <module>
>           setup(
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
>           return distutils.core.setup(**attrs)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 177, in setup
>           return run_commands(dist)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
>           dist.run_commands()
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
>           self.run_command(cmd)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
>           super().run_command(command)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
>           cmd_obj.run()
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/command/install.py", line 68, in run
>           return orig.install.run(self)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/command/install.py", line 695, in run
>           self.run_command('build')
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
>           self.distribution.run_command(command)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
>           super().run_command(command)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
>           cmd_obj.run()
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/command/build.py", line 24, in run
>           super().run()
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
>           self.run_command(cmd_name)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
>           self.distribution.run_command(command)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
>           super().run_command(command)
>         File "/home/jolicoea/vidgen2/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
>           cmd_obj.run()
>         File "/tmp/pip-install-3nvzj2jg/cupy_b0144fd6a6cf445885b7f609ca09f2cc/cupy_setup_build.py", line 991, in run
>           check_extensions(self.extensions)
>         File "/tmp/pip-install-3nvzj2jg/cupy_b0144fd6a6cf445885b7f609ca09f2cc/cupy_setup_build.py", line 728, in check_extensions
>           raise RuntimeError('''\
>       RuntimeError: Missing file: cupy/cuda/cub.cpp
>       Please install Cython 0.28.0 or later. Please also check the version of Cython.
>       See https://docs.cupy.dev/en/stable/install.html for details.

I have Cython 0.29.31, pip install says that 0.28.0 is not available so I can't downgrade.

Option 2:
`pip install cupy` or install from a git clone with `pip install -e .` 
cupy installs properly and I can use it, but chainer does not think that cupy is properly installed and I get cupy.core not found errors

### To Reproduce

```py
pip install Cython
pip install cupy==7.8.0 # error
pip install cupy-cuda110 # error not found
pip install cupy # works

pip install chainer
python -c 'import chainer; chainer.print_runtime_info()' # cupy not recognized by chainer
```

### Environment
```
# python -c 'import chainer; chainer.print_runtime_info()'
Chainer: 4.5.0
NumPy: 1.23.0
CuPy: Not Available

# python -c 'import cupy; cupy.show_config()'
OS                           : Linux-3.10.0-1160.62.1.el7.x86_64-x86_64-with-glibc2.2.5
Python Version               : 3.8.10
CuPy Version                 : 11.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.23.0
SciPy Version                : 1.8.0
Cython Build Version         : 0.29.31
Cython Runtime Version       : 0.29.31
CUDA Root                    : /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/cudacore/11.0.2
nvcc PATH                    : /cvmfs/soft.computecanada.ca/easybuild/software/2020/Core/cudacore/11.0.2/bin/nvcc
CUDA Build Version           : 11040
CUDA Driver Version          : 11060
CUDA Runtime Version         : 11040
cuBLAS Version               : (available)
cuFFT Version                : 10502
cuRAND Version               : 10205
cuSOLVER Version             : (11, 2, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 4)
Thrust Version               : 101201
CUB Build Version            : 101201
Jitify Build Version         : d90e2e0
cuDNN Build Version          : 8200
cuDNN Version                : 8200
NCCL Build Version           : 21104
NCCL Runtime Version         : 21104
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Tesla V100-SXM2-16GB
Device 0 Compute Capability  : 70
Device 0 PCI Bus ID          : 0000:1C:00.0
Device 1 Name                : Tesla V100-SXM2-16GB
Device 1 Compute Capability  : 70
Device 1 PCI Bus ID          : 0000:1D:00.0
```

**Comment by kmaehashi** [comment]
Closing as discussing in https://github.com/cupy/cupy/issues/6933
