### ISSUE TITLE
Broadcastable where

### ISSUE THREAD

**Issue by unnonouno** [chainer/chainer#947]
In a usual case that I use `where` function, condition and values don't have the same shape.

When I use `where` function like this

```
where(condition, x, y)
```

`condition.data.shape` is `(b,)`, and `x.data.shape` and `y.data.shape` are `(b, n)`, where `b` is the mini-batch size and `n` is the dimension of feature vector. For example, `condition` is generated from `x_data.data != EMPTY_LABEL`, and `x` is generated from `model.embed(x_data)`.

In this case, I need to call `expand_dims` and `broadcast_to`.

```
condition = F.broadcast_to(F.expand_dims(condition, -1), x.data.shape)
```

It is desirable to broadcast the condition automatically. Or, we need to prepare `broadcast_where` function.

**Comment by tscohen** [comment]
I agree that auto-broadcasting is nice, but IMO we should follow the numpy conventions: length-1 dimensions are automatically added to the beginning of the array, but not to the end. So we can broadcast arrays of shape (2, 3) and (3,) automatically, but we can't broadcast (2, 3) and (2,) (at least not without adding a trailing length-1 dimension to the vector).

**Comment by beam2d** [comment]
See also #809.
