### ISSUE TITLE
OpenCL support

### ISSUE THREAD

**Issue by kazunori279** [chainer/chainer#99]
CUDA doesn't work on many machines, especially Mac. By supporting OpenCL, chanier could be run with various platforms with non-NVIDIA GPUs and even FPGAs.

**Comment by hobson** [comment]
+1 for supporting the open standard for parallel computing.

**Comment by mingwugmail** [comment]
Any plan to support OpenCL?

**Comment by yawara** [comment]
+1 for supporting OpenCL.

**Comment by cathalgarvey** [comment]
Any movement on this? Open standards would be great, it's sad to see so many otherwise great libraries bogged down in a walled garden. :(

**Comment by t3476** [comment]
These projects try to translate CUDA specific code into portable code:
https://github.com/hughperkins/cuda-on-cl
https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP

HIP looks more complete than cuda-on-cl but its target is C++.

**Comment by cathalgarvey** [comment]
I know that hughperkins is using cuda-on-cl right now to translate Tensorflow to OpenCL, which is pretty exciting.
